### ISSUE TITLE
combine power consumption

### ISSUE THREAD

**Issue by Laui51** [Mogli12/GearboxAddon#1]
Hi,

i thought it might be nicer to keep on here, then to fill the forum.

I just replaced (only) the mrGearboxMogli.lua but it seems, that now there is no influence at all? 
I've tested it with the 5130 as well as with the original 7130...

**Comment by Mogli12** [comment]
Hi Laui51,
Can please give some more details? I just removed the log entries and the coding that limits the threshing power to 90% max power. 
Regards, Stefan

**Comment by Laui51** [comment]
Jepp,  seems  to work now. 

I'll have a bit more testing, when the weather turns worse again. 

Thanks again!
