### ISSUE TITLE
reverse range in manual mode bug

### ISSUE THREAD

**Issue by modelleicher** [Mogli12/GearboxAddon#10]
Hi,

There is a Bug i guess with the reverse ranges in manual/G27 mode. In automatic mode (or automatic clutch mode) it works fine, but in manual mode i can't shift into the ranges with isReverseOnly="true".
With gears it works fine.. I think the problem is that shifting from forward to reverse requires double clutching, and with the gears its possible to shift in neutral but with the ranges there is no neutral.
If i hit the clutch several times while spamming the reverse button it works to get it into (R) mode, but then no gear would engage and the vehicle doesn't move.
If neccessary i can make a video of it.

Und in Deutsch (Dachte du hast hier lieber alles auf englisch wie's aussieht):
Im manuellen/G27 Modus funktionieren die Rückwärts Gruppen/Ranges nicht, Gänge funktioniert, Gang raus, Kupplung raus, Kupplung wieder rein und Rückwärtsgang rein. Aber da es bei den Ranges kein Leerlauf gibt ist vermutlich da das Problem, jedenfalls schaltet das Script nicht in die Rückwärtsgruppen. Wenn ich Kupplung trete/los lasse mehrfach und dabei die Taste für rückwärts dauernd drücke wechselt es manchmal in (R) aber dann kann ich keine Gänge mehr einlegen und das Fahrzeug bewegt sich nicht mehr. (Übrigens muss ich dann meist auch in "vereinfacht" umschalten und dann wieder zurück in "manuell/G27" um überhaupt wieder das Fahrzeug zum bewegen zu kriegen. Die Zahl des eingelegten Ganges steht dann zwar dran, aber es passiert nix bzw. bleibt im Leerlauf.
Wenn nötig kann ich auch gerne ein Video dazu machen.

LG

**Comment by Kynuska** [comment]
Hello. I have the same problem. I work on the gearbox for gold addon. when the G27 mode is turned off, everything works fine. I thought that I had something bad. it occurred to me to try a "standard" until now.
Probably related problem. You can not include the same drive 2 consecutive times.
Example 3 - Neutral - 3 (error NO GEAR)

Keana

**Comment by Mogli12** [comment]
Did you go to neutral and brake?

**Comment by Kynuska** [comment]
at stop:
Brake - Clutch - neutral (lever into neutral) - Brake - tractor stops - release the clutch.
when starting:
still neutral - clutch - if I want to put the same gear as when I stopped, error nogear.

**Comment by Mogli12** [comment]
I think I found it. The check for reverse with double clutch was wrong.
