### ISSUE TITLE
Zero rolling resistance when clutch is disengaged?

### ISSUE THREAD

**Issue by Jurkkis** [Mogli12/GearboxAddon#100]
Example:
In goldcrest valley, I buy tractor and head to 4 lane motorway going from west to east. Going max speed at the downhill (pizza sing), I press down clutch and start gaining speed when coasting, ie. from 40 to 65km/h. But If I keep clutch pressed down, I wont lose any of that speed before the end of the map at east and hit edge of map with 65km/h. Shouldn't there be little rolling resistance always?

Also if you press clutch down when doing field work, if its downhill you will gain speed without resistance even if you have plough in lowered into the ground? Bypassing the implement speed limit here I think.

Can I adjust any of the globals to have effect on these?

**Comment by Quintto** [comment]
well with the going downhill while on the road, your speed should increase to a pretty high number, a tractor is a fairly heavy vehicle and without the clutch nothing is braking it ( with the clutch the engine is keeping the tractor at its speed)

**Comment by Mogli12** [comment]
I do not think that there is any rolling resistance in the game. And the motor brake in the gearbox is *not* simulated via braking anymore. Instead, it uses a fairly high moment of inertia.

**Comment by Jurkkis** [comment]
I'll try to explain more accurately. Gaining speed when coasting downhill clutch pressed sure is as it should be and it works . BUT with gearboxAddon you don't lose any speed even when you reach flat ground after the down hill when clutch is pressed. Without any mods when you lift the throttle and not apply brake, the tractor will come to stop even in slight downhill.. 

And with the plough example, with steep hill you will reach 100km/h ploughing speed if clutch is pressed.

**Comment by Mogli12** [comment]
Hi, issue #101 deals with the same problem but it is written in German. You do not need to translate it. Just try version 2.0.3.3 and check if it is better.

There are two changes: 40% throttle means that the motor torque is set to 0 if RPM is above 
```lua
idleRpm + 0.4 * ( ratedRpm - idleRpm )
```
And there is just a little extra brake sent to the wheels to simulate rolling resistance.

**Comment by Jurkkis** [comment]
Thank you. It did more testing and it seems that the modded ploughs I used, just have so small brakeforce for heavy tractor that they will gain lot of speed downhill when the polugh is in the ground. Lighter (~5t) tractor felt ok with the default 4 furrow plows and 4m cultivator. Guess its just balancing and you can't have all right with physics that are not simulating "everything". Engine brake when in gear is fine and feels good. But for me it still feels that the tractors roll too effiecently in neutral and clutch disengaged on flat ground, without tools lowered to ground. I'll try to find some time to do maybe a video to demonstrate my thoughts. ;) But enjoying a lot doing heavy loads and heavy work with tractors with gears!

**Comment by Jurkkis** [comment]
Video 1, gearboxaddon version 2.0.3.3.:
https://www.youtube.com/watch?v=YZ07_mCu-Rk

As you can see, with clutch down (or neutral) the tractor will roll forever if you do not turn or come to a uphill. I'd like it to have little resistance on flat ground maybe increasing with speed so it would simulate drag from air at high speeds. Too much work to implemen it in the mod, for little use in farming sim, I don't know. What you think Mogli?

Video 2, https://www.youtube.com/watch?v=gZ46i4zH-Hg

When doing work with implements that have speed limit, like manure spreader at 20 km/h. If you press down clutch at downhill, it will bypass the speed limit and you can spread at 50km/h or more if its steep hill. Its not so bad with like cultivators or ploughs that have brakeforce to slow down the tractor. Can the implement speed limit be efective when in neutral or clutch disengaged?

**Comment by Mogli12** [comment]
Hi Jurkkis,
Does the problem still occur in the latest version (v2.0.4.5)?
Best regards!

**Comment by Jurkkis** [comment]
Hi, 

I did a quick test 2.0.4.5 and yes unfortunately it is the same as before. I'm still able to spread manure/fert./slurry, bale, etc. any speed when in neutral or clutch disengaged and going downhill. And don't lose any speed when coasting at flat ground (Goldcrest Valley 4 lane road, eastern flat part). 

But you have made changes that I should see?

**Comment by Mogli12** [comment]
Hi Jurkkis,

Ok, the vehicle will always brake for the working speed limit.

Regards, Stefan

**Comment by cabmac** [comment]
hi... Jurkkis, do you think that this is realistic? When i  "desengage" clutch or in neutral still hold the speedlimit???.... i might be wrong, but the we love the gearbox because it simulate realistic behavior, and holding speedlimit with clutch desengaged is definitely NOT realistic.... my opinion.....

**Comment by Mogli12** [comment]
Hi,
I do not feel that the complete speed limit stuff is very realistic. So this extra break option does not seem to make it worse to me. It only checks the given speed limit of the tools. Not the speed limit of cruise control.
Regards, Stefan

**Comment by Jurkkis** [comment]
Thanks for the update. Yes I agree its not realistic, but its not realistic either to be able coast downhill and mow/rake/bale/plow/cultivate/spray/spread/drill or etc. 60km/h. Keeping the the speed limit when coasting fits the standard game mechanics.
