### ISSUE TITLE
Wirkung des Gaspedals auf den Motor wie beim Benziner

### ISSUE THREAD

**Issue by Patar95** [Mogli12/GearboxAddon#101]
Hallo Mogli,

echt super wie du hinter deinem Mod hängst, ständig am Verbessern und auch sehr ordentlich was den gesamten Projektaufbau (GitHub) betrifft.

Was ich komisch finde dass es noch keiner bemängelt hat, ist, dass das Gaspedal eigentlich von den Auswirkungen auf den Motor so ist als hätte man einen Benzinmotor im Trekker. Im Leerlauf passt das, aber wenn man Fährt und das Gaspedal ist meinetwegen auf 20% beschleunigt er immer und immer weiter und die Drehzahl steigt und steigt.

Ich denke, du bist selbst schonmal gefahren. Wenn ich das Gaspedal konstant halte, bleibt auch die Drehzahl konstant. Außer wir überlasten den Motor oder überschreiten die Motorbremswirkung. So ist es teilweise echt nicht so einfach eine Geschwindigkeit zu halten, und man muss ganz sanfte kurze Gasstöße geben.

Vielleicht könntest du dich dazu ja mal äußern. Ich gehe erstmal davon aus dass das bewusst so gemacht wurde von dir. Verstehe nur den Grund nicht ;-)

Gruß Patar

**Comment by Mogli12** [comment]
Hallo Patar,

in https://github.com/Mogli12/GearboxAddon/blob/master/src/gearboxMogli.lua ab Zeile 6809 gibt es eigentlich ein Stück Coding, was die Drehzahl auf die Gaspedalstellung begrenzen sollte. Daher meine Frage: Hat der Traktor ein stufenloses oder hydrostatisches Getriebe?

Viele Grüße, Stefan

**Comment by BlaggyXD** [comment]
Servus miteinander,

Ich kann Patar da nur zu stimmen wenn ich das Gaspedal so weit drücke dass der Motor im Leerlauf auf 1200 Upm hochdreht und ich ohne das Gaspedal weiter durch zu drücken anfahre dreht der Motor bis auf die Nenndrezahl hoch und dass egal in welchem Gang ich bin

Grüße,
Blaggy

**Comment by Patar95** [comment]
Hey,

bin eben von der Arbeit gekommen und hab das direkt nochmal ausprobiert. Das "Problem" liegt wohl eher darin, dass die Motorbremswirkung komplett außer Kraft gesetzt wird, sobald das Gaspedal nichtmehr auf 0% ist.  Beispiel Fendt Vario. Dem Verhalten nach soll der Vario im Script ja TMS simulieren. Würde ich jetzt auf der Ebenen 50 Fahren, und dann nurnoch "halbgas" geben, müsste der Schlepper ja vom Gas gehen, bzw. aufhören Kraftstoff einzuspritzen, bis die neue Geschwindigkeit erreicht ist. Im LS aber behält der die Geschwindigkeit einfach bei. 

2. Beispiel: Der kleine Deutz Agrostar 6.61. Der hat ein normales Schaltgetriebe mit Lastschaltstufen. Aber auch der fährt gleichbleibend weiter wenn ich von Vollgas auf halbgas reduziere. Die Motorbremswirkung greift erst wieder, wenn ich komplett vom Gas gehe. Um also auf der Ebenen meine Geschwindigkeit von 50 auf 30 zu reduzieren müsste ich gang vom gas, und bei 30 wieder minimal drauftreten. Denn sobald ich wieder minimal mehr Gas gebe beschleunigt er schonwieder auf maximale Drehzahl, trotz nichtmal Halbgas.

Hoffe der Text ist jetzt nicht ganz so verwirrend. Bin etwas unter Zeitdruck ;-)

Gruß Thomas

**Comment by BlaggyXD** [comment]
Meine Vermutung ist dass das Problem liegt daran dass es im LS keine Reibung gibt, die Motorbremswirkung wird meines Wissens nach durch einen Retarder welcher Standardmäßig im LS ist Simuliert daher gibt es auch ein (Retarder) Geräusch sobald man komplett vom Gaspedal geht. Sowie man nicht langsamer wird solange man im Leerlauf ist da der Motor nicht mit den Rädern verbunden ist. 
Daher ist meine These dass diese ganzen Probleme daran liegen dass man den Motor standardmäßig nicht von den Rädern "trennen" kann und er somit Theoretisch keine Reibung braucht da diese (immer) durch den Retarder erzeugt wird.

**Comment by Patar95** [comment]
Ohne jetzt den Script studiert zu haben, würde ich behaupten, es ist keine soooo große Geschichte das Ganze zu ändern. Die Motorbremswirkung darf eben nicht erst bei 0% Gas aktiv sein, sondern schon wenn die Tatsächliche Drehzahl über der Zieldrehzahl liegt, am Besten noch mit leichten übergängen. Der Retarder Sound hat mit dem tatsächlichen Verhalten des Fahrzeugs übrigens nichts zu tun. Der wird einfach eingespielt wenn man playSample(xx) sagt...

**Comment by Mogli12** [comment]
Es gibt aktuell gar keine Motorbremse im Script. Der Motor in FS17 bietet gar keine Bremswirkung an. Die Motorbremse ist derzeit nur über die Massenträgheit realisiert. Da Giants da leider keinen Einblick gewährt, kann ich es auch nicht per Script sinnvoll steuern.

**Comment by Patar95** [comment]
Ich rede auch nicht von einer Motorbremse an sich, sondern an der Bremswirkung die jeder Motor besitzt, sofern er kein Perpetuum Mobile ist. Da wirkt im LS doch die normale "brakeForce" (xml). Nur wird diese von seiten Giants abgeschaltet sobald -wie gesagt- das Pedal nicht auf 0 steht. War das nicht irgendwo in einem der zahlreichen Motor-Scripts?

Schlussendlich heißt das, du kannst vorerst nichts dagegen tun? :(

**Comment by Mogli12** [comment]
brakeForce wirkt direkt auf die Räder, nicht auf den Motor. Der Motor selber verträgt keine negativen Drehmomentwerte. Es gibt zwar jetzt in FS17 Rotationsmassenträgheit, aber zu wenig oder gar keine Reibung.

**Comment by Mogli12** [comment]
Ich habe mal ein kleines Experiment gemacht. Eventuell ist es jetzt etwas zu viel Motorbremse.

**Comment by Patar95** [comment]
Danke, werde ich heute Abend gleich ausprobieren. Aber du weißt wovon ich spreche, oder? Wenn man ganz vom Gas geht, ertönt ja dieses Retarder-Geräusch und die Maschinen "Bremsen" merklich ab. Jedoch nur im Rahmen der besagten Motorbremswirkung. Wenn diese Bremswirkung nun auch aktiv wäre, wenn die Drehzahl über Zieldrehzahl ist, wär das ganze denke ich Ideal.

Aber wie gesagt, ich probiere heute Abend so gegen 5 gleich mal die V2.0.3.0. aus und melde mich.

**Comment by Patar95** [comment]
So...  Getestet, und erstmal für besser befunden. Bei den LKW`s scheint das ganze jetzt fast sauber zu funktionieren. Aber bei genauerem Hingucken ist das Problem nach wie vor vorhanden...  Ich hab wiedermal ein paar Videos gemacht (diesesmal mit Pedalstellungs-Anzeige):

1. Video zeigt den alten pickup. Man sieht hier sehr gut, dass die Drehzahl viel höher wird wenn man die Kupplung draußen hat. Das Gaspedal ist hierbei Konstant.

2. Video ist der Agrostar. Auch hier kann man das sehr gut feststellen.

3. Video zeigt den 700er Fendt. Hier ist es ähnlich, obwohl ich das Pedal nur auf 50% stelle, beschleunigt er bis V-Max. Zwar langsam, aber er beschleunigt.

Videos:
1. https://www.youtube.com/watch?v=_wTTr28oK6s
2. https://www.youtube.com/watch?v=_wTTr28oK6s
3. https://youtu.be/v4M7TlkN_Fo

Eventuell noch nicht von youtube verarbeitet...  Je nachdem wann du es siehst ;-)

Gruß Thomas

**Comment by Patar95** [comment]
Getestet und für gut befunden. Einziges Manko, der Bremseffekt ist jetzt tatsächlich zu stark. Vermutlich jetzt wie im original Spiel, weshalb ich die ganze Zeit diesen Mod drinnen hatte der die Bremswirkung reduziert. Der scheint jetzt nichtmehr zu wirken.   Gibt es dafür schon einen Globaleintrag oder willst du es der Realität halber noch runtersetzen?

Ich bedanke mich vielmals für dein grandioses Feedback aufs Feedback.

**Comment by Mogli12** [comment]
Hallo, der Bremseffekt ist in der Tat wieder sehr hoch. Vielleicht magst Du es ja auch selber mal ausprobieren. Falls noch nicht vorhanden, dann lege doch eine Datei gearoxAddonConfig.xml direkt im mods-Ordner an mit folgendem Inhalt:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<brakeForceRatio type="float" value="0.2"/>
	</gearboxMogliGlobals>
</vehicles>
```
In 2.0.3.2 ist der Wert 0.2. Ich habe eben mal 0.05 probiert. Was passiert bei Dir beim Wert 0?

**Comment by Patar95** [comment]
Hey,

0 -> Funktion ist da, aber zu wenig Bremswirkung
0.05 -> kommt gut ran, für meinen Geschmack aber schon etwas zu viel, nur ein Hauch

Ich habs jetzt mal auf 0.03. Allerdings lässt sich das am besten beim Spielen, ämm... "Simulieren" herausfinden. Ich hatte jetzt nur den kleinen JCB mit fast leerem Überladewagen zum Testen, da schien mir die 0.03 jedoch schon sehr passend...

0.2 habe ich jetzt nicht getestet, müsste aber logisch gesehen deutlich zu viel sein. Mit einem beladenen Anhänger im Heck merkt man die Motorbremswirkung auch in echt kaum noch...

**Comment by Mogli12** [comment]
Ja, 0.03 scheint ganz gut zu passen.

**Comment by Patar95** [comment]
Hey Stefan,

noch ein kleines Anliegen. Es bleibt dir überlassen ob du da etwas machen willst oder ob du es so lässt. Jetzt hast du es so geändert dass das Gasverhalten bei allen Maschinen passt, dafür ist das Auto jetzt unreal...  Beim Auto ist es ja so, dass er schon bei viertelgas hochdreht.

Heißt im LS jetzt natürlich, wenn man den Pickup auf Automatik fährt (Ami eben), muss man das Pedal fast durchtreten dass er mal umschaltet.

Wenn du es so lassen möchtest, kannst du den Issue einfach wieder schließen ;-)

Gruß Thomas

**Comment by Mogli12** [comment]
Hallo Thomas,

ich denke, dass man das Verhalten irgendwie konfigurierbar machen muss. Es gibt jetzt zwei neue XML Attribute, die jeweils `maxRpmThrottle` heißen. Man kann damit bei
```xml
<gearboxMogli maxRpmThrottle="0.8">
```
festlegen, bis zu welcher Gaspedalstellung die Drehzahl übers Wegnehmen von Drehmoment begrenzt wird. Fehlt dieser Eintrag, dann greift:
```xml
<gearboxMogliGlobals>
  <maxRpmThrottle type="float" value="0.8">
</gearboxMogliGlobals>
```
Der Default ist 0.8. Also ab 80% Gaspedal ist die Drehzahl nicht mehr begrenzt. Darunter wird umgerechnet. Beispiel: idleRpm=800, ratedRpm=2100, Gaspedal=40%
=> `maxRpm = idleRpm + Gaspedal / 0.8 * ( ratedRpm - idleRpm ) = 1450`.

Für die LKWs und die beiden Pickups habe ich den Default auf 0.5 (also 50% Gaspedal) runter gesetzt.

Viele Grüße, Stefan

**Comment by Patar95** [comment]
Hallo,

kam aufgrund von Krankheit eine Weile nicht zum ausprobieren. Gestern war es aber dann soweit. Ich war erst skeptisch ob man den Wert bei den LKW`s tatsächlich runtersetzen sollte, hat aber wunderbar geklappt. Also, alles top.

Vielleicht mache ich in nächster Zeit nochmal einen Issue mit ein paar Kleinigkeiten auf, oder soll ich für jedes Problem einen machen? Ist denke ich besser für das Github System, richtig?

Gruß Thomas. Wenn du das hier gelesen hast kannst du gerne den Fall schließen.

**Comment by Mogli12** [comment]
Hallo Thomas,

mach ruhig für jedes einzelne Problemchen ein extra Issue auf. Ich kann dann mit einen Commit (also eine neue Version) mit dem Issue verbinden.

Vielen Dank, Stefan
