### ISSUE TITLE
Make the range stay

### ISSUE THREAD

**Issue by knarF86** [Mogli12/GearboxAddon#103]
Hi,

I just wonder if it is possible to make the range stay even if shifting gears.

Lets say im driving in gear 4, range d.
I get into a hill and have to gear down.
Whats happens is that i get into gear 3 range a.
Which will make my speed really slow compared to gear 4 range d
In real life on most tractors, at least for those i have driven, the range stays in D, even if i have to gear down one step.

Is there any global settings for that, that i have missed?

**Comment by Jurkkis** [comment]
With "range" you mean powershifts?
It's can be configured for each tractor in gearboxAddonConfig.xml. 
`speedMatching="false"` controls if the gear or range keeps it position.

**Comment by Mogli12** [comment]
Which tractor do you use?

**Comment by knarF86** [comment]
Ok.
I've noticed that on more then one tractor. But i really don't remember now, since im not on the computer atm. 
At least i remember the smallest fasttrack act like i described.
Is there any way to force that setting, instead of editing for each vehicle?

**Comment by knarF86** [comment]
And yea, i meant powershifts of course 😊

**Comment by Mogli12** [comment]
Hi,
With version v2.0.3.9 you can disable speed matching globally:
- create gearboxAddonConfig.xml directly in mods folder
- use parameter noSpeedMatching:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<noSpeedMatching type="bool" value="true"/>
	</gearboxMogliGlobals>
```
Regards, Stefan
