### ISSUE TITLE
Kupplung nicht mehr Analog seit 2.0.3.6

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#104]
Nabend, 

habe das Problem das die Kupplung erst bei 50% Kupplungsbetätigung schließt, und dann auch gleich zu 100%. Angezeigt wird es komplett analog, von 0%-100%. 

War in den früheren Versionen meines Wissens nicht. Hast du einen Rat?

Grüße Maxter

**Comment by Mogli12** [comment]
Sorry, aber da hat sich nichts geändert.

**Comment by EastClintwood** [comment]
Moin,

mir ist auch aufgefallen das ich die "großen" MB- Trac´s von Unguided jetzt auf einmal ohne zu Kuppeln die Gänge durchschalten kann. Nur zum wechseln von Vorwärts und Rückwärts bzw um die Gruppen zu wechseln muss ich noch die Kupplung drücken. Ging vorher einwandfrei und habe selber auch sicher nichts verändert. Komme nicht darauf an was das liegen könnte, die anderen Trac´s (Alt, klein, Mittel) gehn alle wie immer nur mit Kupplung durchdrücken zum Gangwechsel wie es sein soll.
Hast nicht zufällig ne Idee an was das liegen könnte?

Gruß East_Clintwood

**Comment by Mogli12** [comment]
Hallo,

ich denke, dass im Mod selber eine Konfiguration fürs Getriebe drin ist. Wenn da die Schaltzeiten zu kurz sind, dann benötigt es keine Kupplung. Am besten ist es dann, eine externe Konfiguration in der gearboxAddonConfig.xml direkt im Mods-Ordner anzulegen.

Gruß, Stefan

**Comment by Mogli12** [comment]
Moin,

mit meiner Konfiguration [gearboxAddonConfig.xml](https://drive.google.com/open?id=0BwwLILj-1B5BQ1RZOWdoLTVKM1U) sollte es besser sein, oder?

Viele Grüße

**Comment by MaxterTM** [comment]
Nein auch deine Config bringt keine Besserung. Habe mal ein Video vom Problem gemacht. Meine Kupplung funktioniert komplett Analog, das sieht man ja daran das ich schön Prozent für Prozent kuppeln kann. 

https://www.youtube.com/watch?v=OerEhoR22CE&feature=youtu.be

Passiert auch mit allen standartmäßig konfigurierten Fahrzeugen. Sicher das da nirgendwo im Skript etwas ist? Es ist auch immernoch so das ich meine Achse nur direkt in der inputBinding belegen kann, nicht im Menu. 

In der inputBinding sieht das so bei mir aus: 

 ` <input name="gearboxMogliCONFLICT_4" key1="KEY_lctrl KEY_space" key2="" button="" mouse="" device="2" category="VEHICLE" visible="false"/>
    <input name="gearboxMogliCLUTCH_3" key1="KEY_period" key2="" axis="" button="" mouse="" device="2" category="VEHICLE" visible="true"/>
    <axis name="gearboxMogliCLUTCH" key1="" key2="" button="" mouse="" key3="" key4="" axis="AXIS_3" button1="" button2="" invert="false" mouseAxis="" mouseInvert="false" device="2" visible="true"/>
    <axis name="gearboxMogliMINRPM" key1="KEY_equals" key2="KEY_minus" button="" mouse="" key3="" key4="" axis="" button1="BUTTON_16" button2="BUTTON_22" invert="false" mouseAxis="" mouseInvert="false" device="2" category="VEHICLE" visible="true"/>`

Grüße Maxter

**Comment by Mogli12** [comment]
Hallo Maxter,

ich sehe da noch nicht wirklich das Problem. 50% Kupplung bedeutet im Skript, dass 50% der Drehzahl von den Rädern (Getreibeausgang) und 50% der Drehzahl vom Gaspedal kommen:

- 0% Kupplung, Vollgas => Motordrehzahl = 0 * Getriebeausgang + 1 * 2350 = 2350
- 25% Kuppling, Vollgas, Traktor steht => Motordrehzahl = 0.25 * 0 + 0.75 * 2350 = 1762.5
- 25% Kupplung, Vollgas, Getriebeausgang auf 2350 U/min => Motordrehzahl = 0.25 * 2350 + 0.75 * 2350 = 2350

Mehr macht das Skript nicht. Es begrenzt vor allem nicht, wie viel Drehmoment eine schleifende Kupplung maximal übertragen kann. Dazu konnte ich nämlich keine Daten finden.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Ich habe mal etwas im "Archiv" gekramt und das maximale Drehmoment für die rutschende Kupplung stark reduziert. (v2.0.4.9)

**Comment by MaxterTM** [comment]
Aber dann haben wir ja eine vollkommen Digitale Kupplung? Im FS15 konnte man die doch schön Analog kommen lassen. 10% Kupplung = 10% schleifen lassen vom Gang. Ich hatte das immer so in Erinnerung? 
Ich hatte da mal bei dir gemeckert, am 03.11.2015 da hatten wir dasselbe Problem und hast es dann gefixt... 

Siehe hier => https://www.youtube.com/watch?v=PnVTrBnHzhI

**Comment by Mogli12** [comment]
In FS15 gab es halt noch keine Massenträgheit. Daher ist in FS17 das Anfahren zunächst mal schwieriger. Dass die Kupplung aber digital wäre, kann ich so nicht nachvollziehen,

**Comment by MaxterTM** [comment]
Aber das sieht man doch in meinem Video?

**Comment by Mogli12** [comment]
Ok, dann baue ich die Kupplung halt aus.
