### ISSUE TITLE
Dedi Fehler...

### ISSUE THREAD

**Issue by xXdanyXx** [Mogli12/GearboxAddon#105]
Tag! 

Kannst du mir vielleicht sagen was der Fehler Aufsich hat?
FS17_GearboxAddon: Error! gearRatio is too small: 0 ------------------------------------------------------------------------ 2: C:/gameservers/s699867/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6397): getGearRatio 3: C:/gameservers/s699867/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (7580): mrGbMUpdateGear 4: C:/gameservers/s699867/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (5942): updateWheelsPhysics 5: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (894): oldFunc 6: C:/gameservers/s699867/ls2017/gameProfile/mods/ZZZ_driveControl/driveControl.lua (1248): oldFunc 7: C:/gameservers/s699867/ls2017/gameProfile/mods/ZZZ_GPS/GPS.lua (251): updateVehiclePhysics 8: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (243): readUpdateStream 9: [string "dataS/scripts/vehicles/Vehicle.lua"] (1867): readUpdateStream 10: [string "dataS/scripts/network/Server.lua"] (389): func ... ------------------------------------------------------------------------

Danke Schonmal im Vorraus!

MFG

**Comment by Mogli12** [comment]
Hallo,

das ist ein Eintrag in der log.txt. Das Problem (hier "gearRatio is too small" wird dabei allerdings automatisch korrigiert. Tritt der Fehler nur einmal auf? Tritt der Fehler bei bestimmten Konfigurationen auf und ist er reproduzierbar? Mit dem kurzen Abschnitt kann ich leider ansonsten nichts anfangen.

Viele Grüße

**Comment by Echelon2k** [comment]
Hallo, wir leiden unter dem selben Problem. Wir haben neu angefangen und uns das Gearbox-Addon auf den Server geladen. Zur Zeit betreiben wir nur die Fendt Schlepper der 800er und 900er Serie daher weis ich nicht ob das Problem nur auf Schlepper mit CVT beschränkt ist.

Sobald das Problem auftritt schaltet das Getriebe auf "Autohold" und springt dann sehr schnell zwischen "Autohold" und "CVT" hin und her und erlaubt nur eine art kriechgang bis man manuell auf "autohold" wechselt (also die Bremse gedrückt hält). Danach läufts wieder wie gewohnt.



Gamelog:

GIANTS Engine Runtime 7.0.0 (14220) 64bit (Build Date: Feb 17 2017)
Copyright (c) 2008-2016, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2016, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: gameProfile
Main System
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  Memory: 16263 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard disabled
  Mouse disabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: NULL
Render System
  Driver: NULL
  NullConsoleDevice initialized
Started 4 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Low (forced)
  View Distance Factor: 0.750000
  Shadow Quality: 0.000000 Size: 1 Filter-Size: 4
  Shader Quality: 0
  Skip Mipmaps: 1
  LOD Distance Factor: 0.750000
  Terrain LOD Distance Factor: 0.750000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.000000
  Foliage Density: 0.300000
  Volume Mesh Tessellation Factor: 1.500000
  Tyre Tracks Segments Factor: 0.500000
  Max. Number of Shadow Lights: 0
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 0
Farming Simulator 17 (Server)
  Version: 1.4.4.0 1.4.4RC8
  Available Languages: en
  Language: en
  Time: 2017-03-19 12:47:55
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load dlc: pdlc_kuhnPack (Version: 1.0.0.0)
Load mod: AAA_UniversalProcessKit (Version: 17.0.9)
Load mod: disableVehicleCameraCollision (Version: 1.0.0.0)
Load mod: FS17_AIVehicleExtension (Version: 0.4.0.8)
Load mod: FS17_ArtMechanic_LS540 (Version: 1.0.0.1)
Load mod: FS17_BigM (Version: 1.3)
Load mod: FS17_Biobeltz_LF180 (Version: 1)
Load mod: FS17_choppedStraw (Version: 1.0.0.7)
Load mod: FS17_ClaasXerion4000Premium (Version: 2.0.0)
Warning: Missing l10n for button SET_DOOROPENER in FS17_ClaasXerion4000Premium
Load mod: FS17_CLAAS_Axion_900 (Version: 1.0.1.0)
Load mod: FS17_Claas_Lexion_700_Stage_IV (Version: 1.4.0.0)
Load mod: FS17_ClarkForklift (Version: 1.0.0.0)
Load mod: FS17_DCK_Compass (Version: 1.0.1.20)
Load mod: FS17_DCK_FollowMe (Version: 1.2.1.40)
Load mod: FS17_DCK_Glance (Version: 1.0.3.40)
Load mod: FS17_DCK_RoundBalerAutoUnload (Version: 1.1.0.24)
Load mod: FS17_DifficultiesImprove (Version: 1.0.0.0)
Load mod: FS17_dogfaceRootStorage (Version: 1.0.0.1)
Load mod: FS17_Fendt1000_steph33_v1_4 (Version: 1.4.0.0)
Load mod: FS17_fendt800 (Version: 1.0.0.0)
Load mod: FS17_fendtHarvesterPackage (Version: 1.0.0.2)
Load mod: FS17_FlieglFlatbed_UAL (Version: 3.0.0.0)
Load mod: FS17_flieglPowerPro (Version: 1.0.1.0)
Load mod: FS17_ForRealModule01_CropDestruction (Version: 1.0.2.1)
Load mod: FS17_ForRealModule02_TireDirt (Version: 1.0.1.0)
Load mod: FS17_ForRealModule03_GroundResponse (Version: 1.0.0.0)
Load mod: FS17_FuelUsageDisplay (Version: 3.0.1)
Load mod: FS17_GearboxAddon (Version: 2.0.3.9)
Load mod: FS17_HauerBaleFork (Version: 1.0.0.0)
Load mod: FS17_holmerHR12 (Version: 1.0.0.0)
Load mod: FS17_holmerPack (Version: 1.0.0.1)
Load mod: FS17_holmerTerraDosT4_30 (Version: 1.0.0.0)
Load mod: FS17_holmer_Auger_Pack (Version: 1.1)
Load mod: FS17_horschTitan34UW_Universal (Version: 1.0.0.0)
Load mod: FS17_Horsch_Tiger_10_LT_Pflug (Version: 2.1)
Load mod: FS17_HT_50_Holmer (Version: 2.0.0.1)
Load mod: FS17_itRunnerPack (Version: 1.0.0.3)
Load mod: FS17_JympaSJSeries (Version: 1.2.2.0)
Load mod: FS17_kotteUniversalPack (Version: 1.0.0.6)
Load mod: FS17_Krampe_Bandit_980 (Version: 1.0.0.0)
Load mod: FS17_Krampe_Bandit_Sattel (Version: 1.0.0.0)
Load mod: FS17_kroneBigXPack (Version: 1.0.0.1)
Load mod: FS17_KroneSwadro2000 (Version: 1.0.0.1)
Load mod: FS17_kuhnSitera3000 (Version: 1.0.0.0)
Load mod: FS17_LightAddon (Version: 2.0.1)
Load mod: FS17_Loesshuegelland (Version: 4.0)
Load mod: FS17_manureSpreaderPack (Version: 1.0.0.0)
Load mod: FS17_MAN_TGS18400_Landei (Version: 1.1.1.0)
Load mod: FS17_MB3D_ClaasJaguar800 (Version: 1.1.0.0)
Load mod: FS17_newhollandT9SmartTrax (Version: 1.0.0.0)
Load mod: FS17_Pallet_Capacity_Upgrade (Version: 1.0.4)
Load mod: FS17_placeableRefillStation (Version: 1.0.0.1)
Load mod: FS17_real_clock (Version: 1.0)
Load mod: FS17_reckJumbo (Version: 2.0.0.1)
Load mod: FS17_repairVehicles (Version: 1.4)
Load mod: FS17_roewerEquipment_PC (Version: 1.0)
Load mod: FS17_SafetyWeight (Version: 1.0.0.0)
Load mod: FS17_shedPackage (Version: 1.0.0.2)
Load mod: FS17_Silo_Cleaner (Version: 17.1)
Load mod: FS17_StopMilkSale_1_0 (Version: 1.0.0.0)
Load mod: FS17_TatraPack (Version: 2.0)
Load mod: FS17_Tieflader (Version: 1.0.0.0)
Load mod: FS17_valtraTSeriesWREdition (Version: 1.0.0.0)
Load mod: FS17_WashAtConfig (Version: 1.0.0.0)
Load mod: LelyJuno100 (Version: 2.5.0)
Load mod: LS17_Ponsse_Mammut_Scorpion_V1_DonMaxxus (Version: 1.0)
Load mod: MilkTrigger_placeable (Version: 1.2.1.0)
Load mod: MoreSaplings (Version: 1.0.0.1)
Load mod: New_Holland_BB1290_Nadal_R90 (Version: 1.0)
Load mod: NF_Marsch (Version: 2.1)
Load mod: NLD_ServicePickup (Version: 2.0)
Load mod: Radladergewichte (Version: 1.0.0.0)
Load mod: timber_runner_autoload_FS17 (Version: 1.0.0.17)
Load mod: vehicleSort (Version: 0.6)
Load mod: ZZZ_BGAextension (Version: 4.00)
Load mod: ZZZ_GPS (Version: 5.01)
Load mod: ZZZ_growthManager (Version: 2.0)
Load mod: zzz_SeedUse (Version: 0.02)
Started network game (10601)
upk debug mode set to 1
AutoSteeringEngine: loading settings from "C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_AIVehicleExtension/autoSteeringEngineConfig.xml"
AutoSteeringEngine initialized
  Register vehicle type: FS17_BigM.GTXM_BigM
  Register vehicle type: FS17_BigM.GTXM_Attach
  Register vehicle type: FS17_Claas_Lexion_700_Stage_IV.Lexion700
  Register vehicle type: FS17_Claas_Lexion_700_Stage_IV.vario
  Register vehicle type: FS17_ClaasXerion4000Premium.Claas_Xerion
  Register vehicle type: FS17_ClarkForklift.forklift
Script loaded: Compass.LUA (v1.0.1.20)
Script loaded: FollowMe.lua (v1.2.1.40)
Script loaded: Glance.lua (v1.0.3.40)
Script loaded: BalerAutoUnload.lua (v1.1.0.24)
  Register vehicle type: FS17_Fendt1000_steph33_v1_4.Fendt1000vario
  Register vehicle type: FS17_FlieglFlatbed_UAL.transportTrailerUAL
  Register configuration 'brushColor'
  Register vehicle type: FS17_flieglPowerPro.flieglPowerPro
  Register vehicle type: FS17_holmer_Auger_Pack.augerWagon_foldable
  Register vehicle type: FS17_holmerPack.augerWagon_foldable
  Register vehicle type: FS17_holmerPack.tractor_crabSteering
  Register vehicle type: FS17_JympaSJSeries.JympaSJ
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_mst
  Register vehicle type: FS17_kotteUniversalPack.kotteUniFuel
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_hookLift
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_man
  Register vehicle type: FS17_Krampe_Bandit_980.Krampe_Bandit
  Register vehicle type: FS17_Krampe_Bandit_Sattel.Krampe_Bandit
  Register vehicle type: FS17_Krampe_Bandit_Sattel.Krampe_Dolly
Script PalettenSammler v3.0.1-107a by Marhu loaded! Support on http://marhu.net
AdditionalMapTypes v1.0.0.8: \__ AdditionalMapTypes V1.0.0.8 by Blacksheep - RC-Devil from 18 Januar 2017 is loading
AdditionalMapTypes v1.0.0.8: \__ AdditionalMapTypes V1.0.0.8 by Blacksheep - RC-Devil from 18 Januar 2017 was loaded successful
 ++ loading SpeedDisplay V 1.3.1.0  -  23.12.2016 (by Blacky_BPG)
 ++ loading BuyOnSiloTriggers V 1.4.0.0  -  08.02.2017 (by Blacky_BPG)
 ++ loading GasStation Extended V 1.4.4.0 A  -  03.03.2017 (by Blacky_BPG)
 ++ loading GasStation Extended - variable fuel price V 1.3.1.0  -  12.01.2017 (by Blacky_BPG)
 ++ loading Digital Storage Amount Mover V 1.4.2.0  -  13.02.2017 (by Blacky_BPG)
  Register vehicle type: FS17_reckJumbo.SilageDistributor
  Register vehicle type: FS17_roewerEquipment_PC.implement_cylindered
  Register vehicle type: FS17_roewerEquipment_PC.implement_configuratableMass
  Register vehicle type: FS17_roewerEquipment_PC.leveler_configuratableMass
  Register vehicle type: FS17_roewerEquipment_PC.silageDistributor
  Register vehicle type: FS17_SafetyWeight.bumbGewicht
  Register vehicle type: FS17_TatraPack.TatraIt
  Register vehicle type: FS17_TatraPack.tatraS
  Register vehicle type: FS17_Tieflader.tieflader
  Register vehicle type: New_Holland_BB1290_Nadal_R90.nadal_r90
  Register vehicle type: NLD_ServicePickup.ServicePickup
  Register vehicle type: timber_runner_autoload_FS17.AutoLoadWoodTrailer
 --- VehicleSort loaded --- 
dataS/cameraPath01.i3d (0.10) ms
dataS/cameraPath02.i3d (0.08) ms
dataS/cameraPath03.i3d (0.07) ms
data/sky/skyUS_day_night.i3d (7.00) ms
data/sky/rain.i3d (0.48) ms
data/sky/hail.i3d (0.30) ms
data/sky/dust.i3d (0.27) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/maps/map01.i3d (7071.78) ms
Lager v1.0: Lager.onCreate(50886) load Lager01
FabrikScript v2.1.7.1: FabrikScript.onCreate(53845) load Pellets_Fabrik
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/
FabrikScript v2.1.7.1: FabrikScript.onCreate(55421) load Compost
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/
Lager v1.0: Lager.onCreate(56306) load Saegewerklager02
FabrikScript v2.1.7.1: FabrikScript.onCreate(56529) load Raffinerie
FabrikScript v2.1.3: FabrikScript_guelle.onCreate(56940) load slurryStorage
FabrikScript v2.1.7.1: FabrikScript.onCreate(57307) load Paletten_Fabrik
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/
FabrikScript v2.1.7.1: FabrikScript.onCreate(58205) load Fabrik
FabrikScript v2.1.7.1: FabrikScript.onCreate(58620) load tomatoGreenhouse
FabrikScript v2.1.7.1: FabrikScript.onCreate(59028) load lettuceGreenhouse
FabrikScript v2.1.7.1: FabrikScript.onCreate(59447) load redcabbageGreenhouse
FabrikScript v2.1.7.1: FabrikScript.onCreate(59866) load cauliflowerGreenhouse
FabrikScript v2.1.7.1: FabrikScript.onCreate(60346) load cardboard production
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/
FabrikScript v2.1.7.1: FabrikScript.onCreate(61767) load GTXM_MS
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/
FabrikScript v2.1.7.1: FabrikScript.onCreate(62294) load Schweinefutterstation
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/maps/New/Anni_Tiere/Textures/Pferde/Horse/HorseReady.i3d (11.56) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/maps/New/Anni_Tiere/Textures/Pferde/Horse/HorseReady2.i3d (11.52) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/maps/New/Anni_Tiere/Textures/Katze/Cat/Cat2.i3d (11.71) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/maps/New/Anni_Tiere/Textures/Hund/Dog/Dog2.i3d (7.81) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/maps/New/Anni_Tiere/Textures/snake/snake.i3d (5.60) ms
Error: Can't load resource 'C:/gameservers/s1184677/ls2017/gameProfile/mods/AAA_UniversalProcessKit/00_ressources/white.dds'.
Error: Can't load resource 'C:/gameservers/s1184677/ls2017/gameProfile/mods/AAA_UniversalProcessKit/00_ressources/black.dds'.
UniversalProcessKit 17.0.9 loaded
--- loading AI Vehicle Extension v0.4.0.8 by mogli ---
  AIVehicleExtension was inserted on selfPropelledSprayer
  AIVehicleExtension was inserted on tractor
  AIVehicleExtension was inserted on combine_animated
  AIVehicleExtension was inserted on loaderVehicle
  AIVehicleExtension was inserted on FS17_Fendt1000_steph33_v1_4.Fendt1000vario
  AIVehicleExtension was inserted on FS17_TatraPack.TatraIt
  Failed to inserting AIVehicleExtension on woodHarvester
  AIVehicleExtension was inserted on FS17_Claas_Lexion_700_Stage_IV.Lexion700
  AIVehicleExtension was inserted on skidSteer
  AIVehicleExtension was inserted on combine_animated_crawler
  AIVehicleExtension was inserted on FS17_holmerPack.tractor_crabSteering
  Failed to inserting AIVehicleExtension on tractor_articulatedAxis
  AIVehicleExtension was inserted on FS17_BigM.GTXM_BigM
  AIVehicleExtension was inserted on conveyorTrailerHireable
  AIVehicleExtension was inserted on tractor_crawler
  Failed to inserting AIVehicleExtension on combine_animated_articulatedAxis
  AIVehicleExtension was inserted on FS17_ClaasXerion4000Premium.Claas_Xerion
  AIVehicleExtension was inserted on tractor_foldable
  AIVehicleExtension was inserted on combine
  AIVehicleExtension was inserted on selfPropelledPotatoHarvester
  Failed to inserting AIVehicleExtension on telehandler_articulatedAxis
  AIVehicleExtension was inserted on telehandler
  Failed to inserting AIVehicleExtension on forwarder
  AIVehicleExtension was inserted on combine_cylindered
  AIVehicleExtension was inserted on tractor_reverseDriving
*** ChoppedStraw v1.0.0.7 | register specialization
*** ChoppedStraw v1.0.0.7 | specialization added to 6 vehicle types
## Glance: Seems to be running on a dedicated-server. So default built-in configuration values will be used.
[DifficultiesImprove] -> Game difficulty is HARD!
--- loading Gearbox v2.0.3.9 by mogli ---
--- FS17_GearboxAddon: inserted into 38 vehicle types / 0 vehicle types updated ---
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_kotteUniversalPack/materials/unloadingEffects.i3d (11.48) ms
MaterialHolder for Kotte Universal loaded successfull!
MaterialType fluid registered successfull!
--- loading repairVehicles mod V1.40 (by Rival)---
--- loading complexBGA mod V4.00 --- (by upsidedown)
--- loading GPS mod V5.01 --- (by upsidedown)
--- loading growthManager mod V2.0 --- (by upsidedown+JakobT)
growthManager:: loading C:/gameservers/s1184677/ls2017/gameProfile/savegame2/growthManager.xml
growthManager:: growth is shifted to midnight
Disabled withering
*** ChoppedStraw v1.0.0.7 | loading straw types
*** ChoppedStraw v1.0.0.7 | fertilizing fruittypes: maize barley oat rape rye sunflower wheat soybean 
*** ChoppedStraw v1.0.0.7 | loaded 4 straw types
data/vehicles/trailers/thueringerAgrar/thueringerAgrarLeguan40.i3d (7.66) ms
data/vehicles/cutters/caseIH/caseIH3020Cutter.i3d (17.21) ms
data/vehicles/tools/bredal/F2WS4000.i3d (11.10) ms
data/vehicles/tools/horsch/horschTiger10LT.i3d (13.52) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Fendt1000_steph33_v1_4/weight.i3d (19.15) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Fendt1000_steph33_v1_4/Fendt1000vario.i3d (171.80) ms
FS17_GearboxAddon: gearboxMogli inserted into FS17_Fendt1000_steph33_v1_4/Fendt1000vario.xml (e)
GPS mod inserted into Drivable Specialization (should happen only once!)
GPS mod inserted into Vehicle Camera (should happen only once!)
data/vehicles/trailers/kroeger/kroegerTAW30.i3d (14.26) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_kotteUniversalPack/Kotte_Universal/kotteUni_fuel.i3d (306.07) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/NLD_ServicePickup/lizardPickupTT.i3d (156.79) ms
FS17_GearboxAddon: looking for default configuration (defaultCars)
data/vehicles/steerable/caseIH/caseIH130Series.i3d (26.07) ms
FS17_GearboxAddon: looking for default configuration (defaultCombine)
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_fendt800/fendt800/fendt800.i3d (497.62) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/timber_runner_autoload_FS17/flieglTimberRunner.i3d (84.90) ms
data/vehicles/trailers/fliegl/flieglDolly.i3d (3.73) ms
data/vehicles/tools/koeckerling/koeckerlingAllrounder.i3d (25.24) ms
data/vehicles/tools/lemken/lemkenSolitair12.i3d (31.17) ms
data/vehicles/steerable/fendt/fendt900.i3d (46.45) ms
FS17_GearboxAddon: gearboxMogli inserted into data/vehicles/steerable/fendt/fendt900.xml (e)
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_SafetyWeight/BumbGewicht.i3d (70.57) ms
C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_Loesshuegelland/maps/Paletten/boardPallet.i3d (34.15) ms
data/placeables/highPressureWasher/kaercher/kaercherHDS918-4M.i3d (8.53) ms
dataS2/character/player/player01.i3d (337.65) ms
data/firstPerson/chainsaws/stihl/stihlMS261.i3d (8.89) ms
Echelon2k joined the game
Error: Failed to open xml file 'C:/gameservers/s1184677/ls2017/gameProfile/vehicleSort/savegame2/v_order.xml'.
VehicleSort: No Save-File found - using standard vehicle order! (This is normal when using the mod for the first time!)
VehicleSort initialized
growthManager:: stepSize: 125
growthManager:: registering fruit wheat growthTime: 24h
growthManager:: registering fruit barley growthTime: 10h
growthManager:: registering fruit rape growthTime: 26h
growthManager:: registering fruit sunflower growthTime: 12h
growthManager:: registering fruit soybean growthTime: 12h
growthManager:: registering fruit maize growthTime: 13h
growthManager:: registering fruit potato growthTime: 12h
growthManager:: registering fruit sugarBeet growthTime: 17h
growthManager:: registering fruit oilseedRadish growthTime: 4h
growthManager:: registering fruit poplar growthTime: 22h
growthManager:: registering fruit grass growthTime: 13h
growthManager:: registering fruit oat growthTime: 10h
growthManager:: registering fruit rye growthTime: 24h
FS17_GearboxAddon: Error! gearRatio is too small: 0
------------------------------------------------------------------------
2: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6412): getGearRatio
3: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (7595): mrGbMUpdateGear
4: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (5957): updateWheelsPhysics
5: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (894): oldFunc
6: C:/gameservers/s1184677/ls2017/gameProfile/mods/ZZZ_GPS/GPS.lua (251): updateVehiclePhysics
7: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (243): readUpdateStream
8: [string "dataS/scripts/vehicles/Vehicle.lua"] (1867): readUpdateStream
9: [string "dataS/scripts/network/Server.lua"] (389): func
10: [string "dataS/scripts/network/ConnectionManager.lua"] (28): 
------------------------------------------------------------------------
Turn joined the game
FS17_GearboxAddon: Error! gearRatio is too small: 0
------------------------------------------------------------------------
2: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6412): getGearRatio
3: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (7595): mrGbMUpdateGear
4: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (5957): updateWheelsPhysics
5: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (894): oldFunc
6: C:/gameservers/s1184677/ls2017/gameProfile/mods/ZZZ_GPS/GPS.lua (251): updateVehiclePhysics
7: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (243): readUpdateStream
8: [string "dataS/scripts/vehicles/Vehicle.lua"] (1867): readUpdateStream
9: [string "dataS/scripts/network/Server.lua"] (389): func
10: [string "dataS/scripts/network/ConnectionManager.lua"] (28): 
------------------------------------------------------------------------
FS17_GearboxAddon: Error! gearRatio is too small: 0
------------------------------------------------------------------------
2: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6412): getGearRatio
3: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (7595): mrGbMUpdateGear
4: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (5957): updateWheelsPhysics
5: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (894): oldFunc
6: C:/gameservers/s1184677/ls2017/gameProfile/mods/ZZZ_GPS/GPS.lua (251): updateVehiclePhysics
7: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (243): readUpdateStream
8: [string "dataS/scripts/vehicles/Vehicle.lua"] (1867): readUpdateStream
9: [string "dataS/scripts/network/Server.lua"] (389): func
10: [string "dataS/scripts/network/ConnectionManager.lua"] (28): 
------------------------------------------------------------------------
FS17_GearboxAddon: Error! gearRatio is too small: 0
------------------------------------------------------------------------
2: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6412): getGearRatio
3: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (7595): mrGbMUpdateGear
4: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (5957): updateWheelsPhysics
5: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (894): oldFunc
6: C:/gameservers/s1184677/ls2017/gameProfile/mods/ZZZ_GPS/GPS.lua (251): updateVehiclePhysics
7: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (243): readUpdateStream
8: [string "dataS/scripts/vehicles/Vehicle.lua"] (1867): readUpdateStream
9: [string "dataS/scripts/network/Server.lua"] (389): func
10: [string "dataS/scripts/network/ConnectionManager.lua"] (28): 
------------------------------------------------------------------------
FS17_GearboxAddon: Error! gearRatio is too small: 0
------------------------------------------------------------------------
2: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6412): getGearRatio
3: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (7595): mrGbMUpdateGear
4: C:/gameservers/s1184677/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (5957): updateWheelsPhysics
5: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (894): oldFunc
6: C:/gameservers/s1184677/ls2017/gameProfile/mods/ZZZ_GPS/GPS.lua (251): updateVehiclePhysics
7: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (243): readUpdateStream
8: [string "dataS/scripts/vehicles/Vehicle.lua"] (1867): readUpdateStream
9: [string "dataS/scripts/network/Server.lua"] (389): func
10: [string "dataS/scripts/network/ConnectionManager.lua"] (28): 
------------------------------------------------------------------------
dataS2/character/pedestrians/woman05.i3d (56.30) ms
growthManager:: Saving to C:/gameservers/s1184677/ls2017/gameProfile/savegame2/growthManager.xml
growthManager:: Saving to C:/gameservers/s1184677/ls2017/gameProfile/savegame2/growthManager.xml
growthManager:: Saving to C:/gameservers/s1184677/ls2017/gameProfile/savegame2/growthManager.xml

**Comment by Mogli12** [comment]
Hallo,

wann tritt das Problem denn auf? Was genau ist vorher passiert?

Viele Grüße

**Comment by Echelon2k** [comment]
Abgesehen davon, dass es sich bei allen Fahrzeugen um Maschinen mit CVT-Getreibe handelt ist kein Muster zu erkennen.  Also sowohl mit Arbeitsgerät oder Hänger angekoppelt als auch ohne. Ich glaube aber, dass es meistens auftritt wenn der Motor mehr oder weniger plötzlich hochdreht. Z.B. bei Steigungen oder wenn man mit Pflug anfährt.

**Comment by Mogli12** [comment]
Tritt das Problem mit Version 2.0.4.1 immer noch auf?

**Comment by Echelon2k** [comment]
Ja, allerdings scheint es nur aufzutreten wenn mehrere Spieler sich auf dem Server befinden.  Ist man allein gibts anscheinend keine Probleme.

**Comment by Mogli12** [comment]
Kann ich bitte die Log-Dateien für 2.0.4.1 haben?

**Comment by Echelon2k** [comment]
Es taucht kein Gearbox-Fehler mehr in der log auf. Das Problem besteht allerdings trotzdem noch.
Die AI-Vehicle Extension Sachen führe Ich jetzt einfach mal auf die Map zurück (Lösshügelland 4.0.0.0).

[log.txt](https://github.com/Mogli12/GearboxAddon/files/867742/log.txt)

**Comment by Mogli12** [comment]
Hallo,
Die Meldugen von AIVehicleExtension sind schon problematisch. Da der Fehler nur im MP auftritt, muss also irgendein Kommunikationsproblem zwischen Server und Client bestehen.
Probiere doch mal Version 1.0 Beta 10 von AIVehicleExtension.
Gruß, Stefan

**Comment by Echelon2k** [comment]
Das Problem mit dem "CVTAutohold" besteht leider auch bei 2.0.4.2 noch. Kurioser weise allerdings nur wenn mehr als ein Spieler auf dem Server ist. Könnte es evtl. einfach ein sync Problem sein?

**Comment by Quintto** [comment]
@Echelon2k if with that you mean that on a server the mod jumps to autohold randomly while playing right? (sorry my german is not what is should be) if so I'm getting exactly the same problems

**Comment by Echelon2k** [comment]
Exactly, Thing is when it happens it happens to everybody on the server at the exact same time which leads me to believe it might be some kind of sync error.

**Comment by Mogli12** [comment]
Do you get this error even if FS17_GearboxAddon is the only mod? A MP sync error could be cause by any mod and could have a negative effect on any other mod.

**Comment by Quintto** [comment]
well that would be strange because it only happened for us (my server) when we updated to the latest  (or the one before that) version, and the fact that 2 people get it separate from each other at the same time. I would test it for you however, but atm I'm not able to do that

**Comment by Echelon2k** [comment]
Tried with 2 players and without any other mods installed and it still happens. However we managed to narrow somewhat down what is causing it. Whenever the other Person opens the Map by pressing "ESC" the other players Gearbox gets stuck in "Autohold". As Soon as you close the Minimap again everything is back to normal. 

With more mods and players this seems to be somewhat more random. Although I can't be sure when someone is entering game menus.

**Comment by Mogli12** [comment]
Please try version 2.0.4.3

**Comment by Echelon2k** [comment]
Issue seems to be fixed. We have been playing for about 2 hrs now without any problems

**Comment by Mogli12** [comment]
Great! 

This was the reason for the bug: The function to stop the vehicle if a dialog is open did not only stop the currently controlled vehicle but all others as well.

**Comment by Mogli12** [comment]
I close this issue. I assume that it is fixed. I am 99% sure that the problem was cause by a change introduced with v2.0.3.9.
