### ISSUE TITLE
Sounds ändern möglich ?

### ISSUE THREAD

**Issue by Claasianer** [Mogli12/GearboxAddon#106]
Grundsätzlich bin ich sehr zufrieden mit der Übersichtlichkeit und Funktion des Addons / Mods !
Jedoch gefällt mir der blowoff Sound nicht so wirklich , nachdem ich jetzt vergebens 2 stunden probiert habe den Sound zu ändern wollte ich hier fragen woran es liegt .
Erklärung: Sound hat den vorgegebenen namen blowOffVentil.wav und liegt in mono im wav 32 bit float vor(dateigröße 200kb) . Datei über 7-zip geöffnet und das original ersetzt , in den Mods Ordner spiel an und im Spiel kommt nur ein rauschen .
Hoffe du kannst mir helfen.

**Comment by Mogli12** [comment]
Hallo,
keine Ahnung woran das liegen kann. Es wird nur loadSample und playSample für blowOffVentil.wav aufgerufen. Die Lautstärke ist 0.14.
Viele Grüße, Stefan

**Comment by Claasianer** [comment]
Ok , danke für die Antwort!
Kannst du selber denn die Sounds ändern? / Hast du es schon mal probiert gehabt?
