### ISSUE TITLE
Fuel usage blinking on dedi

### ISSUE THREAD

**Issue by Quintto** [Mogli12/GearboxAddon#107]
When I use the gearbox mod on a dedicated server, the fuel usage value keeps changing between 0 and the current value.

**Comment by Mogli12** [comment]
Hi, can you please check if the problem is fixed with version 2.0.4.1? Thanks!

**Comment by Echelon2k** [comment]
Problem is still there in 2.0.4.1 :(

**Comment by Mogli12** [comment]
Hi, can you please check if the problem is fixed with version 2.0.4.2? Thanks!

I think that the resolution of the fuel level is too low for the fuel usage calculation. So I tried to smooth it.

**Comment by Mogli12** [comment]
Any news?

**Comment by Quintto** [comment]
much better now, thanks!
