### ISSUE TITLE
New parameter change range below the speed + some questions 

### ISSUE THREAD

**Issue by Kynuska** [Mogli12/GearboxAddon#11]
Hi Mogli and others.
Because some of tractors must stand by shifting range (reduction / road) and some allow you to switch forward / backward to a certain speed without a clutch, is possible to add a __*parameter change range below the speed?*__ Zero would mean to stop before shifting.

Now what do I not succeed (all manual clutch and without G27 mode)

  1 - change of direction when I need to use the clutch, but do not sort neutral. (example I'm going forward - to stop - clutch - reverse gear, release the clutch - ride).

2 - A combination of CVT with manual clutch. for older combines with variator and a manual transmission. (change range)

3 - The combination of shifting. Gears manually and automatically multiplier torque. manual clutch probably turn off automatic = "true"

thank you very much for any advice.

Keana

Edit: version 1.2.99.93

**Comment by Mogli12** [comment]
Hi,
Can you test the lastest version? Number 2 is still not supported. If there is a torque converter the clutch is always automatic. If I look at a Fendt 611 LSA, it has a torque converter and a clutch. The resulting clutch value would be the minimum of the torque converter and the regular clutch.
Regards, Stefan

**Comment by Kynuska** [comment]
Hi. I'll try tomorrow. Today I have a lot of work. Thank you.
K.

**Comment by Mogli12** [comment]
Hi,
manual clutch and torque converter should be possible now. You can test it with http://www.modhoster.de/mods/claas-dominator-105--5 or the Schlüter 1500 TVL from the FS15 Classics DLC.
Regards, Stefan
