### ISSUE TITLE
Anfrage Funktion für Lastzugabe

### ISSUE THREAD

**Issue by Patar95** [Mogli12/GearboxAddon#110]
Hey Stefan,

habe da ein Projekt geplant, zu dem ich nun sowohl zeitlich als auch wegen geringer Motivation nicht komme. Da ich aber inzwischen wirklich Unmengen an Häcksel-Holz auf meiner Map liegen habe, will ich wenigstens für mich alleine eine abgespeckte Version machen.

Idee ist ganz simpel eigentlich. Es geht um den Holzhacker. Drehzahl soll nicht mehr automatisch steigen, die Messertrommel bzw Gebläse bekommt eine Art "Trägheit". Je nach Volumen des Holzes soll dem Motor eine Last gegeben werden, sodass die Drehzahl sich senkt. Unter einer gewissen Drehzahl stoppt der Einzug. 

Mehr Motorleistung -> Mehr Hackvolumen.  
Dünne Hölzer gehen problemlos rein, dicke brauchen ne ganze Weile.
Das ist der Grundgedanke.

Ohne jetzt deine und die Standardscripte durchwühlen zu wollen... (du hast dies ja bereits getan).

Gibt es deinerseits eine Funktion welche die Last des Motors aufstockt und sich entsprechend wie im Fahrbetrieb auf die Drehzahl auswirkt? Dann währe der Rest nicht mehr besonders aufwändig...

Gruß Thomas

**Comment by Mogli12** [comment]
Hallo Thomas,

am einfachsten geht das bestimmt über die Spezialisierung PowerConsumer. Mit einem weiteren kleinen Script (also eine neue Spezialisierung) könnte man nun die Variablen `self.powerConsumer.neededPtoPower` und `self.powerConsumer.ptoRpm` ändern. Die zweite Variable würde ich auch ändern, damit das ganze auch ohne GearboxAddon funktioniert. Eventuell machst Du das nur, wenn `self.attacherVehicle.mrGbMS == nil or not self.attacherVehicle:mrGbMGetIsOn()`.

Viele Grüße, Stefan

**Comment by Patar95** [comment]
Hallo,

danke für die schnelle Antwort. `self.powerConsumer.neededPtoPower` benutze ich bei der Ahwi Forstfräse schon. Dies sorgt ohne Gearbox dafür, dass er beim Fräsen kaum noch Leistung für den Fahrantrieb aufbringen kann, ändert aber nichts an der Motordrehzahl.   Über ptoRpm könnte ich wohl die Motordrehzahl selbst bestimmen, aber das ist ja nicht das was ich will. Der Motor soll mir sein Feedback zur angegebenen Last geben, indem die Drehzahl einbricht. 

Da du aber schreibst "Die zweite Variable würde ich auch ändern, **damit das ganze auch ohne GearboxAddon funktioniert**", bedeutet das also, dass, wenn Gearbox vorhanden, genau das passiert ohne dass ich den ptoRpm-Wert ändere? Dann werde ich mir direkt mal den Hacker als mod machen und das ausprobieren. ;-)

**Comment by Patar95** [comment]
Leider zu früh gefreut.

Habs eben mit dem Ahwi getestet und in einem Video festgehalten. 

Gerät Anschalten -> 60 PS/KW ?
Gerät absenken -> 1800 PS/KW  (Dann wirds definitiv deutlich)

Im Stillstand reagiert er garnicht auf die Leistung. Klar, der Load geht auf 100%, der Spritverbrauch steigt, aber die Drehzahl interessiert sich nicht dafür. Wenn das Getriebe "einkuppelt", merkt er auch noch nichts davon. Wenn man allerdings Gas gibt sinkt die Drehzahl soweit bis er eine gewisse Geschwindigkeit erreicht, dann steigt sie wieder unbekümmert von der Last.

Video: [Hier Klicken](https://youtu.be/NUn0f8x0wCc)

Falls du jetzt nicht die rettende Idee hast, komme ich wohl nicht drum herum die sinkende Drehzahl durch die ptoRpm-Variable zu simulieren. Am schönsten währe es jetzt gewesen, wenn im Falle dieses Versuchs (110 PS verfügbar, 1800 PS abrufen) einfach die Drehzahl soweit absinken würde bis der Motor "aus geht". Ähnlich wie bei Schaltgetrieben und einem zu hohen Gang. 

Liebe Grüße, Thomas

**Comment by Mogli12** [comment]
Tja, weil es Probleme beim Anfahren mit eingeschalteter Zapfwelle gab, habe ich die Leistungsabgabe unter 10 km/h begrenzt.

**Comment by Patar95** [comment]
Das ist natürlich jetzt nicht das was ich mir zu lesen erhofft hab...

Dann werde ich heute Abend mal interessehalber probieren, was passiert, wenn ich die Parameter erst ab 15 km/h erhöhe bzw. verringere.  Das bringt mich zwar dann nicht wirklich weiter im Projekt, aber nungut. Dann muss das Getriebe dazu abgeschaltet werden und die Drehzahl doch wieder automatisch geregelt werden. 

Wenn du nichts mehr dazu sagen kannst, kannst du das gerne schließen. Danke wiedermal ;-)
