### ISSUE TITLE
Gear "sticks" in auto but not manual mode

### ISSUE THREAD

**Issue by Spartan086** [Mogli12/GearboxAddon#111]
Hello, sorry to be bothering. I have this configuration that is not working as I would expect it to. It is based on the New Holland T8 Ultra Command. I might just be doing something wrong but I find the behaviour inconsistent and can't figure out how to get it the way I want it. (Trying so make something that is sometimes reffered to as a "memory shuttle"(?) I think.)

Going to denote Gear and Direction with G(D) so gear 14 Forward becomes 14(F)

**Behaviour 1** (Automatic mode) (forward Not resetting)
Default 11(F) -> shift up twice -> 13(F) -> hit shuttle -> 10(R) -> hit shuttle ->13(F)

**Behaviour 2** (Automatic mode) (but backward is resetting)
Default 10(R) -> shift down twice -> 5(R) -> hit shuttle ->11(F) -> hit shuttle -> 10(R)

**Behaviour 3** (Manual mode) (forward is resetting)
Default 11(F) -> shift up twice -> 13(F) -> hit shuttle -> 10(R) -> hit shuttle ->11(F)

**Behaviour 4** (Manual mode) (backward is resetting)
Default 10(R) -> shift down twice -> 5(R) -> hit shuttle ->11(F) -> hit shuttle -> 10(R)

Behaviour 1 is what I am trying to achieve for both forward and backward in both manual and automatic modes... is it possible? And is the inconsistent(?) behaviour by design or unintended?

PS. The T8 might be a unsuitable machine for this gearbox behaviour, what I'm really trying to make is a gearbox configuration for New Hollands Electro Shift transmission fitted on T6s where you supposedly can set it to gear 12(F) and 9(R) and then it will automatically shift between those two gears each time you switch direction... just understanding how one setup is working in different scenarios is a pain; big kudos to you Mogli for making all the configs that you have in the base mod.

config:
```
<gearboxMogli>
   <gears shiftTimeMs="0" clutchRatio="1" defaultGear="11" automatic="true" reverseReset="true">		
      <gear speed="2.07" forwardOnly="true"/>	
         ...
      <gear speed="57"   forwardOnly="true"/>			
    </gears>
   <reverse ratio="1" shiftTimeMs="500" clutchRatio="1" resetRange="false" resetGear="false"/>
		
   <engines>
      ...
   </engines>
</gearboxMogli>
```

**Comment by Mogli12** [comment]
Hello,

When changing the direction the gearbox takes the gear that is closed to the current gear. 

Regards, Stefan

**Comment by Spartan086** [comment]
That doesn't sound right... 13(F) is forward only and gear 10 is both backward and forward. So if I am in 10(R) and hit shuttle, shouldn't it become 10(F) then? But instead it either goes to 11(F) (if it is in manual mode) because it is the defualt gear or it goes back to 13(F) if it is in automatic mode. That does not follow your explanation that it takes the closest gear?

**Comment by Spartan086** [comment]
I am horribly slow, it took me awhile to notice what you had done, but it is brilliant! Exactly what I wanted to control, and to be able to control it in the game by simply going into the "auto hold" mode... super! Been using this for awhile now and it works fantastic. Thank you very much!
