### ISSUE TITLE
Parkingbrake engage while shifting through forward and reverse on dedi server

### ISSUE THREAD

**Issue by danne77sthlm** [Mogli12/GearboxAddon#112]
Hi,

First of all, no log errors for this, that is the hardest one 
The latest versions that has been put up the latest weeks after version 2.0.3.7 has had this issue

You work as normal, back and forth, especially at loader work, and suddenly you cant move either back or forth, and the parking brake is engaged suddenly
Also, to get that unstuck, you must turn off the engine, then turn off gearbox, start engine and run a bit and then engage again
This is most common on the Ford SLE 7840, but it happens on other tractors as well with manual gearbox

I also had this issue a couuple of times in previous version that was released a couple of days ago even in single player in golden valley

Usual things done, taken away all mods and tested without luck, keep in mind this happens mostly on dedicated server

If you need any info, please feel free to ask

**Comment by Mogli12** [comment]
Hi,

I was never able to reproduce something like this. Can you record a video of it?

Thanks

**Comment by Quintto** [comment]
is it the same issue like is being discussed in #105 at the bottom?

**Comment by Mogli12** [comment]
Yes, I think so.

**Comment by danne77sthlm** [comment]
I think he described it much more well than I do actually in that thread
Me and my friend will try to fix a video of this, unfortunately due to change from wintertime to summertime here my inner clock is fed up with me and wanna go to bed , but we´ll upload a vid for this as soon as we can

**Comment by Mogli12** [comment]
Please try version 2.0.4.3

**Comment by danne77sthlm** [comment]
Tried your latest version and now it works perfekt again, thanks :)

**Comment by Mogli12** [comment]
Great news! Thanks!
