### ISSUE TITLE
Intentional behavior or bug?

### ISSUE THREAD

**Issue by TyKonKet** [Mogli12/GearboxAddon#113]
Hi guys, I received this bug report on my mod:
[FS17_FuelUsageDisplay/issues/15](https://github.com/TyKonKet/FS17_FuelUsageDisplay/issues/15)
Is that an intentional behavior or bug?

**Comment by Mogli12** [comment]
Hi, if a gear is engaged the motor load is calculated from Giants transmission. If no gear is engaged I try to estimate the idle load somehow. Do you have a better way?

**Comment by TyKonKet** [comment]
In my opinion if the gear is not engaged the motor load should be 0, but this is a choice that you must take :)

**Comment by Mogli12** [comment]
I think that a vehicle should consume fuel even if there is no gear engaged. The problem is that we do not get any motor load from the wheels. And many tools, which would consumer power, are no power consumers; e.g. a tipper does not consume power.

**Comment by mieperDE** [comment]
> I think that a vehicle should consume fuel even if there is no gear engaged

So why not 20% load? Or 50%? Because it's too much.
1% will be a simply better value.

Please take a look.
[https://www.quora.com/How-much-gas-does-a-car-burn-per-hour-while-idling](url)

Think on a 600PS Engine. 10% load is insane.

**Comment by TyKonKet** [comment]
Yes @Mogli12, I solved this problem by adding a 2%-3% idle consumption..

**Comment by Mogli12** [comment]
Do you think it is better with v2.0.4.4?

**Comment by mieperDE** [comment]
Much better 👍
