### ISSUE TITLE
auto hold doesn't hold

### ISSUE THREAD

**Issue by mieperDE** [Mogli12/GearboxAddon#115]
Ich habe mir jetzt ein G29 gekauft. Jetzt ist es so das wenn ich bremse stoppt das Fahrzeug. Sobald es auf AutoHold umschaltet fängt es an zu rollen. Nochmal die Bremse treten nutzt da nichts.
Woran kann das liegen? 
Nach einer Parkbremse habe ich schon gesucht. Die gibt es aber glaube ich nicht.

Edit:
Wie es aussieht rollt es immer dann los wenn ich das Lenkrad berühre. AutoHold bleibt dabei als Modus.

**Comment by Mogli12** [comment]
Hallo,
tritt das nur beim Knicklenker auf? Beim Lenken wird die Handbremse automatisch gelöst. Das habe ich vom Standard übernommen: https://gdn.giants-software.com/documentation_scripting.php?version=script&category=69&class=3545#updateWheelsPhysics48082
```lua
if math.abs(self.rotatedTime) < 0.01 or self.articulatedAxis == nil then
```
Gruß, Stefan

**Comment by mieperDE** [comment]
Mit dem Fendt 939 und Fastrac 8000 kann ich das problem nicht reproduzieren. 
Mit dem CaseIH Quadrac und dem Ponsse Harvester kann ich es.

Also ja, es hängt mit den Knicklenkern zusammen.

**Comment by Mogli12** [comment]
Beim Knicklenker funktioniert die Handbremse nur, wenn das Lenkrad in der Mitte steht.

**Comment by mieperDE** [comment]
Ich spiele ohne Deadzone. Es steht nie in der Mitte

**Comment by mieperDE** [comment]
Ein guter Kompromiss wäre noch eine Handbremse. Belegt dann einen Button mehr. Dafür lässt es sich dann definiert am Hang halten.

**Comment by Mogli12** [comment]
Hallo,
um einen Knicklenker im Stand zu lenken - wie unrealistisch - muss man die Handbremse lösen. Ich habe das jetzt aber anders als im Standard implementiert.
Viele Grüße, Stefan

**Comment by mieperDE** [comment]
Du hast recht. Im Stand lenken ist nicht besonders Gesund für das Fahrwerk. Und überhaupt.
Aber es ist möglich. Servolenkung usw macht es möglich 😆 
https://de.pinterest.com/pin/494621971553051294/
