### ISSUE TITLE
Gruppe bleib beim schalten nicht die gleiche

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#117]
Servus ,
Seit der V2.0.4.7 bleibt die Gruppe nicht so wie sie es soll Bsp.:

Motor an machen Gruppe 1MII 
Schalten auf 1HII 
anfahren und in den 2. Gangschalten dann springt die Gruppe wieder auf M also 2MII (sollte aber 2HII sein) 
Erst wenn man die Gruppe von M auf H wechselt und einmal in den R(ückwärts) Gang schaltet bleib die Gruppe beim Schalten die richtige.

Ich hoffe ich konnte das Problem erklären. 

Mit freundlichen Grüßen,
Blaggy

**Comment by Mogli12** [comment]
Hallo,

bei welchem Traktor tritt das auf? Beim Deutz Agrostar? 

Gruß, Stefan

**Comment by BlaggyXD** [comment]
Es tritt bei allen Traktoren auf , außer bei einer LS die bleibt so wie sie es soll.

**Comment by Mogli12** [comment]
Hallo Blaggy,

ich kann das irgendwie noch nicht nachvollziehen. Bist Du im "Vereinfacht"-Modus? 

Gruß, Stefan

**Comment by BlaggyXD** [comment]
Servus Mogli,
Nein , ich spiele mit einem G 27 ( mit H-Schaltung) und echter Kupplung , das mit den Gruppen passiert komischerweise nicht immer und manch mal wenn ich 2 Gruppen schalte bleibt er in der Mittlerengruppe. Für mich sieht es fast so aus als würde die "Speedmatching" Funktion hier die Finger im Spiel haben. 

Gruß,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

deshalb fragte ich ja nach dem Traktor, weil nicht jeder Speedmatching hat. Man kann es aber global ausschalten. 

Gruß, Stefan

**Comment by Mogli12** [comment]
Siehe #103

**Comment by BlaggyXD** [comment]
Speed Matching habe ich schon deaktiviert.

**Comment by BlaggyXD** [comment]
Speedmatching sollte sich doch nur auf die LS beziehen oder ?

**Comment by Mogli12** [comment]
Hallo Blaggy,

tritt es denn ohne Speedmatchting noch auf? Und bei welchem Traktor trat oder tritt es auf?

Gruß, Stefan

**Comment by BlaggyXD** [comment]
Servus,
Wie gesagt Speedmatching habe ich schon seit längerem Deaktiviert.
 Es tritt auf bei allen Traktoren welche von einen kleineren Sprung ( z.B. von 5 auf 10Km/h) von der 1. zur 2. Gruppe haben (z.B. Zetor Major, Deutz AgroStar, Case IH 1455und (Steyr Multi manch mal)) 
Bei Folgenden Traktoren Tritt es nicht auf : Hürlimann H488, Zetor Proxima, Zetor Forterra und Same Fortis. Getestet habe ich alle welche in echt auch ein Schaltgetriebe haben (keine Mods, obwohl es bei denen gleich ist). 

Gruß,
Blaggy

**Comment by BlaggyXD** [comment]
Ich vermute unter anderem dass es mit der #111 zusammen hängt da Bzw. mit der V 2.0.4.5

**Comment by BlaggyXD** [comment]
Wenn der unterschied zu gering ist bleibt er auch in der richtigen Gruppe ca. von 8 auf 10Km/h

**Comment by Mogli12** [comment]
Probier mal v2.0.5.0

**Comment by BlaggyXD** [comment]
Jetzt geht alles wieder wie es soll , Danke.

Mit grüßen,
Blaggy
