### ISSUE TITLE
Stufenloses Getriebe Anfahren/Beschleunigen

### ISSUE THREAD

**Issue by Jan238** [Mogli12/GearboxAddon#118]
Hallo, 
wenn ich mit einem Traktor mit stufenlosem Getriebe aus dem Stand losfahren möchte dauert es bis zu 3 Sekunden bis dieser voll beschleunigt. Davor beschleunigt er nur langsam. Am besten merkt man es bei dem Getriebe was in den Case/NH Traktoren verbaut ist und wenn das Fahrzeug wenig Leistung hat.

Ist das so gewollt? Kann mich gerade nicht erinnern wie es im Ls15 mit dem Mod war.
Könnte man das Verhalten mit irgendwelchen Parametern ändern?

MfG
Jan

**Comment by mieperDE** [comment]
Shift + Ü

Müsste das richtige sein

**Comment by Jan238** [comment]
Shift + Ü verändert bei mir leider gar nichts welche Funktion ist denn oder sollte auf Shift  + Ü sein?

**Comment by mieperDE** [comment]
Hm Tempomat Beschleunigung.
#https://github.com/Mogli12/GearboxAddon/blob/master/Documentation/Beschreibung.pdf

Du hast recht. Es fehlt eine Einstellmöglichkeit für die Steigung bzw Aggressivität vom Getriebe.

**Comment by Quintto** [comment]
I completely agree with you guys. the slow acceleration makes cvt's just a pain to use for loader work (and of course other stuff)

**Comment by Mogli12** [comment]
Ist es mit v2.0.4.8 besser? Ich habe die Massenträgheit beim stufenlosen Getriebe reduziert.

**Comment by Jan238** [comment]
Habe nur zwar nur kurz testen können, aber ist jetzt viel besser, danke.

**Comment by Mogli12** [comment]
Ich denke,, dass es so bleiben kann, oder?
