### ISSUE TITLE
Beim Geraeteausklappen geht das Standgas viel zu hoch

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#119]
hi, mit einer der letzten Versionen (ist mir grad bei der letzten aufgefallen, kann jetzt nicht sagen, ob das bei einer der vorherigen auch war) geht beim Ausklappen der Geraete (x) das Gas viel zu hoch. (real wuerden dir so die Gestaenge um die Ohren fliegen... ;) )

VG
Claudio

**Comment by cabmac** [comment]
edit.... warte mal, bis ich morgen frueh nochmal probiere... ich seh grad, es koennte auch daran liegen:
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=56983&title=fs2017

**Comment by BlaggyXD** [comment]
Servus,
um es mal vorweg zu nehmen: Ja es liegt an diesem mod.
