### ISSUE TITLE
Hydrostatisches Getriebe

### ISSUE THREAD

**Issue by schiewich** [Mogli12/GearboxAddon#120]
Hallo,

ich nutze das Gearbox Addon schon von Anfang an , und möchte mich unter anderem mal für die gute Arbeit bedanken. 
Mir ist jetzt aufgefallen dass z.B. beim 900 Fendt mit Hydrostatischem Getriebe , die Leistung stark abfällt,
wenn man ein Zapfwellengetriebenes Gerät einschaltet und in eine Steigung fährt.
Habe es mit dem Fendt 930 Vario mit 330 PS und Kuhn GF 8702 Zetter mit 40 PS Leistungsaufnahme
getestet.
Wenn ich mich nicht verrechnet habe sollte dem Fendt nach einschalten des Gerätes noch 290 PS
zum Fahrbetrieb zur Verfügung stehen , und damit Problemlos eine Steigung mit 20km/h 
bewältigen können . An einer steilen Wiese auf Sosnovka sinkt die Geschwindigkeit stellenweise auf 2 km/h.
Kann das einer bestätigen ?

MFG Schiewich

**Comment by Mogli12** [comment]
Hallo Schiewich,

ich kann das Problem nicht reproduzieren, Kannst Du bitte die komplette log.txt bei [Gist](https://gist.github.com/) hochladen und eine ScreenShot anfügen?

Danke, Stefan

**Comment by schiewich** [comment]
Hallo Stefan ,
keine Ahnung wie das Einfügen des Log Textes oder ScreenShot geht, hab`s über Gist versucht, kann auch kaum Englisch.
Die Log ist aber sauber, und mit neuem Spielstand , und nur der Gearbox geladen.
Kuhn DLC ist auch Installiert.
Das Problem ist , wenn ich voll eingeschlagen eine Steigung hoch fahre , geht die Leistung in den Keller.
Man muß im Hügel hin und her, hoch und runter abwechselnd fahren.
Müsste der Load Wert unter Last nicht auf 100% steigen?
Der steigt aber nur bis 60-70%
Gibt es in der Gearboxmogli.lua bezüglich PTO nichts zum einstellen?
Wenn ich ohne Gearbox fahre, geht die Leistung zwar auch runter, aber nicht dermaßen viel.
Mit normalem Schaltgetriebe gehts super.

Gruß , Marco

**Comment by Mogli12** [comment]
Hallo,

vermutlich fährst Du weniger als 10 km/h schnell im Gang "Transport". Schalte doch mal auf "Heavy Duty". Allerdings liegt es sicher nicht am Getriebe, dass der Traktor nicht schneller fährt, da die Last nur bei 60-70% liegt. Das bedeutet, dass die Physik-Engine von Giants nur 60-70% der Verfügbaren Leistung benötigte um die gefahrene Geschwindigkeit zu erreichen.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo,

ich habe nochmal versucht das zu reproduzieren. Aber dern Fendt 930 wird einfach nicht langsamer. Da Du mir die log.txt nicht schicken kannst, sehe ich leider auch nicht welche anderen Mods und welche Version Du verwendest. Ich mache dieses Issue daher zu. Wenn Du noch weitere Details hast, Dann kannst Du es ja wieder öffnen.

Viele Grüße, Stefan
