### ISSUE TITLE
Schaltung in die höchste Gruppe!

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/GearboxAddon#121]
Hi! Hab ein kleines "Problem"! Wenn ich die vorwärts oder rückwerts kupple dan schaltet der Traktor immer in die höchtse HauptGruppe was (es gibt ja bei manchen Trekkern 4Hauptgruppen die mann dann mit 4Stufen splitten kann!) bei Courseplay dann dazu führt das er "stecken bleibt"!
Hat das mit einen anderen Mod zu tun?

LG Paul

**Comment by Mogli12** [comment]
Hallo Paul,

Bitte ein gibt mir noch ein paar mehr Details: Welcher Traktor? Welche Geschwindigkeit? Screen Shot?

Du kannst den Gang zum Anfahren in "Auto Hold" für Vorwärts und Rückwärts festlegen.

Danke, Stefan

**Comment by Paul2510** [comment]
Hi! Danke für den Tipp hat das Probelm geöst! War mein fehler in autHold war gang 4 vorgewälth! Jetzt gehts! LG
