### ISSUE TITLE
Eine Bitte fuer configs

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#122]
Hi...kein Issue aber eine Bitte fuer weitere configs, es geht um dei T6s, 2 der Vierzylinder hab ich halbwegs (aus FS15) aber fuer die 6-zylinder hab ich nichts gefunden. Die Teile sinds echt wert, sind gut geworden:

http://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=68402&title=fs2017

VG
Claudio

**Comment by Mogli12** [comment]
Hallo Claudio,

gibt es irgendwelchen speziellen Wünsche fürs Getriebe. Beim Standard T6.140 und T6.160 habe ich das Lastschaltgetriebe genommen.

Viele Grüße,
Stefan

**Comment by cabmac** [comment]
hi, bei den vierzylindern hab ich auch 17/16 drin, das ist schon ok, nur sind bei mir die drehmomente so wies aussieht total verkorkst.... 24 gang mit 2 Lastschaltstufen waere ja auch nicht schlecht.... da ists wieder, das Dilema... :)

**Comment by Mogli12** [comment]
Hi, das 17/16 habe ich im Steyr mit 4 Lastschaltstufen und voller Automatik simuliert. Ich glaube, dass ich Details dazu bei Steyr gefunden habe.

Das 24/24 wäre wohl ganz ohne Automatik. Das ist auf Dauer wohl eher nervig.

Eine Alternative wäre das AutoCommand. Ich würde es sowohl beim 4-Zylinder als auch beim 6-Zylinder anbieten. Beim 4-Zylinder könnte man z.B. den T6.160 mit AutoCommand anbieten. Beim 6-Zylinder dafür den T6.155 und den T6.175 mit AutoCommand un den T6.165 mit ElectroCommand.

**Comment by Mogli12** [comment]
T6.160 AC: http://www.dlg-test.de/tests/0315_NewHolland_T6.pdf

Wobei: http://zugtier.info/new-holland-t6/ Hier habe die 6-Zylinder nur EC.

**Comment by cabmac** [comment]
also EC finde ich eigentlich nicht schlecht, 24/24 hast du recht, wird ein bissl nervig....Waer ja nicht schlecht, wie du gesagt hast, halb und halb AC und EC jeweils fuer 4 und 6 zylinder

**Comment by cabmac** [comment]
wurde ja schonmal angesprochen... waere ja klasse, wenn man das in Zukunft als wählbare oder kaufbare Option anbieten koennte, muesste man die einzelnen configs direkt in den mod einbauen

**Comment by Mogli12** [comment]
Wählbar wäre Klasse. Momentan komme ich aber nicht dazu...

**Comment by cabmac** [comment]
Das ging ja fix, wie immer, thx, morgen frueh mal. ausprobieren ;)

**Comment by cabmac** [comment]
Moin, sieht ja klasse aus....das einzige, was ich mich frage, (und ich weiss nicht, wie das in Real funktioniert), ob der beim wechseln der Gruppe, z.B. den Gang /Geschwindigkeit nicht automatisch anpasst, z.B. wenn man die Gruppe wechselt, springt der nun von 12 auf 16, d.h. man muesst da manuell runtergehen um bei 13 oder 14 zu landen. Oder rechnet die Schaltung das automatisch, so dass er beim wechseln der Gruppe bei 13 weitermacht....wie gesagt, ich weiss nicht, wie das in real bei dieser Schaltung geht...
