### ISSUE TITLE
FS17 moreRealistic compatibility

### ISSUE THREAD

**Issue by wieselflinked** [Mogli12/GearboxAddon#123]
https://fs-uk.com/forum/index.php?topic=195659.0

dural is back and done a lot of work since oct. 16. 

the first issue was reported!?

**Comment by wieselflinked** [comment]
Quote from: astro on Today at 07:52:51 pm
It doesn`t work with gearbox, i made a first very quickly test with all of my mod active.
in my opinion this two mods should be Complementary to have the maximum  realism.
Anyway very nice to see this mod!!!
the "mr" uses it own gearbox (CVT like a fendt vario) model (to be able to have engine braking capabilities for example). The game engine is not realist at all on this point (nvidia physx, rather oriented "arcade" or car games. In our case, we are talking of very heavy vehicles which can be attached together and with varying mass. Nothing to do with a sport car with the exact same mass (and mass repartition) during the whole game).

**Comment by ivanlii** [comment]
Well now we have a better physics and we have to put back the gears on our tractors...
the modding never ends...

**Comment by Mogli12** [comment]
I do not think that these mods will ever come together again.

**Comment by ivanlii** [comment]
I was afraid of that answer...
Let see what i want to play today : geaboxFS or mrFS ?  geaboxFS or mrFS ?  geaboxFS or mrFS ?  geaboxFS or mrFS ?  geaboxFS or mrFS ?  geaboxFS or mrFS ?  geaboxFS or mrFS ?  ..........
OH GOD!!!
really sad news...

**Comment by cabmac** [comment]
gearbox is a (THE)"must-have"....my point of view...

**Comment by Mogli12** [comment]
Look at what Dural wrote. If you want a different gearbox in MR I think Dural has to write it on his own. Here is Durals description of his mod. I marked every line in bold that is done in gearbox as well:

Description of the mod

so, what's different in this version compared to the base game ?
- you are driving farming equipment, not pretenting to  Grin
- real masses for vehicles and content
- **rolling resistance (takes into account ground type and wheel type, and wheel width and wheel radius)**
- air resistance
- **transmission efficiency**
- **real engine torque curve (even if this is not really useful with CVT transmission, we have the correct rpm like IRL)**
- **real acceleration (no more rocket launch start)**
- **new CVT transmission that manages the engine rpm according to power demand (less power = less rpm, engine brake needed = more rpm)**
- no more "glue" tyre with more than 2 times what we can expect IRL (in the base game, with a 5T tractor, you can expect having as more tractive power as a 10T tractor IRL... if not more)
- duals, weight, wide tyre do have an incidence in game now (for example : larger tyre = better in field, but not on the road)
- you have to choose "carefully" your implement/tractor set (especially if you have "sloppy" fields)
- **realistic fuel consumption based on power delivered (and rpm at which the power is delivered) (base game = fuel only depends on "rpm" = you consume more fuel on the road, empty, at full speed than in a field with a bigcultivator)**
- **engine power is now useful on combine (no more "smart" to use a bigger header on a smaller combine). The lesser the yield, the easier for the combine (limits are set by the combine "max capacity", the speed limit of the header and the engine power)**
- when unloading, a combine does use power too !
- real brake force applied to the correct wheels (no more combines braking with all the wheels like a car)
- beware : like IRL, don't trust what is written on the hood of a tractor (example : a nh T6.160 is not at the same level as a "160Hp" tractor)
- pretty realistic tyre slipping (I had to make concessions to get this one right, and so, the vehicles can slide easily laterally. Indeed, the tractive power is defined by the longitudinal and lateral caracteristic of the tyre. This is a limitation of the game engine)
- Balancing of "fruit" yields and prices (potatoes and beet are more rewarding, there is no more a greater yield for barley than corn, ... modification take into account real figures + equipment needed + manual/automated work needed, seeds needed and refilling time, time lost emptying harvester and carting the product)
- Close to real figures for seeding densities (less liter of seeds needed to sow one hectare of rape than one hectare of wheat)
- Base game converted vehicles should have better "off road" capabilities than in the base game (especially true for wider equipment = combine harvester or tractors with wide implement) -> extended use of "component spring joint"
- **No more infinite engine braking force (you can't "over speed" an engine with the base game) -> with "mr", the transmission and engine will try to retains the vehicle, but like IRL, if you don't use your brakes, you have to drive down in low gear to avoid accident Wink**
- Real weight and weight distribution for converted base game vehicles

**Comment by cabmac** [comment]
sorry for my ignorance in lua.....is there no way to "deactivate" the "dural-gearbox" so it could work with yours?

**Comment by Mogli12** [comment]
I looked now three times about durals forum. Does anybody know how much work it was to build the gearbox addon? I will not do the same work again for MR. So I have to make a decision. Right now I am not really playing FS17 anymore. So I quit here. Good buy everybody.

**Comment by cabmac** [comment]
thats is not the question, we know perfectly that this was a hellnof work from you.... and there is a lot of people thinking to stay with your gearbox instead of MR....it was just a question if its possible to do a "simple adjustment" to work.... if that means that yiu have to rework all the gearbox, so we forget MR and that's it.....

**Comment by Ago-Modding** [comment]
I respect the decision of Stefan, I also now that I was finishing of tractors, with gerabox, I do not think I'll finish them ..... I will think only to the development of CNC future ...

**Comment by cabmac** [comment]
sure Ago.... i respect his decision 100%...nobody pretend him to rework all his stuff again

**Comment by ivanlii** [comment]
Hey Stefan who played FS surely heard of Mogli12, Dural, Upsidedown and many other great modders/teams and we thank you very much for your dedication, TIME, patience, forgiveness.
I have now 2 modfolders in my FS.
I use them both.

**Comment by cabmac** [comment]
hi, would be awesome, if you could disable mrgerabox to use yours... like senn at uk...

**Comment by Mogli12** [comment]
Based on durals last [reply](https://fs-uk.com/forum/index.php?topic=195659.msg1273559#msg1273559) I will close this topic again. Many things he writes about the gearbox addon are just not true.

**Comment by ivanlii** [comment]
> Ok, version 2.1.0.4 of the gearbox

Mogli you have a big heart!

**Comment by Anonymous-any** [comment]
@cabmac  "gearbox is a (THE)"must-have"....my point of view..."

My opinion is true @Mogli is the must have gearbox and must not be changed it is so perfect and alterable since I know the configuration file must go in mods folder ^^.
Mr was good mod before 2k15, 2k17 version cause of mass and inertia was not as what it is now in the engine (not perfect) but better I think as before.
Anyway Mr before was not have gears management if I good and must continue to not have it if Dural want his mod be compatible with other that make cense otherwise we have to choose :) and I vote @Mogli12 .

For betters arguments peoples can excels in their category and cannot be good everywhere ! humans are not gods :) event gods cannot be good everywhere too? but that is my question...

Thank you Mogli for you work, time, and results.
fs user
