### ISSUE TITLE
FS17 preorder bonus

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/GearboxAddon#124]
Can you add gearbox to config for preorder bonus?

**Comment by Mogli12** [comment]
Preorder bonus???

**Comment by KITT3000** [comment]
Challenger MT775E Stealth Edition
Challenger MT700E Field Viper
Challenger MT800E Field Python
Challenger MT900E Field Anaconda
Fendt 939 Black Beaty Edition
Massey Ferguson 8737 Black Duals
Valtra T Series Cow Edition

**Comment by Mogli12** [comment]
Sorry, but I do not have these vehicles.
