### ISSUE TITLE
Man Truck - G27 Gear 1-6, Reverse

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#125]
So when I use the G27 gear shift 1-6 and reverse, it chooses gears 7-12 and R2.  How do I switch to the lower 1-6, R gears using my shifter?

**Comment by Mogli12** [comment]
Sorry, but right now the MAN has 12 sequential gears. So the G27 mode chooses the highest 6 forward gears and the highest backwards gear.

**Comment by Mogli12** [comment]
Please watch:
https://www.youtube.com/watch?v=UW-KCf4QAOI
https://www.youtube.com/watch?v=HF6sbAdDgFA

The MAN with TipMatic does not have a gear shifter anymore.
