### ISSUE TITLE
Schlepper Problem

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#127]
Hallo,
meine Beobachtung:
Wenn ich mit einem Schlepper (z.B. Fendt Vario 724) mit angeschaltetem Gerät (z.B. Kverneland Accord DL) eine enge Kurve fahre, reduziert sich die Geschwindigkeit enorm (ca. 3-5 km/h). Die Auslastung ist lediglich bei 20% (laut Getriebe Add-on Anzeigefeld). Fahre ich mit Tempomat habe ich das Problem nicht.

Ist das ein Bug, Feature oder Mod Konflikt?

Hier mein [Log](https://pastebin.com/K7fw607c)

Ähnliches hab ich bei Erntemaschienen gesehen. Maschiene ist an, Schneidwerk oben, Drehzahl nicht am Limit, Auslastung gering (20% - 50%). Beschleunigung gibt es kaum bzw. keine (bei vollem Lenkeinschlag).

Ansonsten Top Mod. Will nicht mehr ohne. Hab MR (Beta) probiert, aber deine Getriebe find ich besser.

Grüße

Fracking

**Comment by Fracking** [comment]
Hi,
ich habs nochmal getestet:
Leerer Mod Ordner nur mit FS17_GearboxAddon (v2.1.0.5 von hier). Neues Savegame. Problem bleibt.
MR hinzugefügt. Problem bleibt. Bei beiden Karten (Goldcrest Valley und Sosnovka).

Wenn ich den Tempomat einschalte beschleunigt der Traktor normal (trotz max. Lenkeinschlag). Gebe ich dann wieder manuell Gas, bremst er ab und kriecht nur noch.

Wie gesagt, keine 100% Auslastung (außer ich stelle den Tempomat ein). Schwankt zwischen 90% und 10%. Auch der Kraftstoffverbrauch ist entsprechend der Auslastung, obwohl ich Vollgas gebe. Öffne ich die Lenkung beschleunigt der Traktor, jedoch langsamer als mit Tempomat, auf die maximal vom Getriebe mögliche Geschwindigkeit.

Schalte ich das Getriebe Addon aus. Ist alles normal.

Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Guido,

Das Video hat den Durchbruch gebracht. Vielen Dank dafür. Beim stufenlosen Getriebe mit Zapfwelle steuert das Gaspedal nur noch die Zielgeschwindigkeit. Aufgrund von einigem hin und her, hat sich die Zielgeschwindigkeit nur in kleinen Schritten erhöht. Beim Kurvenfahren wurde der Traktor aber stärker abgebremst als die Zielgeschwindigkeit erhöht werden konnte.

Lange Rede kurzer Sinn: das war alles unnötig und ich habe es jetzt hoffentlich mit v2.1.0.7 gelöst.

Vielen Dank, Stefan

**Comment by Fracking** [comment]
Hi Stefan,

ich glaub du hast meinen Namen verwechselt. Ist nicht schlimm.

Das Problem hat sich behoben. Geht auch bei Geräten ohne Zapfwelle.

Noch 2 kleine und 1 mittlere "Bugs".

1. Kraftstoffverbrauch bei stehenden Fahrzeugen mit stufenlosen Getrieben ist 0 L/h. Das wird in der Innenansicht deutliche, wenn z.B. der Traktor eine Verbrauchsanzeige hat. Bei Traktoren mit mauellen Getrieben und eingelegter Kupplung ist das korrekt dargestellt. Da fährt der Traktor mit Gang X im Leerlauf (800-900 U/min) X km/h und hat einen Verbrauch von X L/h. Wenn es nicht klar ist was ich meine mach ich noch ein Video.

2. "Eye candy" beim Motorstart. Drücke ich auf "Motorstart" ist die Nadel direkt bei Leerlauf Umdrehung. Mach ich den Motor aus und wieder an, bleibt die Nadel auf 0 bis ich Gas gebe und die Drehzahl etwas steigt. Das ist aber nur kosmetisch und nicht so wichtig.

3. Die Erntemaschienen (Dreschern) legen ein komisches Verhalte an den Tag. MR verändert das Dreschen zwar, aber das [Video](https://youtu.be/9ZCpULkV-FA) zeigt wohl besser was ich meine. Das Verhalten tritt bei Tempomat und manuellem Gas. Mit MR-Getriebe fahren die Drescher ca. 5-7 km/h (Das ist meines Wissens +/- Realität). Mit Getriebe Add-on schwankt es zwischen 3-5 km/h. Die Fläche ist ja relativ eben. Der Ertrag ist überall gleich (schwankender Input sollte nicht der Grund für die schwankende Motordrehzahl/Last sein). Wenn es nicht klar wird was ich meine, soll ich einen neuen Thread öffnen?

Grüße

Andreas

**Comment by Anonymous-any** [comment]
Hi, I don't know if I understand good here and to post my issue I see too but it seem similar from few updates I been lose few Km/h limited at full speed with some tractor and combine where it lose 3 km/h and for tractor between 3/4 km/h. That seem not happen with trucks where they can go 90km/h. I tried to alter my settings like limiter, rpm limiter but nothing do better. For be sure Gearbox is faulty I tried to not load it at savegame and full speed came back. I sorry to not ask or give better explain... Question to linked with limiter is where or how I can disable gearboxMogliACCTOLIMIT gearboxMogliDECTOLIMIT please?

Br :)

**Comment by Mogli12** [comment]
Do you use FS17_KeyboardSteer as well?

**Comment by Anonymous-any** [comment]
Yes I do but I tried to unload it for testing what you say but it was the same meaning FS17_KeyboardSteer seem not the culprit or conflicted with.
