### ISSUE TITLE
Gänge setzen sich zurück

### ISSUE THREAD

**Issue by punchi1** [Mogli12/GearboxAddon#128]
Habe folgendes Problem beim 7R
`	<gearboxMogli autoStartStop="false" rpmInSpeedHud="true" minHudRpm="0" maxHudRpm="2300">
	<blowOffVentilSound volume="0"/>
	<gears **reverseReset="false"** shiftTimeMs="100" clutchRatio="1" defaultGear="8" automatic="true" >

    </gears>`

das fett markierte habe ich eingetragen, damit beim Vorwärts/Rückwärts wechseln die Gänge gespeichert werden. Allerdings passiert dadurch nichts? Habe das einfach aus der Beschreibung übernommen

**Comment by Mogli12** [comment]
Hallo,
Wenn Du in "AutoHold" bist, dann bestimmst Du den Vorwärts- und Rückwärtsgang. Einfach in den richtigen Gang schalten. Soweit ich das gelesen habe, kann man die Gänge bei den meisten Traktoren mit Automatik auf der Armlehne einstellen.
Viele Grüße

**Comment by punchi1** [comment]
habe mich glaub ich nicht gut ausgedrückt. Angenommen ich fahr ans Vorgewende mit Gang 5, schalte dann in Rückwärts Gang X. Dreh um und schalte wieder in den Vorwärtsgang, dann bin ich bei Gang 1 aber ich hätte gerne das er wieder in Gang 5 geht, so wie vorher auch.

**Comment by Mogli12** [comment]
Ich bin mir noch nicht ganz sicher, woran es liegt. Aber mittlerweile kann ich bestätigen, dass die Gänge doch etwas zu oft zurück gesetzt werden.

**Comment by punchi1** [comment]
Sonst probier einfach mal den 7R von Techmod aus... von dem rede ich.
Da wird bei jeder vorwärts/rückwärts Schaltung der Gang zurückgesetzt

**Comment by Mogli12** [comment]
Hallo,

das Issue ist schon ein paar Tage alt und es gab genau in diesem Bereich ein paar Verbesserungen. Besteht das Problem denn noch?

Vielen Dank, Stefan
