### ISSUE TITLE
Big Bud DLC - No XML File

### ISSUE THREAD

**Issue by xyt272** [Mogli12/GearboxAddon#129]
I have the Big Bud DLC installed. Took them both for a quick test spin around the Farm. Both Tractors pair with the Default Tractor transmission of your mod but I would rather use something different. I want to write a replacement transmission but cannot find any XML files. In fact I can only find two files: The install .exe file and bigBudPack.dlc file inside the pdlc folder of the game. Neither of those is getting me anywhere. 

Any Ideas? 

Great Mod by the way. Nice Work. It improves the game so much.

**Comment by sootysax** [comment]
you cannot mod Giants DLC

**Comment by xyt272** [comment]
Thanks. 
I wonder if I could mod the Default Tractor setting then as kind of a work around.

**Comment by Mogli12** [comment]
Please read the chapter "Own configurations" in [Description.pdf](https://github.com/Mogli12/GearboxAddon/blob/master/Documentation/Description.pdf).
