### ISSUE TITLE
Stop Problem

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/GearboxAddon#13]
servus mogli

seit der version 1.2.99.94 hab ich ein problem mit den dreschern beim anhalten

ich kann auf die bremstaste drücken wie ich will ,,, er wechselt einfach nicht in den "neutral" oder "handbremse" modus

keine fehler in der log ....

grüsse grazy

**Comment by Mogli12** [comment]
Hmm, da schiebt die Leerlaufanreicherung wohl zu stark. Bei welchen Drescher tritt es denn auf. Helfen sollte, wenn Du beim Bremsen noch Ö für Neutral drückst.

**Comment by mngrazy** [comment]
zur zeit arbeite ich mit dem NH CR 1090 aus dem HauptGame

und dann noch etwas ^^
diesmal geht das wenden mit AutoCombine nicht

z.b.
Feld ende , AutoCombine ist auf Alternativen Helfer und Auf/Ab Fahrt , wenn das feld zuende ist , möchte AutoCombine einen kleinen satz zurück machen (0,5 oder 1,0m) , dies ist nicht möglich , da bleibt er stecken , als wenn er nicht genügend Power hätte

schon wieder eine neue kupplung besorgen müssen ? ^^

grüsse grazy

**Comment by Mogli12** [comment]
Hi,
Der Drescher hat sich quasi selber abgewürgt. Falls mehr Drehmoment angefordert wird als verfügbar, dann drückt das Getriebe die Drehzahl. Ich habe das jetzt so umgebaut, dass erst oberhalb von 2 km/h gedrückt wird. Auch die Geschwindigkeit um auf Neutral zu gehen habe ich erhöht auf 1 km/h.
Das ist gelöst mit Version 1.2.99.97.
Vielen Dank!
Mogli

**Comment by mngrazy** [comment]
also mit autoCombine haut das noch net so ganz hin ,, jetzt bleibt AC nicht stehen um dann rückwärts zu fahren , jetzt versucht AC stehen zu bleiben , geht nicht und fährt mit ca: 1km/h weiter vorwärts

rest mit in neutral/handbremse modus "schalten" bzw stehen bleiben geht nun wieder 1a

**Comment by Mogli12** [comment]
Hi,
Ich glaube, dass sich da eher AutoCombine verhaspelt hat. Ich habe das Problem zwar manchmal gesehen, aber es nie reproduzieren können. Daraufhin habe ich doch einige Änderungen in AutoCombine gemacht. 
Auf jeden Fall habe ich das Problem derzeit mit den letzten Versionen von AutoCombine und GearboxAddon nicht mehr.
Viele Grüße,
Mogli

**Comment by mngrazy** [comment]
jupp , alles gut ,,, mit letzten GearBox und letzte AC läuft wieder alles bestens ! ;)
