### ISSUE TITLE
Courseplay - JCB 3230 no Automatic

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#130]
So when playing with Courseplay, the JCB 3230 will never go into automatic mode, even when in Automatic mode when starting a course..   it will switch between sub gears (B1, B2, B3) etc, but will not move the main gear (A,B,C,D)

AI (M) is always displayed..

**Comment by Mogli12** [comment]
This is intended. If you want full automatic shifting you can switch to simplified mode with "KEY_rshift KEY_slash".

**Comment by Mogli12** [comment]
Hi Sootysax,
If my last reply is ok, can you close it?
Thanks, Stefan
