### ISSUE TITLE
Gear Groups

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#131]
I'm finding it difficult to use the manual gear on some vehicles...

in the Lizard TX Barrelcore (Labelled CAT C18 in gearbox):

I shift from 1 through 4, then I switch groups and it jumps to 8 and I have to step back through to 5 and back up to 8.   Then when decelerating, it jumps from 5 to 1 when I switch groups.. then I have to shift back up to 4 to continue down to 1.

This is similarly happening on New Holland T6.160:

Gear up 1-4, group switch jumps to 8 and have to step back to 5... 8 to 12, 12 to 16 and similarly on the way down..  if I leave it in first gear, the groups will jump from 1 - 5 - 9 - 13, which does work pretty well in the T6, but not as much with the Lizard TX.

It seems the gearbox remembers where you were in the gear box when you switch groups instead of them being indepentant of each other.. is there a way to change this?

there does not seem to be a simple or realistic mode for either of these vehicles.

**Comment by Mogli12** [comment]
Hi Sootysax,

An eaton 13 or 18 speed transmission is really quite complicated.

Please check:
- #87 
- https://www.youtube.com/watch?v=J0yYn7Do_hQ
- https://www.youtube.com/watch?v=LzB9vZ71v08

I personally always stay in automatic mode. The G27 should match to Lo, 1/5, 2/6, 3/7, 4/8. So you need 4 buttons to shift range1 and range2.

Best regards, 
Stefan

**Comment by Mogli12** [comment]
Hi Sootysax,
If my last reply is ok, can you close it?
Thanks, Stefan

**Comment by sootysax** [comment]
im still having a problem with manual gears. is there any way to get from gear 4 directly to gear 5 on the T6.160??

I am trying to plow on a hilly field, and automatic is not really working, as I have to really work in lower gears trying to get up the hill..  slowly changing from gears 1 through 4..  needing to get to gear 5, I switch groups, and I am in gear 8..  and having to shift back to gear 4, my momentum is dead, and my tractor has stopped and I have to start over.

**Comment by Mogli12** [comment]
Hi,
I updated the configuration of the NH T6. You can now shift all gears sequential. But the G27 will only take the highest 7 gears into account.
Regards,
