### ISSUE TITLE
Handgas Funktion's los bei Zapfwelle Arbeiten

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#133]
Servus,

Seit der v2.1.1.0 geht das Handgas nicht mehr wenn man eine Gerät an der Zapfwelle betreibt, um genauer zu sein bleibt der Motor im Standgas obwohl das Handgas höher wie das Standgas ist.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Bladdy,,

Ich kann das leider nicht reproduzieren. Um welchen Traktor handelt es sich denn? Ist dort ptoRpm eingetragen?

Viele Grüße, Stefan

**Comment by BlaggyXD** [comment]
Hallo Modli,   (nicht böse gemeint sondern ein Spaß)

Es kommt über all vor , ptoRpm ist ( in der gearboxMogli.lua) auf 0 zwecks Realismuss. 

Viele Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Bzw. ptoEcoRpm welches ich nutze solange der Bulldog nicht zuwenig Kraft hat.

**Comment by Mogli12** [comment]
Hallo, Blaggy,

ich denke nicht, dass das GearboxAddon mit `ptoRpm="0"` funktionieren kann. Das Gerät gibt an, dass es ein bestimmtes Drehmoment bei 540 (oder 1000) U/min Zapfwellendrehzahl benötigt. Ohne ptoRpm ist dem Getriebe jetzt nicht klar, bei welcher Drehzahl 540 U/min an der Zapfwelle erreicht.

Viele Grüße, Stefan

**Comment by BlaggyXD** [comment]
Servus Mogli,
bis her hatte es immer funktioniert und im genauer zu sein habe ich gearboxMogli.ptoRpmFactorEco      = 0/3 verändert da her sollte das Getriebe wissen das es dauer haft die benötigt Zapfwellendrehzahl er reicht

**Comment by BlaggyXD** [comment]
Die Fehlermeldung kann nun geschlossen werden da alles wieder klappt wie es soll.
Vielen dank für die schnelle Hilfe.
