### ISSUE TITLE
Motor dreht beim ein Kuppeln von selber hoch

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#134]
Servus ,

Beim anfahren wenn man die Kupplung kommen lässt dreht der Motor von selber hoch was Zwar nicht weltbewegend aber etwas nervig ist. Wenn nötig kann ich ein Video machen damit ich es verdeutlichen kann.

Mit Grüßen,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

Das ist die Leerlaufanreicherung. Es kann sein, dass die nicht so gefühlvoll ist und zuviel Gas gibt.

Viele Grüße, Stefan

**Comment by BlaggyXD** [comment]
Servus Mogli , 
Ja das ist sie , teil weise dreht sie bis auf 1.500 Upm hoch gibt es eine Möglichkeit  die Leerlaufanreicherung  aus zu schalten ? wenn nein könntest du das evtl. in die gearboxmogli.lua ein bauen ? 

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Servus , 
Ich nerve zwar ungern aber tut sich hier noch etwas ?

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Nein
