### ISSUE TITLE
Gearbox is allowed to turn on/off with engine running

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#135]
If Courseplay or Follow Me is driving the vehicle, the key combination to turn the Gearbox on/off is being allowed to work.  When the MR transmission is re-activated when the engine is running, bad things happen.  video: https://www.dropbox.com/s/qsle8rl8l5g2p28/2017-05-16_180608760.mp4?dl=0

This is also happening when using the latest version of Game Extension, that allows you to activate the Gearbox addon when you enter a vehicle..   if you have a hired driver and are using MR, this same thing will happen.

I've already reported it to Dural, but maybe you can look into the bypassing of the restriction of changing the Gearbox when the engine is running.

**Comment by Anonymous-any** [comment]
Hahaha WTF !

**Comment by Mogli12** [comment]
It is a feature to turn off the gearbox while the vehicle is operated by Courseplay, FollowMe or AI.
