### ISSUE TITLE
Fehler auf dem Server mit der version v2.1.1.4 

### ISSUE THREAD

**Issue by LS-Horlacher** [Mogli12/GearboxAddon#136]
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli
ERROR in client coding of mogliBase.lua: unknown type: 65
ERROR in client coding of mogliBase.lua: unknown type: 117
Error reading network ID: 526082 (gearboxMogli

**Comment by Mogli12** [comment]
Das ist sicher nicht die komplette Log Datei. Tritt das Problem auch dann auf, wenn nur gearboxAddon verwendet wird?

**Comment by LS-Horlacher** [comment]
Hallo danke erstmal für die prompte Antwort.

 

Nein das ist natürlich nicht die ganze log.

 

Das werde ich natürlich gerne testen und danach beide Logs schicken

 

Von: Stefan Biedenstein [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Mai 2017 22:30
An: Mogli12/GearboxAddon <GearboxAddon@noreply.github.com>
Cc: LS-Horlacher <heikoschuehle@onlinehome.de>; Author <author@noreply.github.com>
Betreff: Re: [Mogli12/GearboxAddon] Fehler auf dem Server mit der version v2.1.1.4 (#136)

 

Das ist sicher nicht die komplette Log Datei. Tritt das Problem auch dann auf, wenn nur gearboxAddon verwendet wird?

**Comment by LS-Horlacher** [comment]
okay hat sich erledigt. war ein mod.
Danke nochmal für deine top Skripts.

mfg
Heiko

**Comment by Mogli12** [comment]
Hallo Heiko,

leider kann ein einziger kleiner Fehler in einem einzigen Mod bei allen andrern Mods Fehler im MP verursachen.

Viele Grüße, Stefan
