### ISSUE TITLE
Doppel-H-Schaltung?

### ISSUE THREAD

**Issue by RuppMartin001** [Mogli12/GearboxAddon#137]
Hallo Mogli12,

ich finde dieses Add-On wirklich klasse!

Ich habe aber auch ein Problem. 
Ich verwende die Gangschaltung: "TX Racing Wheel TH8A Shifter" und habe innerhalb von Gearbox die Gänge der Schaltung belegt. Das klappt wunderbar bei vielen Fahrzeugen.
Bei einigen aber (z.B. Unimog) scheint es eine Art: Doppel-H-Schaltung zu geben.

Wenn ich in der Schaltung den 1. Gang auswähle, wird tatsächlich der 7. Gang eingelegt.
Statt dem 2. Gang kommt der 8. usw.
Ich kann also nur die Gänge: 7 bis 12 auswählen. Auch mit Rückwärtsschaltung.
Wie kann ich die Gänge 1 bis 6 auswählen?

Dazu müsste es,so denke ich, so etwas wie einen Schalter (oder zwei Schalter geben), um zwischen den Bereichen umschalten zu können. 
Die Schalter für die GruppenGruppenschaltungen(Gruppe1 oder Gruppe 2 werden derzeit nicht dazu verwendet. Wie kann man die Bereich umschalten?

**Comment by Mogli12** [comment]
Hallo Martin (?),

ich denke mal, dass Du die Konfiguration für den Unimog selber erstellt hast, oder? Ich denke, mal, dass bei einem Unimog mit 12 Gängen diese in zwei Gruppen mit jeweils 6 Gruppen unterteilt sind. 

Viele Grüße, Stefan

**Comment by RuppMartin001** [comment]
Hallo Stefan,

ich habe keine Konfiguration für den Unimog vorgenommen. 
Allerdings nutze ich von modhoster die "Erweiterte Gearbox-Config". 

Ich habe nun einen Eintrag für einen Unimog gesucht und wurde nicht fündig.
Stattdessen gibt es offenbar einen Default-Eintrag, der für alle Trucks gültig ist.

Im Tag: "configFile" steht im Attribut: xmlName der Wert: "defaultTrucks".
Ich nehme an, dass das eine Standardbelegung ist. 
In der Doku habe ich dazu nichts gefunden.

Hier ist die Definition, die auch als Standardgang den Gang 7 festlegt.
<vehicle>
		<configFile xmlName="defaultTrucks"/>

		<gearboxMogli speedLimiter="true" maxForwardSpeed="93" maxBackwardSpeed="93" autoStartStop="true" enableAI="true">
			<blowOffVentilSound volume="0"/>
			<gears axleSpeed="2.71" tireWidth="600" tireRatio="50" rimDiameter="22.5" defaultGear="7" automatic="true">
				<gear name="1"  forwardOnly="true" inverseRatio="15.86"/>
				<gear name="R1" reverseOnly="true" inverseRatio="14.68"/>
				<gear name="2"  forwardOnly="true" inverseRatio="12.33"/>
				<gear name="R2" reverseOnly="true" inverseRatio="11.14"/>
				<gear name="3"  forwardOnly="true" inverseRatio="9.56"/>
				<gear name="4"  forwardOnly="true" inverseRatio="7.43"/>
				<gear name="5"  forwardOnly="true" inverseRatio="5.78"/>
				<gear name="6"  forwardOnly="true" inverseRatio="4.56"/>
				<gear name="7"  forwardOnly="true" inverseRatio="3.47"/>
				<gear name="8"  forwardOnly="true" inverseRatio="2.70"/>
				<gear name="9"  forwardOnly="true" inverseRatio="2.09"/>
				<gear name="10" forwardOnly="true" inverseRatio="1.63"/>
				<gear name="11" forwardOnly="true" inverseRatio="1.28"/>
				<gear name="12" forwardOnly="true" inverseRatio="1.00"/>
			</gears>
		</gearboxMogli>	
	</vehicle>

In dem vehicle-Abschnitt sind 12 Vorwärts und 2 Rückwärtsgänge definiert.
Ich weiß nicht, ob ein Unimog 12 Vorwärts-Gänge hat und auch nicht, wie man ihn in der Realität schaltet.
Allerdings kann ich mit dieser Konfiguration, falls diese wirklich als "Default" verwendet werden sollte, alle Fahrzeuge nicht verwenden.

Wenn ich es richtig verstehe, könnte man eine Gruppenschaltung mit jeweils 6 Gängen konfigurieren.
Die Gänge werden damit wahrscheinlich nicht verändert. 
Damit meine ich, dass der Gang in der linken oberen Stellung der Schaltung immer Gang 1 genannt wird, obwohl es je nach Stellung der Bereichsumstellung Gang 1 oder Gang 7 wäre. 
Lässt sich eine Doppel-H-Schaltung konfigurieren, damit links oben jeweils Gang 1 oder Gang 7 ist?
Wenn nicht, wäre es natürlich trotzdem eine Alternative, mit der ich auskommen könnte, wenn man 6 Gänge und eine Gruppe mit zwei Stellungen definiert.

Vielleicht wäre aber auch ein Namesmapping mögich. 

Z.B.: <gear id="1" nameMapping="I=>1|II=>7"  forwardOnly="true" inverseRatio="3.47"/>

Soll bedeuten: Wenn in Gruppe1 range="I" aktiv ist, heißt der Gang "1" und wenn range="II"aktiv ist, heißt der Gang="7". 
Über id="1" erfolgt die Zuordnung zu dem Keymapping "Getriebe: G27 1" in der Konfiguration.
D.h., ist der Hebel im TH8A Shifter auf Stellung 1, wird abhängig vom ausgewählten Bereich über Gruppe 1 entweder Gang "1" oder Gang "7" angezeigt.

Viele Grüße

Martin

**Comment by Mogli12** [comment]
Hallo Martin,

die Default-Konfiguration kann ich irgenwann man ändern. Allerdings hatte ich mich da eher an der automatischen ZF-Schaltung orientiert. Und die wird im manuellen Modus sequentiell geschaltet.

Aber die Konfiguration macht so Sinn. Schau mal bei den beiden amerikanischen Trucks. Es gibt eine Möglichkeit je nach Gruppe einen anderen Namen für den Gang anzuzeigen. Ich bin mir aber nicht sicher, ob das selbsterklärend ist.

Viele Grüße, Stefan

**Comment by RuppMartin001** [comment]
Hallo Stefan,

Super, genau das was ich gesucht hatte!

Hier ist die Konfiguration:

	<vehicle>
		<configFile xmlName="defaultTrucks"/>

		<gearboxMogli speedLimiter="true" maxForwardSpeed="93" maxBackwardSpeed="93" autoStartStop="true" enableAI="true">
			<blowOffVentilSound volume="0"/>
			<gears axleSpeed="2.71" tireWidth="600" tireRatio="50" rimDiameter="22.5" defaultGear="1" automatic="true">
				<gear name="1"  forwardOnly="true" inverseRatio="15.86">
				     <extraName range1="1" name="1"/>
				     <extraName range1="2" name="7"/>
				</gear>	
				
				<gear name="2"  forwardOnly="true" inverseRatio="12.33">
				     <extraName range1="1" name="2"/>
				     <extraName range1="2" name="8"/>
				</gear>	
				    
				<gear name="3"  forwardOnly="true" inverseRatio="9.56">
				     <extraName range1="1" name="3"/>
				     <extraName range1="2" name="9"/>
				</gear>	
				
				
			        <gear name="4"  forwardOnly="true" inverseRatio="7.43">
				     <extraName range1="1" name="4"/>
				     <extraName range1="2" name="10"/>
				</gear>					

				<gear name="5"  forwardOnly="true" inverseRatio="5.78">
				     <extraName range1="1" name="5"/>
				     <extraName range1="2" name="11"/>
				</gear>					
				
				<gear name="6"  forwardOnly="true" inverseRatio="4.56">			
				    <extraName range1="1" name="6"/>
				     <extraName range1="2" name="12"/>
				</gear>					
				
				<gear name="R" reverseOnly="true" inverseRatio="14.68">
				    <extraName range1="3" name="R1"/>
				    <extraName range1="4" name="R2"/>
				</gear>								
				
			</gears>
   	    	        <ranges defaultRange="1" shiftTimeMs="900">
				<range ratio="0.2200" name="I"  forwardOnly="true"/>
				<range ratio="1.0000" name="II" forwardOnly="true"/>
				<range ratio="0.7772" name="I"  reverseOnly="true"/>
				<range ratio="1.0000" name="II" reverseOnly="true"/>
	               </ranges>
		</gearboxMogli>	
	</vehicle>	

Vielen, vielen Dank Stefan und viele Grüße

Martin

**Comment by Mogli12** [comment]
Hallo Martin,

mit Version v2.1.1.9 werden die Tasten zum hoch-/runterschalten  zu Togglebuttons, wenn es genau 2 Gänge oder Gruppen gibt.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo Martin,

ich habe in v2.1.2.0 drei neue Tasten fürs Wechseln mit einer Taste spendiert: KEY_rctrl KEY_quote (ö) für Gänge, KEY_rctrl KEY_backslash (#) für Gruppe 1 und KEY_rctrl KEY_rightbracket (+) für Gruppe 2. Siehe dazu auch Issue #145 

Viele Grüße, Stefan

**Comment by RuppMartin001** [comment]
Hallo Stefan,

vielen Dank, dass du daran gedacht hast für mich etwas zu implementieren und auch die Zeit dafür geopfert hast.
Ich war die letzten Tage im Urlaub und konnte es deshalb leider nicht ausprobieren.

Heute habe ich es versucht, hatte aber kein Glück.
Wahrscheinlich mache ich etwas falsch!
Ich habe eine Taste auf "Gruppe wechseln" konfiguriert.
Wenn ich die Taste anklicke, wechselt auch die Gruppe und ich komme in den Gang-Bereich 7-12.
Leider tut sich nichts, wenn ich die Taste erneut anklicke.  Auch nicht, wenn ich sie mehrmals anklicke.
So wie ich es verstanden habe, sollte die Gruppe wechseln und ich sollte wieder den Gang-Bereich 1-6 erhalten.
Das Zurückwechseln funktioniert auch nicht wenn ich RCTRL + # verwende.
Mache ich etwas falsch?
Ich verwende die Konfiguration, wie oben für default Trucks.

Viele Grüße

Martin

**Comment by Mogli12** [comment]
Hallo Martin,

kannst Du es nochmal mit Version 2.1.2.3 probieren? Du musst auf jeden Fall auch die rechte Strg- (Ctrl-) Taste drücken. Ich habe die Tasten getrennt.

Viele Grüße, Stefan

**Comment by RuppMartin001** [comment]
Hallo Stefan,
ich habe es gestern ausprobiert.
Nun funktioniert es prima.
Ich habe die Gangschaltung Thrustmaster TH8A. Sie hat 7 + 1 Gänge. Ich habe den 7. Gang mit dem Wechseln der Gruppe 1 belegt und kann nun mit dem 7. Gang den Gangbereich wechseln.
Auch der Bereich für die Rückwärtsgänge ist wechselbar. Somit habe ich jetzt 2 Rückwärtsgänge und 12 Vorwärtsgänge.
Vielen vielen Dank für deine Mühe und die Zeit!

Viele Grüße

Martin
