### ISSUE TITLE
PTO maybe issue

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/GearboxAddon#138]
Hi Stephan, sorry to disturb but I got a problem maybe (normal), when I use a trailer with overload system which is useless for the rest like "FS17_kotteUniversalPack.zip" trailer you know (maybe not officially supported idk) for transport various liquids with kotteUni_mini that I rent the overload PTO is already and permanently engaged when attached at shop as example. I had not paid attention until one time (yesterday) with attached PTO load was not activate at rent and then the tractor caseIH1455 or the newHolland8340 can road fine, after save the game and reload it all the other times the tractor is very heavy load that can you think ^^ and it is not unload on road then I would know if it's a mod kotteUniversalPack issue or gearbox normal process? or do I have a conflict somewhere you know?
Br

**Comment by Mogli12** [comment]
Do you use FS17_FuelUsageDisplay?

**Comment by Anonymous-any** [comment]
yes ! :/ :)

**Comment by Anonymous-any** [comment]
Hi that solve the issue by remove it thank Stephan.
