### ISSUE TITLE
Ausrollen / Rollresistenz

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#139]
Servus,
Hier fasse ich zwei Fehler zusammen da sie recht ähnlich sind.
Erstens so lange man im Rückwärtsgang ist kann man nicht vorwärts rollen so wie umgedreht.
Zweitens gibt es keine Rollresistenz so lange man die Kupplung durch drück spricht die Fahrzeuge rollen für immer weiter, das zweite wurde schon mal in einer Fehlermeldung auf Englisch gemeldet aber wie es aus schaut tut sich daran nix mehr also wollte ich es noch mal erwähnen.

Mit freundlichen Grüßen,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,
man kann durchaus mit eingelegtem Gang zurück rollen. Aber bei Fahrzeugen mit "AutoHold" wird halt automatisch gebremst. Und hier geht es um eine Getriebesimulation. Wenn die Kupplung getreten ist, dann bremst der Motor halt nicht mehr. Für Rollwiderstand nimm doch bitte moreRealistic. Generell wären die beiden Themen ohnehin - wenn überhaupt - Wünsche für Verbesserungen. Aber dass das gleich als Fehler klassifiziert wird, steigert nicht meiner Lust mich damit zu befassen.
Gruß, Stefan

**Comment by BlaggyXD** [comment]
Ich glaube du verstehst mich falsch , so lange man im Vorwärts gang ist kann man nicht Rückwärts rollen und um gekehrt.

**Comment by BlaggyXD** [comment]
Anfangs wurden die Fehlermeldungen noch angenommen und bearbeitet , aber was jetzt gerade passiert ist einfach nur traurig. Schade um den schönen mod.
