### ISSUE TITLE
4wd und differentialsperren

### ISSUE THREAD

**Issue by paeppchen** [Mogli12/GearboxAddon#141]
Hallo,
Euer Gearbox mod ist absolute Spitze! Aber wäre es möglich allrar und Differentialsperren einzubauen, damit man nicht auch noch den Drivecontrol mod braucht? Oder habe ich die Funktion einfach noch nicht gefunden?
Anyway, super Arbeit und im spiel super fun.
Liebe Grüße
Rolf

**Comment by Anonymous-any** [comment]
Hi I was try to found a mod that do full options 4wd and a winch for pulling vehicles from mud :) but only drivecontrol I found do the trick. I'm not sure Gearbox must do it but it will be a must for sure.
