### ISSUE TITLE
Fahrzeuge mit Rückfahrpiepen verursachen Call Stack auf Dedi Server

### ISSUE THREAD

**Issue by AGesSonnenschein** [Mogli12/GearboxAddon#142]
Hi,
habe vorhin mal beim Siloking Gb eingeschaltet.
Als ich dann Rückwärts gefahren bin,
tauchte folgender Fehler in der Console auf:
Warning (Script): Unknown entity id 167471 in method 'playSample'.
LUA call stack:
  dataS/scripts/utils/SoundUtil.lua (165) : playSample
  =C:/Users/dhein_000/Dokumente/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua (3007)
  =[C] (4294967295)
  =C:/Users/dhein_000/Dokumente/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogliLoader.lua (45) : pcall
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Client.lua (64) : update
  dataS/scripts/BaseMission.lua (1511) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
Warning (Script): Unknown entity id 167471 in method 'stopSample'.
LUA call stack:
  dataS/scripts/utils/SoundUtil.lua (174) : stopSample
  =C:/Users/dhein_000/Dokumente/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua (3009)
  =[C] (4294967295)
  =C:/Users/dhein_000/Dokumente/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogliLoader.lua (45) : pcall
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Client.lua (64) : update
  dataS/scripts/BaseMission.lua (1511) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update

Scheint bei allen Fahrzeugen zu sein die Rückwärts piepen eingetragen haben, beim Holmer oder einem Radlader war es das selbe.

Greetz Dennis

**Comment by Mogli12** [comment]
Hi,
ich überlege noch, wie ich das korrigieren kann. Aber es sollte im Spiel keine Probleme bereiten. Das ist nur eine Warnung. Im Gegensatz zum Fehler macht die Engine dann einfach weiter und man kann es ignorieren.
Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo,

es sollte mit Version 2.1.2.9 korrigiert sein.

Viele Grüße,
Stefan
