### ISSUE TITLE
Changing the HUD

### ISSUE THREAD

**Issue by Ciggy001** [Mogli12/GearboxAddon#143]
Is it possible to edit the HUD so that it looks the same as the others?

**Comment by Mogli12** [comment]
I felt that the HUD is sometime quite big. This is why it is transparent. You can hide the HUD with KEY_slash.

**Comment by Ciggy001** [comment]
I don't wish to hide it, just change the look of it.

**Comment by Mogli12** [comment]
How? I want to keep it transparent. Please make a proposal.
