### ISSUE TITLE
AutoHold question

### ISSUE THREAD

**Issue by DrewCZ** [Mogli12/GearboxAddon#144]
Hello, I have one question about config parameters. Please can you describe how to turn on/off 'AutoHold' parameter and Handbrake? Or can I config this e.g. by some clutch or global parameters?
Because I'm using keyboard with 'autoclutch' mode, and e.g. cars, where is safe roll out with 'neutral' (no gear). 
As handbrake I use key **;** which turn on 'AutoHold' when vehicle stops, but handbrake (with that nice icon) will be better.
No informations in 'description.pdf' was seen. I promise nobody of my drivers will use neutral in tractors! :-)
Thank you, 
DrewCZ

**Comment by Mogli12** [comment]
Hi,
I am working on it. I developed that in FS15. and in FS15 driveControl had the handbrake. Now I have to create my own handbrake.
Regards, Stefan

**Comment by Mogli12** [comment]
Ok, _KEY_semicolon_ (german ö) only toggles neutral. Automatic is switched on and off with _KEY_rctrl KEY_slash_ (german -). Handbrake is toggled with _KEY_rctrl KEY_space_.

**Comment by DrewCZ** [comment]
Stefan, that's amazing. I'll download and try new commit. Your mods and Season are two, which totally change FS17. Thank you so much.
DrewCZ

**Comment by DrewCZ** [comment]
Great, it works! Only one thing is strange. In **mod xml** must be defined global value:
    <gearboxMogliGlobals>
	<defaultOn     type="bool" value="false"/>      		
    </gearboxMogliGlobals>
Somethink like 'reset'... Then everythinnk works. If that 'global' is missing, no way how to work with 'neutral' and 'handbrake'. Everytime when I set on 'neutral', after short time AutoBrake is applied. But his is only for your information, I'm now lucky with heavy road trailer roll down from the hills :-)
Regards, Ondřej aka DrewCZ
