### ISSUE TITLE
Lastschaltung,zwei mal hoch schalten ist ein mal runter

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#145]
Servus,
Seit der v2.1.1.9 lässt sich eine LS mit einer Stufe ( z.B. Deutz Agrostar) runter schalten in dem man zwei mal hoch schaltet also:  
I , hochschalten
II, hoch schalten 
I , und so weiter und so fort.
Ich hoffe ich konnte den Fehler verständlich machen

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

mit v2.1.2.0 sollte es behoben sein. Details findest Du in #137.

Viele Grüße, Stefan

**Comment by BlaggyXD** [comment]
Servus Mogli,

Jetzt geht wieder alles wie es soll , vielen dank für die Hilfe.

Viele Grüße,
Blaggy
