### ISSUE TITLE
Exorbitant hoher Spritverbrauch beim abwürgen des Motors

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#146]
Beim herum spielen mit der Contest Seilwinde ist mir aufgefallen das bei der neusten Version, wenn man den Motor abwürgt ein exoribitant hoher Spritverbrauch entsteht und der Tank innerhalb weniger Millisekunden leer ist. Das hat aber nichts mit der Winde zu tun, auch wenn ich einen schweren Anhänger ziehe und den Motor abwürge passiert das. 

Hier im Video => https://youtu.be/4g5BJyFLLgI

Grüße Maxter

**Comment by BlaggyXD** [comment]
Servus ,
Das hängt mit dem Spritverbrauch mod zusammen , am besten ein mal STRG + T drücken dann geht der Verbrauch nicht mehr nach Last sondern nach Drehzahl und der Bug ist weg.

Grüße ,
Blaggy

**Comment by MaxterTM** [comment]
Danke hat geholfen 👍

**Comment by Mogli12** [comment]
Ah, FS17_FuelUsageDisplay!
