### ISSUE TITLE
MR/GEARBOX/COURSEPLAY freeze

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#147]
My game is freezing when stopping Courseplay (sometimes starting the course as well) from running a course..   seems to be something new..  here is the log

It seems to be a conflict between GearboxAddon 2.1.1.9 and MR when stopping a CP course.

When I take either MR or Gearbox Addon out of the mods folder, it works fine.

https://gist.github.com/sootysax/431e4f130fbb471d8d02b677bcdb8622

**Comment by Mogli12** [comment]
Hi,
The problem is caused by Courseplay. Courseplay turns on the MR transmission even though GearboxAddon turned it off. I will try to fix it on my side with v2.1.2.2 of the GearboxAddon.
Regards, Stefan

**Comment by sootysax** [comment]
seems to be working thanks!
