### ISSUE TITLE
GearboxAddon im Multiplayer

### ISSUE THREAD

**Issue by BlackscreenHD** [Mogli12/GearboxAddon#148]
Hallo,

Wir haben folgendes Problem, wenn wir das GearboxAddon im Multiplayer verwenden wollen: Die Synchronisation bricht nach wenigen Sekunden ab. Ohne GBAddon läuft es einwandfrei und wir würden gerne mit dem GearboxAddon spielen.

Die Log gibt bei uns keinerlei Auskunft darüber und es handelt sich nicht um einen Server, sondern um ein von mir gehostetes Spiel.

**Comment by Mogli12** [comment]
Hallo,

so eine Problembeschreibung gab es schon mehrfach. Aber bislang war immer ein anderer Mod "Schuld", z.B. #136.

Viele Grüße, Stefan

**Comment by BlackscreenHD** [comment]
Hallo,

ja, kann immer sein,dass ein anderer Mod dazwischen funkt. Weißt du an welchem Mod es gelegen hat bei dem Beispiel? Oder weißt du welche mods sich generell nicht "vertragen"?

MfG
Nick

Am 16.06.2017 21:24 schrieb Stefan Biedenstein <notifications@github.com>:

Hallo,

so eine Problembeschreibung gab es schon mehrfach. Aber bislang war immer ein anderer Mod "Schuld", z.B. #136<https://github.com/Mogli12/GearboxAddon/issues/136>.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo,

kannst Du die kompletten Logs (Server und Client) bei Gist hochladen? Vielleicht sieht man ja was...

Viele Grüße, Stefan

**Comment by BlackscreenHD** [comment]
So,
hat leider ein bisschen gedauert, aber wir haben gestern Abend mal wieder Zeit gefunden und haben es erneut mit dem GearboxAddon versucht. Eine Syncronisation findet immer noch nicht statt.

Deswegen hier mal die Logs:

Host: https://gist.githubusercontent.com/BlackscreenHD/f30321b6f4a83b38a482a18a4e67877a/raw/2159466d703463cb9cb27e49d9c1cdd128dc1244/Log%2520von%2520mir%2520(Host)
Mitspieler:
https://gist.githubusercontent.com/BlackscreenHD/395b45eaff7f91bdee4d67ee208df81c/raw/c77914f87e2499e43edbfbb794db9f420b348f57/Log%2520vom%2520Mitspieler

**Comment by Mogli12** [comment]
Hallo,

folgender Abschnitt ist im Server Log ist problematisch:
```
Tom. joined the game
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/specializations/events/VehicleSetBeaconLightEvent.lua(53) : attempt to index field 'object' (a nil value)
```
Danach bricht das MP Coding anscheinend ab. Das Problem kann durch irgendeinen Mod verursacht werden. Es gibt auch keinen Hinweis darauf, welcher Mod es ist.

Viele Grüße, Stefan

**Comment by BlackscreenHD** [comment]
Hallo,

der Abschnitt ist mir auch schon aufgefallen. Habe da jetzt auch eine Vermutung an welchem oder welchen Mods es liegen könnte. Jetzt beginnt das Testen....

Ich melde mich zurück, wenn ich den Übeltäter gefunden habe.

**Comment by Mogli12** [comment]
Hallo,

kannst Du es mal mit Version 2.1.3.1 (oder wenigstens 2.1.2.9) probieren?

Viele Grüße, Stefan
