### ISSUE TITLE
Stufenlos manuell fahren

### ISSUE THREAD

**Issue by VarioTA** [Mogli12/GearboxAddon#149]
Hallo,

also ich nutze das Gearbox Addon seit einiger Zeit und mit großer Begeisterung! Jetzt frage ich mich aber, ob es wohl möglich ist, die Übersetzung bei den stufenlosen Getrieben wie bei den echten Varios auch manuell anpassen zu können. Man kann zwar natrürlich den Fahrbereich wählen, nicht aber die Übersetzung. Wenn diese Funktion möglich ist, dann wüsste ich gerne, wie ich sie nutzen kann  :)

**Comment by Mogli12** [comment]
Hallo,

das ist eine gute Idee. Man kann es mit key1="KEY_rshift KEY_equals" (ß) key2="KEY_rshift KEY_minus" (´) einstellen. Probier mal Version 2.1.2.1 und schreib mal wie Du es findest.

Vielen Dank,
Stefan

**Comment by VarioTA** [comment]
Wow, das sieht ja schonmal sehr gut aus! Und danke für die schnelle Lösung!

Also bei straßenfahrten funktioniert es super, man kann auch sehr schön mit Motorbremse fahren. Die Anzeige der eingestellten Übersetzung ist Vorbildlich! Leider funktioniert es scheinbar aber nicht mit Handgas und (wo es noch stört) bei Zapfwellenarbeiten (also mit vorgegebener Zieldrehzahl ohne benutzung des Fußgases). Man kann auch nicht im Standgas rein über das Getriebe (an)fahren. Während der Fahrt lässt sich die Drehzahl (je nach fahrzeug) nicht unter ca.1300 Touren drücken. Außerdem regelt mir persönlich die Übersetzung etwas zu schnell.
Das wären erstmal meine ersten Eindrücke mit meckern auf hohem Niveau. Auf jeden Fall vielen lieben Dank, so schnell hätte ich das nicht erwartet! Leider habe ich von der Materie so gut wie keine Ahnung, meinen Respekt hast Du!

Gruß
VarioTA

**Comment by VarioTA** [comment]
Wow, das sieht ja schonmal sehr gut aus! Und danke für die schnelle Lösung!

Also bei straßenfahrten funktioniert es super, man kann auch sehr schön mit Motorbremse fahren. Die Anzeige der eingestellten Übersetzung ist Vorbildlich! Leider funktioniert es scheinbar aber nicht mit Handgas und (wo es noch stört) bei Zapfwellenarbeiten (also mit vorgegebener Zieldrehzahl ohne benutzung des Fußgases). Man kann auch nicht im Standgas rein über das Getriebe (an)fahren. Während der Fahrt lässt sich die Drehzahl (je nach fahrzeug) nicht unter ca.1300 Touren drücken. Außerdem regelt mir persönlich die Übersetzung etwas zu schnell.
Das wären erstmal meine ersten Eindrücke mit meckern auf hohem Niveau. Auf jeden Fall vielen lieben Dank, so schnell hätte ich das nicht erwartet! Leider habe ich von der Materie so gut wie keine Ahnung, meinen Respekt hast Du!

Gruß
VarioTA

**Comment by Mogli12** [comment]
Hallo VarioTA,

ich habe das erstmal schnell beim Ermitteln der "richtigen" Übersetzung eingebaut. Dabei gilt aber weiterhin, dass die Drehzahl nicht unter die minimale Zieldrehzahl (ca. 1300 U/min) fallen soll. Zusammen mit Standgas wird es wohl nicht funktionieren. Soll man es dann ausschalten?

Viele Grüße, Stefan

**Comment by VarioTA** [comment]
Hallo Stefan,

was mir noch sehr gut gefallen würde, wäre halt, dass man mit aktivierter zapfwelle die Fahrgeschwindigkeit über das getriebe regeln kann. Also wie beim Schaltgetriebe, wo man die feste zieldrehzahl (zb wegen aktivierter Zapfwelle) hat und dann nur durch hoch- und runterschalten die Fahrgeschwindigkeit ändern kann. Das "fehlt" mir beim stufenlosen noch. Ich habe aber wie gesagt kaum Ahnung von der Materie, weiß also nicht, ob das geht oder wie aufwändig das wäre. Die minimale Zieldrehzahl (ca. 1300 U/min) finde ich bei manueller Einstellung der Übersetzung nicht nötig, da wäre es mir persönlich lieber, wenn man auch untertourig fahren kann.

Gruß,
VarioTA

**Comment by Mogli12** [comment]
Hallo VarioTA,

zum Regeln der Geschwindigkeit nimmst Du am besten den Tempomat oder die Taste KEY_delete (entf). Ich habe die feste Übersetzung jetzt mal automatisch deaktiviert, sobald die Zapfwelle an ist.

Viele Grüße, Stefan

**Comment by VarioTA** [comment]
Hallo Stefan,

stimmt, den Tempomat gibt´s ja auch noch 😆 

Lässt sich die feste Übersetzung denn theoretisch auch für zapfwellenarbeiten oder Handgas aktivieren? Oder gibt's da Komplikationen? Ich als Laie verstehe einfach nicht so ganz, warum es nur mit fußgas funktioniert.
Dass es überhaupt funktioniert finde ich schonmal ganz große klasse, keine Frage! Ich bin halt nur irritiert, dass es nur mit Fußgas funktioniert.

Gruß,
VarioTA

**Comment by Mogli12** [comment]
Hallo VarioTA,

bei Handgas oder Zapfwelle ist die Drehzahl konstant und die Geschwindigkeit wird über die Übersetzung gesteuert. Im Grunde steuert hier das Gaspedal nur noch die Übersetzung.

Bei fester Übersetzung ist aber die Übersetzung konstant und die Geschwindigkeit wird über die Drehzahl gesteuert. 

Daher kann ich mir beides zusammen einfach nicht vorstellen. Aber falls Du noch eine gute Idee hast, dann bin ich für Vorschläge offen.

Viele Grüße, Stefan

**Comment by VarioTA** [comment]
Hallo Stefan,

bei Schaltgetrieben hat man doch auch eine feste Drehzahl (bei aktivierter zapfwelle/Handgas oder eben standgas) und eine feste Übersetzung, oder nicht? Wenn ich bei einem Schaltschlepper die Zapfwelle anschalte, dann hält der von selbst die Drehzahl und man kann bequem über das getriebe die Geschwindigkeit regeln, indem man hoch- und runterschaltet. wenn die Motorleistung zb an einer steigung nicht ausreicht, dann geht die Drehzahl runter, der schlepper geht also "in die Knie". Das Fußgas hat praktisch keine Funktion mehr, man kann damit nur die Drehzahl noch weiter erhöhen. genau so sollte es beim stufenlosen auch klappen, das wäre perfekt. der rollt aber trotz fester Übersetzung (ohne Fußgas) einfach bis zum stillstand aus. Die vom Fußgas vorgegebene Übersetzung bei aktivierter Zapfwelle (wie du es oben beschreibst) scheint also eine "höhere Priorität" zu haben als die manuell eingestellte Übersetzung. Ich will die Übersetzung bei aktivierter zapfwelle/handgas nicht mit dem Fußgas, sondern manuell einstellen.

Was ich bei den stufenlosen immer noch nicht ganz verstehe ist, warum man nicht im Standgas manuell über das getriebe anfahren kann. wenn die Übersetzung doch fest ist, wie kann man dann trotzdem noch stehen? die leerlaufdrehzahl ist doch nicht null!?

Gruß,
VarioTA

**Comment by Mogli12** [comment]
Hallo VarioTA,

beim normalen Getriebe gibt es noch die Kupplung. Beim stufenlosen Getriebe kann die Übersetzung ins Unendliche gehen. Es ist also möglich, dass der Traktor bei eingelegtem Gang steht. (Aktive Stillstandsregelung)

Jetzt willst Du aber eine feste Übersetzung vorgeben, was ein Konflikt ist.

Trotzdem habe ich es in v3.0 build 209 gleichzeitig ermöglicht.

Gruß,
Stefan

**Comment by VarioTA** [comment]
Hallo Stefan,

Ich habe es jetzt einige Stunden gefahren und muss sagen, dass es wirklich genial ist. Vielen lieben Dank für deine Mühen, funktioniert einwandfrei!

Gruß,
VarioTA

**Comment by Mogli12** [comment]
Danke
