### ISSUE TITLE
Wendeschaltung

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#15]
Hi, ist das moeglich, den  Fahrtrichtungswechsel wenigstens bei stufenlosen Getrieben oder teilweise stufenlosen Getrieben ein wenig "sanfter" einzustellen? So, wies upsidedown nun mit seinem shutle-modul (Stickwort "soft-reverse" :) ) gemacht hat. Das ruckt doch ganz nett im Moment, oder kann man das selber irgendwo einstellen?

**Comment by Mogli12** [comment]
Hi, das ist leider nicht ganz so einfach. Das Anfahren beim stufenlosen Getriebe will nicht ganz so, wie ich wohl will. Ist die Übersetzung zu klein, dann dreht der Motor einfach nur hilflos hoch. Ist sie aber zu groß, dann würgt man den Motor ggf. sogar ab.

**Comment by Mogli12** [comment]
Hi,
falls Du mit der Tastatur spielst, dann verwende doch Version 1.9b6 von https://github.com/Mogli12/KeyboardSteer.
Viele Grüße

**Comment by cabmac** [comment]
ja danke, ja ich spiele mit Tastatur und dem Keyboardsteer...was hast du da geaendert?

**Comment by Mogli12** [comment]
Ja, mit KeyboardSteer dauert es ca. 1 Sekunde, bis das Fahrzeug wieder Vollgas gibt. Das Gaspedal wird also in der ersten Sekunde nur langsam herunter gedrückt.

**Comment by cabmac** [comment]
ok, diese sekunde ist mir ehrlich gesagt nen Tick zu langsam, dauert eine gefuehlte Ewigkeit :D  bis er umschaltet (wenn man diese mit der vorherigen Version vergleicht)...vielleicht auch Gewoehnungssache...

**Comment by cabmac** [comment]
ups, scheint ja jetzt schoen zu gehen, mit der letzten Verison vor 2 Std....nur, bei Agos. 700er fehlt wohl eine Tastenzuweisung fuer "Wendeschaltung", oder? Womit aktiviert man diese?

**Comment by cabmac** [comment]
hat zwar nichts mit dem "thread" zu tun, aber nur eine kurze Frage, sonst konnte man immer sehen, was du an den einzelnen Versionen geaendert hast, das schreibst du seit ein paar Versionen nicht mehr dazu, oder sinds Kleinigkeiten?
