### ISSUE TITLE
Downshifting gears in auto(easy) mode on hills maps.

### ISSUE THREAD

**Issue by nkstyle** [Mogli12/GearboxAddon#151]
Hello Mogli12.

First, thank you for superb mod GearboxAddon, Im playing with yours mods from years. 

I have little issue with downshifting gears in auto mode on hills maps. For example if I drove forward then change drive back and again change to forward gearbox mod set high gear, when I put full throttle mod dont  downshifting gears, vehicles dont start moving.
On few second later I see on my screen info "clutch is overheating".
If I try downshift manualy works good.
Im playing on xbox360 controller on PC, but on keyboard same situation.

**Comment by Mogli12** [comment]
Hi nkstyle,

You can (or must) choose the launch gear forward and backward when you are in neutral/auto hold/handbrake.

Best regards, Mogli12

**Comment by nkstyle** [comment]
Hi Mogli.

It is works.
How can I miss that, I don't know. 
Thank you.

**Comment by Mogli12** [comment]
Setting the launch gear in neutral is quite new...
