### ISSUE TITLE
Verbesserungsvorschläge 

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#153]
Hallo
Ich hätte hier drei , vier Verbesserungsvorschläge,

So lange man das Handgas benutzt kann man kein Fußgas geben in echt über steuert immer das welches mehr Gas gibt. 

Die Leerlaufanreicherung ist etwas stark evtl. könnte man diese ab schwächen oder ganz weg lassen. Da die meisten Traktoren direkt Einspritzer sind macht es meines Wissens nach auch keinen sinn da sie nur mit einem Vergaser funktioniert.

Wenn der Motor um einiges höher dreht wie die RatedRPM geht das Handgas auch höher was eigentlich gut ist aber dann stimmen die an gaben der Geschwindigkeit welche das Gear Box hud gib nicht mehr.

Seit der V2.1.2.4 (Smoothing of motor torque (500 Nm/s max increase)) bzw. V2.1.2.5 fährt es sich sehr Schwammig und Träge vielleicht könnte man daran auch noch etwas ändern. So wie das runter schalten mit Zwischengas einen ruck nach hinten gibt ob wohl die Drehzahl höher ist wie sie bei dieser Geschwindigkeit in dem Gang wäre. Und beim anfahren ist es auch nicht Ideal da er erst ab ca. 70% der Kupplung Leistung frei gibt / die Last geht erst ab da hoch. 

Mit freundlichen Grüßen Frank

**Comment by Fracking** [comment]
Hi,

zum Thema "Smoothing of motor torque" (ich glaub es sind 500 Nm/s² gemeint): Wenn ein traktor ~1000 Nm bei ~1400 U/min hat, braucht er 2 Sekunden bis er das max. Drehmoment erreicht hat. Bei kleinen Traktoren und leichten Einsetzen mag es das Anfahren weicher machen. Aber bei großen Traktoren die schwere Arbeit verrichten ist das problematisch. Das Automatikgetriebe kommt damit nicht klar.

Bsp.: New Holland T9.565 + schwere Bodenbearbeitung.
Der Schlepper hat ~2400 Nm bei 1400 U/min. Eigentlich ausreichend, aber bei jedem Gangwechsel fängt die 500 Nm/s² Regel erneut an. Die anfänglichen 500 Nm reichen aber nicht aus. Er kann nicht lange genug am Gas hängen um 1000, 1500, 2000 usw. Nm aufzubauen ohne Abzusaufen (er braucht ca. 3-4 Sekunden um das volle Drehmoment zu entwickel).

Im manuell Modus, kann man das noch durch ausreizen der Drehzahl managen. Im automatik Modus schafft er nicht auf Geschwindigkeit zu kommen und Schaltet nur hin und her.

Die Lösung wäre mMn, wenn die 500 Nm/s² nur im Bereich von 1-2 km/h beim Anfahren gilt und durch Schalten nicht resetet wird. Oder 500 Nm/s² durch eine Prozentanteil des Max. Drehmoments ersetzen (womöglich wäre letzteres auch in der Realität denkbar)

Wenn das schon bemerkt wurde und in Bearbeitung ist, will ich nichts gesagt haben. :)

Grüße

Andreas

**Comment by Frank1974** [comment]
Hallo,
 Ich bin eher davon überzeugt das es ganz weg sollte da man egal wie es ist nicht sauber fahren kann da der Motor sehr stark verzögert reagiert auch beim anfahren ist es auch nur nachteil haft. 

Grüße, Frank.

**Comment by Mogli12** [comment]
Hallo,

kurze Umfrage zum "Smoothing of Torque". Benutzt ihr moreRealistic? 

Viele Grüße, 
Stefan

**Comment by Frank1974** [comment]
Hallo, 
Ich nicht.
Grüße, Frank

**Comment by Fracking** [comment]
Ich, ja.

**Comment by Mogli12** [comment]
Ok, ich habe es in Version 2.1.2.7 mal überarbeitet. Die Begrenzung des Drehmoments passiert jetzt nur noch bei
- moreRealistic
- kein analoges Gaspedal
- weniger als 10 km/h

Ist es so besser?

**Comment by Frank1974** [comment]
Ja damit ist es wieder wie mit der alten Version also viel besser , danke für die schnelle hilfe.

**Comment by Frank1974** [comment]
Wann ist die Begrenzung Aktiv , so bald einer der genannten Faktoren zutrifft oder erst wenn alle zutreffen ?

Grüße Frank.

**Comment by Mogli12** [comment]
Die Begrenzung ist nur aktiv, wenn alle Faktoren erfüllt sind.

**Comment by Fracking** [comment]
Hi,
die Bodenbearbeitung mit MR geht wieder deutlich besser.

Der Tempomat macht aber noch Probleme (war auch in der letzten Version). Wenn ich den Tempomat einlege beschleunigt er mit maximaler Drehzahl. Das macht sich besonders bei stufenlosen Getrieben bemerkbar.

Grüße

Andreas

**Comment by Frank1974** [comment]
Hallo,
Ich wollte das her noch mal etwas schreiben das es nicht in Vergessenheit gerät.

Grüße Frank

**Comment by Mogli12** [comment]
Hallo Frank,

welche Probleme bestehen denn noch und sollen nicht in Vergessenheit geraten? Dass der Tempomat mit maximaler Drehzahl beschleunigt, halte ich für ok. Man kann das aber auch mit "KEY_rshift KEY_leftbracket" (RShift-Ü) und "KEY_rshift KEY_quote" (RShift-Ä) einstellen.

Viele Grüße

**Comment by Frank1974** [comment]
Hallo Stefan,
das hier meine ich 
( Vorschlag 1-3 ,4 wurde ja schon bearbeitet) 

> So lange man das Handgas benutzt kann man kein Fußgas geben in echt über steuert immer das welches mehr Gas gibt.

> Die Leerlaufanreicherung ist etwas stark evtl. könnte man diese ab schwächen oder ganz weg lassen. Da die meisten Traktoren direkt Einspritzer sind macht es meines Wissens nach auch keinen sinn da sie nur mit einem Vergaser funktioniert.

> Wenn der Motor um einiges höher dreht wie die RatedRPM geht das Handgas auch höher was eigentlich gut ist aber dann stimmen die an gaben der Geschwindigkeit welche das Gear Box hud gib nicht mehr.

Grüße Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

> So lange man das Handgas benutzt kann man kein Fußgas geben in echt über steuert immer das welches mehr Gas gibt.

Das ist meiner Ansicht nach von Traktor zu Traktor verschieden. Vor allem bei stufenlosen Getrieben stellt man übers Handgas die Drehzahl ein und übers Fahrpedal bestimmt man die Geschwindigkeit.
> Die Leerlaufanreicherung ist etwas stark evtl. könnte man diese ab schwächen oder ganz weg lassen. Da die meisten Traktoren direkt Einspritzer sind macht es meines Wissens nach auch keinen sinn da sie nur mit einem Vergaser funktioniert.

Auch ein moderner Traktor verbraucht Diesel im Stand. Schubabschaltung, d.h. dass im Schiebebetrieb kein Diesel verbraucht wird, macht das Getriebe ohnehin schon.

> Wenn der Motor um einiges höher dreht wie die RatedRPM geht das Handgas auch höher was eigentlich gut ist aber dann stimmen die an gaben der Geschwindigkeit welche das Gear Box hud gib nicht mehr.

Inwiefern stimmt die Geschwindigkeit nicht mehr. Hast Du es mit der aktuellsten Version probiert.

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,

> Das ist meiner Ansicht nach von Traktor zu Traktor verschieden. Vor allem bei stufenlosen Getrieben stellt man übers Handgas die Drehzahl ein und übers Fahrpedal bestimmt man die Geschwindigkeit.

Das mit dem Handgas ist nur bei Stufenlosen so , sonst steuert immer das Gas welches höher ist.

> Auch ein moderner Traktor verbraucht Diesel im Stand. Schubabschaltung, d.h. dass im Schiebebetrieb kein Diesel verbraucht wird, macht das Getriebe ohnehin schon.

Das kann gut so sein , aber ich habe bis her noch nie etwas von einem 0815 Schaltgetriebetraktor gehört der eine Leerlaufanreicherung hat (Zumindest keine die bis zur Nenndrehzahl hoch dreht wie es hier der Fall ist) oder eine Schubabschaltung. 

Evtl. verstehen wir uns hier auch falsch , ich hab in irgend einer Issue mal gelesen das die Leerlaufanreicherung für das hoch drehen wenn man die Kupplung kommen lässt verantwortlich ist.

> Inwiefern stimmt die Geschwindigkeit nicht mehr. Hast Du es mit der aktuellsten Version probiert.

z.b. Die Nenndrehzahl ist 2200 er dreht hoch bis 2600 , das Handgas geht bis zu 2500 und zeigt bei 2500 die Geschwindigkeit an welche schon bei 2200 erreicht sein sollte.

Grüße Frank.

**Comment by Frank1974** [comment]
( Das letzt ist rein Visuell im Gearbox Hud )

**Comment by Mogli12** [comment]
Ok, probier mal Version 2.1.4.5

**Comment by Frank1974** [comment]
Hallo Mogli,
 Beim Handgas ist es jetzt so das es beim Automatik so ist wie es sein sollte (das höhere gibt vor) , beim Stufenlos ist es so das er beim Beschleunigen nicht hoch dreht aber sich dann wieder fängt aber immer noch nicht so wie das Handgas es vorgibt hoch dreht ( nur bei einer sehr niederen vor gabe) und beim Schaltgetriebe ist es noch gleich wie davor also das Handgas übersteuert das Fußgas.

Das mit dem hoch drehen beim Anfahren ist immer noch gleich.

Die Km/h Angabe im GB Hud passt jetzt. 

Grüße Frank.

**Comment by Frank1974** [comment]
Hallo , 
Mit der Version 2.1.5.3 ist jetzt auch das mit den Hand- und Fußgas richtig , jetzt fehlt nur noch das hoch drehen beim anfahren dann wären alle meine Vorschläge umgesetzt.

Grüße Frank.

**Comment by Frank1974** [comment]
Hallo,
Entschuldigung das ich noch mal frage,aber ist das hier wieder in Vergessenheit geraten ?
Oder ist das letztere nicht Lösbar ?

Grüße Frank.

**Comment by Frank1974** [comment]
Hallo Stefan,
Gibt es da gar keine Möglichkeit das irgend wie abzuschwächen ?
Bei ca. 10% Kupplung dreht der Motor bis auf seine Maximaldrehzahl und wenn man dann die Kupplung schnell los lässt schießt er los wie eine Rakete. Beim Rangieren ist das teil weise sehr nervig da man nicht sanft anfahren kann ohne dass der Motor voll hochdreht.

Mit der V2.0.4.8 wo die Kupplung noch so war das sie bei 50% ohne schleifen geschlossen hat war das so minimal dass er meistens nur 50 oder 100 Touren höher gedreht hat könnte man das wieder so machen oder geht das nur wenn man die Kupplung dann wieder so zu sagen Digital ist?
Bzw. war das damals so weil die Kupplung so weit geschlossen hat das der Motor nicht genug Leistung hat um hoch zu drehen ?

Grüße Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

ich verstehe nicht, warum der Motor bei 10% Kupplung nicht bis zur Maximaldrehzahl hoch drehen sollte. Ab Version 2.0.4.9 wurde das maximal übertragbare Drehmoment der Kupplung begrenzt. Ich denke, dass das auch einigermaßen der Realität entspricht. Da muss man halt vorsichtiger Gas geben. Wenn Du nur mit der Tastatur spielst und daher nur ein digitales Gaspedal hast (0% oder 100%), dann solltest Du die Kupplung auf automatisch stehen lassen.

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,
genau des wegen habe ich es ja angesprochen , ich verstehe das auch nicht.
Ich spiele mit einem Lenkrad mit drei Pedalen also Kupplung , Bremse und Gas beim anfahren gib ich keinerlei Gas ich lasse nur das Kupplungspedal langsam los ( wie in echt mit einem Diesel bzw. Traktor auch) wenn ich bei ca. 10% Kupplung bin dreht der Motor hoch ohne das ich irgend etwas außer dem Kupplungspedal betätige.

Grüße Frank.

**Comment by BlaggyXD** [comment]
Servus,
Ich hab mal ein Video dazu gemacht evtl. siehst du dann besser was damit gemeint ist.

Zum Video,
da es "nur" in 30Fps auf genommen ist sieht man nicht wie schnell die Drehzahl ( also das halb durchsichtige grüne und motor.lastThrottle) eigentlich schwankt. Beschrieben ist es ca. so schnell das man es kaum sieht aber das grüne etwas dunkler und durchsichtiger und die vorderen zwei zahlen (10) von den 100 flackert auch sehr schnell so das man zwar dauerhaft 100 sieht aber es halt flackert.
 
Zum Profiler / G27 anzeige/ anzeige wie weit und welches Pedal ich drücke:

![g27_profiler_legende](https://user-images.githubusercontent.com/20562677/29614533-c62537ca-880a-11e7-8b99-ff9c81964b36.png)

und zum Schluss noch das [Video](https://youtu.be/1y8BOkEqybA) 
(das Video wird ca. 15Min. nach dem ich das hier geschrieben hab aufrufbar sein)

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Ich habe die Leerlaufreicherung mal etwas geglättet. Damit sollte das Problem nicht mehr so stark auftreten, aber der Leerlauf mit eingelegtem Gang wird wohl etwas sägen.

**Comment by BlaggyXD** [comment]
Servus,
jetzt ist sind es nur noch ca. 50-70 Touren die der Motor hoch dreht wenn man bei 10% Kupplung ist. Damit lässt es sich viel angenehmer fahren , er macht zwar noch einen kleinen Satz wenn man die Kupplung dann schnell kommen lässt und ist bei ca. 1100 Touren aber das ist um Welten besser wie davor. 

Super arbeit.

Grüße,
Blaggy

**Comment by Frank1974** [comment]
Hallo,
dito.
Ich denke so kann man es lassen.

Und da alles abgehackt ist kann ich die Issue ja schließen ?

Grüße Frank.
