### ISSUE TITLE
Speed/Gearing issue on Case 1455 XL

### ISSUE THREAD

**Issue by Dwinesk** [Mogli12/GearboxAddon#154]
I have noticed a speed/gearing problem with the case 1455 xl and any mod variant of the same. the tractor only does Kph 42 vanilla. but with gearboxaddon its top speed is Kph 52 without the appropriate gearing to get to that speed.

**Comment by Mogli12** [comment]
The Case does not have a speed limiter IRL.

**Comment by Dwinesk** [comment]
Ok, I understand now. Thanks for the clarification.
