### ISSUE TITLE
Beschleunigung bei Vollgas etwas mau

### ISSUE THREAD

**Issue by mieperDE** [Mogli12/GearboxAddon#156]
Ich habe ein Problem mit dem JCB 260 Eco. Bei vollgas beschleunigt er einfach kaum.
Er beschleunigt erst richtig wenn er im Drehzahllimit läuft.
Als würde das Fahrzeug eine träge **Fliehkraftkupplung** haben.
Der Kompaktlader hat aber einen hydrostatisch betätigten Hauptantrieb.

https://youtu.be/e99X3roWpfM

http://www.bng-schlueter.de/images/phocadownload/Download/JCB/Kompaktlader/Datenblatt225-330.pdf

Auch das schnappen lassen der Kupplung macht keinen Unterschied.

Bei den anderen Fahrzeugen ist es mir auch aufgefallen. Nicht so extrem. Aber es fühlt sich dennoch nicht wie ein echtes Gaspedal an.

Grüße ;)

Edit:
Version v2.1.2.8

**Comment by mieperDE** [comment]
Hab gerade festgestellt das ein Richtungswechsel sofort funktioniert. Rückwärts gibt es einen Raketenstart. Vorwärts kommt kaum was.

**Comment by Jan238** [comment]
Mich hat das langsame Reagieren der hydrostatischen Getriebe auch gestört.

Als Lösung habe ich folgende Werte in der gearboxMogli.lua geändert:
gearboxMogliGlobals.momentOfInertiaBase  auf 1   
gearboxMogliGlobals.momentOfInertia auf 2 

Ich hoffe, dass das dein Problem löst.

**Comment by Mogli12** [comment]
Hallo,

bitte keine Änderungen direkt in gearboxMogli.lua. Man kann gearboxMogliGlobals auch ohne Modifikation am Mod selber ändern. Erstelle dazu ggf. eine gearboxAddonConfig.xml im Mods-Ordner und darin dann:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<momentOfInertiaBase type="int" value="1"/>
		<momentOfInertia type="int" value="2"/>
	</gearboxMogliGlobals>
...
</vehicles>
```
Viele Grüße,
Stefan

**Comment by mieperDE** [comment]
Danke für die Vorschläge. Ist schon besser geworden. 
Eine Denksekunde gibt es aber dennoch. Als hätte der Loader kein Drehmoment. Ich hab was von einer Drehmomentbegrenzung gelesen. Kann man die abschalten? Oder zumindest runtersetzen?
