### ISSUE TITLE
Lastschaltstufen schalten zu früh hoch

### ISSUE THREAD

**Issue by Jan238** [Mogli12/GearboxAddon#157]
In der aktuellen Version des Mods werden nun die Lastschaltstufen, wenn diese automatisch geschaltet werden schneller runter geschaltet was ich sehr gut finde. 
Dafür kam aber ein neues Problem:
Die Lastschaltstufen werden jetzt meist schon zwischen ca. 1600 und 1700 rpm hochgeschaltet. Dadurch ist keine ordentliche Beschleunigung mit Last möglich.
Das Problem fällt z.B. beim Valtra S oder T ? auf. Meistens sind es die letzten Lastschaltstufen die zu früh geschaltet werden

**Comment by Mogli12** [comment]
Hallo,

das Getriebe schaltet in den nächst höheren Gang, wenn dort bereits 85% der geforderten Leistung bei niedrigerem Verbrauch anliegen. Die Valtras haben den niedrigsten Verbrauch bei 1300 U/min und das maximale Drehmoment bei 1500 U/min. Es mag sein, dass er etwas zu früh hoch schaltet, aber wann soll er denn schalten? Du musst dabei auch an die Spieler mit Tastatur denken, die quasi immer Vollgas geben.

Viele Grüße,
Stefan

**Comment by Jan238** [comment]
Danke für deine Antwort und Erklärung, 
habe noch mal mit einer älteren Version verglichen und festgestellt das kein großer Unterschied in der Beschleunigung da ist. 
Damit hat sich das erledigt.
