### ISSUE TITLE
Tempomat

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#158]
Hallo,

hast du etwas am Tempomat in den letzten paar Versionen verändert? Ich hatte es schon mal erwähnt, aber ich melde das erneut, falls es untergegangen ist.

Wenn ich den Tempomat aktiviere dreht der Motor auf maximale Drehzahl und beschleunigt nicht.

Das Problem ist auch bei Helfern. Da dreht der Motor hoch, der Helfer kommt aber kaum von der Stelle.

Grüße

Andreas

**Comment by BlaggyXD** [comment]
Servus,
Das liegt glaube ich daran daran das der Helfer die Kupplung nicht schließen kann , versuch doch anstatt des Tempomaten das Handgas zu nehmen das sollte genau so gut gehen.
Grüße,
Blaggy

**Comment by Fracking** [comment]
Das Handgas löst das Problem nicht.

Aber das mit der Kupplung stimmt. Gilt auch für den normalen Tempomat. Ich konnte das Problem lösen indem ich kurz manuell aus- und eingekuppelt hab.

Ist das ein Bug?

**Comment by BlaggyXD** [comment]
Gute Frage, das müsstest schon Mogli selber fragen.

**Comment by Mogli12** [comment]
Hallo,

ich habe das Problem sporadisch beobachtet. Mir schien es, dass es sporadisch passierte, wenn man zu schnell losfahren wollte. Mit Version 2.1.2.9 konnte ich es aber nicht nochmal reproduzieren.

Wenn Du es also mit 2.1.2.9 noch nachvollziehbar hin bekommst, dann wäre ich über eine detaillierte Beschreibung mit log.txt (bitte bei Gist oder Pastebin) sehr dankbar.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo Andreas,

Das nenne ich mal eine perfekte Problembeschreibung. Besser geht es nicht. Jetzt muss ich nur noch das Problem finden.

Danke, Stefan

**Comment by Mogli12** [comment]
Hallo Andreas,

bei mir funktioniert der Tempomat ohne Probleme. Ich habe also eine neues Spiel gestartet und ich habe FS17_GearboxAddon als einzigen Mod ausgewählt. Dann habe ich über die Console mit gsCheatMoney mit eine Million gezaubert und den Fendt gekauft. Da automatischer Motorstart an ist, läuft er sobald ich mit Tab hinein wechsle. Dann drücke ich auf 3 und ab geht's.

Hast Du eine eigene gearboxAddonConfig.xml im Mods-Ordner? Wenn Du das Spiel vorher gespeichert hattest, kannst Du mir dann die vehicle.xml schicken?

Danke, Stefan

**Comment by Fracking** [comment]
Hi Stefan,

ich hab da nichts geändert. Hab den Mod Ordner leer gemacht und ne frische GearboxAddon zip rein gelegt. Dann neuen Spielstand gestartet. Gespeichert. Geld editiert. Neu geladen. Dann das Video gemacht.

Die vehicle.xml ist zwar nicht mehr 100% wie die vom Video, aber ich habs eben getestet und das Problem ist noch da.

[vehicles.zip](https://github.com/Mogli12/GearboxAddon/files/1113037/vehicles.zip)

(Geht das so mit dem Hochladen?)

Ich finde es auch komisch, dass der "AutoHold" Verbrauch wieder bei 0,0 l/h liegt, obwohl der Motor läuft. Mach ich das Addon im Spiel aus und lasse den Motor laufen, gibt es einen Verbrauch.

Ich hab zwar paar mods (z.B. MR) installiert, aber die müssten ja komplett "deaktiviert" sein, wenn sie aus dem Mod Ordner raus sind.

Wie gesagt, für das Video hatte ich nur "FS17_GearboxAddon" als ZIP im Ordner.

Grüße

Andreas

**Comment by Mogli12** [comment]
Hi Andreas,

hast Du irgendwie die Kupplung belegt und versehentlich betätigt? Probier auf jeden Fall mal Version 2.1.3.1 aus und schick mir nochmal die log.txt.

Danke,
Stefan

**Comment by Fracking** [comment]
Hallo Stefan,

ich hab die neuste Version (siehe Log) mal schnell geteste. Mir fällt zwar was auf, aber ich muss da noch etwas genauer testen. Wenns mich störrt melde ich es :).

[Log](https://gist.github.com/Fracking/dd790e92a83c401edca56e6f1db045c1)

Ansonsten ist alles normal. Tempomat unter Last funktioniert. Helfer arbeiten normal.



Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Andreas,

super, ich hatte ein paar kleine Änderungen auf Verdacht gemacht. Da hatte ich wohl die richtige Korrektur dabei.

Viele Grüße,
Stefan

**Comment by Fracking** [comment]
Hallo Stefan,

ich hab hier noch ein [Video](https://youtu.be/B-wgzYNRhU8)

Und ein [Log](https://gist.github.com/Fracking/48226d2a74830a7fa0319c019a40cfa9)

Beschreibung:
Wie im Video zu sehen, schalte ich den Tempomat ein. Die Drehzahl fällt aber nach dem Anfahren auf ca 1300 U/min (je nach Traktor / Getriebe Fabrikat anders, aber definitiv "zu" niedrig). Nach ein Paar Sekunden dreht die Drehzahl höher.
Beim manuellen Beschleunigen dreht der Motor sauber bei 1800 U/min (wie er es soll).

Ich hoffe ich kann damit weiterhelfen.

Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Andreas,

ja genau, der Tempomat hat eine maximale Beschleunigung eingebaut. Die kann man im Fahrzeug mit RShift und Ü oder Ä ändern. Im F1-Fenster kommt dazu ein kleiner Text.

Viele Grüße,
Stefan

**Comment by Fracking** [comment]
Ach, stimmt ja. Sorry, mein Fehler. Ich schließe das dann mal. :)
