### ISSUE TITLE
Standard AI Drescher + GearBoxAddon

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/GearboxAddon#16]
hi mogli

wenn die standard AI mit dem Drescher arbeitet und am ende des feldes ist , bekommt die standard AI das wenden nicht mehr hin mit gearboxAddon 

z.b. NH TC590 (jeder andere drescher ebenfalls) 
am feld ende und die AI wenden will , der erste turn vorwärts funktioniert , doch dann wenn er rückwärts setzen will kommt er nicht in den rückwärtsgang und fährt dann einfach vorwärts weiter

in kombination mit autoCombine gehts , aber nicht mit dem standard helfer

gearBox version 1.3.0.2

PS : hat nix mit dem problem zu tun was ich bei autoCombine geschrieben habe ^^

grüsse grazy

**Comment by Mogli12** [comment]
Hi,

das könnte daran liegen, das der Standard-Helfer nur 50% Gas gibt. Ich habe das mal vorsichtshalber im Getriebe verdoppelt. (v1.3 rc2)

Viele Grüße

**Comment by Mogli12** [comment]
#
