### ISSUE TITLE
Stufenlos Massenträgheit / Trotz Analogerbeschleunigung Digital 

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#160]
Servus,

 in der #101 wurde meiner Vermutung nach das gleiche schon mal beim Schaltgetriebe behandelt.
Da dem letzt einige Änderungen am CVT gemacht wurden habe ich es mal wieder getestet und muss sagen jetzt macht es Spaß damit zu fahren aber nur solange man entweder das Handgas benutzt oder die Übersetzung begrenzt, sonst fährt man immer Vollgas egal wie weit man das Pedal durch drückt und gerade eben ist mir gekommen wo ran es liege könnte ( #101 ).

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

das Problem ist eher, dass das Gaspedal am Ende nur steuert, wie viel Prozent vom Drehmoment zu den Rändern geschickt wird. Bei kleiner Übersetzung dreht der Motor aber schneller hoch, als das Getriebe die Übersetzung anpassen kann. Da muss ich leider einen Kompromiss machen (siehe #156).

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo,

wie ist es mit Version 2.1.3.3? Falls es korrekt ist, dann mach einfach das Issue wieder zu,

Vielen Dank

**Comment by BlaggyXD** [comment]
Servus,

Ist ist auf jeden fall besser , aber unter 21 Km/h komme ich dennoch nicht ( Fendt 300 Vario) aber von 21-43Km/h kann ich analog beschleunigen.

Im Handgas- / Arbeitsmodus bremst er erst ab wenn ich das Pedal komplett los gelassen hab davor fährt er dauer haft mir der gleichen Geschwindigkeit weiter wenn ihn keine Beeinflussung von außen abbremst.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo,

es gibt da noch die "keep speed" Taste. Damit verhalten sixh Gaspedal und Bremse wie der Fahrhebel und es wird nur noch über die Tempomatfunktion gebremst und beschleunigt. Ich habe mir die Taste auf dem Joystixk gelegt.

Ansonsten müssten 23 km/h eigentlich passen.

Viele Grüße, 
Stefan

**Comment by BlaggyXD** [comment]
Servus,
Die "keep speed" Funktion muss ich mir mal anschauen.
Sauberes fahren ist mit den 23Km/h minimal m.M.n nicht möglich. 

Dafür kann man aber das Handgas so nieder wie es geht einstellen und schon hat man ein richtiges Stufenlos Getriebe , die Drehzahl regelt sich selber und man kann die Übersetzung mit dem Pedal vor geben ( von 1Km/h bis Vollgas nur mit dem Pedal gesteuert) , nur zum langsamer werden muss man halt komplett vom Pedal gehen.

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Ich hab die Keepspeed mal eben getestet damit geht es auch gut , aber für die wurde ich mir einen Umschalter wünschen das man nicht dauer haft eine Taste drücken muss damit sie an ist.

**Comment by Mogli12** [comment]
Die Idee beim "keep speed" ist gerade, dass es nicht dauerhaft an ist. Der normale Tempomat ist ja bereits dauerhaft an und kann auch über eine entsprechende Achse gesteuert werden.

**Comment by BlaggyXD** [comment]
Dafür fehlt mir ehrlich gesagt die Achse , ich habe alle Achsen belegt.
Aber die Idee an sich mit dem Tempomat auf einer Achse klingt gut.

**Comment by Mogli12** [comment]
Oder es ist vielleicht doch keine schlechte Idee...?

**Comment by BlaggyXD** [comment]
Sag mal Mogli, hast du evtl. Discord ? da könnte man etwas besser schreiben.

**Comment by Mogli12** [comment]
Hallo,
ich schreibe nur so nebenbei während ich was anderes mache. Tagsüber habe ich sogar nur vom Smartphone geantwortet.
Mit Version 2.1.3.5 kannst Du mit KEY_rctrl KEY_delete das "keep speed" dauerhaft einschalten. Dazu habe ich für diesen Modus ein paar kleine Anpassungen vorgenommen.
Viele Grüße, Stefan

**Comment by BlaggyXD** [comment]
Servus, 
Ach so.
Super , damit hat man jetzt für jede Situation das Richtige Getriebemanagement 
Vielen dank für die "Hilfe", wie immer.

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Etwas hab ich noch zu bemängeln , man kann sehr schlecht umschalten da es dauernd wechselt wenn man auf der Taste bleibt und das im Millisekunden Takt.

**Comment by Mogli12** [comment]
Das mit der Taste war ein Flüchtigkeitsfehler und ist mit 2.1.3.6 behoben.

**Comment by BlaggyXD** [comment]
Super.
