### ISSUE TITLE
clutch issues

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#161]
is there any trick to working the clutch so the vehicle doesnt come to a complete stop when needing to switch gears?  especially the auto clutch, when plowing, vehicle comes to a complete stop whenever trying to gear up, usually resulting in a stalled vehicle (when using ai vehicle extension)

maybe my approach to plowing is all wrong, i watch the automatic gear shifting trying to step up into higher gears on an uphill plow and getting into trouble..   manually i wind up using a lower gear, winding it up pretty high and burning alot of fuel.. 

what do you do IRL?

**Comment by Mogli12** [comment]
The vehicle slows down because there is no torque transferred. You can just try to decrease the time to shift. Additionally, if clutch is open the gearbox limits the maximum torque that could be transferred. If more torque is needed vehicle stalls.

**Comment by sootysax** [comment]
is there a way to get my g27 pedal to allow partial clutch?  i have it setup through Joy2Key and it's either on or off..  with the trigger about half way thorugh my press..

**Comment by Mogli12** [comment]
You can assign an axis to the clutch (gearboxMogliCLUTCH, "Gearbox: clutch"). So there are two options in parallel: operate the clutch with one digital button or assign an analog axis.

**Comment by Mogli12** [comment]
You can try to play around with the following global parameter:
<clutchExp type="float" value="2"/>
2 is the default but you can try 1 as well. 
Just check out #156 about how to change globals.

**Comment by sootysax** [comment]
I had my g27 setup for 'combined pedals' so i wasnt able to assign the clutch...  setting it up the other way made a huge difference for me thanks!

**Comment by Mogli12** [comment]
Can we close this issue?
