### ISSUE TITLE
Beschleunigung mit Pedalen

### ISSUE THREAD

**Issue by Jan238** [Mogli12/GearboxAddon#162]
Hallo,
ich habe mal wieder mein G27 angeschlossen und muss sagen, dass es schon echt Spaß macht. 

Nur beim Rangieren und beim Versuch langsam zu fahren ist mir was aufgefallen:
Bei den stufenlosen Schleppern ist es kaum möglich eine langsame Geschwindigkeit zu halten. Wenn ich das Gaspedal nur minimal betätige wird fast wie mit vollgas  auf Höchstgeschwindigkeit beschleunigt. 
Das gleiche Verhalten bei automatischen Schaltgetrieben. 

Schalte ich das Getriebe aus also fahre ich ohne den Mod kann ich mein Gaspedal z.B. 1/3 drücken und eine entsprechende Geschwindigkeit wird gehalten.

Bei Manuellen Getrieben wie beim 1455XL funktioniert jedoch alles sehr gut.

**Comment by mieperDE** [comment]
Das ist mir auch schon aufgefallen. Ich habe bei mir die Empfindlichkeit vom Gaspedal schon auf 10% gestellt. Muss aber trotzdem aufpassen das er keinen Satz macht.

**Comment by Jan238** [comment]
Wo genau hast du die Empfindlichkeit eingestellt? Im Spiel selber kann ich nur von 100% bis 200% einstellen.

**Comment by mieperDE** [comment]
In der Logitech Software

**Comment by Jan238** [comment]
Ich hab jetzt mal mit den Einstellungen gespielt konnte aber keiner merklichen Veränderungen beobachten. Da ich dachte das die Einstellungen nicht übernommen werden hab ich die Achse mal invertiert aber das funktionierte also wurde wohl auch die Empfindlichkeit übernommen aber brachte keine Veränderung. Schade aber trotzdem Danke für den Tipp

**Comment by BlaggyXD** [comment]
Servus ,
das gleiche habe ich schon mal in der #160 angesprochen.

**Comment by Mogli12** [comment]
Hallo,
das mit dem Gaspedal beim stufenlosen Getriebe sollte mit 2.1.3.3 gelöst sein.
Viele Grüße
