### ISSUE TITLE
Gear AI in Courseplay

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#163]
I'm finding that the AI gear changing is not downshifting to lower gears and getting stuck on inclines...   my  argo 6.61 tractor is trying to start a row in M II 5 (the gear it came downhill with) and will not downshift and I have to manually shift it to lower gears to get it started

**Comment by Mogli12** [comment]
Yes, this is correct With AI or courseplay the gearbox does not automatically shift all gears. You have to turn on "All Auto" (gearboxMogliAllAuto). But you can change this with a global setting:
```xml
<defaultEnableAI type="string" value="A"/>
```
Possible values are 
- "P"owershift: automatically shift only if shifting time is below 250ms
- "N"o: turn off gearbox during AI
- "A"ll Auto: automatically shift all gears and ranges
- "Y"es: keep gearbox as iss.
Default is "P"

**Comment by sootysax** [comment]
where do you change this setting?

**Comment by Mogli12** [comment]
Just look at issue #156 or check page 6 of https://github.com/Mogli12/GearboxAddon/blob/master/Documentation/Description.pdf.

**Comment by D3ltorohd** [comment]
Wäre das so richtig, ich erstelle eben diese xml im Mods Ordner und trage dort folgendes ein.

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<defaultEnableAI type="string" value="A"/>
	</gearboxMogliGlobals>
</vehicles> 

In etwa so, oder wie sollte das aussehen. Damit auch mein Coursplay Fahrer keine Probleme mehr hat und das ding so lange im Automodus fährt, bis ich wieder ans Steuer geh.

**Comment by Mogli12** [comment]
Ja, genau. Das wäre so richtig.

**Comment by D3ltorohd** [comment]
Hm leider scheint das Ingame nicht zu funktionieren. Liegt im Modsordner wo der Mod selber liegt. Oder ist Value A nix ? Müsste da eher N rein ? Hätte halt gedacht mit A schalten die Box automatisch durch. Dann klingt es auch beim Helfer gut, wenn er schaltet.

**Comment by alpha117** [comment]
I have created the above xml and placed in MOD folder, but AI still selects AI(M) when in courseplay and slipping still happens
[gearboxAddonConfig.zip](https://github.com/Mogli12/GearboxAddon/files/1289644/gearboxAddonConfig.zip)

**Comment by Mogli12** [comment]
Hi, 
The globals always come from gearboxAddonConfig.xml directly in the mods folder. It does not work if it is in gearboxAddonConfig.zip.
Regards,
Stefan
