### ISSUE TITLE
Kraftstoffverbrauch im Auto Hold

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#164]
Hallo Stefan,

Ein [Video](https://youtu.be/UP-5rfCJVY8)

Zur Vollständigkeit der [Log](https://gist.github.com/Fracking/48226d2a74830a7fa0319c019a40cfa9)

Beschreibung:

Der Kraftstoffverbrauch liegt im "Auto Hold" Modus bei 0,0 L/h. Das ist in der Kabinenanzeige und im Add-on Hud zu sehen. Im "Neutral" Modus ist der Verbauch ebenfalls 0,0 L/h.

Wenn man nicht in den "Auto Hold" Modus geht, gibt es einen Verbrauch (wie es sein soll).

Ich hoffe das hilft das Add-on zu verbessern.

Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Andreas,

danke, bei den letzen Korrekturen ist der Kraftbedarf des Motors im Leerlauf verloren gegangen. Es ist mit Version 2.1.3.4 korrigiert.

Vielen Dank,
Stefan

**Comment by Fracking** [comment]
Ja, ist behoben. Ich schließe das hier.

Dickes Danke.
