### ISSUE TITLE
Kein Rückwärtsgang via Button

### ISSUE THREAD

**Issue by DerPotsdamer** [Mogli12/GearboxAddon#165]
Hallo Stefan

Ich habe das Problem, dass ich mit meinem G27 Schalthebel nicht in den Rückwärtsgang wechseln kann. Alle anderen 6 Gänge gehen problemlos. Die Schaltstellung des Rückwärtsganges wird erkannt, daran liegt es nicht. Ich habe auch schon versucht eine beliebige Taste der Tastatur mit dem Rückwärtsgang zu belegen, auch hier tut sich nix. Ich muss immer mit den Tasten vorwärts und Rückwärts jeweils die Richtung wechseln. Dann hab ich zwar auch mehrere Rückwärtsgänge, aber ich hätte lieber beim einlegen des Rückwärtsganges direkt die richtige Fahrtrichtung.

Ich habe den LS17 mit aktuellsten Patchstand, sowie dein Addon in der V2.1.3.4
Meine Log:
https://gist.github.com/DerPotsdamer/1b2ac87042e6eb104fc1863023f10a81

Danke Alexander

**Comment by Mogli12** [comment]
Hallo Alexander, 

ich habe selber kein Lenkrad mit Gangschaltung. Ich kann Dir daher nicht helfen. Bei welchem Fahrzeug tritt das Problem überhaupt auf? Wie sieht Deine inputBinding.xml aus. Eventuell kann Dir mit den Informationen jemand anderes helfen. 

Gruß, Stefan

**Comment by BlaggyXD** [comment]
Servus,

Da ich ein Lenkrad habe kann ich evtl. weiter helfen.
Als erstes mal , ist es ein Rückwärts Gang oder eine Rückwärts Gruppe ?

Ich habe es bei mir so belegt das so wohl der R Gang also auch die R Gruppe auf dem 7. Gang vom G27 Schalter ist und damit kann ich so wohl die R Gruppe um schalten als auch in den R Gang gehen.

Evtl. liegt es daran das es eine R Gruppe ist wenn das so ist musst du wieder einen Gang einlegen nach dem du von Vorwärts auf Rückwärts geschalten hast.

Grüße,
Blaggy

**Comment by DerPotsdamer** [comment]
Hallo Blaggy

Nett, dass du mir helfen möchtest.
Ich kann in den Optionen vom LS doch lediglich "Getriebe: G27R" mit dem Rückwärtsgang des Schalthebels belegen.
Da gibt es doch keine Unterscheidung von Gruppe oder Gang. >>>siehe Anhang

Ich habe das übrigens bereits ohne weitere Mods probiert und sowohl im NewHolland als auch im Standard IHC.

Gruß
Alexander


-------- Ursprüngliche Nachricht --------
Von: BlaggyXD <notifications@github.com>
Datum: 02.07.17 14:35 (GMT+01:00)
An: Mogli12/GearboxAddon <GearboxAddon@noreply.github.com>
Cc: Alexander Knüppel <alexander@familie-knueppel.info>, Author <author@noreply.github.com>
Betreff: Re: [Mogli12/GearboxAddon] Kein Rückwärtsgang via Button (#165)


Servus,

Da ich ein Lenkrad habe kann ich evtl. weiter helfen.
Als erstes mal , ist es ein Rückwärts Gang oder eine Rückwärts Gruppe ?

Ich habe es bei mir so belegt das so wohl der R Gang also auch die R Gruppe auf dem 7. Gang vom G27 Schalter ist und damit kann ich so wohl die R Gruppe um schalten als auch in den R Gang gehen.

Evtl. liegt es daran das es eine R Gruppe ist wenn das so ist musst du wieder einen Gang einlegen nach dem du von Vorwärts auf Rückwärts geschalten hast.

Grüße,
Blaggy

-

**Comment by BlaggyXD** [comment]
Servus,
Doch, der Unterschied ist das an beim Gang einfach nur in den 7'ten schaltet und er ist drin , bei der Gruppe ist der 7'te nur ein Umschalter und man muss wieder in einen Gang schalten und zum Umschalten musst du " Getriebe Rückwärts" belegen.

Grüße,
Blaggy

**Comment by DerPotsdamer** [comment]
Hallo Blaggy

Genau so will ich das eigentlich, in den „7ten“ und man fährt Rückwärts.
Und so hab ich das eigentlich auch belegt.

Meine ich jedenfalls. :-)

Ich hab die entsprechenden Passage mal verlinkt:
https://gist.github.com/DerPotsdamer/a4f7c1ba08375b9fdf3f3267cbfeedd3

Erklärung dazu:
Device 8 ist mein Schalthebel
Device 4 eine meiner Konsolen
Device 7 ist das Lenkrad mit den Pedalen

Gruß
Alexander

**Comment by Mogli12** [comment]
Hallo Alexander,

der G27-Rückwärtsgang kann als Rückwärtsgang nur funktionieren, wenn man diesen Rückwärtsgang auch bei den Gängen findet. Beim Wendegetriebe geht das so leide nicht.

Beim IHC 1455 XL gibt es 6 Gänge. Zwischen Rückwärts und Vorwärts wird im Gruppengetriebe geändert. Was soll ich da mit G27-R machen? Es ist ja nun gar kein Gang mehr eingelegt.

Viele Grüße, Stefan

**Comment by BlaggyXD** [comment]
Beim Auto mag das so sein das man 6V und 1 R hat , aber beim Bulldog hat man meistens 2 oder mehr Schalthebel z.B. einen für die Gange ( 1-6) und einen Für die Gruppen (V R) Da man keinen Rückwärtsgang hat schaltet man das mit den Gruppen also dem zweiten Schalthebel  und da man den nicht man den nicht am G 27 hat schaltet man eben um zwischen V und R aber muss jedes man wieder den gewünschten Gang ein legen sonst kann man nicht fahren.

**Comment by DerPotsdamer** [comment]
Hallo Blaggy, Hallo Stefan

Danke für die Infos, hab ich verstanden.
Wenn man es weiß kann man damit auch arbeiten ***grins***

Gruß
Alexander
