### ISSUE TITLE
Controller / Wheel set up?  key commands

### ISSUE THREAD

**Issue by sootysax** [Mogli12/GearboxAddon#166]
just wondering if you personally use a steering wheel setup or other controller..  Gearbox has so many possible key commands (toggles vs. up/down; direct gears vs switches)..  

I would be interested to know how you setup your controls..

**Comment by Mogli12** [comment]
Most times I use just the keyboard. Sometimes I use my very old joystick (MS sidewinder). And I have a Logitech wheel (driveforce GT). But I rarely use it.
