### ISSUE TITLE
ERROR 7 container or whatelse :p

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/GearboxAddon#167]
Night Stephan maybe I have a container buggy can you try it? when buy it I get with full option it can sell:
`C:/Blabla/path/FarmingSimulator2017/mods/IT_Runner_ContainerDeckel/ContainerDeckel.i3d (128.43) ms
FS17_GearboxAddon: looking for default configuration (default)
Error 7 loading gearboxMogliLoader: C:/Blabla/path/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua:6601: attempt to perform arithmetic on local 'idleTorque' (a nil value)
Error 7 loading gearboxMogliLoader: C:/Blabla/path/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua:6601: attempt to perform arithmetic on local 'idleTorque' (a nil value)`
here the mod link I been verify it's the same hash file it's ok:
http://sharemods.com/1khoozfmltjg/IT_Runner_ContainerDeckel.zip.html
You need  an HKL truck or It runner for use it but the issue I get seem only when buy it I advise you too I've no issue using the mod event if Gearbox is not happy with :)
BR

**Comment by Mogli12** [comment]
Hi,
The container has specializations steerable and motorized. But the <motor...> tag is missing in the XML. So I think the error messages are ok.
Regards, Stefan

**Comment by Anonymous-any** [comment]
:) thank a lots.
