### ISSUE TITLE
G27 Rückwärtsgang

### ISSUE THREAD

**Issue by Lizzar92** [Mogli12/GearboxAddon#17]
Hi,

bei mir funktioniert der Rückwärtsgang im G27 Modus nicht. Geht bei mir in allen Versionen nach 1.21 nicht mehr.

Gruß,
Lizzar

**Comment by Mogli12** [comment]
Hi Lizzar,

da ich selber kein G27 habe, kann ich mit der knappen Beschreibung so leider nichts anfangen. Wie schaltest Du denn in den Rückwärtsgang? Welche Tasten hast Du dazu zugewiesen?

Viele Grüße

**Comment by Lizzar92** [comment]
Hab den Rückwärtsgang auf den Button 15. Hab es mit manueller Kupplung und automatischer Kupplung probiert. Hab den Rückwärtsgang auch mal auf einen anderen Button gelegt um zu testen ob es vielleicht am Button 15 liegt.

**Comment by Mogli12** [comment]
Was hast Du genau auf den Button 15 gelegt? mrGearboxMogliGEARR?

**Comment by Lizzar92** [comment]
ja
<input name="mrGearboxMogliGEARR" key1="" key2="" mouse="" button="BUTTON_15" device="1" category="VEHICLE" visible="true" />

**Comment by Mogli12** [comment]
Ich habe nochmals ins Coding geschaut. Auf Anfrage von anderen Spielern mit G27 wurde die Logik für mrGearboxMogliGEARR etwas verschärft. Dieser Rückwärtsgang funktioniert nur, wenn das normale Getriebe einen Rückwärtsgang hat. 

Bei eine Wendeschaltung musst Du stattdessen entweder mrGearboxMogliREVERSE (default ist Leertaste) oder die beiden Tasten mrGearboxMogliGEARFWD und mrGearboxMogliGEARBACK verwenden.
