### ISSUE TITLE
eigene gearboxAddonConfig.xml für meine Konfigurationen

### ISSUE THREAD

**Issue by reinholdmaehler** [Mogli12/GearboxAddon#171]
Hallo Stefan,

ich habe mir mittlerweile in der gearboxAddonConfig.xml schon so ca. 30-40 eigene Fahrzeuge angelegt. Um mit deinen Updates mithalten zu können, muss ich das immer wieder kopieren etc.

Wäre es möglich, dass es parallel zur gearboxAddonConfig.xml eine "yourown_gearboxAddonConfig.xml" gibt, die ich dann einfach von Version zu Version komplett mitnehmen kann?

Das würde mein Leben verschönern.
Gruss
Reinhold

**Comment by Mogli12** [comment]
Hallo Reinhold,

ich verstehe die Frage leider nicht. Die gearboxAddonConfig.xml direkt im Mods-Verzeichnis ist doch schon Deine. Die Dateien in FS17_GearboxAddon.zip solltest Du eigentlich nicht verändern. Schau doch bitte auch in das Kapitel "Eigene Konfigurationen" in https://github.com/Mogli12/GearboxAddon/blob/master/Documentation/Beschreibung.pdf.

Viele Grüße

**Comment by reinholdmaehler** [comment]
*Hand-an-den-Kopf-schlag*

man was haette ich mir eine Arbeit sparen koennen mit besseren lesen.... Danke.
