### ISSUE TITLE
Lastschaltstufen im G27 modus

### ISSUE THREAD

**Issue by TanteGretti** [Mogli12/GearboxAddon#172]
Hallo
Super Erweiterung für LS17, spiele nie wieder ohne :).
Nutze die Mod mit einem TM T150 Lenkrad und einem FFB Joystick als Schalthebel.
Was mich jedoch ein wenig stört ist das im G27 Modus beim Gruppenwechsel, zB Valtra T, die selbe Lastschaltstufe  eingelegt bleibt und  sich nicht an die Geschwindigkeit anpasst.
Zum Beispiel:
Beschleunige im Gang C5 und schalte hoch auf die Gruppe D
Im manuellen Modus mit Tastatur wird dazu automatisch die 3. Lastschaltstufe ausgewählt also D3.
Im G27 Modus hingegen bleibt die selbe Lastschaltstufe eingelegt also D5 und ich muss zurückschalten.
Gäbe es eventuell eine Möglichkeit das selbst zu lösen?

**Comment by Mogli12** [comment]
Hallo
ich könnte das SpeedMatching im Settings-UI auswählbar machen.
Viele Grüße

**Comment by Mogli12** [comment]
Hallo,
ab Version 3.0 build 304 kann man das SpeedMatching ein- und ausschalten.
Viele Grüße,
Stefan

**Comment by TanteGretti** [comment]
Vielen Dank.
Ich freue mich, dass du dich um mein Anliegen gekümmert hast.
Viele Grüße
Dominik

2017-12-18 13:37 GMT+01:00 Stefan Biedenstein <notifications@github.com>:
