### ISSUE TITLE
Energiebedarf von "MR" Geräten

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#173]
Hallo Stefan,

mir ist aufgefallen, dass der Kuhn PRIMOR 15070 M ("Ballenschredder" bei Kategorie "Tiere") beim Entladen (also "schreddern") keinen Energiebedarf entwickelt. MR hat das in den letzten Versionen verändert. Vllt. ist die "neue" Last nicht für das Getriebe Addon sichtbar. Hab in der MR XML mal nachgeguckt und gesehen, dass es da einen Eintrag:`<moreRealistic>			
		<trailer unloadingPtoPower="50" />
	</moreRealistic>` gibt. 

Schalte ich das Addon aus, gibt es beim Entladen einen Energiebedarf (Drehzahl und Kraftstoff gehen hoch).

[Log](https://gist.github.com/Fracking/07e1170f01f044aa941a282cb298b244)

Ich hoffe das ist leicht zu beheben.

Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Andreas,

das Problem ist, dass Dural hier leider nur seine eigenen Funktionen nutzt und PowerConsumer.getTotalConsumedPtoTorque und PowerConsumer.getMaxPtoRpm nicht anpasst.

Viele Grüße, Stefan

**Comment by Mogli12** [comment]
Hallo Andreas,

Dural hat es in Version v0.4.15 korrigiert. (https://www.fs-uk.com/forum/index.php?topic=195659.new#new)

Vielen Dank, 
Stefan
