### ISSUE TITLE
Jenz Mobilhacker funktioniert nicht mit Gearbox

### ISSUE THREAD

**Issue by mieperDE** [Mogli12/GearboxAddon#174]
Grüße

Habe gerade meinen Jenz Mobilhacker ausgepackt und festgestellt das er mit dem Gearbox Mod zusammen nicht funktioniert. Er häckselt kein Holz. Schalte ich das Mod mit RShift+Ö ab funktioniert der Hacker wieder.
Als Schlepper hält der Fendt 939 her.

[log.txt](https://github.com/Mogli12/GearboxAddon/files/1132948/log.txt)
https://youtu.be/BfJ-gqglQSM

Edit:
Akte ungelöst ;)
https://github.com/Mogli12/GearboxAddon/issues/116

**Comment by Mogli12** [comment]
Hallo,

Hast Du es nur mit dem GearboxAddon ohne die anderen Mods (z.B. FS17_FuelUsageDisplay) probiert? Das Video funktioniert leider nicht.

Viele Grüße

**Comment by mieperDE** [comment]
Hab das Video gefixt. Falsche einstellung >.>
Ich probiere es mal ohne andere Mods

**Comment by mieperDE** [comment]
[log.txt](https://github.com/Mogli12/GearboxAddon/files/1132997/log.txt)

Gearbox alleine: funktioniert
Gearbox + Betterfuel: funktioniert nicht
Gearbox + Betterfuel + RShiftÖ: funktioniert

**Comment by Mogli12** [comment]
Das ist nicht das erste Problem, welches bei Zapfwellenarbeiten in Kombination mit FuelUsageDisplay auftritt. Ich habe auch keine Ahnung, was der Entwickler da macht. Allerdings wurde er bei FS-UK recht unfreundlich, weil das GearboxAddon bei Helfer mit der Einstellung Helfer kauft Treibstoff keinen Verbrauch mehr berechnet.

Ich gehe mittlerweile grundsätzlich davon aus, dass GearboxAddon und FuelUsageDisplay nicht miteinander kompatibel sind. Am Ende überschreiben sie beide die Berechnung von Motorlast und Kraftsoffverbrauch. FuelUsageDisplay zeigt den Verbrauch nicht nur an.

**Comment by mieperDE** [comment]
Das hab ich gelesen xD

Gut ist dann so. Durch das deaktivieren von Betterfuel ist mir noch aufgefallen, dass sich die ganze Spielperformance stark verbessert hat. 
Grüße
