### ISSUE TITLE
Keybind and function

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/GearboxAddon#175]
Hi Stefan 2 questions please, I don't found the usage what do for gearboxMogliCONFLICT_1 to 4 that are in moDesc but not translate file are these unused? and how I can make unusable gearboxMogliACCTOLIMIT, gearboxMogliDECTOLIMIT to be always 10 20km/h ?
Br

**Comment by Anonymous-any** [comment]
Hi Mogli just UP to say I'm not sure you understand what I would want to say?
Br

**Comment by Mogli12** [comment]
Hi,
I need the CONFLICT key bindings to avoid conflicts with other mods like DriveControl. These key bindings are invisible and it is not necessary to translate them.
I propose to increase ACCTOLIMIT and save your savegame. The value is part of the savegame.
Nevertheless, it is possible to change the value with the global parameter accelerateToLimit. Please check issue #156 about how to change globals.
Regards, Stefan

**Comment by Anonymous-any** [comment]
Hi :) many thank for reply, you mean CONFLICT key bindings for "us" players we have nothing to do with them (somehow) ok but key binding are attributed to theses functions, then can we remove and leave them empty if needed for other bind functions without modifying what CONFLICT you explain you resolve with them and without having issue with removing that in future?
Thank too for your 2nd answer I go investigate global parameter :)
Best regard

**Comment by Anonymous-any** [comment]
![1](https://user-images.githubusercontent.com/25174503/28704886-5b87693a-736d-11e7-809b-9620b6161d80.png) at start game :)
With your latest build v2.1.5.4 all be better the log ask:
Loading settings from "/blablapath/mods//gearboxAddonConfig.xml"

`
    <accelerateToLimit type="float" value="20"/>
    <defaultEnableAI type="string" value="N"/>
    <hudPositionY type="float" value="0.14000000059605"/>
    <stallMotorOffTime type="float" value="500"/>
    <DefaultRevDownMs type="float" value="300"/>
    <hudPositionX type="float" value="0.60500001907349"/>
    <hudTextSize type="float" value="0.01799999922514"/>
    <brakeNeutralTimeout type="float" value="300"/>
    <hudTitleSize type="float" value="0.019999999552965"/>
    <DefaultRevUpMs1 type="float" value="100"/>
    <DefaultRevUpMs0 type="float" value="300"/>`
but persist the value is been saved in vehicle.xml like mrGbMSpeedAcc="20" and if I don't add the globals option in gearboxAddonConfig.xml that won't work I mean the saved value seem not loading at start.

Many many thank for the fix Stephan.
Best regard

**Comment by Mogli12** [comment]
I try to save values in vehicle.xml only if there is a difference between the actual value and the default value. Via gearboxAddonConfig.xml you change the default. That is why the value in vehicle.xml disappears.

**Comment by Anonymous-any** [comment]
Yes it's ok thank you, that not explain why the value stored in vehicle.xml is not used at start game right? also globals Via gearboxAddonConfig.xml otherwise I will not need to add it :) Br
