### ISSUE TITLE
Unable to easily control speed with pedals in automatic mode

### ISSUE THREAD

**Issue by SoloTwo** [Mogli12/GearboxAddon#176]
I'm not entirely sure if this has been a constant issue or somehow I hit an incorrect button and it started but lately, I'm unable to control my speed when the transmission is in auto.  In manual I can very easily control my speed but when in auto if I apply a tiny amount of constant throttle it will accelerate at almost full throttle, shift through the gears, then eventually settle down at the correct speed.  Here is a video, should explain it much better.

https://youtu.be/NL81Uo8OFSc

Only a tiny amount of constant throttle is applied and you see it goes full 100% load through the gears before settling to the correct speed.  The same throttle was applied in manual mode.  I don't remember this problem when I was playing earlier, there was a point where I was pressing a bunch of incorrect key bindings when I lost the hud at one point so I'm not sure if that was the cause or not. :-/

**Comment by Mogli12** [comment]
Hello,

I think in the manual mode the throttle limits the torque and the maximum RPM. The the motor RPM is above this maximum RPM the torque will be set to 0.

In automatic mode the RPM is only limited in the highest gear otherwise the automatic shifting will not work anymore.

**Comment by Mogli12** [comment]
Hello,

Please check version 2.1.4.0. I enabled the RPM limiter for automatic shifting as well.

BR

**Comment by SoloTwo** [comment]
It now works just as I would expect it to in real life Mogli.  Just perfect.  Thanks for your continued hard work. 👍 

Instead of making another issue I figured I should just ask while I'm here.  Regarding eco mode, just wondering what effect it has in general.  Secondly, in my Massey 7722 I noticed that when I switched transmission modes it has 2 automatic modes and the manual mode.  Just wondering what the difference is between the two automatic modes.  

Thanks again. :)

**Comment by Mogli12** [comment]
Hi,

The eco mode shifts a little earlier and turns off the boost if there is any. Furthermore, it will use the ECO PTO speed, which is typically between 1600 and 1700 instead of 1900 and 2000.

Regarding the different automatic modes: you can operate gears and ranges in automatic or just gears or just ranges. Shifting between gears (1, 2, 3, 4) takes about half a second. Ranges (A to F) are power-shifted, there is not interruption between.

BR

**Comment by SoloTwo** [comment]
Thanks again. :)  

When it comes to PTO speeds and setting my RPM I'm never quite sure what RPM to put the hand throttle at to properly mimic real life.  A constant battle I'm in lol.
