### ISSUE TITLE
How to tweak gearbox mod

### ISSUE THREAD

**Issue by Yamasaki450F** [Mogli12/GearboxAddon#177]
Hello there :)

I'm using this mod together with DC and MR and its much more fun compared to vanilla... But there are some things i don't like and i would like to tweak them.

1st thing i don't like is when you stop to zero and then release brake tractor will still pull forward slightly i would like to disable this. I tried to set AutoHold from false to true in gearboxMogli.lua but it doesn't work...

2nd thing is when i attach baler or anything with PTO shaft tractor will start moving forward soon as PTO is turned on. Only way to control this is clutch key  but its too complicated for keyboard...

3rd is switching between forward and reverse driving direction it will automatically  change gear... for example i stop in HH4 gear then switch to reverse it will automatically change to HH1(reverse) i would like it to stay in HH4(reverse)

And the last thing is to disable shuttle control so you can switch driving direction without pressing space.

So i need some help tweaking this its a bit too complicated for me.

Thanks... great mod :)

**Comment by Mogli12** [comment]
Hi,

Please do not modify files inside the ZIP file FS17_GearboxAddon.zip. It is not necessary if you want to tweak the gearbox.

Please look at issue #156 or check page 6 of https://github.com/Mogli12/GearboxAddon/blob/master/Documentation/Description.pdf.

In your case you can use these settings in gearboxAddonConfig.xml:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<autoStartStop type="bool" value="true"/><!-- turn on auto start/stop for all vehicles -->
		<noSpeedMatching type="bool" value="true"/><!-- turn off speed matching for all vehicles -->
	</gearboxMogliGlobals>
</vehicles>
```

If you already looked into gearboxMogli.lua you already saw gearboxMogliGlobals. You can change all values of this structure with the above method.

But the GearboxAddon always works with shuttle control. I cannot disable this.

Best regards,

**Comment by Yamasaki450F** [comment]
Ok thanks for Description.pdf i didn't know for this it's very useful.

I did as you said... and it works but only without MR mod... If MR mod is enabled tweaks don't apply...

**Comment by Yamasaki450F** [comment]
I updated MR and GB mod to the newest version and autoStartStop tweak works now... noSpeedMatching still doesnt...
