### ISSUE TITLE
Verbesserungsvorschlag am Wandler / Strömungskupplung

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#178]
Servus,
Ich hab mir dem letzt mal ein Volllastgeschaltenesgetriebe mit Strömungskupplung gebastelt so dass ich mit manueller Kupplung fahren kann ohne kuppeln zu müssen, dabei ist mir auf gefallen das die Strömungskupplung nicht sauber "trennt" so bald die Übersetzung zu klein ist schiebt es den Bulldog weiter ob wohl ich die Bremsen voll durch drück teil weise ist es auch so das man fast steht und die Räder durch drehen.

In echt bin ich zwar erst ein mal wissentlich mit einer Strömungskupplung gefahren aber da war es so das man selbst im kleinsten Gang einfach angehalten hat so bald man die Bremse gedrückt hat und so bald man von der Bremse gegangen ist ist er wieder weiter gefahren im Standgas (das weiterfahren ist im LS auch so wenn man die Öffnungs / Schließzeiten richtig einstellt nur kann man an dem anhalten leider nichts machen außer man stellt die Bremskraft sehr hoch ein was aber dann bedeutet das man von 40 zu 0 Km/h inner halb von 1-2m Stoppt wenn man die Bremse komplett durch drückt) evtl. könnte man das in der GB auch noch so einfügen / ab ändern.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

probiert mal Version 2.1.4.1. Ich denke, dass beim Bremsen nicht die Kupplung richtig geöffnet wurde.

Viele Grüße

**Comment by BlaggyXD** [comment]
Servus,
Damit trennt er sauber , super arbeit und danke für die schnelle Hilfe wie immer.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

kannst Du mal die Version 2.1.5.6 oder höher probieren. Ich habe einige PDF von Voith durchgelesen und daraufhin die Strömungskupplung mal stark geändert. Ich bin mir aber nicht sicher, ob es wirklich besser und/oder realistischer ist.

Vielen Dank,
Stefan

**Comment by Mogli12** [comment]
Hallo Blaggy,

wie gefällt Dir die Strömungskupplung aktuell?

Grüße,
Stefan

**Comment by BlaggyXD** [comment]
Servus Stefan,

 so wie sie aktuell ist gefällt sie mir sehr gut. 

Hier ein paar beispiele:
-Sauberes anfahren
-keine Starkensprünge mehr, eher ein sanftes wechseln zwischen den beiden Bereichen "fest verbunden" und "nicht fest verbunden" 
-Sauberes anhalten
-Im "nicht fest verbundnen" Bereich dreht er auch nicht zu hoch bis ca. 1500 Upm

Ich glaube damit sind alle meine Kritikpunkte abgedeckt,
tolle Arbeit von dir.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Danke!
