### ISSUE TITLE
Leistungsangaben / Gangwechsel bei Gefällen

### ISSUE THREAD

**Issue by Marc85BPG** [Mogli12/GearboxAddon#18]
Moin moin Mogli,
hab da folgendes Anliegen komme da nicht so ganz weiter. 

Folgendes: Der Traktor 190HP / Deutz Agrostar 6.81 wechselt sehr häufig die Gänge bei Gefällen / zb. auf Björnholm vom Händler den Feldweg hoch zum Hof. Desweiteren fällt mir auf das bei egal was gezogen wird/ egal welche Arbeit verrichtet wird immer max 145-158 HP lt. Hud beansprucht werden. Da passt was nicht und ich weiß beim besten willen nicht mehr was- die Werte irretieren mich zunehmenst da eine ausführliche Beschreibung dessen welcher Wert was in Welchen zusammenhang wie macht doch fehlt. Auch in der PDF bin ich nicht fündig geworden.

Vor allem aber bei den andauernden permanenten hin und hergeschalte (automatik) kommt der Deutz OHNE Anhänger oder Gerät bei diesem Gefälle nichtmal mehr über 10 kmh... das erscheint mir sehr viel zu gering bzw. unrealistisch

Zur Anschauung meiner XML - habe ich diese mal hochgeladen- evtl kannst du / jemand mir helfen bei meinem Problem. 

Vielen Dank im Vorraus und Grüße
[XML_DeutzAgrostar681_Mogli.txt](https://github.com/Mogli12/GearboxAddon/files/121559/XML_DeutzAgrostar681_Mogli.txt)

**Comment by Mogli12** [comment]
Hi,

2 Kleinigkeiten habe ich gefunden. ratedRpm sollte die Nenndrehzahl sein und dort sollte motorTorque noch nicht 0 sein. 

Hier mal mein Vorschlag auf Basis des Tests http://www.dlg-test.de/pbdocs/traktoren/deutzfahr-681agrostar.pdf:
			<realEngine idleRpm="1000" ratedRpm="2350" >
        
        <torque rpm="350" motorTorque="282" fuelUsageRatio="373.2"/>
        <torque rpm="700" motorTorque="535" fuelUsageRatio="264.5"/>
        <torque rpm="900" motorTorque="645" fuelUsageRatio="227.7"/>
        <torque rpm="1000" motorTorque="687" fuelUsageRatio="216.2"/>
        <torque rpm="1100" motorTorque="714" fuelUsageRatio="209.3"/>
        <torque rpm="1200" motorTorque="723" fuelUsageRatio="207"/>
        <torque rpm="1300" motorTorque="716" fuelUsageRatio="207.2"/>
        <torque rpm="1400" motorTorque="708" fuelUsageRatio="207.7"/>
        <torque rpm="1500" motorTorque="698" fuelUsageRatio="208.6"/>
        <torque rpm="1600" motorTorque="688" fuelUsageRatio="209.8"/>
        <torque rpm="1700" motorTorque="676" fuelUsageRatio="211.3"/>
        <torque rpm="1800" motorTorque="663" fuelUsageRatio="213.3"/>
        <torque rpm="1850" motorTorque="656" fuelUsageRatio="214.3"/>
        <torque rpm="1900" motorTorque="649" fuelUsageRatio="215.5"/>
        <torque rpm="1950" motorTorque="641" fuelUsageRatio="216.8"/>
        <torque rpm="2000" motorTorque="633" fuelUsageRatio="218.1"/>
        <torque rpm="2050" motorTorque="625" fuelUsageRatio="219.6"/>
        <torque rpm="2100" motorTorque="617" fuelUsageRatio="221.1"/>
        <torque rpm="2150" motorTorque="608" fuelUsageRatio="222.7"/>
        <torque rpm="2200" motorTorque="599" fuelUsageRatio="224.4"/>
        <torque rpm="2250" motorTorque="590" fuelUsageRatio="226.2"/>
        <torque rpm="2300" motorTorque="580" fuelUsageRatio="228"/>
        <torque rpm="2350" motorTorque="568" fuelUsageRatio="230"/>
        <torque rpm="2400" motorTorque="531" fuelUsageRatio="234.2"/>
        <torque rpm="2450" motorTorque="447" fuelUsageRatio="253.5"/>
        <torque rpm="2500" motorTorque="328" fuelUsageRatio="294.8"/>
        <torque rpm="2550" motorTorque="177" fuelUsageRatio="363"/>
        <torque rpm="2600" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="460"/>
			</realEngine>


Bei der Lastschaltung ist es am besten, wenn Du shiftTimeMs="0" verwendest. Vorher kannst Du aber auch die neueste Version vom Getriebe probieren.

Ansonsten kannst Du mal probieren, die Zeiten zu erhöhen:
<gears defaultGear="2" shiftTimeMs="80" automatic="true" autoShiftTimeout="5000" autoShiftTimeout2="1000">

5000 und 1000 Millisekunden sind Standard. autoShiftTimeout2 sollte auf jeden Fall kleiner als autoShiftTimeout sein.

Viele Grüße

**Comment by Marc85BPG** [comment]
Sehr viel besser rechtherzlichen Dank für deine schnelle Hilfe :) Mit dem Setup kann ich mehr als gut leben. 

Beste Grüße
