### ISSUE TITLE
Automatik schaltet nicht mehr seit update 2.4.1

### ISSUE THREAD

**Issue by n3cRomaNiac** [Mogli12/GearboxAddon#180]
Hi, erstmal danke für den hervoragenden Mod.

Das ist meine erste Issue bei Github also seit bitte gnädig! :)

Ich spiele jetzt seit einer Weile mit der gearbox aber seit update 2.4.1 schalten meine Automatik Schlepper nicht mehr automatisch.

Es steht jetzt [Automatik (--2)] oben im Hud.

Der Traktor dreht bis zum Drehzahlbegrenzer aber schaltet nicht mehr. Stattdessen kann ich mit dem Ganghebel alle 23 Gänge durch tappen.

Kann sein das ich mich jetzt als Leihe aute, aber ist das so gewollt oder ein Bug?

**Comment by Mogli12** [comment]
Hi,

man kann es leicht mit KEY_rctrl KEY_slash (Strg rechts plus "-") korrigieren. Ich hoffe, dass es mit v2.1.4.2 behoben ist. Man kann jetzt alle möglichen Kombinationen von manuell und automatisch Schalten einstellen. Am besten probierst Du es mal am großen amerikanischen Truck mit 3 Achsen aus.

Vielen Dank!

**Comment by n3cRomaNiac** [comment]
Danke für die schnelle Antwort.

Funktioniert jetzt einwandfrei :)
