### ISSUE TITLE
engine load at ~90% when in neutral using engine limiter

### ISSUE THREAD

**Issue by miracleman51** [Mogli12/GearboxAddon#181]
Hi.  Firstly fantastic mod.  The only issue I have noticed is that when manually setting the engine rpm (for instance ~1700 rpm before I start ploughing) the engine load is high (like 90%) but when moving it is not (before I have lowered the plough into the ground).

Otherwise fantastic work.

**Comment by Mogli12** [comment]
Hi,
It should be fixed with 2.1.4.3.
Thanks

**Comment by BlaggyXD** [comment]
Hello,
Now its on 0% Load while Reving up , could you mabye do it in a way that it goes to about 100% when reving up but when it reached its Max. Rpm it goes down to about 20 or 30 %? (Like it is if you are in Gear and speeding up)
That would be the most realistic way , i dont know if its Possible , but it would begreat.

Greets,
Blaggy

**Comment by miracleman51** [comment]
I think I get what you mean but tbh I thinks its fine how it is now.  An engine wouldn't need 100% load while just free revving.  maybe like 5-10% resting load to account for things like hydraulic pump/fan, alternator, etc?

**Comment by BlaggyXD** [comment]
It would sound a lot better if it was like i said , I think you dont play with with a Mannual Clutch and H-Shiftig ?

**Comment by Mogli12** [comment]
Please try version 2.1.5.0

**Comment by BlaggyXD** [comment]
Now its allmost like bevor the chanches , deffnitly a lot better then 0% Load.

**Comment by miracleman51** [comment]
nah this is wrong,  no if you have no load on the engine and you have the rpm set at say 1800 rpm you have like 80% load on the engine... this is not realistic at all??

**Comment by Mogli12** [comment]
80% load? With version 2.1.5.x?

**Comment by miracleman51** [comment]
yep, ive gone back to 2.1.4.9

**Comment by ivanlii** [comment]
G27, H-shifter, pedal Clutch :
clutch at 0%, maxThrottle (maxRPM), any lower gear, release clutch => RPM stays at max...
I find 2.1.4.9 better.
Who's watching the load numbers all the time anyway? I appreciate the load by motor sound(revs) and throttle press.

**Comment by BlaggyXD** [comment]
Yeah there is a big bug after v2.1.4.9 , i made an issue for that #186 .

**Comment by Mogli12** [comment]
This issue is about engine load in neutral. Can we please stick to the topic?

**Comment by Mogli12** [comment]
The last fix did not check for hand throttle. Now the load should be about 30% at high RPM in neutral.

**Comment by miracleman51** [comment]
Yes that works really nicely now!  I think I see what you meant now Blaggy... Im liking it!
