### ISSUE TITLE
Drehzahlabsenkung bei Tempomat

### ISSUE THREAD

**Issue by reinholdmaehler** [Mogli12/GearboxAddon#182]
Hallo Stefan,

ich weiss nicht wie ich es erklären soll. Ich habe DriveControl wegen Allrad / Diff. Sperren. Wenn ich mit dem 900 Axion mit Frontgewicht sonst Solo aus deiner Config bei z.B. 50 kmh fahre, dreht der Motor bei 1800 Umdrehungen. Sobald ich DC Allrad einschalte, senkt sich der Motor auf 14-1500 Umdrehungen. Allrad aus - Motordrehzahl wieder hoch.
Ich kann mir folgenden Grund vorstellen: der Schwerpunkt des Fahrzeugs ist wegen Frontgewicht weiter vorne und es ist Schlupf auf den Hinterrädern. Leider habe ich das Verhalten (wenn auch weniger schlimm) auch ohne Frontgewicht gesehen. Ander kann ich mir vorstellen, dass die VA die Hauptachse ist bei den Smety Axions.

Ist kein Weltuntergang - nur da dein Mod so gut funktioniert, möchte ich drauf hinweisen. 

LG!
Reinhold

**Comment by Mogli12** [comment]
Hallo Reinhold,
ich habe es gerade probiert, aber kann es leider nicht reproduzieren. Nachdem 52 km/h erreicht wurden senkt sich die Drehzahl mehr oder weniger schnell auf 1630 U/min.
Viele Grüße,
Stefan
