### ISSUE TITLE
Anfahrt des Helfers mit Last (Grubbern)

### ISSUE THREAD

**Issue by taylorfx** [Mogli12/GearboxAddon#184]
Hallo,

Ich habe folgendes Problem.  Wenn ich einen Helfer grubbern lasse mit einem Giant 6m Grubber und Traktor (6r oder 7r) passiert es recht häufig, das er nach der Wende am Feldrand nicht mehr ankommt. Das läßt sich lösen, indem man einsteigt und 2 Gänge runterschautet (im Helfermode), dann fährt los und schaltet erwartungsgemäß je nach Last hoch. Klar könnte man jetzt im Helfermode die Gearbox ausschalten, um das Problem zu lösen, aber dann ist auch der schöne Sound weg. Ich fahre alle Traktioren mit der Gearbox, egal, ob Helfer oder courseplay. Das Problem hängt wohl mit der Drehmomentproblematik zusammen - und da kann man es wohl nie allen Recht machen. Mein Problem, das ja eigentlich auch andere haben müßten, könnte man doch vielleicht lösen, wenn man die Startstufe beim Anfahren bestimmen könnte, in meinem Falle: fahre immer mit B4 an (JD 6R).
Ist sowas vielleicht möglich und sinnvoll?

Gruß

Frank

**Comment by Mogli12** [comment]
Hallo Frank,

die Startstufe kann man bestimmen. Im Stand ("Auto Hold") einfach den Vorwärtsgang auswählen, fertig.

Gruß,
Stefan

**Comment by taylorfx** [comment]
Au au au, wie so oft, liegt der Fehler dann wieder zwischen den Ohren, das bedeutet, stelle ich die Fahrstufe auf bzw. B4, und starte dann den Helfer, fährt er nach jeder Wende wieder mit B4 an? Aber okay, ich werde heute Abend testen

Danke für die Antwort

Gruß

Frank

**Comment by Mogli12** [comment]
Es gab noch ein paar Probleme, dass sich das Getriebe nicht in allen Situationen den Gang zum Anfahren gemerkt hat. Mit 2.1.5.2 sollte es besser sein.

**Comment by taylorfx** [comment]
Aha, ok, ich hatte es nämlich getestet und die Schlepper sind tatsächlich nicht immer losgefahren mit der damals aktuellen Version, aber jetzt aktuell klappt es prima. Wenn ich allerdings den Startgang im Autohold wähle, mußte ich ja wieder in den nächsten Modus wechseln, sonst schaltet er ja nicht mehr hoch. Aber jetzt geht es ja eh.

Andere Sache: keine Unterstützung mehr für MR, ich finde es nicht ganz so dramatisch, da die Gearbox ja nach meinem Verständnis in Sachen Funktion mit MR konkurriert und wirklich gut funktioniert, und für die Bodenrealität gibt es ja noch den Giant-Mod. Aber den Link ins FS-UK-Forum verstehe ich nicht. Dort wünschen sich doch alle die Kompatibilität beiden Mods und sind voll des Lobes für die Gearbox (so übersetzte ich zumindest die Artikel :-) )

Gruß

Frank
