### ISSUE TITLE
Schaltgetriebe sind wie Hydrostat- / (Wandler-) getriebe 

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#186]
Servus,
Seit der v2.1.5.0 drehen alle Bulldogs mit einem normalem Getriebe bis zu Maximaldrehzahl (nach dem anfahren) und beschleunigen dann so bis auf die Maximalgeschwindigkeit in dem gewählten Gang, in der anzeige von der Gearbox steht das so (und der Ton passt auch dazu) , aber in den Vehikel Daten dreht der Motor so hoch wie er es sollte.
Aber sie lassen sich ganz normal abwürgen.
Wenn nicht ganz klar ist was ich meine kann ich noch ein Video dazu machen.

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Servus,
Das trifft bei allen Bulldogs auf von dem her sollte die Getriebe Konfiguration un interessant sein.

Hier z.b. der Hürlimann H488:
 ( Standgas , Anfang der Beschleunigung , Mitte der Beschleunigung, ende der Beschleunigung)

![fsscreen_2017_07_25_16_00_53](https://user-images.githubusercontent.com/20562677/28576248-b4d70dd6-7153-11e7-9808-a874bb66e5e6.png)
![fsscreen_2017_07_25_16_00_56](https://user-images.githubusercontent.com/20562677/28576249-b4d7e8d2-7153-11e7-9cfa-6613d065dd5e.png)
![fsscreen_2017_07_25_16_00_59](https://user-images.githubusercontent.com/20562677/28576250-b4d9c2e2-7153-11e7-821d-56fbaa6e089e.png)
![fsscreen_2017_07_25_16_01_03](https://user-images.githubusercontent.com/20562677/28576251-b4da2016-7153-11e7-9cb4-30ab523375f5.png)


Grüße,
Blaggy

**Comment by Mogli12** [comment]
Kannst Du mir noch die log.txt schicken?

**Comment by BlaggyXD** [comment]
Das Tritt auf egal wie man fährt , (Auto. Kupplung , Kupplung , G 27 Auto. Kupplung , G 27 Kupplung)

In der Log steht zwar nix , aber :

[Log](https://pastebin.com/AZdShEr4)

**Comment by Mogli12** [comment]
Bei mir ist alles normal. Kannst Du es mal nur mit den notwendigsten Mods probieren? Komisch sind auch Meldugen wie 

`Error: Invalid mod name 'FS17_GearboxAddon-1'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit`

Was hast Du denn alles im mods-Ordner noch drin?

**Comment by BlaggyXD** [comment]
An der Meldung ist nichts Komisch , das ist die v....49 welche noch geht, das ich nicht dauernd wechseln muss nenn ich sie so dass das Spiel sie nicht Läd.

Wenn ich alle mods raus nehm bis auf die GB ist es gleich.

Evtl. hängt es damit zusammen bzw. verstärkt es dass ich das Hoch / Runter drehen schneller ( Realistischer) gemacht hab.

**Comment by Mogli12** [comment]
> Evtl. hängt es damit zusammen bzw. verstärkt es dass ich das Hoch / Runter drehen schneller ( Realistischer) gemacht hab.

Wie hast Du das gemacht. Da ich nichts dazu im Log sehe, haast Du in gearboxMogli.lua geändert?

**Comment by BlaggyXD** [comment]
Ja das hab ich in der .lua gemacht.

**Comment by Mogli12** [comment]
Die Werte in gearboxMogliGlobals kann man ganz bequem über die Datei gearboxAddonConfig.xml ändern. Modifizierte ZIP- oder LUA-Dateien möchte ich eigentlich nicht supporten.

Bitte mache nochmal ähnliche ScreenShots wie oben mit Version 2.1.5.2.

**Comment by Mogli12** [comment]
Sind die Bilder jetzt mit der unveränderten LUA aus 2.1.5.2 oder hast Du sie wieder verändert. Man sieht, dass getLastMotorRpm() und self.clutchRpm icht zusammen passen, obwohl die Kupplung auf 100% steht. Das kann ich mir nur mit falschen Werten für RpmDecFactor und RpmIncFactor erklären. Vermutlich ist RpmDecFactor negativ. Im Standard sollte er irgendwo zwischen 0.5 und 1 liegen.

**Comment by BlaggyXD** [comment]
Ja hab ich , aber nur das Hoch- / Runterdrehen. Soll ich es mal versuchen wenn ich das in den Globals mache ?

**Comment by Mogli12** [comment]
Hallo, ich denke, dass das Problem mit 2,1.5.3 gelöst ist. Vorsicht, ab 2.1.5.4 geht das Getriebe nicht mit mit moreRealistic zusammen. da ich das ständige Gemecker von Dural leid bin.

Die Defaults fürs Hoch-/Runterdrehen kannst Du mit 
DefaultRevUpMs0 
DefaultRevUpMs1 
DefaultRevDownMs
ändern.

**Comment by BlaggyXD** [comment]
Servus,
Super , damit geht wieder alles Einwand frei. Mit MR hab ich bis her noch nicht gespielt da es nicht mehr den Nutzen hat welchen ich davon erwarte, und selbst wenn würde ich die Gearbox MR bevorzugen.

**Comment by Mogli12** [comment]
Ich machen dieses Issue jetzt zu, ok?
