### ISSUE TITLE
Motorbremse

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#187]
Hallo Stefan,

mir ist aufgefallen, dass die Motorbremse bei Schalt- und Stufenlosengetrieben nicht so richtig will. Bei beiden geht die Drehzahl auf Leerlauf, obwohl man z.B. 40 km/h fährt. Soll das so sein?

Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Andreas,

bitte nenne ein konkretes Beispiel und füge am besten einen ScreenShot hinzu.

Danke,
Stefan

**Comment by Fracking** [comment]
[Video](https://youtu.be/NBBn_zIY1xM)
[Log](https://gist.github.com/Fracking/b99d322c2a38ed0ebdb7874b95825c81)

Im Video kann man sehen, wie die Drehzahl nach dem Beschleunigen auf Leerlauf-Niveau runter geht und dort bleibt. Ich glaub das kommt im Video gut rüber. Ansonsten geb ich gerne weiter Erleuterungen.

Andreas
