### ISSUE TITLE
Question (not an issue) - Transmission Configuration in mod XML

### ISSUE THREAD

**Issue by jkisaragi** [Mogli12/GearboxAddon#188]
Mogli,

I have a few vehicles I am working on, one is a Floater (like a n AGCO TerraGator or Case Titan or similar). and I would like to include GearboxAddon in the configuration for it.  I have a few questions with regards to the XML files for FS17 and including the configuration within them:  

The transmission is based on Allison M6620 Automatic w/ 6 Forward and 2 Reverse gears, using the samplemod2 in the repository as an example:

```
<gears defaultGear="3" reverseReset="true">	
	<gear speed="5.5"  forwardOnly="true" name="1"/>
	<gear speed="7.9"  forwardOnly="true" name="2"/>
	<gear speed="12.5" forwardOnly="true" name="3"/>
	<gear speed="17.6" forwardOnly="true" name="4"/>
	<gear speed="25"   forwardOnly="true" name="5"/>
	<gear speed="8.8"  reverseOnly="true" name="R"/>
</gears>
```

To match the Allison M6620 would the configuration be:

```
<gears defaultGear="?" reverseReset="true">	
	<gear speed="x" forwardOnly="true" name="1"/>
	<gear speed="x" forwardOnly="true" name="2"/>
	<gear speed="x" forwardOnly="true" name="3"/>
	<gear speed="x" forwardOnly="true" name="4"/>
	<gear speed="x" forwardOnly="true" name="5"/>
        <gear speed="x" forwardOnly="true" name="6"/>
	<gear speed="x" reverseOnly="true" name="R1"/> <!-- or would it be name="1" -->
        <gear speed="x" reverseOnly="true" name="R2"/> <!-- or would it be name="2" -->
</gears>
```

**defaultGear** - Is this the launch/starting gear that the transmission will be in by default?  Any reason not to use gear 1? or what would be the appropriate starting gear in this instance?

**gear speed="x"** - Is this speed in kmh/kph that the transmission shifts for that gear?

Thanks for your support!

v/r,

J. Kisaragi

**Comment by Mogli12** [comment]
Hi,
speed="x" is the speed in km/h at rated RPM. I propose to choose a default gear with speed between 10 and 15 km/h.
Regards,

**Comment by jkisaragi** [comment]
Mogli,

Great! Thank you!

Also, is it possible to use different configurations for different motor configurations?  Would I add them in under the motors?

-J

**Comment by Mogli12** [comment]
> Also, is it possible to use different configurations for different motor configurations?

Do you want to add configurations directly to the vehicle?. In this case it should be under the motor-tag.

If you want to add configurations to the gearboxAddonConfig.xml in your mods-folder (please do not modify any file inside FS17_GearboxAddon.zip) you can use the engines-tag. Please check my configuration for the FS17_MB3D_JohnDeere7030 in https://github.com/Mogli12/GearboxAddon/blob/master/FS17_GearboxAddon/gearboxAddonConfig.xml.

BR

**Comment by jkisaragi** [comment]
Correct, I wanted to add the configurations directly to the vehicle, have gearbox "built-in" to the tractor.

Of course, I definitely will not modify any of the files inside your mod! 

I have a hosted dedicated MP server and when I upload the gearboxAddon it gives me this "issue" warning:

![capture3](https://user-images.githubusercontent.com/30470443/28676871-dc58b30c-72b9-11e7-9502-ec746227ab26.PNG)

Is that an actual issue I should be concerned about or ignore?

**Comment by Mogli12** [comment]
It is not possible to have different transmission options for different motor configurations. You can use the <transmissions> tag in the vehicle XML with Gearbox v3.1, but not per motorConfiguration.
