### ISSUE TITLE
Warning: Character '180' not found in texture font ().

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/GearboxAddon#19]
Hallo mogli,

wenn ich die aktuelle  Beta des Gearbox Addon im Mods Ordner habe und dann über "Optionen - Steuerung" in den Screen zur Steuerungskonfiguration gehe erscheint dieese Warnung in der log.txt:

GIANTS Engine Runtime 6.0.2 (Build Date: Jan 19 2016)
Copyright (c) 2008-2015, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2015, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: 8 @ 3.5 GHZ
  Memory: 16384 MB
  OS: Mac OS X 10.10.5
Physics System
  Version: 5.9.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
    Name: Logitech Rumblepad 2 USB
    Number of Axes: 4
    Number of Buttons: 16
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Boom2Device
  Max. sources: 512
Render System
  Driver: OpenGL
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 780M OpenGL Engine
  Version: 4.1 NVIDIA-10.4.2 310.41.35f01
  Shader Version: 4.10
    GL_ARB_pixel_buffer_object not supported
    GL_NV_texture_compression_vtc not supported
    GL_ARB_texture_compression_rgtc not supported
    GL_ARB_framebuffer_sRGB not supported
    GL_EXT_texture_sRGB not supported
    GL_ARB_framebuffer_sRGB not supported
    GL_ARB_texture_compression_rgtc not supported
    GL_ARB_draw_instanced not supported
    GL_ARB_uniform_buffer_object not supported
    GL_EXT_framebuffer_object not supported
    GL_EXT_framebuffer_blit not supported
    GL_ARB_occlusion_query not supported
    GL_ARB_fragment_program not supported
    GL_ARB_get_program_binary not supported
    GL_ATI_texture_float not supported
    GL_ARB_texture_float not supported
    OpenGL initialization successful
Hardware Profile
  Level: Very High (auto)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Foliage View Distance Factor: 1.600000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
Farming Simulator 15
  Version: 1.4.2.0 1.4.2RC2
  Available Languages: en fr es it nl pt
  Language: en
Game vehicle types loaded
Mod directory: /Users/don_apple/Library/Application Support/FarmingSimulator2015/mods/
Load mod: zzzMrGearboxAddon
Warning: Character '180' not found in texture font ().

Laut [https://forum.giants-software.com/viewtopic.php?t=55095#p445509](url) stimmt da wohl etwas mit der UTF8 Kodierung der modDesc.xml nicht.

**Comment by Mogli12** [comment]
Hi, die Meldung ist aus FS15. Ich hoffe mal, dass sie unter FS17 nicht auftritt.
