### ISSUE TITLE
2 cruise control options instead of 3?

### ISSUE THREAD

**Issue by SoloTwo** [Mogli12/GearboxAddon#190]
Just wondering if it would be possible for me to make it so there were only 2 cruise control speed options when pressing the 5 key.  I'd like to be able to have one speed for working and one for the headland ideally.

**Comment by Mogli12** [comment]
Hello,

There is a new mod "Tempomat Addon". It is very similar to my spec tempomatMogli, which is part of the gearbox addon. Should I disable the cruise control additions in my gearbox?

Regards, Stefan

**Comment by cabmac** [comment]
nooooo, i think the gearbox-Tempomat works great, there is no reason to change to other tampomat-mod

**Comment by SoloTwo** [comment]
What kind of effect would this have?  I don't want anything to negatively affect anyone who prefers the 3 cruise control options.  In the older documentation, the option of 2 speeds, one for working and one for headlands was mentioned.  Since my main tractor, I use is the MF 7722 and it has the option for 2 cruise control speeds only I was just trying to emulate it.  

I've just never personally found the need for 3 separate options and it becomes awkward if you change between all 3 to try and set a headland and working speed.  But I'm sure many others prefer the 3 options.   If there is an easy way to adjust the option to 2 instead of 3 that'd probably work best.  But either way, it's not the end of the world.  

Whoops just saw the new mod available.  Sounds interesting but also kind of complicated.  Perhaps if we could just have input bindings to choose each cruise control setting instead of the 5 key scrolling through all 3 options?

**Comment by Mogli12** [comment]
Hi,

Please create a file gearboxAddonConfig.xml in your mods folder if not already present. You can disable the third speed with this parameter:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<onlyTwoSpeeds type="bool" value="true"/>
	</gearboxMogliGlobals>
```

**Comment by SoloTwo** [comment]
Thank you so much, works perfectly. 👍
