### ISSUE TITLE
Allrad / Differentialsperren

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#192]
Servus,
Das neue Allrad /Diff. ist genial und nix im vergleich mit dem von DC . Man muss jetzt wirklich auf die Gewichtsverteilung achten , da für gibt ein riesen Lob von mir!

Beim ersten testen ist mir gleich mal aufgefallen das die Anzeigen sich mit denen von einem Frontlader überlappen. Hier ein Bild zur Verdeutlichung:
![gb_4wd_diff](https://user-images.githubusercontent.com/20562677/28888689-d526deb2-77c1-11e7-8062-52124429eb73.png)

Und noch ein etwas ist mir aufgefallen, aber ich bin mir nicht sicher ob man das lösen kann.
Die Vorderräder treiben immer etwas mit an so wie die Differentiale nicht mehr richtig schließen so bald man das Allrad an hat.
Aber das ist mehr oder weniger rein Optisch und wie gesagt ich meine schon mal gehört zu haben dass man das im 17'er nur so lösen kann.

Grüße,
Blaggy

**Comment by ivanlii** [comment]
Hi Stefan, 
Why the load and fuelConsumption are greater by about 25-33% when no middleDiffLock?
I thought more diff are locked => more fuel consumption, less speed, less turning angle.
Anyway, very nice addition!

**Comment by Mogli12** [comment]
Hi,
The fuel consumption should be fixed now. It would be great if few people could test this a little. Please remember, diff.locks in gearbox addon only work if the vehicle has standard differentials and if the differentials are not manipulated by zzzDriveControl.
Regards, Stefan

**Comment by BlaggyXD** [comment]
Servus,
Man verbraucht jetzt ca. 1-4l mehr wenn die Sperren an sind also das klappt so wie es soll.( Getestet mit Hürlimann H-488 und vollem Miststreuer Bergauf, John deere 7X50 und vollem Miststreuer Bergauf.)

Wenn man nur die Sperre hinten an hat sind die Differentiale zu fast 100% zu aber die Vorderräder treiben etwas mit an wenn man dann noch das Allrad an macht sind die Differentiale wieder etwas "offener" aber nicht ganz so wie wenn man sie aus hat. Und wenn man nix an hat treibt immer nur ein Hinterrad an. Aber ich denke das merkt man kaum da ich beim Testen einfach gegen eine Wand gefahren bin und die Sperren / Das Allrad angemacht hab, und das sind solch Extreme Bedingungen das man sie wahrscheinlich so beim spielen nie erreichen würde bzw. es kaum auffallen würde. (Getestet mit dem Hürlimann H-488.)

Grüße,
Blaggy

**Comment by normada** [comment]
Werden die Differentiale auch noch helfertauglich gemacht ? Z.Zt. werden sie jedesmal beim Einschalten des Helfers (AIVehicleExtension) ausgeschaltet. Schade.

Gruss
Ron

**Comment by Mogli12** [comment]
Hallo Ron,

was genau verstehst Du unter "helfertauglich"? Momentan ist es so, dass beim Helfer die ursprünglichen Standard-Differentiale aus dem Fahrzeug verwendet werden. Das sollte doch für den Helfer die optimale Lösung sein, oder?

Gruß,
Stefan

**Comment by normada** [comment]
Hallo Stefan,
keine Ahnung ob der Helfer (Standard oder AIVehicleExtension) irgend ein Differential benutzt. Ist das ersichtlich ? Ich benutze seit ewig den 4wd und die Differentiale von DriveControl, welche man beim Helferbetrieb durch Shift+4 etc. zuschalten kann. Auch Courseplay kann diese an/ausschalten. Bei DC sind halt auch  im Helferbetrieb die entsprechenden Icons aktiviert (4wd, Differentiale).
Das Ergebnis des Zuschaltens von 4wd/Differentialen sowohl bei DC als auch beim GB-Addon ist ja auch sofort an der Umdrehung der Räder zuerkennen. 
Es wäre halt super, wenn man die GB-Differentiale, welche augenscheinlich die Besseren sind, auch mit dem Helfer nutzen könnte. Will sagen, aktiviere ich zB. den 4wd (GB) und schalte den Helfer ein, ist 4wd deaktiviert. Dasselbe mit den Differentialen. Beim DC werden sie im Helferbetrieb nicht deaktiviert.

Anyway, weiter so mit Deiner guten Arbeit

Gruss
Ron

**Comment by Mogli12** [comment]
Hallo Ron,

zzzDriveControl übersteuert immer die Differentiale. Also musste CoursePlay da etwas machen, um sie automatisch zu sperren.

GearboxAddon setzt die Differentiale wieder auf den originalen Zustand zurück, sobald der Helfer oder Courseplay eingeschaltet sind. Daher muss man die auch nicht ein- oder ausschalten. Mir schien das irgendwie sinnvoller.

Gruß,
Stefan

**Comment by ivanlii** [comment]
Hi Mogli, v2174: seems that diffs are kept (from GB) when turning GB off (rightShift ;). This is intentional?

**Comment by Mogli12** [comment]
This was not intentional. Is it fixed with in the latest version?

**Comment by ivanlii** [comment]
All ok. thanks!
