### ISSUE TITLE
Fahrhebelmodus geht nicht mehr richtig.

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#193]
Servus,
Mir ist gerade eben aufgefallen das der Fahrhebelmodus am CVT nicht mehr richtig geht mit dem neuem Tempomat (ich vermute entweder seit der 2.1.5.6 oder der 2.1.5.7) .So bald man anfährt beschleunigt er einfach nur auf die Geschwindigkeit der ausgewählten Tempomatstufe .Wenn man das Pedal ganz durch drückt beschleunigt er bis auf die Höchstgeschwindigkeit aber so bald man das Pedal los lässt geht er wieder auf die vom Tempomat vorgegebene Geschwindigkeit zurück.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

ja, da war ein Fehler drin. Mit 2.1.6.0 sollte es wieder klappen. Außerdem funktioniert dann auch die Taste 3 (sowohl antippen, als auch gedrückt halten).

Grüße,
Mogli

**Comment by BlaggyXD** [comment]
Servus Mogli,
ich bin heute endlich mal zum testen gekommen und es geht wieder alles so wie es soll. Top Arbeit.

Grüße,
Blaggy
