### ISSUE TITLE
Realistisches Getriebe, Automatik, Gruppen und Gänge

### ISSUE THREAD

**Issue by hnsstrk** [Mogli12/GearboxAddon#195]
Hallo Mogli,

wenn ich das realistische Getriebe aktiviert habe und auf Automatik fahre, dann schaltet diese durch die Gruppen und nicht durch die Gänge. Ich muss zugeben, dass ich keinen Meter Ahnung von Traktoren habe, aber anderes herum käme es mir irgendwie logischer vor. 

Viele Grüße
Hans

**Comment by Mogli12** [comment]
Hallo Hans,

Du hast vermutlich den "Vereinfacht"-Modus eingeschaltet, oder? Bei manchen Traktoren (Case IH 1455) schaltet das Getriebe dann die Gruppen.

Viele Grüße,
Stefan

**Comment by hnsstrk** [comment]
Hmmm,.... 
Die Einstellung war schon auf "realistisch". 
Ich habe leider ein paar Schwierigkeiten, das Ganze zu reproduzieren, arbeite aber dran.
Zwischenzeitlich hatte ich die 2.1.5.9 getestet und mein Setup versaut. ;-)
Ich komme nicht mehr in den Automatikmodus.
Wenn ich es hin bekomme mache ich mal ein Video.

By the way... Danke für die Mods.
Sollten wir uns mal über'n Weg laufen hast du ein :beer: gut.

**Comment by hnsstrk** [comment]
Hier mal ein Video mit dem MF 5613:

- http://hnsstrk.deneb.uberspace.de/FS17_Gearbox2160_MF5613.mp4

Die Einstellung ist auf Automatik, dass man im Video leider nicht erkennen.
Der eingestellte Gang bleibt fix und die Automatik schaltet durch die Gruppe.
Oder zumindest glaube ich das. Die Wahrscheinlichkeit, dass ich das Ganze nicht verstanden habe ist nicht gerade gering. Lieder...

**Comment by Mogli12** [comment]
Hallo Hans,

ja, das ist so von mir konfiguriert. Der MF schaltet nur die Lastschaltstufen automatisch. Die Gänge muss man selber von Hand schalten.

Viele Grüße,
Stefan
