### ISSUE TITLE
Valtra N und T Serie - Tastenbelegung für Gänge und Getriebe

### ISSUE THREAD

**Issue by hnsstrk** [Mogli12/GearboxAddon#196]
Bei der Valtra N und T Serie ist ggf. die Belegung der Tasten für Gänge und Gruppen vertauscht. So lassen sich die Gänge mit "+" und "#" rauf und runter Schalten, die Gruppen (range A - D) aber mit "ü" und "ä". 

Bei der S Serie wechselt man zwischen "heavy dury" und "transport" auch mittels "ü" und "ä". Wenn ich mir Zeile 2571 und 2572 der "gearboxAddonConfig.xml" anschaue ist das aber richtig.

- Getestet in Version 2.0.0.9 und 2.1.6.0.
    - http://hnsstrk.deneb.uberspace.de/FS17_Gearbox2009_ValtraN174.mp4
- Getestet in Version 2.1.6.0.
    - http://hnsstrk.deneb.uberspace.de/FS17_Gearbox2160_ValtraT234.mp4
    - http://hnsstrk.deneb.uberspace.de/FS17_Gearbox2160_ValtraS374.mp4

**Comment by Mogli12** [comment]
Hallo Hans,

ich habe bei Getrieben mit Gängen und automatischen Lastschaltstufen grundsätzlich die Gänge auf die Tasten für Gänge gelegt, die Lastschaltstufen auf die Tasten für Gruppen. Da die Lastschaltstufen automatisch geschaltet werden, muss man eigentlich nur die Tasten Ä/Ü verwenden. Das ist also Absicht.

Bei Getrieben mit manuellen Lastschaltstufen habe ich diese auf die Tasten Ä/Ü gelegt, weil man diese ja ständig ändern muss.  (Beispiel New Holland 8340).

Bei stufenlosen Getrieben kann man eh nur Gänge wechseln, also Ä/Ü.

Es ist für die Zukunft ohnehin geplant, dass man sich pro Fahrzeug die Zuordnung, was ein Gang und was eine Gruppe ist, selber ändern kann.

Viele Grüße,
Stefan
