### ISSUE TITLE
speedMatching

### ISSUE THREAD

**Issue by punchi1** [Mogli12/GearboxAddon#197]
Moin,

kann man das speedMatching irgendwie für den Richtungswechsel ausschalten? Also Vorwärts/rückwärts schalten?

**Comment by Mogli12** [comment]
Hallo,

man kann das Speed Matching nur global ausschalten: https://github.com/Mogli12/GearboxAddon/issues/103

Viele Grüße,
Stefan

**Comment by punchi1** [comment]
Ich mein das anders,
also das er Speedmatching nur bei den Gruppen macht. 
Beispiel ist der 800er Axion.
Hab da Speedmatching angemacht, damit er z.b. nicht von C 6 auf D 6 springt sondern auf D1.
Jetzt springt er allerdings auch beim Vorwärts/rückwärts wechsel auf den entsprechenden Gang.

**Comment by Mogli12** [comment]
Wie gesagt, man kann es nur global an- oder ausschalten.

**Comment by Mogli12** [comment]
-> settings UI

**Comment by Mogli12** [comment]
With version 3.0 build 304 you can configure speed matching in the settings UI
