### ISSUE TITLE
Cant Change Range 2

### ISSUE THREAD

**Issue by Tanglewolf** [Mogli12/GearboxAddon#198]
hi, im having an issue changing the second range, im recieving this error

Error 3: F:/My Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua:5120: attempt to call method 'combineGear' (a nil value)

`
5120         			local newRange = gearboxMogli.mrGbMGetNewEntry( self, self.mrGbMS.Ranges, self.mrGbMS.CurrentRange, new, "range" )`

in manual mode using the duetz 661 if its in gear i can adjust range 1 but not range 2, that error pops up each time i hit the button.  If its in neutral it works. Is it just me suffer from a mod conflict or can others replicate this?

thanks, Dave

**Comment by Mogli12** [comment]
Hi,

Which version are you using?

Best regards,
Stefan

**Comment by Tanglewolf** [comment]
v2.1.6.0

**Comment by Mogli12** [comment]
No, I cannot reproduce it. Can you reproduce it with no other mods activated?

**Comment by Tanglewolf** [comment]
iv managed to find the issue, there is a conflict with your 'favourite' mod.... mod realistic lol

Iv rolled both back to mr1 and gearbox v2.1.0.6, i think these were the first two together and the issue appears to start at the beginning. I did recieve a warning for a different line of code in my testing though, in v2.1.0.6


Error 3: F:/My Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua:4191: attempt to call method 'combineGear' (a nil value)

`
			local fr    = self.motor:combineGear( self.mrGbMS.CurrentGear, self.mrGbMS.CurrentRange )`

I no you have stopped support for mr and with the stupid comments directed at you i dont blame you.
gearbox is awesome, i went out a bought the g29 shifter to get the full benifit and will continue to use it. thanks for all your hard work on this and your other mods, they add so much to the game.

i thought this was worth bringing to your attention at least

thanks again, Dave

**Comment by Mogli12** [comment]
Hi Dave,

ok, maybe it is fixed with version 2.1.6.1.

Regards,
Stefan

**Comment by Tanglewolf** [comment]
Iv just started my night shift I'll test in the morning, 

thanks, have a good evening
Dave

**Comment by Tanglewolf** [comment]
Tested and all is working, ill close the issue

thanks again, dave
