### ISSUE TITLE
[Kein Fehler] Tempomat Addon

### ISSUE THREAD

**Issue by krzgw** [Mogli12/GearboxAddon#199]
Hallo Stefan,

im Modhub ist seit kurzem das [Tempomat-Addon](http://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=85129&title=fs2017) verfügbar, welches es einem erlaubt den Tempomaten mit dem Joystick zu steuern.
Nun würde ich gerne Mähdrescher mit dem Joystick fahren, jedoch erlaubt mir das Tempomat Addon nur Vorwährtsfahrten, das heißt die negative Joystickachse kann nicht rückwärts genutzt werden.
Nun wollte ich fragen ob ich die Funktion "gearboxMogli:mrGbMSetReverseActive" im Tempomat Addon aufrufen kann, sobald die Joystickachse einen Wert kleiner 0 annimmt um rückwärts zu fahren und auch anders herum um wieder vorwärts zu fahren.

Ich weiß, das ist kein Fehler vom Gearbox Addon an sich, aber ich habe leider keine Kenntnisse in lua und wollte fragen, ob du mir da vielleicht behilflich sein könntest (entsprechende Code-Schnipsel um die Funktion aufzurufen, falls dies möglich ist würden mir genügen).

Grüße, Michael

**Comment by Mogli12** [comment]
Hallo Michael,

die Joystick-Funktion gibt es im GearboxAddon schon seit Version 2.1.3.5: https://github.com/Mogli12/GearboxAddon/commit/b05075e8ada1ea8fe01e5ce62099610e0cf80935. Du kannst es über "KEY_rctrl KEY_delete" umstellen. 

Aber auch beim Rückwärtsfahren musst Du weiterhin den Fahrhebel nach vorne drücken um zu beschleunigen.

Viele Grüße,
Stefan

**Comment by krzgw** [comment]
Hallo Stefan,

vielen herzlichen Dank schon einmal für deine schnelle Antwort. Leider ist das nicht das was ich mir erhofft habe.
Ist es denn nicht möglich, im Joystick Addon die Reverse Funktion aufzurufen? Ich denke nämlich dass ich mit dem Addon und in Verbindung mit der Reverse-Funktion des GearboxAddon das Rückwärtsfahren umsetzen könnte. Nur scheitert es bei mir an den lua-Kenttnissen :/

Herzliche Grüße und einen Schönen Abend,
Michael

**Comment by Mogli12** [comment]
Hallo Michael,

das musst Du mich nicht fragen. Das Tempomat Addon wurde ohne meine Kenntnis gebaut und einen Großteil der Funktionen gibt es auch schon seit einiger Zeit im Gearbox Addon. Ich denke ohnehin nicht, dass man beide Mods gleichzeitig verwenden sollte.

Viele Grüße,
Stefan
