### ISSUE TITLE
Hand throttle to slider

### ISSUE THREAD

**Issue by ivanlii** [Mogli12/GearboxAddon#200]
Hi, i`m trying to bound the hand throttle to an slider on my joystick. (thrustmaster 1600)
The default game sees it as middle resting slider.
GB works but uses only half of the slider. 
I`ve searched/tried different solutions (controller apps) with no success.
Is there a workaround to this?
Thank you!

**Comment by Mogli12** [comment]
Hi,

I think there is nothing I could do in LUA. Maybe another user has the same device?

Regards

**Comment by yumi-modding** [comment]
Hello,

Have you tried looking into inputBinding.xml and adding isHalfAxis="false" to the hand throttle key so it might consider the full axis ?

**Comment by BlaggyXD** [comment]
Hello,
That is normal because the Slider got 2 Axis one from 0-100 and one from 0-(-)100 and FS can ounly read one of them. I got two Joysticks ( Thrustmaster T.16000M and Logitech X3D Pro) and its on both of them like this.

**Comment by ivanlii** [comment]
Thank you all for answers, i`ll keep my eyes open...

**Comment by rubberburner89** [comment]
I'm actually trying to set up the same thing, been at it for two days trying to find a work around... lemme know if anyone gets something!

**Comment by doc3d** [comment]
I use a program called joytokey and it works pretty well. I have the thrust-slider set up for manual throttle and it works

**Comment by ivanlii** [comment]
@doc3d Did you assigned up/down to KEY_=/KEY_-, with repeat option ?

**Comment by doc3d** [comment]
If I remember correctly, I mapped the function to the slider just like any axis, and it does work from 0-100%

**Comment by ivanlii** [comment]
Hi Mogli, still not found a clean solution to this problem but:
since game give axis value [-1, 1] and we use only half of it [0,1] why not convert it to full length, something like this:
`handThrottle = InputBinding.getAnalogInputAxis(InputBinding.gearboxMogliMINRPM)` to
`handThrottle = (InputBinding.getAnalogInputAxis(InputBinding.gearboxMogliMINRPM)+1)/2` ?
What do you think ?

**Comment by Mogli12** [comment]
There are joysticks with sliders. These axes have a range from 0 to 1.

**Comment by ivanlii** [comment]
This is exactly what i`m talking about and trying to set. The problem is game engine read (convert) those slider axles as [-1,1] even if they are default [0,1] (by driver or other software). Their default bound(default imputbinding) is "extend loader arm", <0=extend, >0=contract arm. I have a Logitech and a Thrustmaster and both are default [0,1] but ingame they are read as -0+. _isHalfAxis_ does not work either.

**Comment by Mogli12** [comment]
I do not agree. I have it working fine with a simple joystick. So it is neither a GB nor an engine problem.

**Comment by ivanlii** [comment]
Is not a problem, is an enhancement.
The stick axis and the slider axis are two very different types of axles.
The improvement for us will be the possibility to choose what type of axis we use.
[-1,1] stick or [0,1] slider.
But if is too complicated no problem, i will close this issue.
Thank you

**Comment by ivanlii** [comment]
from Cruise Control Addon:

> The axis can be in joystick mode (like New Holland and Fendt tractors) or direct input (like Case and most combines). Joystick mode works with any generic joystic while direct input mode works with throttle axes without centering springs and no negative axis. 

and a short video, min 0:30:
[https://www.youtube.com/watch?v=SoNuRzxojfw](url)

**Comment by Mogli12** [comment]
How and where should all of these differences be configured? Who should be able to keep an overview of so many configuration options? We already have too much right now.

**Comment by ivanlii** [comment]
No problem, tank you for your work!
Regards
