### ISSUE TITLE
Probleme mit dem Ausschalten Right Shift + Ö

### ISSUE THREAD

**Issue by RuppMartin001** [Mogli12/GearboxAddon#204]
Hallo Stefan,

gestern hatte ich die Version 2.1.6.5 installiert und festgestellt, dass man die Gearbox nicht mehr mit Right Shift + Ö (= Manuelles Getriebe = Off) deaktiveren kann. Im Hilfefenster steht aber noch die Tastenkombination.

Für mich persönlich ist das ein Problem, da ich manchmal nur mit Xbox-Controller spiele und dabei nicht die Gangschaltung + Lenkrad usw. nutze.
Ich bin einfach auf Version 2.1.6.3 zurückgegangen. Da funktioniert das Ausschalten noch.

Ich habe (erst danach) die Readme gelesen und gesehen, dass die Gangschaltung nun eine Option beim Kaufen werden soll. Heißt das, dass man in Zukunft die Gangschaltung über die Fahrzeugkonfiguration entfernen muss, damit man Gearbox temporär deaktiveren kann?

Wird das Abschalten nicht mehr möglich sein?

Viele Grüße

Martin Rupp

**Comment by Mogli12** [comment]
Hallo Martin,

ja, die Tastenkombination habe ich bewusst deaktiviert. Aber an Deinen Fall habe ich dabei nicht gedacht. Hast Du mal den "Vereinfacht" Modus RShift-Minus ("-") ausprobiert?

Viele Grüße,
Stefan

**Comment by Rapax4884** [comment]
Hallo Stefan, 

ich würde mir die Möglichkeit des Deaktivierens der Gearbox auch sehr zurückwünschen! 
Ich z.B spiele zusammen mit meiner Freundin. Ich benutze Gearbox da ich mit Lenkrad usw. spiele. Sie kann damit allerdings gar nichts anfangen und möchte ganze einfach "vanilla" fahren.. Bisher war es kein Problem, sie konnte die Gearbox einfach aus, bzw.  ich einfach einschalten. Mit den neuen Versionen ist das nicht mehr möglich. 
Die Möglichkeit die Transmission im Shop zu wählen finde ich absolut klasse! Z.b beim Axion 800 echt klasse zwischen CMATIC oder HEXASHIFT wählen zu können. Ich denke aber, die Möglichkeit die Gearbox wie bisher zu deaktivieren sollte trotzdem vorhanden sein! Meiner Meinung nach schließt das eine Feature das andere nicht aus.

Liebe Grüße, Chris

**Comment by Mogli12** [comment]
Hallo zusammen,

der XBox-Controller hat mich ja noch nicht überzeugen können. Aber wenn Chris jetzt schon die Freundin als Argument auffährt, dann kann ich natürlich nicht "nein" sagen.

Ab 2.1.7.0 ist die Tastenkombination zum Ein-/Ausschalten des Getriebes wieder da. Ich muss mir noch mal überlegen, ob dafür die Konfiguration "off" wieder verschwindet. 

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Chris,
ist es so besser?
Viele Grüße,
Stefan

**Comment by Rapax4884** [comment]
Hallo Stefan!

Danke der Nachfrage, ja es ist wunderbar. Dank dir hängt der Haussegen wieder gerade! :)
Vielen Dank nochmals!
Grüße, Chris
