### ISSUE TITLE
im shop keine gearbox auswahl mehr

### ISSUE THREAD

**Issue by Fendtfan84** [Mogli12/GearboxAddon#207]
Moin Mogli
bei der neusten Version ist beim kaufen im shop keine Gearbox Auswahl mehr möglich.
Hierdurch fahren jetzt alle Fahrzeuge nur noch durch gedrückt halten der Bremse rückwärts.
Auch die Fahrzeuge die in der  Gearboxconfigaddon.xml stehen.
Vielen Dank für diesen Mod ist eine wahre Bereicherung für den realitätslosen LS.

**Comment by Mogli12** [comment]
Hallo,
kannst Du mal die log.txxt bei Gist oder Pastebin hoch laden?
Danke

**Comment by Fendtfan84** [comment]
Yeap das mache ich.
Das ist der link von der log [https://gist.github.com/Fendtfan84/eac2fde4c47ceb530eec993e91982ccc](url)
Das ist der link von dem GearboxconfigAddon [https://gist.github.com/Fendtfan84/71f936efb81d02e63ab40f0d21bcb110](url)
Ich glaube beim einfügen der Gearboxconfig vom Deutz 6.71,6.91 vom Modhub vom Mr.Fox und DeutzFahrAustria ist mir ein Fehler unterlaufen.
Sorry schonmal von meiner Seite der Fehler liegt bei mir.
schöne Grüße
Fendt Fan

**Comment by Mogli12** [comment]
Hallo FendtFan,

die 3 Deutz von MrFox sind doch schon im GB drin (seit https://github.com/Mogli12/GearboxAddon/commit/f0846049e45cfbc96c30473f1e780db84c4be924)

Viele Grüße

**Comment by Fendtfan84** [comment]
Vielen Dank das habe ich glatt übersehen :-D.
Habe noch eine Frage zum JD vom MB3D Modelling die JD fahren jetzt durch gedrückt halten der Bremse rückwärts.
Könntest evtl. noch hinzufügen damit man den Vorwärts und Rückwärtsgang wie bei den vorigen Versionen auswählen muss?
Darüber würde ich mich sehr freuen

Vielen Dank für die Arbeit dir du in der Freizeit verichtest ziehe meinen Hut davor.
schönen abend wünsche ich dir
Fendt Fan

**Comment by Mogli12** [comment]
Hallo FendtFan,

ich habe es gerade nochmal probiert. Bei mir läuft der JD 7x30 ohne Probleme. Ich habe beim Kauf das AutoQuad ausgewählt. Kann es sein, dass bei Dir das "falsche" Getriebe konfiguriert ist?

Viele Grüße

**Comment by Fendtfan84** [comment]
Yeap
Ich hatte beim Kauf das Getriebe ausgewählt das zuerst erscheint.
Werde morgen dann den JD mit dem AutoQuad kaufen.
Ist bei autoquad auch bei anderen Fahrzeugen das Rückwärtsfahren so umgesetzt?

Viele Grüße

**Comment by Mogli12** [comment]
Hallo FendtFan,

die Texte sind wohl noch nicht so intuitiv. Das Getriebe built-in ist das Standardgetriebe von Giants. Dann ist das GearboxAddon also aus.

Viele Grüße

**Comment by Mogli12** [comment]
Hallo,

sind die Texte nun besser zu verstehen?

Viele Grüße

**Comment by Fendtfan84** [comment]
Hallo,

yeap jetzt sind die Texte im Shop super zu verstehen.
somit kannst diesen Thema schließen.

Viele Grüße
Fendt Fan
