### ISSUE TITLE
MR und GB inkompatibel?

### ISSUE THREAD

**Issue by THFalcon** [Mogli12/GearboxAddon#208]
Durch mehrere Test aufgefallen, dass nun MR und GB total inkombatibel geworden ist!
Jetzt muss man sich entscheiden, was man nutzen möchte, ich finde dies sehr, sehr schade, aber gleichzeitig kindisch!

Echt Schade sowas!

**Comment by Mogli12** [comment]
Keine Ahnung, was Du meinst. Seit Version 2.1.5.5 läuft GB und MR, allerdings mit einer dicken Warnung. Ich werde aktiv auch keine Anpassungen für MR mehr machen, obwohl es in der Vergangenheit schon etlich waren.
