### ISSUE TITLE
New "in shop" options

### ISSUE THREAD

**Issue by doc3d** [Mogli12/GearboxAddon#209]
Is there anywhere in the documentation where I can find the difference between the options?
I don't quite understand the difference between standard and the other different options.

I assumed built in is no gearbox -so standard fs17, but there are gearbox manual, auto, ctv etc as well as the standard option. Are the names set up in the config and different for each tractor? Does the mod author set these or are they predefined? And what is the difference between standard and the other options?

**Comment by doc3d** [comment]
Is there anywhere in the documentation where I can find the difference between the options? 
I don't quite understand the difference between standard and the other different options. 

I assumed built in is no gearbox -so standard fs17, but there are gearbox manual, auto, ctv etc as well as the standard option. Are the names set up in the config and different for each tractor? Does the mod author set these or are they predefined? And what is the difference between standard and the other options?

**Comment by Mogli12** [comment]
Hello,

The option is very new and the texts are not yet final. The first option "built-in" does not use the gearbox addon; this is the standard gearbox in FS17. All tractors have two options at the end with names "default manual" and "default vario". These are generic transmissions. "default normal" has 4 gears and 4 automatic power shift stages. The "default vario" very similar like a Fendt Vario with two ranges. Other vehicles only have a "default" options. Trucks have 6 gears in 2 ranges, wheel loaders a torque converter, 3 gears (power shift) and 2 ranges, all other vehicles have a hydrostatic transmission.

The transmissions between the first "build-in" and the "default" transmissions are configured inside the gearbox addon. Typically, there is only one entry with text "gearbox addon".

BR

**Comment by doc3d** [comment]
Ok thank you, that clears it up a bit.
So with the newer versions there is no way to switch to default without going into the workshop?

**Comment by olliebob** [comment]
I'm loving what Uve done mogli👍 It's working great and the choice of gearbox is fantastic

**Comment by olliebob** [comment]
I've just updated to the latest from the last .6 from a few days ago, I've noticed not that u can turn it off with key_rctrl-key_; what's the point of this? Seeing u can turn it on and off even though u have purchased?

**Comment by reallogger** [comment]
Think this is a great enhancement to an already great mod. 

If I understand it correctly the "standard" gearbox for mods, is the gearbox config specified in the vehicle.xml. "gearbox addon" is on the other hand a gearbox specified in the config file of Gearbox mod. Can you confirm if my understanding is correct?

**Comment by Mogli12** [comment]
I changed the texts recently. Is it now easier to understand?
