### ISSUE TITLE
either switch gears or drive

### ISSUE THREAD

**Issue by SchorschiBW** [Mogli12/GearboxAddon#21]
I have the Thrustmaster T500RS with the corresponding shifter. I can switch the gears, but i can't drive. If i switch to the easy mode, i can drive, but i can't switch the gears.

**Comment by Mogli12** [comment]
Can you please add a screen shot of the gearbox hud when not in easy mode?

**Comment by SchorschiBW** [comment]
Has done, it was the tractor. Obviously there was something incorrectly installed. Two other tractors are working properly

I am sorry for the error message

**Comment by Mogli12** [comment]
Hi, which tractors caused the problem? Are they oubluc mods? If yes please send me the link. Thanks

**Comment by SchorschiBW** [comment]
No, it's a not a public mod.

**Comment by Mogli12** [comment]
I close this isses, ok?

**Comment by SchorschiBW** [comment]
do it;-)
