### ISSUE TITLE
Periodically unable to move

### ISSUE THREAD

**Issue by doc3d** [Mogli12/GearboxAddon#210]
I also have an issue where I sometimes (no clear pattern here, some times it works, some times it doesn't) where I seem to be stuck or unable to move. If I floor the accelerator I can sometimes get going, but it's like I'm stuck in gum, and other times I get no movement at all. If I then switch to reverse, it works normally, as does going back into forward after that. Very strange, and I can't figure out why

**Comment by Mogli12** [comment]
Tractor, GB version, log.txt? Maybe a screen shot?

**Comment by doc3d** [comment]
GB v2.1.6.6
Tractor: John Deer 77810 (FS17JD7710_7810v2.zip)
![fsscreen_2017_08_15_20_12_13](https://user-images.githubusercontent.com/20613871/29329773-41512c8e-81f7-11e7-9896-349735a961fa.png)
This screenshot is from I just started moving again. 

I had my accellerator floored for 10-15 seconds with no movement, then when I got set up to do the screenshot, it started moving just as I took the shot (thats why its moving 3km/h in the shot)

I did get this line in my log just before taking the screenshot:
"WARNING: undefined input in gearboxMogli: " -thats it, no text after the colon

**Comment by Mogli12** [comment]
Hi,
This problem was already reported in #205 in German. It is fixed wit Version 2.1.6.7.
Best regards!

**Comment by doc3d** [comment]
ah, ok. Thank you
