### ISSUE TITLE
Feedback about new Settings UI

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/GearboxAddon#211]
Hello,

There is a new settings UI. You can open it with the combination "KEY_rctrl KEY_semicolon" (RCtrl-Ö). This is still work in progress and several texts are not yet final or translatable. 

I think I would like to keep it on one page with three columns. Dependencies between settings are quite difficult and I would like to avoid this if possible.

Please share your feedback about the new UI. Do you have further ideas?

Thanks,
Mogli

**Comment by ivanlii** [comment]
Hi Stefan, nice addition, all seems ok for now.
What is SWAP?
A new page with a imputBindings list will be nice... they are so many and is hard to keep TABing out of the game to search for them.
How about different GB configurations (for same or other motor)?

**Comment by Mogli12** [comment]
> How about different GB configurations (for same or other motor)?

The different gearbox configurations are part of the vehicle shop configuration. It would be too difficult to change the gearbox in a running tractor. It caused already some trouble the change between build-in transmission and gearbox addon.

**Comment by ivanlii** [comment]
If globals are possible in new UI will be nice to have defaultEnableAI, drawTargetRpm, drawReqPower, settings that don`t have keybindings in general.
And of  course settings save.
Regards

**Comment by Mogli12** [comment]
>...o have defaultEnableAI, drawTargetRpm, drawReqPower, settings ...

Good idea! Thanks!

**Comment by Anonymous-any** [comment]
Hi thank for informations for me I think there is not so far of perfection but there lots of options and configurable tweak then I have nothing to add, thank you Maestro for you work irreplaceable :)
Br

**Comment by olliebob** [comment]
I'm getting the same warnings when I use the quadtrac and default manual gearbox set to simple?

**Comment by BlaggyXD** [comment]
Servus,
mir ist dem letzt auf gefallen das die "Vor-/Rückwärts-Tasten" (so wie das Allrad/Diff.) nach einem neustart nicht gespeichert werden so das man jedes mal neu fest legen muss wie man die Richtung wechseln möchte. Ist das so gewollt oder ist das ein "Fehler" ?

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

> mir ist dem letzt auf gefallen das die "Vor-/Rückwärts-Tasten" (so wie das Allrad/Diff.) nach einem neustart nicht gespeichert werden so das man jedes mal neu fest legen muss wie man die Richtung wechseln möchte. Ist das so gewollt oder ist das ein "Fehler" ?

Das ist ein Fehler.

Viele Grüße

**Comment by Gonimy-Vetrom** [comment]
Now the settings look great. 
But. There are not enough tips for each item. Abbreviations are not always clear. When I was engaged in the translation of the text, I had to read a lot to understand the purpose of the settings.

**Comment by Mogli12** [comment]
Good point!

**Comment by Gonimy-Vetrom** [comment]
Tips already working? I can not see them. I translated it for a long time, but I can not check it out in games.

**Comment by Mogli12** [comment]
No, I am not sure what is wrong with the tool tips.

**Comment by KITT3000** [comment]
As for the **tips**, I found something like this in the original script:
>function InGameMenu:onLeaveSettingsBox(element)
    self:setHelpBoxText("")
end

>function InGameMenu:onFocusSettingsBox(element)
    if element.toolTip ~= nil then
        self:setHelpBoxText(element.toolTip)
    end
end

And such attributes are added to each **GuiElement**:
`<GuiElement ... onFocus="onFocusSettingsBox" onLeave="onLeaveSettingsBox" ... >`

**Comment by Mogli12** [comment]
@KITT3000 Many thanks. This is a good hint. But there is still some work to do

**Comment by Mogli12** [comment]
Hi,
ToolTips work with v3.1 build 3. It will not make it into version 3 anymore, which is since more than 2 weeks for testing at ModHub. Additionally, I disabled all buttons that are not applicable.
Regards, Stefan

P.S.: Check the description of the mod
