### ISSUE TITLE
Tempomat + Kupplung

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#214]
Hi Stefan,

Problem: Kupplung überhitzt bei Feldarbeiten mit Tempomat.

Beschreibung: Die Kupplung schließt nicht komplett wenn der Tempomat angeschaltet wird. Daher "schleift" sie und Überhitzt. Geb ich manuell Gas, schließt sie zu 100%. Schalte ich den Tempomat ein schließt sie, seinbar zufällig zwischen 50-95%. Folge ist, dass die Kupplung früher oder später Überhitzt.

Schritte: Traktor mit Schalt- oder Lastschaltgetriebe und z.B. ein Grubber ankoppeln (es ist egal ob der Traktor "zu stark" oder "zu schwach" ist). Übers Feld fahren. Tempomat einschalten (Egal ob max oder 10 Km/h). ->Kupplung schließt nicht richtig<-. Folge: Überhitzung. -> Manuell Gas geben. Kupplung schließt wieder.
Das Schließen der Kupplung kann man durch schnelles Antippen der "Kupplung" Taste erhöhen, wenn man im Tempomat drin ist. Meistens aber nur zu 95% (immerhin besser als 50%)

[Log](https://gist.github.com/Fracking/b6769e27248d73f34e8cef693d8e0583)

Beste Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Andreas,

ich habe es gerade probiert und kann das Problem nicht nachvollziehen. Bei welchen Fahrzeugen und Geräten tritt es konkret auf. Welcher Gang wurde verwendet? Welche Geschwindigkeit war im Tempomat eingestellt? Am besten wäre ein Screenshot.

Viele Grüße,
Stefan

**Comment by Fracking** [comment]
![2017 08 23-15 59](https://user-images.githubusercontent.com/28556963/29619885-8d035974-881c-11e7-8241-d7870836c4e8.png)

Starken Traktor und leichtes Gerät. Tempomat rein und etwas fahren.

**Comment by Mogli12** [comment]
Hallo Andreas,

ich habe das Problem nicht. Hast Du ein Lenkrad oder Joystick angeschlossen? Mir scheint, dass die Kupplung erstmal über die Achse gesteuert wird. Drücken man dann die "."-Taste, dann übernimmt diese Logik und die Kupplung schließt.

Viele Grüße,
Stefan

**Comment by Fracking** [comment]
Hi,

das Problem hat sich geklärt. "Kupplung öffnen" und "Kupplung schießen" waren auf den xbox Controller belegt. Hab die entfernt. Jetzt läuft es.

Danke

Andreas
