### ISSUE TITLE
Beim Ausblenden des HUD's steht der aktuelle Gang mitten im im unteren HUD

### ISSUE THREAD

**Issue by D3ltorohd** [Mogli12/GearboxAddon#215]
Hallo,
mir ist was aufgefallen. Wenn ich das HUD mit - ausblende sieht man ja immer noch den aktuellen Gang, dieser steht aber in mitten der aktuellen Geschwindigkeit im unteren HUD in mitten der Drehzahlanzeige.

Vllt könntest du da noch mal drüber schauen.

**Comment by Mogli12** [comment]
Das ist Absicht

**Comment by Mogli12** [comment]
Please check v3.1 build 5
