### ISSUE TITLE
Game friert ein

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/GearboxAddon#216]
Hi Stefan hab das kleine Problem das Spiel einfriert und folgender Fehler kommt
nil true nil
Error 3: C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua:5684: attempt to index a nil value
FS17_GearboxAddon: Error! gearRatio is too big: 1000000000
------------------------------------------------------------------------
2: C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/mogliBase.lua (615): printCallStack
3: C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua (7901): getGearRatio
4: C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua (7269): updateWheelsPhysics
5: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (894): oldFunc
6: C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/ZZZ_driveControl/driveControl.lua (1306): updateVehiclePhysics
7: [string "dataS/scripts/vehicles/specializations/Drivable.lua"] (494): update
8: [string "dataS/scripts/vehicles/Vehicle.lua"] (2598): update
9: [string "dataS/scripts/network/Server.lua"] (56): update
10: [string "dataS/scripts/BaseMission.lua"] (1508): update
...
------------------------------------------------------------------------
dataS2/character/pedestrians/woman02.i3d (53.96) ms

**Comment by Mogli12** [comment]
Das tritt bei welcher Version auf?

**Comment by Paul2510** [comment]
1.1 B08

**Comment by Mogli12** [comment]
Was soll ich jetzt mit einer Fehlermeldung aus einer so alten Version machen? Nimm doch einfach die aktuelle Version.
