### ISSUE TITLE
Slipping with CoursePlay

### ISSUE THREAD

**Issue by alpha117** [Mogli12/GearboxAddon#218]
Good Morning

Just started using GB and have an issue with tractors slipping when using CoursePlay, as the 4wd/diff locks are not engaged.  Not sure how to fix this

Any help would be good

Thanks
Clive

**Comment by alpha117** [comment]
thanks  let you know

**Comment by alpha117** [comment]
OK, looks like the slipping is a Seasons issue, wet ground no traction, that is good and GB reflects that.
All good
Now, when in courseplay I only get AI(M) and unless I baby sit a change gear for them, the Cp will not get up any change in gradient, which defeats the objective of CP.

Have I missed something, to allow GB to go into Auto, when starting CP?

I'm liking GB a lot, just need to understand the different functions and how they work, hopefully this issue is a 'user' issue and not GB

Thanks

**Comment by Mogli12** [comment]
You can either set the gearbox into simplified mode before starting courseplay or you go to the settings screen and choose "simple" for the "hired worker" setting.

**Comment by alpha117** [comment]
Cool, thank

**Comment by alpha117** [comment]
just finished seeding on the west coast, very good indeed. Like it a lot

If you want any testing then let me know

cheers

**Comment by alpha117** [comment]
v.76, selected 'simple for AI, then started CP  got AI(M) B4, stayed in that gear.

Sowing  TWC field #15

**Comment by alpha117** [comment]
Good Morning

More questions!

1. GearBox: Reality Switch
2. GearBox: Limiter
3. GearBox: Fixed ratio

What do the different options of the above achieve

Also you can change from Automatic/manual via the GB options screen, how can you do this without going to the options screen?

Thanks

**Comment by Mogli12** [comment]
ad 1: here you can control what is shifted automatically if you are in simplified mode
ad 2: this enables the speed limiter. You have to use the normal keys to accelerate and brake. But you cannot drive faster than the cruise control speed
ad 3: this is for CVTs only (e.g. Fendt Vario). You can choose a fixed gear ratio

**Comment by alpha117** [comment]
Thanks Stefan

All good

**Comment by alpha117** [comment]
We do I find/see the changelog for each version?

**Comment by Mogli12** [comment]
code->commits

**Comment by alpha117** [comment]
using V2177 hired worker :CVT  with courseplay, spot on, good one.

Now see there is 2178, you are very quick.
Need to see what happens when GB is manual and Hired worker is CVT, should change when in CP and then go back to manual when out of CP?

**Comment by Mogli12** [comment]
Hi alpha117,
What is the status of this issue?
Regards,

**Comment by alpha117** [comment]
Hi 

Yep, seems OK now

Thanks
