### ISSUE TITLE
Bei G27 kein Rückwärtsgang

### ISSUE THREAD

**Issue by Hagy0815** [Mogli12/GearboxAddon#22]
Hallo,

folgendes Problem:

wenn man dem Traktor den Rückwärtsgang in Gruppen legt und nicht als einzelner Gang,
steht immer im Hud folgendes: Kein Gang (R) G27.
Schaltet man aber mit der Tastatur kann man ohne Probleme Rückwärtsfahren.
Ich habe einen Screenshot von dem Problem gemacht:

http://abload.de/image.php?img=fsscreen_2016_02_28_1e2sft.png

Habe es mit mehreren Traktoren und. Habe jetzt mal den Originalen Hürlimann genommen mit der in der Gearbox angegebenen Parameter um zu zeigen, dass es nicht nur an Mods liegt.

Legt man aber nur einen Gang als Rückwarts an, geht alles ohne Probleme:

http://abload.de/image.php?img=fsscreen_2016_02_28_19jsqd.png

Problem mit dem Schalten ist wie gesagt nur mit dem Lenkrad.

**Comment by Mogli12** [comment]
Auf Wunsch von einigen Usern schaltet beim G27 der Rückwärtsgang vom G27 nur dann den Rückwärtsgang, wenn dieser auch zu den Gängen gehört. Wendeschaltungen oder Rückwärts in der Gruppe wird über eine andere Tastenbelegung geschaltet. 
Du muss also einen Gang einlegen und kannst dann mit Leertaste (mrGearboxMogliREVERSE) die Fahrtrichtung ändern. Zusätzlich gibt es noch zwei Inputs, die noch nicht belegt sind: mrGearboxMogliGEARFWD und mrGearboxMogliGEARBACK für Vorwärts und Rückwärts.

**Comment by Mogli12** [comment]
-> #17
