### ISSUE TITLE
Tempomat warning

### ISSUE THREAD

**Issue by Fendtfan84** [Mogli12/GearboxAddon#220]
Servus Mogli,
ich habe folgende Fehler Meldung in meiner LOG:
WARNING: undefined input in tempomatMogli: gearboxMogliCONFLICT_1
Das ist der link von meiner log:
https://gist.github.com/Fendtfan84/bd10469d2cb306a0c7dab51baaeb38be

Ich spiele mit dem aktuellen MR Mod auf der OldStreamsV2.

Ich hoffe dieses Problem lässt sich leicht beheben.

schöne Grüße aus Südhessen
Fendt Fan

**Comment by Mogli12** [comment]
Hallo,
die Warnung sollte mit 2.1.7.9 verschwunden sein.
Viele Grüße,
Stefan
