### ISSUE TITLE
Question: Config Optionen im Multiplayer

### ISSUE THREAD

**Issue by debejerry** [Mogli12/GearboxAddon#221]
Hallo Stefan,

**zu allererst ein riesen Dankeschön an dich!!
Für das GearBoxAddon und die viele Zeit die du in dieses Projekt investierst.**

So nun aber: ich habe eine Frage zum Multiplayer, dazu muss ich erstmal etwas weiter ausholen.

Wir spielen mit mehreren Leuten auf einem Dedi Server, jetzt auch mit GearBox Addon (Juhu, endlich).

Es kommt durchaus öfter vor, dass man mal das Fahrzeug eines Kollegen fährt.

Nun mag nicht unbedingt jeder der Mitspieler mit dem GearBox Addon fahren.

In den neueren Versionen muss das Getriebe ja beim Fahrzeug Kauf als Option konfguriert werden.
Gerade denjenigen die ohne GearBox fahren möchten ist natürlich nicht unbedingt klar was mit welcher Option gemeint ist.
   
Ja es gibt die Möglichkeit das GearBox Addon bzw. das realstische Getriebe per "Umsch+Ö" zu deaktivieren, wenn es als Option konfiguriert ist.
Derjenige der aber "nie" mit GearBox Addon spielen möchte ist davon, sagen wir mal, leicht genervt, 
weil sowas musste er ja vorher auch nie deaktiveren.

Damit aber diejenigen die mit GearBox Addon fahren möchten, das auch tun können, müssen die Fahrzeuge entweder alle mit der GearBox Addon Option gekauft werden (und dann muss manuell deaktiviert werden s.o.), oder jedesmal "umständlich" umkonfiguriert werden. 
Wobei sich dann der eigentliche "Besitzer" freut wenn man die Getriebe Konfiguration nicht wieder auf den Ursprungszustand zurück gedreht hat.

Um hier für alle Seiten (gearbox vs non-gearbox player) ein "friedliches Miteinander" zu finden kommt jetzt meine eigentliche Frage; 

Könntest du dir eine Möglichkeit vorstellen (z.B. über die gearBoxAddonConfig.xml im mod Ordner der einzelnen Spieler) eine Möglichkeit zu schaffen, mit der jeder für sich festlegen kann mit welcher Standard Einstellung (GearBox Addon Ja oder Nein, wenn ja ggf. noch ob realstisch oder Vario?) er spielen möchte?

Beispiel:

```
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<gearboxMogliGlobals>

	<userDefaultGearbox active="true" gearBoxOption="geaboxaddon" /> 	
	Mögliche Werte für 'gearBoxOption'   darüber pro user steuern welches Getriebe beim einsteigen in das Fahrzeug gewählt wird.
							"gearboxaddon"
							"default_vario"
							"default_standard"
							
	<defaultGearBoxBuyOption value="gearboxaddon"  />				
	Mögliche Werte für 'value' darüber könnte eine Vorbelegung für den Shop definiert werden
							"gearboxaddon"
							"default_vario"
							"default_standard"
							"off"
</gearboxMogliGlobals>
<vehicles>

	<vehicle>newHolland8340
		...
		...
		<gearboxMogli ..
			<gears ...
			</gears>
			<ranges ...
			</ranges>
		</gearboxMogli>
	</vehicle>
</vehicles>

```

Ich hoffe ich habe unsere (Luxus-) Probleme verständlich darstellen können und freue mich auf deine Reaktion.

Viele Grüße
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,

leider kann ich das Getriebe nicht abhängig vom Client wählen. Die einzige Möglichkeit ist derzeit  "Umsch+Ö".

Viele Grüße,
Stefan

**Comment by debejerry** [comment]
Hallo Stefan,

Danke für die Antwort.
Evtl. habe ich es unglücklich formuliert, deshalb ein zweiter Versuch.

Es geht mir dabei quasi eher um eine Möglichkeit "Umsch-Ö" zu "automatisieren".
Deshalb die Idee einen Wert in der config zu setzen der aussagt ob das GB Addon für diesen Spieler aktiviert sein soll oder eben nicht. (immer vorrausgesetzt das Fahrzeug wurd mit GB Addon Konfiguration gekauft).

Damit würde das GB Addon nicht generell (wie in den Kauf Optionen) deaktiviert, sondern nur wie per "Umsch-Ö" aktiv/inaktiv geschaltet (wenn der Motor aus ist)

Vielleicht schreib ich auch grad Quatsch, und du hattest das grad schon genauso verstanden, aber wer nicht wagt... ;=))

Gruß
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,

zum Speichern möchte ich es erstmal nicht machen. Ich habe in der Vergangenheit mal darüber nachgedacht, dass die Tasten "Umsch-Ö" und "Umsch--" sich nur auf den aktuellen Client aber auch alle Fahrzeuge auswirken. Ich habe das mal so umgebaut.

Das GB Addon 

Viele Grüße,
Stefan

**Comment by debejerry** [comment]
Hallo Stefan,

das hört sich schonmal super an und ich kann mir sehr gut vorstellen, dass das in meinem Team ebefalls auf Gegenliebe stößt ;=))

Danke für den schnellen Support, testen werde ichs aber erst heute am (späten) abend können, und werde dann nochmal feedback geben.

Gruß
Stefan

**Comment by debejerry** [comment]
Hallo Stefan,

im SP player sieht mir das soweit alles super aus -> works as designed
im MP kann ich allerdings die Gearbox Konfiguration nicht mehr auswählen (wie in #217 ) ist das so gewollt?

Gruß
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,

nein, das ist so nicht gewollt. Aber das Anpassen der Shop-Daten ist im MP nicht so einfach.

In #217 warte ich noch auf die Logs mit der aktuellen GB Version. Kannst Du mir diese Logs von Server und Client schicken?

Vielen Dank, 
Stefan

**Comment by debejerry** [comment]
Hallo Stefan,

ich habe hier einmal die logs vom server und vom client mit der Version 2.1.8.0.

[Client log](https://gist.github.com/debejerry/142a086414ed8679ff9c33e5adf58e0d)

[Server log](https://gist.github.com/debejerry/142a086414ed8679ff9c33e5adf58e0d)

**Comment by debejerry** [comment]
Hallo Stefan,

hier einmal 
[Client Log](https://gist.github.com/debejerry/9ec47c2627f58f011f45fdfab3ea589e)   und  [ Server Log](https://gist.github.com/debejerry/142a086414ed8679ff9c33e5adf58e0d)

Was ich noch beobachten konnte.
Ich habe im mods Ordner eine funktionierende gearboxAddonConfig.xml liegen, die eine Getriebe Konfiguration für den "kleinen" MB Trac enthält.
Im SP wird diese Konfiguration geladen und ich habe das konfigurierte manuelle Schaltgetriebe zur Verfügung.
Im MP(Dedi Server) wird für den MB Trac das default Getriebe (4 Gänge und 4 LS Stufen) geladen.
Die im GearBoxAddon für die Standard Fahrzeuge hinterlegten Getriebe funktionieren im MP (z.B. Case 1455/Lizard Pickup).

Ich hoffe das hilft erstmal weiter.

Viele Grüße
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,

mit 2.1.8.2 sollte das Problem hoffentlich gelöst sein.

Vielen Dank,
Stefan

**Comment by debejerry** [comment]
Hallo Stefam,

leider nein.
Die Konfiguration aus der gearboxAddonConfig.xml wird für den kleinen MB Trac noch nicht geladen.
Auszug aus der Client log:

```
Joined network game (18)
data/vehicles/trailers/metaltech/db8000.i3d (139.36) ms
data/vehicles/tools/salford/salford4204.i3d (87.74) ms
data/vehicles/tools/stoll/stollToolPalletFork.i3d (71.71) ms
data/vehicles/trailers/poettinger/poettingerEuroboss330T.i3d (209.59) ms
data/vehicles/tools/kverneland/kvernelandQualidisc3m.i3d (87.64) ms
data/vehicles/tools/kverneland/kvernelandExactaEL.i3d (89.91) ms
data/vehicles/tools/kverneland/kvernelandAccordDL.i3d (91.41) ms
data/vehicles/steerable/caseIH/caseIH1660.i3d (236.50) ms
Warning: GearboxAddonConfigurations are not present in 'data/vehicles/steerable/caseIH/caseIH1660.xml' anymore! Ignoring this configuration.
C:/Users/admin/Documents/My Games/FarmingSimulator2017/mods/FS17_AIVehicleExtension/AutoCombine.i3d (0.15) ms
loading C:/Users/admin/Documents/My Games/FarmingSimulator2017//driveControl_config.xml for driveControl-Mod configuration
driveControl module shuttle started
driveControl module fourWDandDifferentials started
driveControl module cruiseControl started
driveControl module showNearestFillLevel started
driveControl module pipeCam started
driveControl module implementControl started
driveControl module softGas not started
driveControl module showMotor started
driveControl module variGear started
driveControl module freeSteering not started
driveControl module inching started
driveControl smoothAlpha set to 7%
driveControl motor autoTurnOff set to false
GPS mod inserted into Drivable Specialization (should happen only once!)
GPS mod inserted into Vehicle Camera (should happen only once!)
data/vehicles/cutters/caseIH/caseIH1030Cutter.i3d (175.37) ms
data/vehicles/steerable/fendt/fendt300.i3d (272.76) ms
Warning: GearboxAddonConfigurations are not present in 'data/vehicles/steerable/fendt/fendt300.xml' anymore! Ignoring this configuration.
data/vehicles/tools/agco/agco650.i3d (206.09) ms
data/vehicles/tools/poettinger/poettingerNovaCat301.i3d (94.94) ms
data/vehicles/steerable/masseyFerguson/MF5600.i3d (213.43) ms
Warning: GearboxAddonConfigurations are not present in 'data/vehicles/steerable/masseyFerguson/MF5600.xml' anymore! Ignoring this configuration.
data/vehicles/tools/stoll/stollFrontLoaderFZ.i3d (15.47) ms
data/placeables/highPressureWasher/kaercher/kaercherHDS918-4M.i3d (69.19) ms
dataS2/character/player/player01.i3d (433.24) ms
gearboxMogli: client is requesting configuration items from server
gearboxMogli: received configurations for 92 vehicles
data/objects/bigBagContainer/bigBagContainerFertilizer.i3d (67.87) ms
Error reading network ID: 143 (gearboxMogli)
C:/Users/admin/Documents/My Games/FarmingSimulator2017/mods/FBM17_MBtracKlein/i3d/MBtracKlein.i3d (751.61) ms
Warning: GearboxAddonConfigurations are not present in 'C:/Users/admin/Documents/My Games/FarmingSimulator2017/mods/FBM17_MBtracKlein/xml/MBTracKlein.xml' anymore! Ignoring this configuration.
WARNING: undefined input in gearboxMogli: 
```

Auszug aus der server log:
```
Stefan(Jerry) joined the game
gearboxMogli: received configuration request
gearboxMogli: Sending 92 configuration items to the client
C:/gameservers/s1240431/ls2017/gameProfile/mods/FBM17_MBtracKlein/i3d/MBtracKlein.i3d (554.70) ms
```

Gruß
Stefan

**Comment by debejerry** [comment]
Eine kurze Ergänzung:
Standard Fahrzeuge sehen gut aus, die Option ist da und kann ausgewählt werden.
Es werden auf den ersten Blick keine Fehler geworfen.

Bei Mods (hab hier z.Zt. nur den kleinen MB Trac zum testen) wird die Auswahl nicht angezeigt.

Eine Frage noch zur gearboxAddonConfig.xml. Bzw allgemein zur GearBox Konfiguration für Mods im MP.

im Moment habe ich für den MBtrac nur in meiner gearboxAddonConfig.xml in meinem mods Ordner auf dem Client eine gearbox Konfiguration hinterlegt.

Im SP funktioniert das so. müsste die gearboxAddonConfig.xml für den MP auf den Server geladen werden (Problem kein FTP Zugriff auf den Gameserver also können nur ZIP mod files hocgeladen werden)

**Comment by Mogli12** [comment]
Hallo,
die gearboxAddonConfig.xml müsste auf dem Server geladen werden. Ich überlege mal, ob man das irgendwie auch mit einer ZIP-Datei machen könnte.
Viele Grüße

**Comment by Mogli12** [comment]
So, mit Version 2.1.8.3 kannst Du jetzt Deine Konfigurationen in der ZIP-Datei gearboxAddonConfig.zip in der Datei gearboxAddonConfig.xml speichern.

**Comment by debejerry** [comment]
Hallo Stefan,

zum testen der 2.1.8.3 im MP bin ich leider noch nicht gekommen.

Aber mit der  2.1.8.2 waren wir gestern noch auf dem Dedi Server unterwegs.
Wenn mich mein Gedächtnis nicht vollständig im Stich lässt wurde die Option "Getriebe" im Shop nicht angezeigt und alle Fahrzeuge wurden automatisch mit "gearBoxAddon" gekauft.

Was weiterhin in den logs auftaucht sind Einträge à la 

> Error reading network ID: 143 (gearboxMogli)

Die Stabilität des Spiels  scheint das aber nach erster Einschätzung nicht zu beeinflussen.

Ein Kuriosum hätte ich noch:
Der "Gruß vom Getriebe" scheint immer für **alle** Mitspieler hörbar, egal wie weit sie weg sind, und egal wer sich verschaltet hat. (evtl soll ich dazu einen neues Issue aufmachen?)

Danke und Gruß
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,

die Meldung

> Error reading network ID: 143 (gearboxMogli)

macht mir doch etwas Sorgen. Tritt sie mit 2.1.8.4 immer noch auf?

Vielen Dank,
Stefan

**Comment by debejerry** [comment]
Hallo Stefan,

leider ja nur mit einer anderen ID:
Server Log:

> Stefan(Jerry) joined the game
> gearboxMogli: received configuration request
> gearboxMogli: Sending 93 (308) configuration items to the client
> C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_IHC_744/IHC_744.i3d (191.65) ms

Client Log:

> data/vehicles/trailers/farmtech/farmtechTDK1600.i3d (67.41) ms
> dataS2/character/player/player01.i3d (358.52) ms
> gearboxMogli: client is requesting configuration items from server
> gearboxMogli: received configurations for 93 vehicles
> Error reading network ID: 464 (gearboxMogli)
> C:/Users/admin/Documents/My Games/FarmingSimulator2017/mods/FS17_IHC_744/IHC_744.i3d (255.09) ms

Die Gearbox Konfiguration kann bei Standard Fahrzeugen ausgewählt werden, bei MOD Fahrzeugen nicht.

Gruß
Stefan

**Comment by debejerry** [comment]
Nochmal Nachschub vom Server log, das passende client log hab ich grad nicht lässt sich aber evtl auch noch organisieren...

```
gearboxMogli: received configuration request
gearboxMogli: Sending 93 (308) configuration items to the client
C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_IHC_744/IHC_744.i3d (190.69) ms
C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_SuitCaseWeights/Suitcase_weights.i3d (18.45) ms
C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_Hankmo90/Hankmo90.i3d (127.96) ms
C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_Hassia_FS/hassiaFS.i3d (18.17) ms
Error sending network ID: nil (gearboxMogli)
------------------------------------------------------------------------
2: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (960): writeStream
3: [string "dataS/scripts/network/Connection.lua"] (88): sendEvent
4: [string "dataS/scripts/network/Server.lua"] (508): broadcastEvent
5: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (494): mrGbMSetState
6: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6235): mrGbMDoGearShift
7: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (4851): 
8: [C] (-1): pcall
9: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogliLoader.lua (47): loadFromAttributesAndNodes
10: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (280): 
------------------------------------------------------------------------
Error sending network ID: nil (gearboxMogli)
------------------------------------------------------------------------
2: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (960): writeStream
3: [string "dataS/scripts/network/Connection.lua"] (88): sendEvent
4: [string "dataS/scripts/network/Server.lua"] (508): broadcastEvent
5: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (494): mrGbMSetState
6: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6235): mrGbMDoGearShift
7: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (4851): 
8: [C] (-1): pcall
9: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogliLoader.lua (47): loadFromAttributesAndNodes
10: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (280): 
------------------------------------------------------------------------
Error sending network ID: nil (gearboxMogli)
------------------------------------------------------------------------
2: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (960): writeStream
3: [string "dataS/scripts/network/Connection.lua"] (88): sendEvent
4: [string "dataS/scripts/network/Server.lua"] (508): broadcastEvent
5: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (494): mrGbMSetState
6: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6308): setAutoMinMaxGearSpeed
7: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6237): mrGbMDoGearShift
8: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (4851): 
9: [C] (-1): pcall
10: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogliLoader.lua (47): loadFromAttributesAndNodes
...
------------------------------------------------------------------------
Error sending network ID: nil (gearboxMogli)
------------------------------------------------------------------------
2: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (960): writeStream
3: [string "dataS/scripts/network/Connection.lua"] (88): sendEvent
4: [string "dataS/scripts/network/Server.lua"] (508): broadcastEvent
5: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/mogliBase.lua (494): mrGbMSetState
6: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6308): setAutoMinMaxGearSpeed
7: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (6237): mrGbMDoGearShift
8: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogli.lua (4851): 
9: [C] (-1): pcall
10: C:/gameservers/s1240431/ls2017/gameProfile/mods/FS17_GearboxAddon/gearboxMogliLoader.lua (47): loadFromAttributesAndNodes
```

**Comment by Mogli12** [comment]
Hallo Stefan,

wie hast Du die Konfiguration der Mod-Fahrzeuge denn auf dem Dedi-Server gespeichert?

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Probiere bitte mal 2.1.8.5. Vielen Dank!

**Comment by debejerry** [comment]
Hallo Stefan,

die 2.1.8.5 konnte ich mangels Zeit (und Zeitfenster aufm Dedi-Server) leider noch nicht testen... (seit die Stappenbach raus ist der Dedi quasi dauerbelegt) :roll_eyes: :smiley: 

Ich werde dann, wenn sich die Möglichkeit ergibt direkt die aktuellste Version testen.

> 
wie hast Du die Konfiguration der Mod-Fahrzeuge denn auf dem Dedi-Server gespeichert?
Bei den Mods die wir z.Zt. verwenden ist direkt in der vehicle.xml eine <gearboxMogli> Definition gespeichert (Beispiel Case IHC 744/844 von Kreters Islands) 
Damit funktioniert das Getriebe, die Auswahl im Shop ist aber nicht vorhanden.

Danke und Gruß
Stefan

**Comment by debejerry** [comment]
Hallo Stefan,

gerade getestet mit der 2.1.8.7 
Server log:
```
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/specializations/events/AnimatedVehicleStartEvent.lua(44) : attempt to index field 'object' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/specializations/events/AnimatedVehicleStartEvent.lua(44) : attempt to index field 'object' (a nil value)
gearboxMogli: received configuration request
gearboxMogli: Sending 98 (318) configuration items to the client
gearboxMogli: received configuration request
gearboxMogli: Sending 98 (318) configuration items to the client
```

Die Konfiguration des Getriebes ist als Option jetzt wieder im Shop vorhanden :+1: 

Gruß
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan,

ich denke nicht, dass die beiden AnimatedVehicleStartEvent-Meldungen vom Getriebe kommen. Wenn es jetzt auch auf dem Dedi-Server läuft, dann können wir dieses Issue zu machen, oder? Man kann es ja später auch wieder auf machen, falls doch noch ein Fehler auftritt.

Vielen Dank,
Stefan

**Comment by debejerry** [comment]
Mit Bezug auf die Shop Option können wir hier gerne zu machen.
Bei der oben geposteten Server log war ich voreilig und habe im Eifer des Gefechts nicht genau hingesehen, :innocent: 

Sollten im MP noch Fehler geworfen werden mache ich ein neues Issue auf.

Vielen Dank für deine Unterstützung!! :+1:
