### ISSUE TITLE
some power issues

### ISSUE THREAD

**Issue by miracleman51** [Mogli12/GearboxAddon#223]
Im finding recently that some of the machines are not working correctly with seeders.  For example the ford TM35 (with MR mod and GB mod) doesn't want to pull some of the drills, and the big bud 470 and the Terminator drill also doesn't work properly - like when you turn on the drill there is ~80% engine load.   It wasnt an issue a few revisions back (Im not exactly sure which one).  

Also I know its not now 'supported' however GB mod and combines does not seem to work.  when the combine is turned on, there is no power to 'drive' it.  as in the the thresher seems to be taking way too much power.

Otherwise having great fun with this fantastic mod!  Trucks especially are fun!

**Comment by miracleman51** [comment]
weirdly I now have another issue, the CVT or gearbox keeps resetting every time I change the hired worker.

**Comment by Mogli12** [comment]
Did you use "KEY_rshift KEY_semicolon" while hired worker was enabled? Please check the settings screen ("KEY_rctrl KEY_semicolon")

**Comment by miracleman51** [comment]
erm.. well I think so, but I don't think I had the problem before hand.  i.e. every time now it 'resets'  whereas before I could turn the GB on and off and it would remember it.  Now for example, I have to unhire the worker, switch the engine off, change the gb mode, turn engine back on and rehire worker.... unless Im doing something stoopiD!

**Comment by Mogli12** [comment]
I propose you turn on/off the GB via configuration and not via "KEY_rshift KEY_semicolon".

**Comment by miracleman51** [comment]
OK Thanks, and again, great mod!  highly realistic and really adds that level of variation and gives each machine a unique feel... rather than point and shoot with maybe the ability to pull a bigger a trailer.

**Comment by miracleman51** [comment]
hmm,  so when I turn on off the gb config, it acts globally, rather than machine specific, it seemed to be machine specific before (which was better IMO), but something has happened that has caused to to act globally.  for example, if I switch it off for the combine (as GB mod doesn't play well with the MR combines), it switches off for the other machines?  is there a setting to change this.  Ive tried a few options to no avail.

**Comment by Mogli12** [comment]
Yes, the turn on/off switch is now global if the machine is not operated by the hired worker. If you want to turn on/off the transmission per vehicle you can use the new shop configuration option.

**Comment by Mogli12** [comment]
Hi, Did you try it? BR
