### ISSUE TITLE
GearBoxAddonConfig.zip

### ISSUE THREAD

**Issue by alpha117** [Mogli12/GearboxAddon#224]
Morning all

Like this idea, but where do you get the xml's from to add to this?

Is it going to be the same idea as MR addon:

http://tlg-webservice.de/index.php

Thanks

Clive

**Comment by Mogli12** [comment]
If you use moreRealisticXmlDatabank you can add the gearbox config already to the adjusted vehicle XML. the gearboxAddonConfig.xml inside of gearboxAddonConfig.zip just replaces the former gearboxAddonConfig.xml directly in the mods folder.

**Comment by debejerry** [comment]
Hi, I have chime in here,

I've also did run tests with MR and MR databank enabled.
But I've never got the GearboxAddon (in the latest versions, can't say actualy for older versions) to take the gearbox configuration from the vehice xml files stored in mrDatabank.

If I tried it 've always got the default Gearbox 4 gears + 4 powershift

All tested in SP.

**Comment by alpha117** [comment]
Guys, I'm slightly confused now, what files do I need to move from where to where

Thanks

**Comment by Mogli12** [comment]
There 3 options to configure the transmission:
1. The GB has configurations built in for most of the built in vehicles plus several vehicles from modhub. Please do not change any file in FS17_GearboxAddon.zip. So you cannot change these configurations. Please look at 3 instead.
2. You can place a configuration in the vehicle.xml. If you are using moreRealisticXmlDatabank  togehter with moreRealistic the vehicle.xml is in moreRealisticXmlDatabank 
3. You can put your own configurations in an external gearboxAddonConfig.xml. Up to version 2.1.8.1 you had to place this xml file directly in the mods folder. But this does not work on dedi servers. So gearboxAddonConfig.zip is an alternative way. For SP the gearboxAddonConfig.xml direclty in the mods folder is easier.

**Comment by alpha117** [comment]
Got it, Thanks
