### ISSUE TITLE
Vehicles go at 8km/h

### ISSUE THREAD

**Issue by alpha117** [Mogli12/GearboxAddon#225]
Not sure what's changed, but start any vehicle, accelerate and then idle, vehicle will not stop not even going up a hill, will go back to 8km/h and stay at that until you brake and get auto(hold).

Remove GB MOD and all is fine.

**Comment by Mogli12** [comment]
This is standard. The vehicle starts with gear engaged.

**Comment by alpha117** [comment]
OK

**Comment by yumi-modding** [comment]
I think you might activated gearboxMogliKEEPSPEED by error and so you can see that cruiseControl remains active and automatically set to max speed you reach.
It occurred to me on 1 tractor and it took me a long time to understand and disable it by using key KEY_rctrl KEY_delete.

**Comment by alpha117** [comment]
Yep, it is that, but when I disable it comes back on automatically

**Comment by Mogli12** [comment]
I think you enabled gearboxMogliKEEPSPEEDTOGGLE ("KEY_rctrl KEY_delete"). This puts the tractor in some kind of joystick mode. I like it for modern tractors with CVT. But I would not use it for older vehicles w/o auto hold.

**Comment by alpha117** [comment]
How do you stop it automatically  coming 'on' when you have used ("KEY_rctrl KEY_delete") to turn it off?

**Comment by Mogli12** [comment]
I do not know. You provided way too little information about your problem. You just write that suddenly something strange happens. 

If the gearbox addon is too complicated it might be better if you play without.
