### ISSUE TITLE
config from FS15

### ISSUE THREAD

**Issue by Maogami** [Mogli12/GearboxAddon#228]
Hey, I have quick question. 
Do I have to change something in order to make it work in FS17 aswell?

		
		<gearboxMogli maxBackwardSpeed="52" maxForwardSpeed="52" clutchEngagingTimeMs="500">
      <hydrostatic profile="ZF"/>
      <gears automatic="true">
        <gear speed="6.36" name=""/> 
        <gear speed="12.72" name=""/> 
        <gear speed="25.45" name=""/> 
        <gear speed="50.89" name=""/> 
      </gears>
			
			
			
			
			<realEngine idleRpm="800" ratedRpm="1900">
        
        <torque rpm="350" motorTorque="863" fuelUsageRatio="299"/>
        <torque rpm="700" motorTorque="1772" fuelUsageRatio="216.7"/>
        <torque rpm="900" motorTorque="2254" fuelUsageRatio="192.2"/>
        <torque rpm="1000" motorTorque="2401" fuelUsageRatio="186"/>
        <torque rpm="1100" motorTorque="2450" fuelUsageRatio="184"/>
        <torque rpm="1200" motorTorque="2442" fuelUsageRatio="184.3"/>
        <torque rpm="1300" motorTorque="2419" fuelUsageRatio="185.3"/>
        <torque rpm="1400" motorTorque="2380" fuelUsageRatio="186.9"/>
        <torque rpm="1500" motorTorque="2325" fuelUsageRatio="189.1"/>
        <torque rpm="1600" motorTorque="2255" fuelUsageRatio="192"/>
        <torque rpm="1700" motorTorque="2169" fuelUsageRatio="195.5"/>
        <torque rpm="1800" motorTorque="2068" fuelUsageRatio="199.7"/>
        <torque rpm="1850" motorTorque="2002" fuelUsageRatio="202"/>
        <torque rpm="1900" motorTorque="1922" fuelUsageRatio="204.4"/>
        <torque rpm="1950" motorTorque="1796" fuelUsageRatio="208.1"/>
        <torque rpm="2000" motorTorque="1514" fuelUsageRatio="225.3"/>
        <torque rpm="2050" motorTorque="1110" fuelUsageRatio="262"/>
        <torque rpm="2100" motorTorque="598" fuelUsageRatio="322.7"/>
        <torque rpm="2150" motorTorque="0" fuelUsageRatio="408.9"/>
			</realEngine>			
		</gearboxMogli>

I have copied it from FS15 gearboxAddonConfig.xml

**Comment by Mogli12** [comment]
Hi,

It should work in FS17 as well. If you want you can replace "ZF" by "Input".

Regards, Stefan

**Comment by Maogami** [comment]
Thank you.
