### ISSUE TITLE
No Automatic or Simple mode

### ISSUE THREAD

**Issue by Ridlerr** [Mogli12/GearboxAddon#229]
In version 2.1.9.1 the automatic mode and the simple mode do not work, selecting the last ratio of the gearbox, the tractor works, seeming to be equipped with a CVT, has been verified in several of the original tractors of the giants, as the NH T8, NH T9, Case Quadtrack and some few more , the T8 for example before the default mode was automatic, now does not exist.

**Comment by Mogli12** [comment]
Hi,
What was the name of the transmission that you bought? The last option  ("off") is Giants standard CVT.
BR

**Comment by Ridlerr** [comment]
Gearbox Adon mogli, when i updated to 2.1.9.1 Automatic and simple modhad disapear, i'm gone try 2.1.9.2
