### ISSUE TITLE
Motor geht aus

### ISSUE THREAD

**Issue by Beuko** [Mogli12/GearboxAddon#23]
Moin
Wenn ich mit dem Anhänger getreide oder was auch immer abkippe geht der Motor aus und startet sofort wieder, hab tasten schon versucht umzulegen geht trotzdem nicht, log sagt gar nix dazu bzw ist sauber, verwende drive control sonst nur standards 
Gruß Beuko

**Comment by fdanapfel** [comment]
Hast du vielleicht auch noch den "Motordrehzahlerhöhung beim abkippen" mod von marhu.net installiert:
http://marhu.net/phpBB3/viewtopic.php?f=141&t=3850&start=10#p47387

**Comment by Beuko** [comment]
Ja das war es, danke 
Gruß Beuko

**Comment by Mogli12** [comment]
So, das Problem sollte in den aktuellen Versionen behoben sein.
