### ISSUE TITLE
V2.1.9.3  MOTOR OFF(R)

### ISSUE THREAD

**Issue by alpha117** [Mogli12/GearboxAddon#231]
Hi,

MOTOR OFF(R)  is all I get now in the HUD, it's like GB is not working, was OK this morning in 2191

Unless I'm missing something

Thanks

Clive

**Comment by Mogli12** [comment]
Hi,

I tested version 2.1.9.3 in SP and on Dedi. It is working fine. I even tried it together with moreRealistic 0.5.30. Do you really think that I upload a new version that is not working at all?

Please post the complete log.txt and a screen shot or close the issue.

Regards,
Stefan

**Comment by alpha117** [comment]
![image](https://user-images.githubusercontent.com/30005040/30774115-8557c5f4-a075-11e7-864b-6c78c60f9d70.png)
[log.zip](https://github.com/Mogli12/GearboxAddon/files/1326600/log.zip)

With engine stopped ALL keyboard keys work OK, start Engine and NO  keyboard keys work(the keys assigned to GB, that is)

I'm going back to the previous version to conform that everything is OK.

I will let you know.

Stefan, I'm only trying to help that is all, nothing else.

**Comment by alpha117** [comment]
OK, gone back to V2.1.9.0  and all is fine and works as normal

**Comment by Mogli12** [comment]
It should be fixed with 2.1.9.4. The previous test was always together with FS17_KeyboardSteer that's why I did not get this error before.

**Comment by alpha117** [comment]
That is what testing is all about, thanks for the quick fix

**Comment by alpha117** [comment]
2.1.9.4   no issues, works perfect

thanks
