### ISSUE TITLE
Vorschlag: Drehzahlbereich eingrenzen

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#233]
Hi Stefan,

ich hab zufällig bei den Valtra Traktoren gesehen, dass man einen Drehzahlbereich, also untere und obere Grenze, festlegen kann. Wäre das auch in GB denkbar?

[Beispiel ab 0:48](https://www.youtube.com/watch?v=gQ_NJRdw2zI)

Grüße

Andreas

**Comment by BlaggyXD** [comment]
Servus,
das gleiche geht auch bei der 80'er Serie von Steyr.
Da wird das Standgas über das Handgas fest gelegt da man diese Steyr über das Handgas abstellt und die Maximaldrehzahl wird über eine Schraube an der Einspritzpumpe eingestellt.
 
Rein Theoretisch kann man das auch an jedem anderem Bulldog über die Einspritzpumpe machen.

Ich hab schon öfters mal überlegt das gleiche vor zu schlagen also kann ich Fracking hier nur zustimmen

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo,

man kann den Bereich der Solldrehzahl in den Settings einstellen (Strg-Ö). Wenn man Unfug eingibt, dann gewinnt Max. gegenüber Min.

Grüße,
Stefan

**Comment by Fracking** [comment]
Hi Stefan,

schönes Einstellungsfenster. Ich hab min. Solldrehzahl auf 1060 U/min und max. Solldrehzahl auf 1790 U/min eingestellt, aber der Traktor dreht nicht im Leerlauf auf 1060 U/min. Die max. Solldrehzahl funktioniert. 
Funktioniert das anders als ich mir das vorstelle?

Grüße

Andreas

**Comment by Mogli12** [comment]
Hi Andreas,

im Stand geht der Traktor immer auf Leerlaufdrehzahl herunter. Klappt es bei mehr als 2 km/h?

Grüße,
Stefan

**Comment by Fracking** [comment]
Hi,

mit 2.2.0.0 funktioniert es auch im Stand.

Ich mach den Issue zu.

Andreas

**Comment by BlaggyXD** [comment]
Servus,

ich hab das gestern mal eben auf einem Dedi Server getestet , im stand geht es aber sobald man einen Gang drin hat (und fährt) dreht er hoch bis an die Maximaldrehzahl. 
Geht es da nur mir so oder hat noch jemand den gleichen Fehler ?

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

wenn Du es reproduzieren kannst, dann mache bitte mit ein paar mehr Details und eventuell einem ScreenShot ein neues Issue auf. Ich habe es manchmal auch im SP gehabt, konnte es aber nie reproduzieren.

Grüße,
Stefan

**Comment by BlaggyXD** [comment]
Servus Stefan,

Ich hab es eben noch mal im SP getestet , es tritt dauerhaft auf, ich mach die Tage mal eine Issue dafür auf.

> Wenn man 2-mal Umschalt-Ö drückt, dann sollte es aber weg sein.

Das Hilft leider auch nicht.

Grüße,
Blaggy
