### ISSUE TITLE
Standgas nicht mehr Aktiv

### ISSUE THREAD

**Issue by Martin1500** [Mogli12/GearboxAddon#236]
Hallo Stefan 
Ich nutze immer Standgas bei der Feldarbeit aber seid  der Version 2.2.0.0 Funktioniert es nicht richtig.
Ich kann auf 2300 rpm Standgas hoch drehen aber soweit ich mein Fuß vom Gas nehme bleib der Schlepper stehen. 
Ich hoffe  ich konnte dir helfen. 
MfG Martin

**Comment by Mogli12** [comment]
Hallo, 

kannst Du noch ein paar Details nennen? Welcher Schlepper, welches Gerät, mit oder ohne moreRealistic, mit Tastatur oder analogem Gaspedal? 

Danke, 
Stefan

**Comment by Martin1500** [comment]
Moin 
IHC 844  Fortschritt Saatbettkombi ohne mr

**Comment by Mogli12** [comment]
Hallo Martin,
ich habe es mal selber mit dem IHC 844 und der Kuhn Sitera 3000 Kombination probiert. Derzeit gibt der Traktor auch bei Handgas nur maximal 50% Gas. Mit gsVehicleDebugRendering habe ich gesehen, dass mindestens 70% Gaspedal notwendig gewesen wären. Das habe ich mit jetzt geändert, so dass er bei Handgas bis zu 100% Gas gibt um die Drehzahl zu halten. Wenn nur die Zapfwelle an ist ohne Handgas, dann bleibt es aber bei maximal 50% Gaspedal.
Viele Grüße,
Stefan

**Comment by Martin1500** [comment]
Hallo 
OK Vielen Dank Mach weiter so
MfG  Martin
