### ISSUE TITLE
<mrBoost />

### ISSUE THREAD

**Issue by Jurkkis** [Mogli12/GearboxAddon#239]
MoreRealistic has this option found in modern IRL tractors to boost power, depending if PTO is active or speed is over preset treshold. It seems to work with the Durals converted default machinery using GearboxAddon transmission (ie. I tested NH T6 and Valtra N), but I can't get it to work with my mod that I'm converting for MR. The boost works for my tractor when I disable GearboxAddon transmission (with keybind or through customization menu in shop) and default to MRgearbox. GearboxAddon for my mod is configured in the vehicle xml inside the mod tractors zip file.

Gearbox addon version  2.200
MR Version 0.5.30

**Comment by Mogli12** [comment]
Hi Jurkkis,

Gearbox addon does not support <mrBoost />. I propose to specify an extra torque curve to the gearbox addon. If you use multiple motorConfigurations you should place the gearboxMogli tag inside the motorConfiguration tag. Inside the engine tag there is motorTorque for the torque with boost and motorTorqueEco for the torque w/o boost.

BR

**Comment by Jurkkis** [comment]
Thank you for quick answer. In gearboxMogliMotor.lua starting at line 336 there is something related to this I guess. But does GearBoxAddon switch beetween the 2 torque curves automatically and/or does the <mrboost> tag have effect in the switching at all? I thought I would need to switch normal/ECO modes myself with keypress.

**Comment by Jurkkis** [comment]
I think I understand it now. GearBoxAddon has its own boost feature. Every tractor that has motorTorqueEco curve configured, will always be in eco mode if PTO=off or Speed<30km/h. And if PTO=on or Speed>30km/h it will switch to motorTorque curve. But isn't 30km/h bit high? maybe 15km/h would be closer where the boost comes on?

**Comment by Mogli12** [comment]
Yes, you are completely right. This is how boost is implemented in GB Addon. There is just one addition. You can specify the boostMinSpeed at the engine tag (the tage where you specify idleRpm and ratedRpm). The default is indeed 30 km/h. If you specify boostMinSpeed="15" you would change it to 15 km/h.

**Comment by Jurkkis** [comment]
Oh thats nice and will solve my problem I think. I'm converting a 1998-2000 Valtra Hitech 8950 for MoreRealistic and those tractors were the pioneers in boosting engine power from PTO load but did not feature boost from vehicle speed. So setting boostMinSpeed above say 50km/h for that tractor, it should not boost from speed. Now to test it out->. Thank you!
