### ISSUE TITLE
Problem mit Registrieren von Standard-Fahrzeugen

### ISSUE THREAD

**Issue by Patar95** [Mogli12/GearboxAddon#24]
Hallo "Mogli",

ich war die ganze Zeit mit der V1.2 sehr zufrieden. Als die V1.3 rauskam, wurde ich von dieser bitter enttäuscht. Alle Stufenlose Fahrzeuge und Hydrostaten benötigen sehr viel Drehzahl bis sie sich in Bewegung setzen, und wenn es dann los geht sind sie kaum noch aufzuhalten. Kein Dosierbares fahren mehr, in Kurven bleiben sie einfach stehen, ich weiß nicht ob das so normal ist...

Was ich allerdings sehr gut finde ist, dass es die "default"-Einstellung gibt. Die Forstmaschinen lassen sich mit dem default-Setup sehr schön steuern.

Deshalb wollte ich jetzt wieder auf die alte V1.2 umsteigen, aber das Default-Setup für die standard Forstmaschinen nutzen. Also die große V1.2 in den Modsordner, die zzzMrGearboxAddonConfig.xml von der V1.3 dazu geschmissen, das "default" kopiert und den Originalpfad vom Buffalo und Scorpion eingetragen.

Spiel laden, bringt er die Meldung, dass er keine Konfiguration für diese Fahrzeuge findet.

Also testweise NUR den Pfad vom piQup geändert auf die xml vom Buffalo, und er behauptet immernoch, dass er keine Konfiguration für den Buffalo finden kann.

Was ist denn da los? Leider kann ich deine Dokumentation mangels Microsoft Office nicht öffnen. Ich dachte PDF wäre das gängigere Dateiformat für Anleitungen ;)

Gruß Thomas (Patar)

**Comment by Mogli12** [comment]
Gerade für die Version 1.2 gibt es doch eine PDF-Doku. Allerdings glaube ich nicht, dass Du die Default-Konfiguration von 1.3 in Version 1.2 zum Laufen bringen kannst.
Wäre es nicht sinnvoller, wenn Du beschreibst, was Dir an Version 1.3 nicht gefällt?

**Comment by Patar95** [comment]
Die Doku im PDF-Format habe ich inzwischen auch gefunden. Leider hilft mir diese aber nicht weiter.

Das Problem mit der V1.2: Ich bekomme keine Konfiguration für den Buffalo rein. Ich habe mir das Config-File, in welchem die meisten Standard-Schlepper eingetragen sind in den Mods-Ordner kopiert, dort nur den Absatz vom Standard-Pickup (PiQup) gesucht, den Pfad auf den vom Buffalo geändert. Jetzt hätte der Buffalo ja eigentlich das Getriebe vom Auto haben sollen, beim Laden des Spiels kommt aber nach wie vor die Meldung in der log, dass keine Konfiguration für den Buffalo gefunden wurde.

Das Problem mit der V1.3: Beispiel Teleskoplader; Ich will langsam ein Stückchen vorwärts fahren. Eigentlich gebe ich jetzt langsam Gas (Lenkrad+Pedale vorhanden), bei leicht gestiegener Drehzahl sollte er dann auch langsam vorwärts fahren, tut er aber nicht. Erst irgendwo bei... ~3/4 der Maximaldrehzahl beginnt er sich zu bewegen, aber nicht langsam, sondern trotz gleicher Gasstellung beschleunigt er sehr sehr stark nach Vorne.

Im Eco-Modus ist dies nicht so sehr der Fall, da die Drehzahl unten bleibt fängt er auch bei geringer Drehzahl an sich zu bewegen, allerdings steigt auch bei Vollgas die Drehzahl kaum -> Keine Lösung

Zweites Problem der V1.3: Hänge ich einen Anhänger hinter einen Schlepper, fahre gemütlich mit Halbgas auf eine enge Kurve oder Abzweigung zu. Fahre ich jetzt weiterhin mit Halbgas in die Kurve (Abzweigung), bleibt der Trekker einfach stehen als würde ihm zum Kurven fahren die Leistung nicht ausreichen.

Drittes Problem der V1.3: Stufenlose Getriebe (Default) an sehr starkem Gefällt. Ich fahre mit halbgas das gefälle, die Motorbremse reicht nichtmehr aus oder ich will stehen bleiben. Lasse ich aber jetzt nur das Gaspedal los, kuppelt er wohl komplett aus und rollt ungebremst den Hang herunter. Das selbe passiert glaube ich auch wenn man den Hang mit Tempomat fährt (dann genügt auch die Motorbremswirkung), und diesen im Hang dann deaktiviert.

Das wars erstmal, kann hier auf der Arbeit nicht soooo viel schreiben ;-) 
Danke dass du dich dem Problem annimmst...

**Comment by Mogli12** [comment]
Verwendest Du die aktuelle Version 1.3.1.2 (v1.31 b2) hier von GitHub? Ältere Versionen kann ich leider nicht unterstützen.

In Version 1.31 ist das Anfahren etwas anders geregelt. Der Traktor kriecht immer mit mindestens 0,5 km/h und gibt unterhalb selbstständig Gas.

Zum 2. Problem: Da reicht vermutlich tatsächlich die Leistung nicht aus. Das passiert vor allem, wenn eine falsche Lenkgeometrie zu zuviel Reibung führt. 

Und beim Bergabfahren wählt das Stufenlose Getriebe bergab meisten die größt möglichen Gang. Es wird allerdings nicht ausgekuppelt. Mit Tempomat passiert das nicht, da hier der Tempomat automatisch selber bremst.

**Comment by Patar95** [comment]
Hallo. Habe mir nun die ganz aktuelle Version 1.3.1.2 von GitHub geladen. Leider besteht das Problem weiterhin. Zur Verdeutlichung habe ich ein Video dazu hochgeladen. Man sieht hier ein X-beliebiges Fahrzeug (hier JCB aus dem DLC).

- Stillstand "auto hold", dann langsam das Gaspedal runterdrücken. Ich drücke permanent und gleichmäßig das Gaspedal nach unten, aber erstmal bleibt die Drehzahl sehr lange so bei ca. 1600 1/min.  Dann steigt die Drehzahl langsam an, und irgendwann bei ca 2000 1/min beginnt er sich zu bewegen, wohlgemerkt sobald er beginnt loszufahren drücke ich das Pedal nicht weiter (ist ohnehin fast auf Anschlag...)

Link zum Video: https://www.youtube.com/watch?v=yTbyUJotlco


Bei einem Zweiten Video sieht man die Situation in den Kurven. Ich glaube, die beiden Probleme hängen zusammen. Ich habe hier das Gas auf dem weg zur Hofeinfahrt gleichmäßig ca. auf Halbgas gehalten. Dabei fällt die unnötig hohe Drehzahl auf. Als ich dann abbiege in die Einfahrt bleibt er einfach stehn als würde er es nicht packen, aber bei dieser Drehzahl packt er das locker, was man ja auch sieht wenn ich wieder gas gebe...

Link zum Video: https://youtu.be/q3Oa91p5wK4


Zu den Mods: Abgesehen vom DriveControl ist KEIN globaler Script drinnen, der auf Getriebefunktionen o.Ä. zugreift.

Gruß, Patar (Thomas)

**Comment by Mogli12** [comment]
Probiere mal Version 1.3.1.3. Ich glaube, dass ich einen kleinen Fehler gefunden habe.

**Comment by Mogli12** [comment]
Irgendwie funktioniert GitHub nicht mehr. Ich kann meine letzten Commits nicht mehr sehen. Aber mit diesem Link klappt es:
https://github.com/Mogli12/GearboxAddon/commit/3be5b41445b2a46bb6d3ce78ea3e1d8900db4013

**Comment by Patar95** [comment]
Es ist besser, aber immernoch schlecht dosierbar. Er fährt jetzt auch beim leichten Gas geben los, beschleunigt allerdings wieder viel zu start. (Testfahrzeug war wieder der JCB)

Neu ist jetzt, dass, wenn man Bremst dass ab einer gewissen Geschwindigkeit kurz die Reifen "blockieren". Ich habe jetzt leider keine Zeit mehr, aber wenn du willst, mach ich morgen nochmal Videos mit Dargestellter Pedal-Stellung.

**Comment by Mogli12** [comment]
In welchem Gang bist Du eigentlich? In Version 1,3 gibt es nur noch ein stufenloses Getriebe mit 2 Gängen. Das ist so ähnlich wie beim Fendt und bei einigen Mähdreschern. Zum Rangieren schaltest Du besser in den Gang "Lo".

**Comment by Mogli12** [comment]
P.S.: Die Videos sind leider privat. Ich habe aber auch einen passenden Google-User (mbiedens@gmail.com)

**Comment by Patar95** [comment]
Meistens im "Hi", ist aber meine ich auch im "Lo" nicht wirklich besser. 

Dachte Privat bei Youtube bedeutet "Nur für Leute sichtbar, die den Link haben". Habe deine E-Mail mal in die freigeschalteten eingetragen. 

Hast du selbst eigentlich Analoge Controller um das nachzuvollziehen?

**Comment by Mogli12** [comment]
Hi,
anscheinend verträgt die Engine von Giants keine so kleinen Übersetzungen. Ich wollte eigentlich ermöglichen, dass man stufenlos bis auf eine Geschwindigkeit von 0,05 km/h herunter kommen kann. Ich begrenze das jetzt allerdings beim stufenlosen Getriebe zunächst auf 1 km/h und gehe nur bei Bedarf weiter runter bis 0,05 km/h.

Probiere doch einfach mal Version 1.3.1.5. (https://github.com/Mogli12/GearboxAddon/commit/0b880e8368438d8e6804af988e34f1770f6fbac5)

Vielen Dank

**Comment by Patar95** [comment]
Hey,
entschuldigung dass ich mich so lange nicht gemeldet habe. Kam selten zum Spielen letzte Zeit. Bin zufrieden mit der aktuellen Version.

Bevor ich jetzt wegen jeder Kleinigkeit ein neues Thema auf mache, letzt habe ich die Fendt 700 Reihe von [AGO-Systemtech](url=https://www.modhoster.de/mods/fendt-700-vario-scr-series-v-4-ls15-profi-plus-pack) (https://www.modhoster.de/mods/fendt-700-vario-scr-series-v-4-ls15-profi-plus-pack) benutzt, der ja schon in der config eingepflegt ist. Dummerweise hat er, obwohl man ihn auf "transport" fährt, mehrere Stufen die gerade beim vom Gas gehen ziemlich hart geschalten werden. Ist das Absicht?

Außerdem gibt es einen Konflikt mit driveControl im Multiplayer. Sobald ein zweiter Spieler drinnen ist, flackert die Ganganzeige beim Server zwischen "auto hold" und dem richtigen Modus (z.B. "Stufenlos", "manual") hin und her und das Getriebe arbeitet nichtmehr richtig. Beim Stufenlosen wirkt sich das so aus, dass er sofort eine Vollbremsung hinlegt sobald man vom Gas geht. Ein Video gibts hier: https://youtu.be/vsGIJWBYDtw

Sorry für das gequatsche und die Musik. Man sieht im Video erst das Verhalten beim Stufenlosen. Er fährt zwar, aber es flackert auf auto hold. Beim manuellen getriebe bleibt er immer auf "auto hold", nur wenn ich auf Ö drücke (umschalten auf Manual) flackert kurz "manual" auf, bevor er wieder auf "auto hold" switcht. Fahren kann ich so leider garnicht.

Ist kein Mitspieler im MP, kann ich als Server ganz normal fahren. Ist einer drinnen, kann dieser auch normal fahren (wenn ich mich richtig erinnere), nur beim Server machts Probleme.

Entferne ich den Drive-Control mod, funktioniert auch wieder alles normal. Nächster Test wäre, die einzelnen Module nacheinander abzuschalten und zu sehen, an welchem es liegt. Ich tippe allerdings auf den reverser (Shuttle)

**Comment by Mogli12** [comment]
This should be fixed in FS17 (v2.0)
