### ISSUE TITLE
Range and group modes?

### ISSUE THREAD

**Issue by SoloTwo** [Mogli12/GearboxAddon#240]
Recently I updated to the latest version that included the buyable transmissions.  So many great additions make it easily the best version to date.  One thing I am missing, or perhaps overlooking, is the ability to select range or group transmission modes.  Being able to stay in a specific range while plowing, for instance, was very handy.  In full auto mode, it tends to skip around instead of being in the optimal range.

**Comment by Mogli12** [comment]
Did you check the settings UI? You can open it with "KEY_rctrl KEY_semicolon".

**Comment by SoloTwo** [comment]
Yes, is there a setting there that I am missing?  Not 100% sure what every setting does at this point.

**Comment by Mogli12** [comment]
In the 2nd column there are several settings about automatic, manual or simplified mode. In simplified mode you can choose different combinations of automatic and manual shifting.

**Comment by Mogli12** [comment]
With hired worker?

**Comment by SoloTwo** [comment]
Just with me driving, no hired worker.

**Comment by Mogli12** [comment]
Please add two screen shots, one of the settings screen and one while you are ploughing. I do not understand what you are doing.

**Comment by SoloTwo** [comment]
I dunno if the images will really show it, tomorrow I can make a video if necessary.  

So in the first image, I have selected simple and then range 1.  

![image](https://user-images.githubusercontent.com/13190734/31372511-a9640398-ad5b-11e7-99df-479b4443a628.png)

Then it shows (-R) on the display.  But when I accelerate it will go through range 3 right into range 4.

![image](https://user-images.githubusercontent.com/13190734/31372541-d7021d6c-ad5b-11e7-85ad-5880c4420be3.png)

And whenever I change the "settings simplified" setting, when I reopen the menu it always defaults back to sequential.  

![image](https://user-images.githubusercontent.com/13190734/31372595-2e106118-ad5c-11e7-833f-94e0c7e3501c.png)

**Comment by Mogli12** [comment]
Hi,

The screen shots were great! Changing the "settings simplified" did not work if the vehicle did not have 2nd range group. This should be fixed with v3.0 build 205.

Many thanks!

**Comment by SoloTwo** [comment]
Well, the settings now stay, but the transmission still works as a sequential. :-/  

Here is a quick video that can explain it better.

https://youtu.be/uhlsNIPOpHI

**Comment by SoloTwo** [comment]
Works great now, thank you! 👍
