### ISSUE TITLE
Small bug with handbrake.

### ISSUE THREAD

**Issue by UserB4D** [Mogli12/GearboxAddon#242]
Hi, I recently discovered a small bug, exactly: when the handbrake is turned on and turned off it is still active held until we put in the slack and re-select a gear (for example first gear).
Regards ;)

**Comment by Mogli12** [comment]
Do you use a gear shifter (e.g. G27)?

**Comment by UserB4D** [comment]
Yes, exactly G27.

**Comment by BlaggyXD** [comment]
Hello, 
In a older Version of the GB if you opened the vehicle debug you could see that the break is still on 100% after you released the handbreak but there where no breaking lights flashing, and as soon as you got it in gear* the break released and it startet rolling.

*i dont remember it correctly but i think it was like selecting a gear and letting the clutch come untill it startet rolling (and after breaking it still rolled) or if you just needed to tap the throttle a little bit.

Greets,
Blaggy

**Comment by UserB4D** [comment]
I recorded a short video to show you exactly. I hope it will help ;)  https://youtu.be/ifRABkZ9Q8Q
Regards. 
Ps. Watch for 720p.

**Comment by Mogli12** [comment]
Hi,
Please try version 3.0 build 207.
Thanks,
Stefan

**Comment by UserB4D** [comment]
Hi, now it works, but I'm surprised why the engine does not turn off with the handbrake applied  (when does the handbrake and gear 1 are set) ?

**Comment by Mogli12** [comment]
Hmm, should we really stall the engine if hand brake and a gear are engaged? Right now it goes automatically into neutral.

**Comment by BlaggyXD** [comment]
How about this, dont make it stall , but make it like it "fights" againste the brake/ give it a higher resistance to drive when the handbreak is engaged.

**Comment by Mogli12** [comment]
I though about it and I really like the idea. I will make the handling of hand brake and neutral completely independent. The normal play uses the automatic clutch, and this will automatically open if hand brake is engaged.

**Comment by Mogli12** [comment]
How is build 208?

**Comment by BlaggyXD** [comment]
While i was testing the v3.0 b207 i found an other little "bug" some how there is like a auto hold in every vehicle , if you are on a steep hill and roll (with out a gear engaged) you can stay a few seconds on the break and it wount roll any more , the same is after you released the handbreak.
If it is needed i can make a Video about it.

Im am now going to test b208.

**Comment by BlaggyXD** [comment]
The handbreak is perfect with b208.

Also the "auto hold" bug is not because you press the break / handbreak i think , it is if you stay long enough, some times it even workes that you stay a few seconds then start rolling and some how it just breakes by it selfe and wount roll any further.

**Comment by Mogli12** [comment]
Yes, most vehicles have the auto hold feature. If stay long enough on the brake the vehicle will keep the brake until you accelerate. Additionally, it will engage brakes if you are going in the wrong direction.

**Comment by BlaggyXD** [comment]
I know that .....

thats why is said:  

> there is like a auto hold in every vehicle 

I tested it in the Hürlimann H-488 an he hasnt got AutoHold.

Also autohold workes by staying on the break for a certint time this right here happens just if you dont move for a certint time.

**Comment by UserB4D** [comment]
"The normal play uses the automatic clutch, and this will automatically open if hand brake is engaged" - Now, understand ;) Thanks for fix.
Regards.
