### ISSUE TITLE
Maximale Solldrehzahl wird nicht eingehalten

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#243]
Servus,
es tut mir leid das es trotz einer Ankündigung so lange gedauert hat diese "Issue" auf zu machen, aber bis her hatte ich noch keine Zeit gefunden

Wie der Titel schon sagt wird die Maximale Solldrehzahl nicht eingehalten bzw. nur im Stand eingehalten,
evtl. ist das von Interesse: das hoch drehen wurde ist auf 500Ms festgelegt und das runter drehen auf 1500Ms.
Da mir nicht mehr zum erklären einfällt sind hier ein paar Bilder:

![fsscreen_2017_10_16_16_21_00](https://user-images.githubusercontent.com/20562677/31617096-bbc6fe90-b28e-11e7-8d80-3b785f314d5c.png)
![fsscreen_2017_10_16_16_21_12](https://user-images.githubusercontent.com/20562677/31617099-bcc9b6d4-b28e-11e7-928e-fb006e20fd0c.png)
![fsscreen_2017_10_16_16_21_19](https://user-images.githubusercontent.com/20562677/31617105-be603dc4-b28e-11e7-8a6a-e102cf860a99.png)
![fsscreen_2017_10_16_16_21_26](https://user-images.githubusercontent.com/20562677/31617109-c0fe1506-b28e-11e7-9560-f6430c52be7c.png)
![fsscreen_2017_10_16_16_21_35](https://user-images.githubusercontent.com/20562677/31617114-c32dc5d8-b28e-11e7-898c-2f77f05f44c9.png)
![fsscreen_2017_10_16_16_21_49](https://user-images.githubusercontent.com/20562677/31617117-c43c228a-b28e-11e7-95c0-a68220fa9dea.png)
![fsscreen_2017_10_16_16_22_03](https://user-images.githubusercontent.com/20562677/31617118-c5121458-b28e-11e7-84b3-ccd1e82712ea.png)

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

das ist kein Drehzahlbegrenzer. Mit der Einstellung werden nur die Grenzen für die Solldrehzahl gesetzt. Die hat aber im manuellen Modus eigentlich kaum Auswirkungen. Du kannst sie trotzdem anzeigen.

Grüße,
Stefan

**Comment by BlaggyXD** [comment]
Servus Stefan,

also wenn ich das richtig verstehe hat diese Einstellung eigentlich keine Wirkung bzw. keinen richtigen sinn oder habe ich da etwas falsch verstanden ?, wenn ja könntest du mir bitte den sinn/ die Wirkung davon erklären.

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Diese Einstellung wurde ja nach der #233 hinzugefügt , und da ist ja der sinn dass man die Maximale / Minimale Drehzahl im spiel festlegen kann oder nicht ?

**Comment by Mogli12** [comment]
Die Solldrehzahl ist die Drehzahl, die der Traktor möglichst erreichen soll. Das ist aber nur bei einem stufenlosenen oder automatischen Getriebe relevant. Bei manueller Schaltung und geschlossener Kupplung bestimmt sich die Drehzahl ausschließlich über die Geschwindigkeit, mit der sich die Räder drehen.

**Comment by BlaggyXD** [comment]
Servus,
mir ist gerade eben noch mal ein Fehler auf gefallen mit dem b212 geht die Wendeschaltung nur noch wenn man auch eine Automatik hat (z.b. am Steyr Multi geht sie aber am Zetor Proxima nicht). Wenn man keine hat muss man die Kupplung drücken , (Richtung um) schalten, anhalten und erst dann fährt man wieder (von selber) los.

Grüße,
Blaggy
