### ISSUE TITLE
Animation with Gearbox

### ISSUE THREAD

**Issue by UserB4D** [Mogli12/GearboxAddon#245]
Hi, I wanted to propose another interesting proposition, namely, animations that can be written in .xml (tractor or another vehicle) and which would work by adding an attribute to gearboxAddonConfig.xml. For example: animations of gears, manual gas or pedals (brake, clutch, gas - to act when you push the pedal on G27). What do you think about it ?

**Comment by BlaggyXD** [comment]
This is allready possible: 

https://www.youtube.com/watch?v=7x7RuxM6vW8

https://www.youtube.com/watch?v=15w1NjMLke4

**Comment by Mogli12** [comment]
Hi,

There are several functions at self you can use to ask for a state/variable in the gearbox. But someone has to create a specification out of it, similar to this one:
https://github.com/Mogli12/LS15_Specializations/blob/master/src/LinkToGlobalScripts.lua

So you have a specification inside of the tractor that checks:
- is the gearbox addon available (e.g. `if type( self.mrGbMGetIsOn ) == "function" then`...)
- is gearbox is swiched on (e.g. `if type( self.mrGbMGetIsOn ) == "function" and self:mrGbMGetIsOn() then`...)

And especially for gears and ranges the translation from gear number to animation position is probably not so easy.

If someone wants to write such specification I will help. But I cannot offer it easily inside the gearbox addon.

Best regards

**Comment by UserB4D** [comment]
Can someone write such a script ?

**Comment by Mogli12** [comment]
I think such script is always very specific to one vehicle. Thus this is part of modding a vehicle in my opinion.

**Comment by Mogli12** [comment]
Please check this mod: [IHC/CaseIH D-Familie](https://www.modding-welt.com/downloads/entry/2134-ihc-caseih-d-familie)

I looked at the standard vehicles. Here the complete interior is one node in the i3d file. So animations with just few settings in gearboxAddonConfig are not possible.

**Comment by UserB4D** [comment]
Thank you very much ;) Many animations are well done on the script compatible with GB.
Regards.
