### ISSUE TITLE
Fahrzeug rollt nicht mehr nach einer gewissen Standzeit/ Bremst von selber

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#246]
Servus,
nach einer gewissen Zeit im Stand oder unter ca. 2Km/h haben alle Fahrzeuge irgend eine art Bremse welche das (weg) rollen verhindert (nicht Autohold). Man kann keinen unterschied im Vehicle Debug Rendering oder am GearBox hud sehen ob man gerade "rollen kann" oder nicht.

Bsp.,
Wenn man an einem Bergs steht wo das Fahrzeug von selber runter rollt aber man Bremst und kurz stehen bleibt (ca.2-3 Sekunden) rollt man nicht mehr los , sobald man dann in jeglichem Gang die Kupplung etwas kommen lässt fängt man wieder an zu rollen.

Wenn man mit ca. 1-2 Km/h auf dem ebenen rollt hält das Fahrzeug nach ca. 2-3 Sekunden von selber an aber wenn man mit 3 oder mehr Km/h rollt passiert nichts.

Wenn unklar ist was ich meine kann ich gerne noch ein Video dazu nachreichen.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo,

das ist so gewollt. Nicht jeder Spieler kennt die Handbremse und da es im System so gut wie keinen Rollwiderstand gibt, würden die Traktoren irgendwann einfach von selber wegrollen.

Es ist halt nur eine Simulation und ich möchte, dass das GearboxAddon auch von normalen Spielern bedient werden kann.

Grüße,
Stefan

**Comment by BlaggyXD** [comment]
Servus,
könnte man das nicht so machen das man es entweder Deaktivieren kann (über die globals oder den Konfigutationsdialog) oder es sich selbst ausschaltet sobald man die Manuelle-Kupplung an hat ?

Dann wäre es für jeden spielbar auch wenn derjenige die Handbremse nicht kennt oder nicht benutzt.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Probier mal v3.0 build 210

**Comment by BlaggyXD** [comment]
Mit dem b10 hat sich leider noch nichts geändert.

**Comment by Mogli12** [comment]
Ich bin mir sicher, dass das GearboxAddon nicht mehr bremst. Aber Giants nimmt Fahrzeuge nach einer gewissen Zeit aus der Physik. Vielleicht liegt es daran. Hast Du mal gsVehicleToggleDegugRendering probiert?

**Comment by BlaggyXD** [comment]
Wie gesagt, im Vehicle Debug Rendering sieht man keinen unterschied zwischen "roll fähig" und "nicht roll fähig" , mit dem b10 hat sich daran auch nix geändert. Selbst wenn er mit 2Km/h fährt und abbremst gibt's es nirgends eine Änderung auf die man das Bremsen zurück führen könnte.

**Comment by Mogli12** [comment]
Giants nimmt Fahrzeuge nach einer gewissen Zeit aus der Physik.
