### ISSUE TITLE
Verbesserungsvorschlag an der Wendeschaltung/Lastschaltung 

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#247]
Servus,
die jetzige Wendeschaltung mit der Manuellen Kupplung ist etwas harsch und würgt gerne den Bulldog ab wäre es möglich die Wendeschaltung so zu machen das sie wie in echt auch nicht sofort ohne zu Kuppeln anfährt/schaltet sondern sanft und langsam ein kuppelt.

In etwa umgedreht ist es bei der Lastschaltung , in echt ist es bei den neueren Bulldogs so wie im LS , aber bei den älteren schaltet die Lastschaltung meistens so schnell/stark das man vom Gas gehen muss da es sonst einen sehr starken ruck gibt.

Vielleicht wäre es eine gute Idee wenn man die Stärke / Geschwindigkeit bzw. Kuppelzeit der Lastschaltung / Wendeschaltung als Parameter in der Konfiguration ein stellen kann ?

Ich hab zwar schon versucht etwas mit den Schaltzeiten zu spielen , aber so lange man die Manuelle Kupplung aktiviert hat werden diese nicht übernommen.Also selbst wenn man die Wendeschaltung auf sagen wir 4000Ms eingestellt hat schaltet sie sofort , hingegen mit der Auto. Kupplung dauert es 4000Ms bis sie schaltet , das gleiche gilt für die Lastschaltung.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Probier mal v3.0 build 210

**Comment by BlaggyXD** [comment]
Damit ist die Wendeschaltung wesentlich besser um nicht perfekt zu sagen. 
Da das der Hauptgrund für diesen Vorschlag war würde ich sagen man kann sie zu machen, aber das lasse ich dich entscheiden.

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Eine Sache die es zu bemängeln gibt habe ich doch noch gefunden , auf einem Dedi Server geht die neue Wendeschaltung leider (noch) nicht.

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Mit b212 funktioniert es jetzt auch auf einem Dedi Server.
Tolle arbeit!

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Danke

**Comment by BlaggyXD** [comment]
Servus,
mir ist gerade eben noch mal ein Fehler auf gefallen mit dem b212 geht die Wendeschaltung nur noch wenn man auch eine Automatik hat (z.b. am Steyr Multi geht sie aber am Zetor Proxima nicht). Wenn man keine hat muss man die Kupplung drücken , (Richtung um) schalten, anhalten und erst dann fährt man wieder (von selber) los.

Grüße,
Blaggy
