### ISSUE TITLE
Fuel Usage x2

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/GearboxAddon#249]
If I use mod FS17_FuelUsageDisplay http://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=56983&title=fs2017, then I see different fuel consumption.  Which one is correct?

![fsscreen_2017_10_20_23_43_17](https://user-images.githubusercontent.com/8200153/31841532-8e6428c6-b5f2-11e7-8580-44f82e44f554.jpg)

**Comment by Mogli12** [comment]
I do not know, which display value is correct. I am quite sure that my calculation is correct. The GearboxAddon uses the used torque and the specific fuel consumption (g/kWh) to calculate the real fuel consumption in l/h. But in the past the FuelUsageDisplay overwrote my internal variables. So I am not sure is 102 is really the value calculated by GearboxAddon. 

There is only one way to find out: Please drive the same road at nearly the same speed with and without FuelUsageDisplay.

**Comment by Gonimy-Vetrom** [comment]
Today I'll try to test by an experimental method.

**Comment by Gonimy-Vetrom** [comment]
The test is executed. 
The conditions are the same: on the 6th gear, rested against the wall.
1 liter of fuel is consumed in 108 seconds. Then for 1 hour 33 liters are consumed.
GearboxAddon shows fuel usage correctly.

![fsscreen_2017_10_21_10_12_36](https://user-images.githubusercontent.com/8200153/31849274-d611b336-b648-11e7-97b5-4a981039c9da.png)
![fsscreen_2017_10_21_10_03_21](https://user-images.githubusercontent.com/8200153/31849275-d63068a8-b648-11e7-8f31-10a9e5176ed1.png)

**Comment by Mogli12** [comment]
Should we open an issue in the github repository of FuelUsage?

**Comment by Gonimy-Vetrom** [comment]
I think that it is necessary. I also like this mod. Now I will do it.
