### ISSUE TITLE
error v1.3.1.7

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#25]
hab einen error widerholt in der log mit dieser Version, in Kombination mit der Krone Optima (BM), wenn man sie anstellt. Das Spiel haengt sich quasi auf, habe es allerdings noch nicht mit anderen Maschinen probiert

Error in updateVehiclePhysics :C:/Users/xxxx/Documents/My Games/FarmingSimulator2015/mods//zzzMrGearboxAddon/mrGearboxMogli.lua:6338: attempt to compare number with nil

**Comment by Mogli12** [comment]
HI,
I had the same error. It is already fixed with commit https://github.com/Mogli12/GearboxAddon/commit/e36fac133ef1bc2e2d92f0ad92e0b01dcc6165c9.
Thanks

**Comment by cabmac** [comment]
Hi, next error feeding cows with mixfeeder:

Error in updateVehiclePhysics :C:/Users/*****/Documents/My Games/FarmingSimulator2015/mods//zzzMrGearboxAddon/mrGearboxMogli.lua:6805: attempt to compare nil with number

**Comment by Mogli12** [comment]
Hi,

How can I reproduce this problem? 

Thanks

**Comment by cabmac** [comment]
will check it, this weekend.

**Comment by Mogli12** [comment]
With the latest commit you should see a warning instead of the error message.

**Comment by cabmac** [comment]
ok, curios thing, i cannot reproduce this problem, so....

**Comment by Mogli12** [comment]
I think we can close this one for now...
