### ISSUE TITLE
Animation of exhaust after engine stop

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/GearboxAddon#252]
If the engine is stopped due to low RPM or heavy load, sometimes the animation of the exhaust remains.

**Comment by Mogli12** [comment]
Do you use FS17_GameExtension?

**Comment by Gonimy-Vetrom** [comment]
Yes. Only and always latest version.  And problem with this tractor https://www.modhoster.de/mods/steyr-plus-760-2wd#description
his gearbox https://www.modhoster.com/mods/gearbox-fur-steyr-traktoren.
It seems to me that the problem in the script newExhaustEffects.lua. May be.

**Comment by Mogli12** [comment]
Hi,
This sounds very similar to #201. I just looked into FS17_GameExtension. I have no idea.
Best regards

**Comment by Gonimy-Vetrom** [comment]
What am I not attentive !!!  FS17_GameExtension not use in this game. :)
