### ISSUE TITLE
Fahrzeug rollt nur in gewählte Richtung

### ISSUE THREAD

**Issue by deutzfahraustria** [Mogli12/GearboxAddon#253]
Hallo,
Mir ist aufgefallen, wenn man bergauf am Berg steht und die Kupplung gedrückt hält rollt das Fahrzeug nicht rückwärts. Erst wenn man die Fahrtrichtung auf Rückwärts ändert, rollt er auch rückwärts. Das selbe auch bergab, obwohl die Kupplung ganz getrennt ist.
So gewollt oder nicht anders möglich?
MFG

**Comment by Mogli12** [comment]
Hallo,
welcher Traktor? Traktoren mit AutoStartStop betätigen selber die Bremse.
Viele Grüße

**Comment by deutzfahraustria** [comment]
Mit dem Same Fortis aus dem standart Spiel.
MFG

**Comment by Mogli12** [comment]
Ja, der bremst automatisch

**Comment by Banone** [comment]
@Mogli12 Kann man diese automatische Bremse irgendwie ausschalten?

**Comment by Mogli12** [comment]
Hast Du schon v3.0 build 212 oder 213 probiert?

**Comment by Banone** [comment]
@Mogli12 Ich benutze v3.0 build 214

**Comment by Mogli12** [comment]
Bei getretener Kupplung solltest Du ab build 212 entgegen der Fahrtrichtung rollen können. Abschalten lässt es sich aber nicht.
