### ISSUE TITLE
Manuelle-Kupplung wie Automatische-Kupplung (Anzeigefehler)

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#254]
Servus,
mit dem b212 ist die Manuelle-Kupplung wie die Automatische von der Anzeige her , davor war es immer so das die Manuelle sehr schnell den genauen Stand der Kupplung angegeben hat jetzt ist es so das sie nur langsam / selten aktualisiert wird , so wie es schon immer bei der Automatischen-Kupplung der Fall ist.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo,
Ist das im SinglePlayer oder auf dem Dedi-Server?
Viele Grüße,
Stefan

**Comment by BlaggyXD** [comment]
Servus,
om Singleplayer ist es auf jeden Fall und auf dem Dedi-Server hab ich es noch nicht getestet.

Grüße,
Blaggy

**Comment by BlaggyXD** [comment]
Servus,
bevor es noch untergeht da die Issue eigentlich schon zum zweiten mal geschlossen ist wollt ich noch mal eben erwähnen das ich in der #247 einen neuen gravierenden Bug gefunden hab, genaueres steht in meinem letzten Beitrag dazu.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Sorry, aber war soll das jetzt mit "zum zweiten Mal geschlossen"? Du wolltest, dass trotz manueller Kupplung, bei der Wendeschaltung die automatische Kupplung zeitweise die manuelle Kupplung übersteuert. Das das nicht ohne negative Seiteneffekte gehen kann, sollte hoffentlich klar sein.

**Comment by BlaggyXD** [comment]
Wie was soll das ? ich wollte dich nur darauf hinweisen das ich noch mal einen gravierenden Bug gefunden habe , und ich dachte mir bevor du es übersiehst da die Issue ja schon geschlossen ist da sie ja eigentlich fertig war erwähne ich es hier noch mal, mehr nicht.

Daran war nix negativ gemeint.

**Comment by Mogli12** [comment]
Das sollte mittlerweile gelöst sein. Es war ja auch nur ein Anzeigeproblem
