### ISSUE TITLE
Drive uphill, the wheels slip, instead of turning off the engine.

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/GearboxAddon#256]
I was driving the original Case IH 1455 under a very steep hill (ori USA map) on top gear. The tractor stopped, but there was no message about too low RPM (automatic clutch off). HUD displayed "wheel slip: 100%", but none of the wheels was spinning. I have locked the differential lock and turned on the four wheel drive (I use the GB function). Nothing has changed, still the wheels slip 100%, wheels do not spin, any message with low RPM, the engine is still running.

**Comment by Mogli12** [comment]
Hi,
Can you please add a screen shot?
Thanks

**Comment by KITT3000** [comment]
https://www.dropbox.com/s/kseuxdagz8ke98e/Zrzut%20ekranu%202017-10-24%2020.04.18.png?dl=0

I will try to record a video. I also found in it a mistake that when driving backwards when I press the clutch and change the direction of the tractor, as if still on the clutch drive though I let go. It spins backward and until it stops it will not go forward.

**Comment by BlaggyXD** [comment]
KITT300 , i allready made a Issue/a comment for the bug you are reporting here (the one with the engaged gear but you are still in neutral / got a fully pressed clutch) ( #247 ) but its on German.

**Comment by Mogli12** [comment]
Hi,
This is only a display problem. You cannot go up such a steep hill in 6th gear. Even the torque converter cannot do that for you.
Best regards

**Comment by KITT3000** [comment]
Ok, the error is just the information displayed on the HUD, and the impossibility of the drive itself is simply the gear ratio.
Here's a video for clarity: https://www.dropbox.com/s/7x9gb9wr0iog0j8/2017-10-24%2020-31-39.flv?dl=0

**Comment by Mogli12** [comment]
Tritt das Problem in der aktuellen Version noch auf?

**Comment by KITT3000** [comment]
I checked version 2.2.1.7 and the wheel slip is displayed correctly.
