### ISSUE TITLE
Wendeschaltung funktioniert nur in Verbindung mit Automatik

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#259]
Servus,
wie der Titel schon sagt, die Wendeschltung bei manueller-Kupplung geht nur wenn das Fahrzeug auch eine Automatik hat. 

(b213)
Z.B.:
Der Steyr Mutli hat eine Automatik bei der Lastschaltung und eine Wendeschtlung, deswegen kann man mit ihm bei manueller-Kupplung die Richtung wechseln ohne die Kupplung treten zu müssen.

Der Zetor Forterra hat keine Automatik aber eine Wendeschaltung, deswegen verhält er sich trotz Wendeschaltung also hätte er keine, also wenn man die Kupplung nicht drückt um die Richtung zu wechseln gibt er einfach nur den "Grinding" sound von sich aber Schaltet nicht um

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo,

das ist aktuell so passend zur Konfiguration. Das geht konkret über
```xml
<reverse manualClutch="false"/>
```
Das ist aber in den seltesten Fällen angegeben, daher zieht als Default der Wert von autoStartStop. Und da steht aktuell beim Forterra:
```xml
<gearboxMogli autoStartStop="false" maxAIRange="2" rpmInSpeedHud="true">
```

Viele Grüße

**Comment by BlaggyXD** [comment]
Servus,
danke für die schnelle Antwort, damit klappt es jetzt.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
In der nächsten Version sollte der Default besser sein.

**Comment by Mogli12** [comment]
Und, ist es in der aktuellen Version besser?

**Comment by BlaggyXD** [comment]
Jain, jetzt geht die Wendeschatung zwar über all wo sie gehen sollte, aber da man z.B. am Zetor kein Autohold hat bremst er nicht also rollt er ca.4 Sekunden nach dem schalten ungebremst weiter und kuppelt dann erst ein. Evtl. sollte man das "Autoholdbremsen" auch hinzufügen wenn man im "reverse" Tag den Atribut  clutchRatio="1" drin hat.

**Comment by Mogli12** [comment]
Ich denke, dass man beim Zetor schon selber bremsen muss. Ich fürchte sogar, dass IRL das Getriebe dadurch kaputt ginge.
