### ISSUE TITLE
G27 - Gruppen / Ranges schalten

### ISSUE THREAD

**Issue by Actionlog90** [Mogli12/GearboxAddon#26]
Hallo wertes Modding-Team,

ich habe folgendes Problem bei der Benutzung von Traktoren, bei denen die Gänge mit den Gruppen getauscht wurden [swapGearRangeKeys="true"] festgestellt:

Während des Schaltvorganges wählt das Script zwar die Passende Gruppe aus, jedoch wird dabei der Gang auf "Neutral" gesetzt, was zur Folge hat, dass kein Gang mehr eingelegt ist --> "kein Gang".
Das anschließende Schalten der Gänge bewirkt dabei keine Veränderung.

Aufgetreten ist der Fehler beim standard "Lindner Geotrac 94" , sowie beim "John Deere 6810".
Log ist sauber, keine weiteren Mods.
Gearbox-Version ist die aktuelle, mit dem lua 6338 fix (trat aber auch bei vorherigen Versionen auf).

Ich hoffe, dass ihr mit meiner Beschreibung etwas anfangen könnt und wäre froh, wenn ihr euch diesem Problem annehmen würdet (insofern dies überhaupt machbar ist).

MfG Actionlog90

**Comment by Mogli12** [comment]
Hallo,

leider steckt hinter dem Mod kein Team, sondern nur ich als Einzelperson.

Nutzt Du ein Lenkrad und den G27-Modus?

Viele Grüße

**Comment by Actionlog90** [comment]
Hi,
ja ich nutze ein Lenkrad in Kombination mit einem modifizierten G27-Shifter.
Modifiziert bedeutet in dem Fall, dass er eine Platine von einem Joystick bekommen hat und auch als solcher funktioniert (nur halt mit Rastpunkten und Schaltkulisse).
Die Eingaben greife ich mit einem Xpadder Programm ab, welches dann Tastatureingaben an den LS weitergibt.
Die Gangschaltung im LS habe ich dafür auf den Ziffernblock gelegt.
Also praktisch gesehen habe ich für jede Gruppe immer eine Taste gedrückt (z.B. KP7 für Gruppe 1).
Beim Gruppenwechsel gehe ich auf Neutral ( also die Taste wird los gelassen) und genau danach tritt das Problem auf:


Beim schalten in die nächste Gruppe (z.B. KP4 für Gruppe 2) wird diese Taste gedrückt und auch geschalten. **Damit wird zwar die nächste Gruppe korrekt ausgewählt (laut Anzeige), jedoch bleibt der Gang durch das Skript weiterhin auf Neutral** und somit lässt sich der Traktor nicht mehr bewegen.



MfG Actionlog90

**Comment by Mogli12** [comment]
Hi,
kannst Du mal schauen, ob die Beta11 das Problem löst?
Danke

**Comment by Actionlog90** [comment]
N'abend Mogli,
ich hab's eben mal fix angetestet und kann soviel sagen, dass sich das Problem zwar gebessert, aber noch nicht vollständig gelöst hat.

Das Schalten der Gruppen, sowie der Wechsel auf Vorwärts/ Rückwärts funktioniert jetzt einwandfrei. Allerdings wird der Gang nicht "gemerkt" und bleibt, bis zu einem erneuten Gangwechsel auf Neutral.

Der Schaltvorgang funktioniert jedoch vollständig, wenn man 2x kuppelt, also:
-Auskuppeln
-Gruppe einlegen
-Einkuppeln --> Gang weiterhin auf Neutral
-Auskuppeln
-nächsten/ vorherigen Gang einlegen
-Einkuppeln

Ich hoffe, du kannst damit etwas anfangen und danke nochmal für deine Mühen!


Actionlog90

**Comment by Mogli12** [comment]
Hi,

mit welchem Traktor hast Du es probiert? Nach deiner Beschreibung klingt es so, dass die Gänge nicht synchronisiert sind. 

Viele Grüße

**Comment by Actionlog90** [comment]
Hallo,

getestet habe die gleichen Traktoren wie aus dem ersten Post: also den originalen "Lindner Geotrac 94" und den gemoddeten "John Deere 6810" . Bei Beiden sind die Gänge als Lastschaltstufen definiert, müssten dementsprechend synchronisiert sein und sich auch ohne Kupplung schalten lassen. Dies funktioniert allerdings, wie gesagt, erst nach dem 2. mal kuppeln.

**Comment by Mogli12** [comment]
Hi,
das Problem sollte seit Beta12 nicht mehr auftauchen.
Viele Grüße
