### ISSUE TITLE
NH T6. automatic, no neutral with G27

### ISSUE THREAD

**Issue by Jurkkis** [Mogli12/GearboxAddon#261]
Is it intended when using default New Holland T6.160 and gearbox in automatic mode with G27/29 shifter, that when moving the shifter stick to neutral the tractor will stay in gear? Using default keyboard bind for "neutral" it will go to neutral but not with moving the shifter out of gear like it works with most of the manual gearboxes. 

v2.2.0.6 and playing on dedicated server

**Comment by Mogli12** [comment]
Can you please try the latest version?

**Comment by Jurkkis** [comment]
Thank you. G27 Neutral works with 2.2.1.4.
