### ISSUE TITLE
Speichern der Einstellungen

### ISSUE THREAD

**Issue by MrJoni0707** [Mogli12/GearboxAddon#263]
Moin, 
ich habe nachgeschaut und habe kein anderes Thema gefunden also hier ist es!
Ich würde es wieder toll finden, wenn z.B. ich grade mit einem Trecker, der kein gearbox hat, dass Addon aus bleibt und ich einen anderen auf dem Hof habe der es unterstützt, jeder seine Einstellung hat...
Dies war früher so... habe dann seit langen mal wieder eine neue Version geladen und das ist mir aufgefallen, da ich die FL steuerung, sowie dein Addon auf der Schaltung...
So könnte man das trennen um die Steuerung bei zu behalten!
Würde mich über eine Antwort freuen, wenn diese "Funktion" zurück kommt!

Lg
Jonas

**Comment by Mogli12** [comment]
Hallo Jonas,

seit man beim Kaufen bzw. beim Konfigurieren das Getriebe auswählen kann, ist der Schalter zum Ein-/Ausschalten global. Wähle doch einfach in der Konfiguration des Fahrzeugs das Getriebe (Transmission) "off".

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Jonas,
Hast Du mal probiert das Getriebe über die Konfiguration ein- oder auszuschalten? Kann dieses Issue geschlossen werden?
Viele Grüße,
Stefan
