### ISSUE TITLE
Speedmatching

### ISSUE THREAD

**Issue by JohnDeere6920** [Mogli12/GearboxAddon#264]
Hallo Zusammen,
Ich bekomme es einfach nicht hin, bei meinen Johnnys (Schaltung: Autoquad) das Speedmatching zu aktivieren. Evtl kann mir ja jemand helfen. Beim alten gearboxaddon von modhub haben die schaltungen einwandfrei funktioniert. Ich spiele Mit dem Logitech G29 und H-Schaltung.

MFG
JohnDeere6920

**Comment by Jan238** [comment]
Habe das gleiche Problem mit G27 und Schaltung. Mit Tastatur funktioniert alles wie es soll.

**Comment by JohnDeere6920** [comment]
Hallo, 
Ja das problem tritt auch bei dem auf. Es Tritt bei jedem traktor auf, der lastschaltstufen hat.

MFG
JohnDeere6920

**Comment by Mogli12** [comment]
Hallo,
probier mal die Version 3.0 build 219.
Vielen Dank,
Stefan

P.S.: Bei Lastschaltstufen ist nicht grundsätzlich auch Speedmatching an.

**Comment by JohnDeere6920** [comment]
Hallo,
Vielen, Vielen Dank. Es funktioniert jetzt einwandfrei.

MFG 
JohnDeere6920
