### ISSUE TITLE
GEAR BOX 1.3 JZD STRAZNICE 

### ISSUE THREAD

**Issue by Libor2904** [Mogli12/GearboxAddon#27]
Please help with mode 1.3 Gearbox do not know how to do to me in the HUD display machine performance (HP) ....
Thanks for any reply
Libor

**Comment by Mogli12** [comment]
Hi Libor,
Please check the chapter about gearboxMogliGlobals in the description.pdf. You can switch this on with <drawReqPower type="bool" value="true"/>
BR
