### ISSUE TITLE
Towing a vehicle in MP

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/GearboxAddon#270]
Today I noticed a bug when playing in MP. When the second player pulled me and I turned off the engine or turn on the neutral gear, the tractor braked the tow vehicle, even when I had the clutch open. I had to turn on the engine and turn on some gear so that the tractor would drive freely.

**Comment by Mogli12** [comment]
Yes, if the motor is turned off it will automatically turn on the hand brake. But I think this is standard and not modified by the gearbox addon.

**Comment by KITT3000** [comment]
So there is no way to change it? A little makes it difficult to towing vehicles.

**Comment by Mogli12** [comment]
I just tried it with a john deere that has auto hold. So if you are in Neutral and slow down it will go into auto hold. But it seems to work if I turn off the engine and press Neutral (KEY_semicolon) afterwards.

**Comment by KITT3000** [comment]
I tried to do just like you and still have the same problem. While the engine is off I can not tow another vehicle even if I turn on the neutral gear (key or Logitech Profiler). Only when the engine is running does it work. Maybe something is wrong with my tractor configuration, which I tow?

```
<vehicle>Ursus 1604
		<mod name="FS17_Ursus1604">
			<xmlFile name="Ursus1604.xml"/>
		</mod>

		<gearboxMogli autoStartStop="false" maxAIRange="2" rpmInSpeedHud="true">
			<realEngine idleRpm="650" ratedRpm="2200" >
			<!-- 2200: 150(150) | 2200: 150(150) | 1450..1450: 477(477) | 85 | 0,5 | 1 | 2 | 2200 | 1270: 238 -->
				<torque rpm="350" motorTorque="331" fuelUsageRatio="261.3"/>
				<torque rpm="700" motorTorque="414" fuelUsageRatio="246.9"/>
				<torque rpm="900" motorTorque="443" fuelUsageRatio="241.8"/>
				<torque rpm="1000" motorTorque="454" fuelUsageRatio="240"/>
				<torque rpm="1100" motorTorque="463" fuelUsageRatio="238.8"/>
				<torque rpm="1200" motorTorque="470" fuelUsageRatio="238.1"/>
				<torque rpm="1300" motorTorque="474" fuelUsageRatio="238"/>
				<torque rpm="1400" motorTorque="477" fuelUsageRatio="238.5"/>
				<torque rpm="1500" motorTorque="477" fuelUsageRatio="239.6"/>
				<torque rpm="1600" motorTorque="477" fuelUsageRatio="241.3"/>
				<torque rpm="1700" motorTorque="477" fuelUsageRatio="243.7"/>
				<torque rpm="1800" motorTorque="478" fuelUsageRatio="246.6"/>
				<torque rpm="1850" motorTorque="478" fuelUsageRatio="248.3"/>
				<torque rpm="1900" motorTorque="478" fuelUsageRatio="250.1"/>
				<torque rpm="1950" motorTorque="478" fuelUsageRatio="252.1"/>
				<torque rpm="2000" motorTorque="478" fuelUsageRatio="254.3"/>
				<torque rpm="2050" motorTorque="478" fuelUsageRatio="256.6"/>
				<torque rpm="2100" motorTorque="478" fuelUsageRatio="259.1"/>
				<torque rpm="2150" motorTorque="479" fuelUsageRatio="261.7"/>
				<torque rpm="2200" motorTorque="479" fuelUsageRatio="264.4"/>
				<torque rpm="2250" motorTorque="0" fuelUsageRatio="528.9"/>
			</realEngine>
		
			<gears defaultGear="1" shiftTimeMs="1200" speedMatching="false">
				<gear speed="7.625" name="1" />
				<gear speed="12.013" name="2" />
				<gear speed="19.094" name="3" />
				<gear speed="27.156" name="4" />
			</gears>
			
			<ranges defaultRange="2" shiftTimeMs="1200" doubleClutch="false">
				<range ratio="0.3422" name="I" forwardOnly="true" />
				<range ratio="1" name="II" forwardOnly="true" />
				<range ratio="0.4682" name="R" reverseOnly="true" />
			</ranges>
			
			<ranges defaultRange="1" shiftTimeMs="0">
				<range ratio="1" name="N" />
				<range ratio="0.7474" name="WZ" />
			</ranges>
		</gearboxMogli>
	</vehicle>
```

**Comment by Mogli12** [comment]
I think that there are too many disadvantages for the casual user if we would enable towing. And I was able to two a vehicle even with `autoStartStop="true"`. I turned of the vehicle and pressed neutral afterwards.

**Comment by KITT3000** [comment]
In version 2.2.2.1 something has changed. You can now tow vehicles with the engine off, but the handbrake has broken. When the engine is off and the handbrake is switched on or some gear is engaged. The towing vehicle is not loaded at all, it goes like it did not pull another vehicle. When the engine is running, the manual brake is the same, but the gear is slowed down by the towing tractor.

**Comment by Mogli12** [comment]
Hi, I think I cannot make it better.
