### ISSUE TITLE
Transmission-Tag ohne externe gearboxAddonConfig / gearboxAddonConfig.xml in die .zip eines Mods integrieren 

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#271]
Servus,
wie der Titel schon sagt geht es darum einen Mod mit einer Konfiguration auszustatten in welchem das Transmission-Tag benutzt wird ohne eine externe .xml oder .zip zu verwenden.

In der vehicle.xml des Mods geht dies ja leider nicht da es zu kompliziert wäre*², könnte man dann nicht theoretisch die  gearboxAddonConfig.xml und die gearboxMogli.lua in den Mod integrieren so das es die Gearbox und die dazugehörige Konfiguration direkt aus einer externen .xml in der .zip des Mods läd ?
Oder das die Gearbox die .zips abfragt ob in ihnen eine gearboxAddonConfig.xml ist und dann daraus die Konfiguration läd ?

*²Deine Aussage in einer vorherigen Issue war ja:
> Regarding different buyable transmissions per vehicle: This will get too complicated. The client-server-
    synchronization of the modified shop items is anyway already a night mare.

Grüße,
Blaggy

**Comment by Mogli12** [comment]
Hallo Blaggy,

Du kannst das Tag gearboxMogli unterhalb von motorConfiguration platzieren. Dann müsstest Du zwar deutlich mehr Motorkonfigurationen anlegen, könntest aber auch die Sichtbarkeit von Decals anpassen. Beispiel: Die Massey Fergusons haben den Namen des Getriebes auf der Motorhaube, also "dyna4", "dyna6" oder "dynaVT".

Viele Grüße

**Comment by Mogli12** [comment]
Hallo Blaggy,

ich habe mir das nochmal angeschaut. Ich denke nicht, dass man konfigurierbare XML-Einträge unterhalb von konfigurierbaren XML-Einträgen verwenden kann. Das XML-Tag `<transmissions>` entspricht aber anderen Tags wie `<wheelConfigurations>` oder `<motorConfigurations>`. Daher kann man `<transmissions>` nicht innerhalb von `<motorConfigurations>` verwenden.

Viele Grüße
