### ISSUE TITLE
Build 220 in game menu

### ISSUE THREAD

**Issue by alpha117** [Mogli12/GearboxAddon#273]
Hi

When I call up this menu (RCTRL+;), where you can change the GB options, there is no mouse cursor, and you cannot change anything.

I've checked other in game menu(seasons) and this is OK. Just seems an issue with the GB menu

Thanks

Clive

**Comment by alpha117** [comment]
Morning,

Still the same issue on build 221

**Comment by debejerry** [comment]
I Have seen ths as well, and could workaround it by holding "RCTL".
Then the mouse cursor appeared and everything was usable.

Currently I have no idea what's causing this beahaviour, maybe double used keys i.e. some sort of IC Control where RCTRL is often used to enable IC and showing the mouse cursor.
I'll try to check this with vanilla vehicle, if time permits.

**Comment by Mogli12** [comment]
If the mouse cursor appears with RCTRL it is most likely caused by another mod turning off the mouse cursor. This could be InteractiveControl.

**Comment by alpha117** [comment]
OK, found the MOD conflict. It is 'MoreRealistic(MR)' MOD.

Turn MR off and all is fine

**Comment by debejerry** [comment]
Ok, I'm going to try and verify, as I'm also having MR enabled most of the time (if not everytime ;=))  ) I'm playing.
Thanks @alpha117 

@Mogli12:  any chance for a workaround on this in one?  Other menus work correct even with MR enabled. :thinking:

**Comment by alpha117** [comment]
Result 222 fixes this issue.

Great work and very quick also
Many thanks

**Comment by Mogli12** [comment]
@alpha117 : I did not even have time to write a short comment about build 222. 

Many thanks for testing!
