### ISSUE TITLE
Nur 50% Gaspedal

### ISSUE THREAD

**Issue by UnixRoot2k** [Mogli12/GearboxAddon#274]
Hallo, Ich habe ein Prblem mit deinem Mod. 
Ich fahre mit Lenkrad und Pedalen, das klappt soweit auch wie es soll.
Sobald ich jedoch deinen Mod aktiviere sind nur noch 50% des Gaspedalsweges nutzbar. Die ersten 50% sind komplett tot. Das heißt ich muss das Pedal über 50% durchtreten damit im Spiel etwas ankommt.

Die Pedale sind nicht als Kombinierte Achse eingestellt, sondern sind komplett eigenständige Achsen.

Wie oben schon geschrieben, tritt das Problem nur mit deinem Mod auf, ohne Mod geht das Gaspedal wie es soll.

**Comment by Mogli12** [comment]
Das kann ich so leider nicht reproduzieren.

**Comment by UnixRoot2k** [comment]
Ich verwende ein Thrustmaster T500RS Lenkrad. Da ich keine kombinierten Achsen einstellen kann, ist im Spiel für Gas und Bremse heweiks eine getrennte Achse festgelegt. Ich befürchte ja, das die Achse keine Werte von 0-1 liefert, sondern von -1 bis 1. Das würde die genau 50% totzone am anfang erklären.

Kann ich da eventuell selbst etwas ändern? Irgendwo im code muss ja die Achse ausgelesen werden. Eventuell lässt sich der Wert ja per clamp funktion oder Ähnlichem in den richtigen bereich verschieben. Wie gesagt, das problem tritt ihne mod nicht auf.

**Comment by Mogli12** [comment]
Das GearboxAddon verwendet auch einfach nur self.axisForward und liest keine Achsen selber aus.

**Comment by UnixRoot2k** [comment]
Trotzdem kommen Werte an die so nicht erwartet werden. Dein Mod erwartet Werte von 0 bis 1 für das Gaspedal. Mein Gaspedal sendet aber Werte von -1 bis 1.

Ich habe das Problem jetzt Quick & Dirty gefixt. Allerdings nur speziell für meinen Fall.
In der Datei gearboxMogliMotor.lua in Zeile 1698 habe ich folgendes geändert:
`
elseif accelerationPedalRaw > -1 then
		accelerationPedal = ((accelerationPedalRaw+1)/2)^self.vehicle.mrGbMG.accThrottleExp
	end
`
So liest er den Wert schon ab -1 aus und rechnet ihn um in den erwarteten Bereich von 0 bis 1.
Eventuell liegt das daran das RAW Werte ausgelesen werden.

**Comment by debejerry** [comment]
Interessant, ich hatte auch schon gelegentlich das Problem dass bei Vollgas (Lenkrad, Pedale) die Drehzahl (und auch Solldrehzahl) nur bis auf 50% gingen.
per Handgas oder mit der Tastatur ließ sich das dann übersteuern.

Einzige Chance war dann das Spiel neuzustarten.

Allerdings tritt/trat das "Problem" nicht permanent, sondern sporadisch auf.
Auslöser scheint bei mir  das "raus-tabben" aus dem Vollbild LS-Fenster zu sein, wobei auch dabei keine 100% Garantie besteht, dass das 50% Gaspedal Problem auftaucht.

**Comment by UnixRoot2k** [comment]
Naja in meinem Fall liegt das zu 100% an der Hardware die eben im Bereich von -1 bis 1 sendet, der Mod allerdings nur Werte zwischen 0 und 1 auswertet. So wird der halbe Pedalweg einfach nicht ausgewertet. Das Problem dürften sämtliche Nutzer von Thrustmaster Lenkrädern haben.

Das Spiel ohne Mod wertet das Signal ja auch korrekt aus, im Mod wir aber eben laut Quellcode nur von 0 nis 1 gelesen.

**Comment by Mogli12** [comment]
Der Mod wertet die Achse nicht aus!

**Comment by Mogli12** [comment]
Ich denke, dass Du dann mit Deiner Hardware das GearboxAddon nicht verwenden kannst. Ich werde mir sicher nicht so ein Lenkrad kaufen, um das Problem nachzuvollziehen.

**Comment by debejerry** [comment]
Ich verweise nochmal auf meinen Kommentar von 09:30 Uhr.

@UnixRoot2k   Evtl solltest du dir einen anderen Ton angewöhnen wenn du kostenlose Hilfe  von jemandem erwartest der seine Freizeit einsetz und das Ergebnis dritten zur Verfügung stellt.

@Mogli12  m.E.n. ist das Auftreten nicht Hardware spezifisch, ich werde bei Gelegenheit mal versuchen ob ich es mit einem X-Box Controller  (analoge Axen) auch auftreten würde.
Was ist dir dazu dann lieber, diesen Issue weiterführen oder einen neuen aufmachen?

Gruß
Stefan

**Comment by Mogli12** [comment]
Hallo Stefan

Wir können das wieder aufmachen. 

Allerdings überschreibt das GearboxAddon the function [WheelsUtil.updateWheelsPhysics](https://gdn.giants-software.com/documentation_scripting.php?version=script&category=69&class=3545#updateWheelsPhysics48082). Dort sind Gaspeadal und Bremse bereits in dem einen Parameter `acceleration` kombiniert.

Viele Grüße,
Stefan

**Comment by UnixRoot2k** [comment]
Entschuldigung, wenn das aufmüpfig rüberkam. Aber was soll ich denn noch tun? 

Ich hab dass Problem mehrfach beschrieben und habe auch einen Lösungsansatz gebracht. 
Dafür muss sich Mogli12 doch nicht so ein Lenkrad kaufen. 

Man müsste doch im Prinzip nichts weiter tun, als die Werte die da im Mod ankommen zu normalisieren, das sie im richtigen Bereich liegen. 

Ich glaube ihm ja, das er keine Achsen direkt ausliest, das Spiel sendet aber trotzdem je nach Hardware in einem anderen Wertebereich der vom Mod nicht abgegriffen wird. 

Das Problem tritt ja nicht nur mit meinem Lenkrad auf, sondern sollte dann bei allen Achsen auftreten die von -1 bis 1 werte senden. Bei sämtlichen Joysticks z.B. 

Die Lösung wäre auch ohne Entsprechende Hardware zu erreichen. Die werte müssen nur normalisert werden.

**Comment by Mogli12** [comment]
Die Achsen werden ganz wo anders ausgelesen. Im GearboxAddon kommen Gaspedal und Bremse bereits kombiniert in einem Feld an. Da kann ich also nichts machen.

**Comment by UnixRoot2k** [comment]
Das ist leider doof. Ich habe den Code zwar jetz so angepasst, das die Werte normalisiert werden, aber diese Lösung funktioniert natürlich nur in meinem Fall. Für mich ist das Problem dadurch gelöst. ich hab 100% Pedalweg. Es wäre eben schön gewesen eine allgemeingültige Lösung zu finden. Nur ist eben Normalisieren nicht möglich wenn der Minimalwert sich unterscheidet.

Ich frage mich sowieso was da schief läuft. In sämtlichen anderen Spielen produziert mein Gaspedal Werte von 0 bis 1. Nur nicht im LS, da Wird das Pedal als isHalfAxis="true" erkannt aber dennoch voll ausgelesen. Dass Resultat ist, das Werte von -1 bis 1 kommen. Eigentlich komplett unnötig.

**Comment by Mogli12** [comment]
Tritt das Problem auch auf, wenn GearboxAddon als einziger Mod aktiv ist?

**Comment by UnixRoot2k** [comment]
Ja, also in meinem Fall schon.
