### ISSUE TITLE
Simple mode won't disengage handbrake.

### ISSUE THREAD

**Issue by Dwinesk** [Mogli12/GearboxAddon#275]
On the newest build 222 if you switch to simple gearbox mode either via the options of by keyboard controls the vehicles handbrake immediately engages and can not be turned off. Done everything I can think of to no avail

**Comment by alpha117** [comment]
Yes, can also confirm this, stuck with handbrake on

**Comment by Paul2510** [comment]
Hi I have the same problem
LG

**Comment by ivanlii** [comment]
For me is the opposite, cant engage handbrake in manual with universal from 50keda.

**Comment by Mogli12** [comment]
I hope it is fixed now with build 223

**Comment by alpha117** [comment]
Yep, perfect and yet again another quick fix

many thanks

**Comment by Dwinesk** [comment]
Yes it does. Thank you.

**Comment by Mogli12** [comment]
Thanks for testing!
