### ISSUE TITLE
Base stock wheel loaders skating on map

### ISSUE THREAD

**Issue by djdusty** [Mogli12/GearboxAddon#276]
Hello, 
Just noticed the both the stock front wheel loaders when driving act as if they are on ice. Just everywhere.
Running build 224
Latest MR mod
Pleasant valley v3 for map.
I havr a new holland mod front loader and it works flawlessly .

**Comment by Mogli12** [comment]
Hi,
GearboxAddon has nothing to do with skating around. Do you use Update 1.5.1?
Regards

**Comment by djdusty** [comment]
Yes 1.5.1, i only brought it up. Because when i disable the gearbox it stops skating.

**Comment by Mogli12** [comment]
Did you get errors in log.txt?

**Comment by Mogli12** [comment]
I think there was a bug related to articulated axis, which was fixed in the meantime.
