### ISSUE TITLE
Mouse cursor

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/GearboxAddon#277]
Once you enter the Gearebox ( **CTRL** + **;** ) settings and exit, the mouse cursor is displayed and you can not rotate the camera. This is done on SP and MP (but only on server).
PS. GB v2.2.2.4

**Comment by Mogli12** [comment]
Do you use a standard vehicle? Do you use moreRealistic? Does the mouse cursor disappear after pressing RTcrl?

**Comment by KITT3000** [comment]
1) I use the standard mod and vehicles, the problem occurs in all.
2) No, I don't use MR.
3) No, the mouse cursor remains after exit from the settings window (RCTRL +;), even if I open the game window (ESC, etc.), it remains until the game is restarted.

The problem had to occur after version 2.2.2.2 because in this version I used to last and did not notice this, and after updating to 2.2.2.4 the problem came up.

**Comment by KITT3000** [comment]
In version 2.2.2.7 the problem still occurs.

**Comment by Mogli12** [comment]
Hi,
I changed it in a way that the mouse cursor is show by the standard script of the game. There seems to be a problem if you leave with ESC. 
Regards,

**Comment by Mogli12** [comment]
Hi,
ESC works now as well.
Regards,
Stefan
