### ISSUE TITLE
Telelader-Drehzahl

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#278]
Moin, irgendwie laufen die Telelader seit den letzten zwei updates komisch (Tastatur, autm. Kupplung): Man gibt Gas, rollt ein bisschen aus oder bleibt stehen und es kommt einem vor, als ob das Gaspedal "klemmt". Er bleibt immer ein paar Sekunden auf dem Gas stehen.
Kann gerne ein Vid dazu machen...

Gruesse,
Claudio

edit: Telelader mit default-gearbox (hi-low)

**Comment by Mogli12** [comment]
Hallo Claudio,

ja, das ist so. Die Solldrehzahl senkt sich erst mit einer gewissen Verzögerung ab.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Es sollte behoben sein.
