### ISSUE TITLE
Gearbox Version 1.3.1.9

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#28]
Hallo biedens, 

ich nutze deine aktuellste Version. Ich habe das Problem dass wenn ich im Rückwärts fahren einen Gang nach oben schalten möchte er jedes mal den Neutral Gang einlegt. Beim mähen mit der Rückfahreinrichtung meines MB-Tracs wäre das schalten sehr hilfreich. Ich fahre mit einem G25 in Verbindung mit PPJoy und GlovePie. 

Kann ich etwas in der Config anpassen oder handelt es sich um einen Bug im Skript? 

Wäre für eine Rückmeldung dankbar. 

Grüße Maxter

**Comment by Mogli12** [comment]
Hi,
kannst Du mal schauen, ob es mit der Beta11 wieder klappt?
Danke

**Comment by MaxterTM** [comment]
Hallo, danke für deine Antwort!
Bin eben erst zum testen gekommen. Nun funktioniert es allerdings nur in den ungeraden Gängen. In 2,4,6 ist keine Kraftübertragung. Auch die genannten Bugs von modelleicher kann ich bestätigen. 

Grüße

**Comment by modelleicher** [comment]
Hallo, hänge mich hier mal mit ran.. Bei mir hat auch nur jeder 2. Gang Kraftübertragung und zwar in Vorwärtsfahrt.. Beta 11.
Scheint auch nicht gerade/ungerade zu sein sondern jeder zweite, d.h. wenn man mit nem geraden Gang anfängt haben die ungeraden keine Kraftübertragung und anders herum.

LG

**Comment by Mogli12** [comment]
Hi,
dann probiert doch jetzt mal die Beta12. Ich hatte zwar Probleme, das Phänomen zu reproduzieren, aber damit sollte es stabiler sein.
Vielen Dank

**Comment by modelleicher** [comment]
Also bei mir lassen sich mit der Beta 12 jetzt wieder alle Gänge durch schalten :) 

Danke ;) 
LG

**Comment by MaxterTM** [comment]
Bei mir auch, 1A :) Klasse Arbeit

**Comment by MaxterTM** [comment]
Habe jetzt gerade als Client im Multiplayer einen Fehler der mir die Log füllt, habe Sie mal angehängt. 

http://pastebin.com/NTdFAYwB

**Comment by Mogli12** [comment]
Hi,
Tritt das Problem auch auf, wenn Du den NewHollandT7Michi nicht im Mods-Ordner hast?
Viele Grüße

**Comment by Mogli12** [comment]
Hi,
probiere doch mal die 1.4 beta 15. Es sollte zumindest eine bessere Fehlermeldung kommen...
Danke

**Comment by Mogli12** [comment]
Hi,
gestern konnte ich dieselben Fehler mit einem anderen Mod reproduzieren. Höchst wahrscheinlich gibt es einen anderen Mod oder eine Spec., deren MP-coding (writeUpdateStream und readUpdateStream) nicht ganz sauber sind. Ich habe das jetzt in v1.4 b29 stabiler gemacht.
Viele Grüße
