### ISSUE TITLE
this gearbox does not have a simplified mode

### ISSUE THREAD

**Issue by taylorfx** [Mogli12/GearboxAddon#282]
Hallo,
ich bin von v227 auf v230 gesprungen und bekomme bei dem schönen JD6210R (FBM) diese Meldung. In der Hoffnung, das sich das erledigt, habe ich auf die nächste Version gewartet, aber das hat nichts geändert, scheinbar wurde da schon was geändert.

Kann ich das irgendwie selbst wieder beheben?

Gruß
Frank

**Comment by Mogli12** [comment]
Hallo Frank,
Der John Deere hat die Möglichkeit zur Konfiguration des Getriebes bekommen. Das AutoPowr ist ein stufenloses Getriebe, welches keine simplified mode hat.
Viele Grüße,
Stefan
