### ISSUE TITLE
MAN TGS 6x6/8x8 mit HKL-System. Cant add GearBoxConfig

### ISSUE THREAD

**Issue by Jurkkis** [Mogli12/GearboxAddon#283]
Hi,

https://www.modhoster.de/mods/man-tgs-8x8-mit-hkl-system

I've trouble adding gearBoxConfiguration to above mod. I've succesfully added/copied the default Man TGS gearbox to the KotteUniversal pack Man, and to Man TGS Forestry by h3rich by using external gearboxAddonConfig.zip, and i can't see difference in this mod but can't get it work. And I'm stuck with troubleshooting what could cause this. Could it be the amount of differentials?

My full log:
https://pastebin.com/mJ1MeRqk

My gearboxAddonConfig.xml from external gearboxAddonConfig.zip
https://pastebin.com/d8tFF0Ds
(the torque curves for HKL Man are incorrect but they are not the promlem atm, engines are named correctly though. )

**Comment by Paralox** [comment]
I've done it through setting the default transmission to the one trucks use, but have done every thing to make it work.

Check if in the first line of the "manTGS68HKL.xml" is <vehicle type="manTGS68HKL"> (you have to add the vehicle type as it is blank by default). 

Also I've added this before the wheel configuration line starts:

<gearboxMogli>
		<engines>
			<engine idleRpm="930" ratedRpm="1900">
        
        <torque rpm="350" motorTorque="980" fuelUsageRatio="220.9"/>
        <torque rpm="700" motorTorque="1785" fuelUsageRatio="203.7"/>
        <torque rpm="900" motorTorque="2065" fuelUsageRatio="197.9"/>
        <torque rpm="1000" motorTorque="2100" fuelUsageRatio="196.2"/>
        <torque rpm="1100" motorTorque="2100" fuelUsageRatio="195.2"/>
        <torque rpm="1200" motorTorque="2100" fuelUsageRatio="195"/>
        <torque rpm="1300" motorTorque="2100" fuelUsageRatio="195.6"/>
        <torque rpm="1400" motorTorque="2091" fuelUsageRatio="197"/>
        <torque rpm="1500" motorTorque="2060" fuelUsageRatio="199.3"/>
        <torque rpm="1600" motorTorque="1931" fuelUsageRatio="202.4"/>
        <torque rpm="1700" motorTorque="1817" fuelUsageRatio="206.3"/>
        <torque rpm="1800" motorTorque="1717" fuelUsageRatio="211.1"/>
        <torque rpm="1850" motorTorque="1670" fuelUsageRatio="213.8"/>
        <torque rpm="1900" motorTorque="1626" fuelUsageRatio="216.7"/>
        <torque rpm="1950" motorTorque="1584" fuelUsageRatio="220.5"/>
        <torque rpm="2000" motorTorque="1522" fuelUsageRatio="238.6"/>
        <torque rpm="2050" motorTorque="1275" fuelUsageRatio="277.1"/>
        <torque rpm="2100" motorTorque="794" fuelUsageRatio="340.7"/>
        <torque rpm="2150" motorTorque="0" fuelUsageRatio="433.3"/>
			</engine>
		</engines>
			<transmission name="Manual" speedLimiter="true" maxForwardSpeed="123" maxBackwardSpeed="93" autoStartStop="true" enableAI="true" maxRpmThrottle="0.5" fuelPerDistanceMinSpeed="10">
				<blowOffVentilSound volume="0"/>
				<gears axleSpeed="2.71" tireWidth="600" tireRatio="50" rimDiameter="22.5" defaultGear="7">
					<gear name="R2" reverseOnly="true" inverseRatio="11.14">
						<extraName range1="3" name="R1"/>
						<extraName range1="4" name="R2"/>
					</gear>	
					<gear name="7"  forwardOnly="true" inverseRatio="3.47">
						<extraName range1="1" name="1"/>
						<extraName range1="2" name="7"/>
					</gear>	
					<gear name="8"  forwardOnly="true" inverseRatio="2.70">
						<extraName range1="1" name="2"/>
						<extraName range1="2" name="8"/>
					</gear>	
					<gear name="9"  forwardOnly="true" inverseRatio="2.09">
						<extraName range1="1" name="3"/>
						<extraName range1="2" name="9"/>
					</gear>	
					<gear name="10" forwardOnly="true" inverseRatio="1.63">
						<extraName range1="1" name="4"/>
						<extraName range1="2" name="10"/>
					</gear>	
					<gear name="11" forwardOnly="true" inverseRatio="1.28">
						<extraName range1="1" name="5"/>
						<extraName range1="2" name="11"/>
					</gear>	
					<gear name="12" forwardOnly="true" inverseRatio="1.00">
						<extraName range1="1" name="6"/>
						<extraName range1="2" name="12"/>
					</gear>	
				</gears>
				<ranges defaultRange="1" shiftTimeMs="900">
					<range ratio="0.219" name="L" forwardOnly="true"/>
					<range ratio="1.000" name="H" forwardOnly="true"/>
					<range ratio="0.759" name="L" reverseOnly="true"/>
					<range ratio="1.000" name="H" reverseOnly="true"/>
				</ranges>
			</transmission>	
			
		</gearboxMogli>

Idk if it is necessary but as a temporary solution its fine. 

The way it should work is by adding an additional vehicle to "gearboxAddonConfig.xml" file, just insert it to the end of the file:

<vehicle>manTGS68HKL
		<mod name="FS17_cMAN_TGS_HKL_68_V6">
			<link href="https://www.modhoster.de/mods/man-tgs-8x8-mit-hkl-system"/>
			<xmlFile name="manTGS68HKL.xml"/>
		</mod>
				
		
		<gearboxMogli>
		<engines>
			<engine idleRpm="930" ratedRpm="1900">
        
        <torque rpm="350" motorTorque="980" fuelUsageRatio="220.9"/>
        <torque rpm="700" motorTorque="1785" fuelUsageRatio="203.7"/>
        <torque rpm="900" motorTorque="2065" fuelUsageRatio="197.9"/>
        <torque rpm="1000" motorTorque="2100" fuelUsageRatio="196.2"/>
        <torque rpm="1100" motorTorque="2100" fuelUsageRatio="195.2"/>
        <torque rpm="1200" motorTorque="2100" fuelUsageRatio="195"/>
        <torque rpm="1300" motorTorque="2100" fuelUsageRatio="195.6"/>
        <torque rpm="1400" motorTorque="2091" fuelUsageRatio="197"/>
        <torque rpm="1500" motorTorque="2060" fuelUsageRatio="199.3"/>
        <torque rpm="1600" motorTorque="1931" fuelUsageRatio="202.4"/>
        <torque rpm="1700" motorTorque="1817" fuelUsageRatio="206.3"/>
        <torque rpm="1800" motorTorque="1717" fuelUsageRatio="211.1"/>
        <torque rpm="1850" motorTorque="1670" fuelUsageRatio="213.8"/>
        <torque rpm="1900" motorTorque="1626" fuelUsageRatio="216.7"/>
        <torque rpm="1950" motorTorque="1584" fuelUsageRatio="220.5"/>
        <torque rpm="2000" motorTorque="1522" fuelUsageRatio="238.6"/>
        <torque rpm="2050" motorTorque="1275" fuelUsageRatio="277.1"/>
        <torque rpm="2100" motorTorque="794" fuelUsageRatio="340.7"/>
        <torque rpm="2150" motorTorque="0" fuelUsageRatio="433.3"/>
			</engine>
		</engines>
		
		<transmissions>
			<transmission name="Manual" speedLimiter="true" maxForwardSpeed="123" maxBackwardSpeed="93" autoStartStop="true" enableAI="true" maxRpmThrottle="0.5" fuelPerDistanceMinSpeed="10">
				<blowOffVentilSound volume="0"/>
				<gears axleSpeed="2.71" tireWidth="600" tireRatio="50" rimDiameter="22.5" defaultGear="7">
					<gear name="R2" reverseOnly="true" inverseRatio="11.14">
						<extraName range1="3" name="R1"/>
						<extraName range1="4" name="R2"/>
					</gear>	
					<gear name="7"  forwardOnly="true" inverseRatio="3.47">
						<extraName range1="1" name="1"/>
						<extraName range1="2" name="7"/>
					</gear>	
					<gear name="8"  forwardOnly="true" inverseRatio="2.70">
						<extraName range1="1" name="2"/>
						<extraName range1="2" name="8"/>
					</gear>	
					<gear name="9"  forwardOnly="true" inverseRatio="2.09">
						<extraName range1="1" name="3"/>
						<extraName range1="2" name="9"/>
					</gear>	
					<gear name="10" forwardOnly="true" inverseRatio="1.63">
						<extraName range1="1" name="4"/>
						<extraName range1="2" name="10"/>
					</gear>	
					<gear name="11" forwardOnly="true" inverseRatio="1.28">
						<extraName range1="1" name="5"/>
						<extraName range1="2" name="11"/>
					</gear>	
					<gear name="12" forwardOnly="true" inverseRatio="1.00">
						<extraName range1="1" name="6"/>
						<extraName range1="2" name="12"/>
					</gear>	
				</gears>
				<ranges defaultRange="1" shiftTimeMs="900">
					<range ratio="0.219" name="L" forwardOnly="true"/>
					<range ratio="1.000" name="H" forwardOnly="true"/>
					<range ratio="0.759" name="L" reverseOnly="true"/>
					<range ratio="1.000" name="H" reverseOnly="true"/>
				</ranges>
			</transmission>	
			
			<transmission name="TipMatic" maxForwardSpeed="123" maxBackwardSpeed="123" maxRpmThrottle="0.5" fuelPerDistanceMinSpeed="10">
				<gears axleSpeed="2.71" tireWidth="600" tireRatio="50" rimDiameter="22.5" defaultGear="7" automatic="true">
					<gear name="1"  forwardOnly="true" inverseRatio="15.86"/>
					<gear name="R1" reverseOnly="true" inverseRatio="14.68"/>
					<gear name="2"  forwardOnly="true" inverseRatio="12.33"/>
					<gear name="R2" reverseOnly="true" inverseRatio="11.14"/>
					<gear name="3"  forwardOnly="true" inverseRatio="9.56"/>
					<gear name="4"  forwardOnly="true" inverseRatio="7.43"/>
					<gear name="5"  forwardOnly="true" inverseRatio="5.78"/>
					<gear name="6"  forwardOnly="true" inverseRatio="4.56"/>
					<gear name="7"  forwardOnly="true" inverseRatio="3.47"/>
					<gear name="8"  forwardOnly="true" inverseRatio="2.70"/>
					<gear name="9"  forwardOnly="true" inverseRatio="2.09"/>
					<gear name="10" forwardOnly="true" inverseRatio="1.63"/>
					<gear name="11" forwardOnly="true" inverseRatio="1.28"/>
					<gear name="12" forwardOnly="true" inverseRatio="1.00"/>
				</gears>
			</transmission>
		</transmissions>
		</gearboxMogli>

But this didn't work for me for some reason.

It seems that setting the default transmission worked but it might interfere with additional mods. But if you choose the "default" gearbox type in the store it's good. Stefan should take a look at it nonetheless.

(attached my gearboxAddonConfig.xml if you want to see what I've done. 
[gearboxAddonConfig-file.zip](https://github.com/Mogli12/GearboxAddon/files/1536324/gearboxAddonConfig-file.zip)

**Comment by Paralox** [comment]
And the mod xml just in case. 
[manTGS68HKL.zip](https://github.com/Mogli12/GearboxAddon/files/1536336/manTGS68HKL.zip)

**Comment by Jurkkis** [comment]
Thanks the issue is indeed the blank type in manTGS68HKL.xml  <vehicle type="">.
Replaced with <vehicle type="manTGS68HKL"> and my external gearboxAddonConfig.zip works and the truck has the same manual and TipMatic as the default semi Man. Feel free to use it from the pastebin.
