### ISSUE TITLE
I can't start machine 

### ISSUE THREAD

**Issue by UserB4D** [Mogli12/GearboxAddon#284]
Hi, I found a (probably) mistake today. When I want to run a machine, it does not start until I turn off the gearbox mode. Required power: 130HP, the tractor has 150HP and is not able to run. I tried the original Valtra with the power of 145HP and was able to run (with the gearbox on).

Configuration this tractor (from gearboxAddonConfig.xml) : https://pastebin.com/bgxcdDUW

**Comment by Jurkkis** [comment]
Try this: Apply full Handthrottle, then engage the PTO.

**Comment by Mogli12** [comment]
Hi,
are you sure that the vehicle just has 477 Nm peek torque? Or is it 577 Nm peek torque? Because 150 HP @ 2200 RPM is already 478 Nm.
https://gist.github.com/Mogli12/348aaa5a1fe7954b60432c4025e78dc4
Regards, Stefan

**Comment by BlaggyXD** [comment]
Hello,
i think the bug you found is that you got more HP with a PTO implement on with the handthrottle/ PTO RPM then with the footthrottle. 
You can see that if you use a 100Hp tractor on the Kuhn mower from the DLC if you try to start it with the handthrottle at ~900 Rpm it wount start even if you got the engine at ~2200 Rpm with the footthrottle but as soon as you get the handthrottle to ~1500RPM it will start if you then rev it up to ~2200Rpm with the footthrottle and take the handthrottle againe down to ~900Rpm the mower will turn off againe. 

I often thought about makeing a Issue for that , but i think that it would need a allmost complete rewrith of the Gearbox.

I dont know if you understand what i mean , if you didnt i could make a Video about it.

Greets,
Blaggy.

**Comment by UserB4D** [comment]
Could you record this video ?
Regards.

**Comment by BlaggyXD** [comment]
Hello,
sure , i've just made a new issue in english so everybody can read it with.

#286

**Comment by Mogli12** [comment]
Hello,

I do not think that #286 is a bug.

Regards

**Comment by BlaggyXD** [comment]
Hello,

i think it is a very big bug.

Greets.
