### ISSUE TITLE
Less PTO HP if you dont use the handthrottle

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#286]
Hello,
heres a bug i found a long long time ago, but i havent found the time to make a Issue for it , so now here it is.

I think i dont need to say a lot because the Video says everything. 

[Video](https://youtu.be/UpBXC-UF_yI)

**Comment by Mogli12** [comment]
Hello,

hand throttle RPM overrides the PTO RPM and thus both RPM and torque are too low. You can use hand throttle to adjust the PTO RPM but I think it makes no sense to operate the mower at idle RPM.

Additionally, most tools use the same power independent of speed, load and crop/gras cut.

Regards,
Stefan

**Comment by BlaggyXD** [comment]
Hello,
i dont want to operate it at idle RPM but i want to start it at idle rpm and have the Handthrottle at like 1200 RPM like it would be IRL but that wouldnt worke because some how the HP is lower if i ounly use the footthrottle.

I think you didnt unterstood my problem.

 If you got the footthrottle at 100% on a PTO driven implement but the handthrottle at 1200RPM you wount get as much HP as if you got the handthrottle at full speed. Wich is total nonsense

Additionaly, the hole "PTO RPM" thing is also total nonsense for me IRL there is not a single tractor that gets the engine speed up as soon as you activate the PTO.

Greets,
Blaggy.

**Comment by Mogli12** [comment]
Hello,

The PTO RPM thing comes from Giants. The fact that the mower always uses full power even if raised comes from Giants. And at 1200 RPM you do not have enough power.

Regards,

**Comment by Blaggy2** [comment]
Why do you even got your mod on Github if you just block people when they report a bug?
Anyway , that wount keep me from writhing further.


Hello, 
did you even read my bug report / watched the video i made , or do you just ignore what i say? 
Or should i mabye writh it againe in german so you can understand it better ? 

Das Problem ist, wenn ich mit dem Handgas 1200 U/min hab kann ich das Mähwerk anschalten , aber wenn ich mit dem Fußgas 1200 U/min hab nicht, da er warum auch immer weniger Leistung mit dem Fußgas hat. Und das hat nix mit Giants zu tun sondern ist ein Fehler in der Gearbox. 

Grüße/Greets, 
Blaggy.

**Comment by Mogli12** [comment]
Lass doch das Handgas aus bei Zapfwellenarbeiten. Die Drehzahl ist viel zu niedrig und daher ist nicht genug Leistung da.

**Comment by modelleicher** [comment]
Vielleicht kann ich etwas Licht ins Dunkel bringen so weit ich das verstehe, das Problem hatte ich ja auch schon.
Zum Beispiel beim mähen muss ich mit dem Handgas vollgas geben, dann kann ich die Mähwerke einschalten. Wenn ich jetzt fahren möchte steht aber nicht genug Leistung zur Verfügung, der Traktor beschleunigt extrem zäh und träge.
Sobald ich jetzt aber zusätzlich Fußgas gebe steht dann extra Leistung zur Verfügung und der Traktor fährt sich normal. Eigentlich sollte ja das Handgas auf max. schon die maximale Leistung des Motors zur Verfügung stellen und fortan das gasgeben mit dem Fußpedal keinen Einfluss mehr haben.

Umgekehrt, wenn ich mit dem Fußpedal 100% Vollgas gebe reicht die Leistung ebenfalls nicht aus um das Mähwerk zu betreiben und zu fahren.

Sprich Fußgas allein auf Anschlag oder Handgas allein auf Anschlag hat jeweils weniger Leistung als wenn ich beides zusammen auf Anschlag habe.
Irgendwas stimmt also nicht mit der Leistungsberechnung zwischen Handgas/Fußgas.

Konkret bedeutet das, die einzige Möglichkeit Zapfwellengeräte die eine gute Portion der Traktorleistung erfordern zu bedienen ist per Handgas auf Vollgas stellen, und dann zum fahren noch das Fußgas durchzutreten.

**Comment by Blaggy2** [comment]
Ich kann das Hangas nicht auslassen sonst lässt sich das Mähwerk ja nicht anschalten. 

Die Drehzahl ist nicht zu niedrig , ich geb ja mit dem Fußgas vollgas also hab ich ~2200 U/min nur hab ich alleine da durch nicht genug Leistung und kann das Mähwerk nicht an machen. 
Wenn ich dann aber das Hangas auf 1200U/min stell hab ich auf einmal genug Leistung und kann das Mähwerk an machen , und das kann ja nicht so gewollt sein oder? 

Eventuell ist es verständlicher so wie es Modelleicher beschrieben hat.

**Comment by cabmac** [comment]
hmmm, ich Spiel zwar mit Tastatur aber das dürfte derselbe Fall sein, kam mir gleich komisxh vor. In meinem Fall ists der Optum mit der BM-Kronepresse, Handgas rauf, damit er die Presse angeschmissen bekommt, dann cruuse control rein und die Sache laeuft ueberaus traege, gebe ich mit W Gas dazu, scheint das besser zu gehen...

**Comment by BlaggyXD** [comment]
Servus,
mit dem b302 ändert sich nix.

Mehr oder weniger ist es sogar noch schlimmer geworden da die "HydraulicRPM" dazu gekommen sind welche genau so viel sinn wie die "PTORPM" machen.

Grüße,
Blaggy.

**Comment by Mogli12** [comment]
Ich habe den Standard-Hürlimann mit dem Heckmähwerk aus dem Kuhn DLC getestet und konnte es ohne Handgas starten.

Und die Funktion des Handgas ist nunmal, dass der Traktor dann diese Drehzahl für die Zapfwelle verwendet. Dann muss das Fahrzeug bereits bei dieser Drehzahl die vom Gerät geforderte Leistung haben.

**Comment by Blaggy2** [comment]
Warum bin ich jetzt eigentlich schon wieder gesperrt / blockiert / gebannt ?

> Und die Funktion des Handgas ist nunmal, dass der Traktor dann diese Drehzahl für die Zapfwelle verwendet. **Dann muss das Fahrzeug bereits bei dieser Drehzahl die vom Gerät geforderte Leistung haben**.

Warum hat man dann mit dem Handgas mehr PS wie mit dem Fußgas?

Warum reicht es nicht wenn ich mit dem Fußgas auf diese Drehzahl geh?

Die Funktion des Handgases ist das man das Standgas erhöhen kann ( z.B. wenn man am Berg anfahren muss) oder man dauerhaft die gleich Drehzahl halten muss was mit dem Fußgas unbequem werden kann.

In echt hat man **nie** mehr PS nur weil man das Handgas benutzt.
