### ISSUE TITLE
Bremsen

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/GearboxAddon#287]
Guten Morgen! Hätte nur eine Frage wegen dem Bremsverhalten! Hab bei machen Mods das Problem das der sehr schlecht bremst! 
Kann ich das irgendwie verändern oder liegt das Problem bei meinen mods??

LG

**Comment by Mogli12** [comment]
Hallo,
an der Stärke der Bremse ändert das Getriebe eigentlich nichts.
Viele Grüße

**Comment by Paul2510** [comment]
Ok Dank wird dann ein Problem bei den Mods sein! Schöne Adventszeit!!
