### ISSUE TITLE
Acceleration problem

### ISSUE THREAD

**Issue by Dwinesk** [Mogli12/GearboxAddon#288]
There is an issue that the acceleration when done via keyboard or game pad is severely reduced (I'd estimate by about half) however, if you activate the cruise control the vehicle accelerates to it's full potential as normal. The Tatra truck is a good example of this. Did you include any new controls like a togle that is still currently un-mapped?  

There is also the issue of this error code that comes up from time to time in the log. Though I don't know if the two issues are related: 
Error in updateVehiclePhysics :C:/Users/Edwin/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogliMotor.lua:4073: attempt to perform arithmetic on a nil value

**Comment by Mogli12** [comment]
Please send the complete log, e.g. via https://gist.github.com/

**Comment by Dwinesk** [comment]
[https://gist.github.com/Dwinesk/e19523274080744ca82ba398e995e0ea
](url)

![fsscreen_2017_12_11_23_11_02](https://user-images.githubusercontent.com/29665879/33851987-da1d9130-dec9-11e7-981d-8438bf61cf07.png)

![fsscreen_2017_12_11_23_11_21](https://user-images.githubusercontent.com/29665879/33852004-e5c489a8-dec9-11e7-94fa-8edc7c8ad909.png)

The 1st pic is acceleration maxed out while using a xbox 360 controller.
2nd pic is acceleration using cruise control.

Vehicle used is the JCB wheel loader.

**Comment by Mogli12** [comment]
Does the problem still occur?

**Comment by Dwinesk** [comment]
No everything is fine now. Thanks for the quick fix.
