### ISSUE TITLE
FS17_FuelUsageDisplay.zip

### ISSUE THREAD

**Issue by cater901645** [Mogli12/GearboxAddon#289]
Gibt es Probleme mit Diesem Mod?
Jedesmal wenn ich ein Fahrzeug kaufen möchte ohne Gearbox  (off)
bekomme ich einen Fehler.
Error: Running LUA method 'update'.
C:/Users/Cater2/Documents/My Games/FarmingSimulator2017/mods-test/FS17_FuelUsageDisplay/specializations/betterFuelUsage.lua:224: attempt to index field 'mrGbMS' (a nil value)

**Comment by Mogli12** [comment]
Hallo,
dann mach doch bitten ein Issue bei https://github.com/TyKonKet/FS17_FuelUsageDisplay auf.
Danke
