### ISSUE TITLE
Build 1.3.1.9 motor load sound

### ISSUE THREAD

**Issue by miracleman51** [Mogli12/GearboxAddon#29]
Great build so far,  really nice and realistic hydro etc, However I miss the motor sound increasing/deepening when under load.  Is it possible to have this added?

**Comment by Mogli12** [comment]
Hi,
Currently, I just try to modify the standard sounds. There are 3 sounds: idle, run and run2. Run2 is for the transmission. The pitch of idle and run depends on the motor RPM, the pitch of run2 depends on the vehicle speed. The volume of idle and run depends on the motor load.
Best regards

**Comment by miracleman51** [comment]
Hi,


OK Thanks Stefan.

Great job by the way.  I missed MR from 2013 too much to play FS15 until you developed this.  Makes the game from my point of view.  just as a thought, I had wondered if it were possible to take a recording of a turbo whistle and have that get louder/higher pitch when under load.  maybe something to think about in future :).


Matt


________________________________

**Comment by Mogli12** [comment]
Shall we continue the motor sound discussion in issue #41?
