### ISSUE TITLE
Lua Fehler gearboxMogli.lua:3992

### ISSUE THREAD

**Issue by cater901645** [Mogli12/GearboxAddon#292]
Guten Tag!
Folgender Fehler taucht bei mir nach einer gewissen Spielzeit auf meinem Server auf.

Error 3: C:/Users/Cater2/Documents/My Games/FarmingSimulator2017/Server/FS17_GearboxAddon/gearboxMogli.lua:3992: attempt to perform arithmetic on field 'volume' (a nil value)

kann leider nicht reproduzieren wie er zustande kommt (kann das was mit der AIVehicleExtension zu tun haben?)

taucht auf verschiedenen Maps mit verschiedenen Mods auf.

mfg Jens

**Comment by Mogli12** [comment]
Hallo Jens,
welche Version verwendest Du? (das ist wichtig wg. der Zeilennummer). Kannst Du eventuell eine komplette log.txt zuschicken. Das klappt super mit Gist.
Vielen Dank, Stefan

**Comment by cater901645** [comment]
Ich habe die letzten Versionen beider Mods drauf(heute frisch runtergeladen hier.
(habs auch mit anderen versionen probiert.
Log musste ich kürzen is scho 20 mb groß.
[log.txt](https://github.com/Mogli12/GearboxAddon/files/1569446/log.txt)

**Comment by cater901645** [comment]
ich konnte den Fehler jetzt soweit reproduzieren, das er kommt wenn ich den Rückwärtsgang über Spastaste (Shuttelcontrol aktiviere).
mit meinem G27 über den Gangschaltungshebel, machts kein Problem.
Testobjekt war die Original große Feldspritze

**Comment by Mogli12** [comment]
Hallo,
ist es mit v3.0 build 306 behoben? Die Spritze hat keinen separaten Sound für Motorlast.
Viele Grüße

**Comment by cater901645** [comment]
Das ich die Spritze als Testobjekt genommen habe war ein Fehler, weil ich für die Spritzen auch eine Schaltung eingebaut habe (ähnlich der für Traktoren).
Soweit funktioniert es jetzt, wenn ich jetzt versehentlich Space drücke gibt der Trecker nur e bissel Zwischengas (kein Error mehr), super wenns so bleibt.
Ich werd noch e paar andere Konfigurationen testen, ich hätt ja nix gesagt wenn nur eine Zeile von dem Fehler gekommen wär, aber der Hat ja die Log vollgeschrieben bis mann das Spiel beendet hat.

**Comment by Mogli12** [comment]
Hallo,
das Zwischengas kommt von der 2. Gruppe. Vielen Dank, dass Du die Meldung aufgemacht hast. Es war ja tatsächlich ein Problem da.
Viele Grüße, Stefan
