### ISSUE TITLE
Brake light suggestion

### ISSUE THREAD

**Issue by Dwinesk** [Mogli12/GearboxAddon#295]
This mod in FS15 did as advertised: [https://www.modhoster.com/mods/bremslicht-erweiterung](url)

Could you incorporate such a similar feature? Especially for the handbrake feature that you have already installed.

**Comment by Mogli12** [comment]
Hmm, I do not know. The brake lights are already visible if you are on the brake. But in auto hold or with hand brake they are not shown.

**Comment by Dwinesk** [comment]
Just think it over. Personally I think it would be good addition that if a vehicle is running and has its handbrake in the on position, that the brake lights should be on. Vehicle off, everything off regardless. I also agree with you that it should not just copy what that mod does but tie in to your own mods functionality. Borrow only the good :)

**Comment by Mogli12** [comment]
So you think the brake lights should be on with hand brake if the motor is on? Is this what you propose?

**Comment by Dwinesk** [comment]
Yeah that's the idea. You could try it out, see how it is received by people on here (plus yourself) and if not well taken you can always ditch it.

**Comment by Mogli12** [comment]
Please try v3.0 build 309

**Comment by Dwinesk** [comment]
I have tried it but so far I have not seen the brake lights come on with handbrake.. I was going to do more testing on my part just to make sure that it isn't an error on my part.

**Comment by Mogli12** [comment]
There will be no brake lights if just handbrake is on. I mainly improved the brake lights if the vehicle is driven by the hired worker, courseplay or followme.

**Comment by Dwinesk** [comment]
Oh.. ok. I'll test for that then.
