### ISSUE TITLE
GearboxAddon vs Handbrake by Blacky_BPG

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/GearboxAddon#297]
Hey. I'm glad you're back.
So I decided to write this question.
I use these two mods together: GearboxAddon + Handbrake by Blacky_BPG.
And I have to turn off the two hand brakes: GearboxAddon and Handbrake by Blacky_BPG.
For starters, I changed this parameter: gearboxMogli.registerState( self, "Handbrake",  true ) and changed the key for the brake to do it at the same time.
But sometimes there is an out-of-sync: one brake is turned on, and the second is turned off.
Can you make these two mods be friends?
This is just for convenience.
Thank you!

**Comment by Mogli12** [comment]
Hello,
Please check build 308.
Best regards

**Comment by Gonimy-Vetrom** [comment]
Thank you. Works great.
