### ISSUE TITLE
permanent Stufenloses Getriebe

### ISSUE THREAD

**Issue by RagnarRoeg** [Mogli12/GearboxAddon#30]
Ich wollte meinem Famulus ein getriebe verpassen. es hatte damals schonmal geklappt und seit ich nun die neue version vom gearboxaddon nutze nicht mehr.

ich habe nur 2 Ranges (HI und LO) und das ganze ist stufenlos.

hier mal mein zzzMrGearboxAddonConfig.xml auszug

   

> <vehicle>

	<configFile modName="Famulus_V2" xmlName="Famulus.xml"/>
	
		<gearboxMogli autoStartStop="false">>
			<realEngine idleRpm="800" ratedRpm="1500" >
				<torque rpm="0" motorTorque="0"/>
				<torque rpm="700" ptoTorque="376"/>
				<torque rpm="800" ptoTorque="388"/>
				<torque rpm="900" ptoTorque="395"/>
				<torque rpm="1000" ptoTorque="400"/>
				<torque rpm="1200" ptoTorque="415"/>
				<torque rpm="1400" ptoTorque="438"/>
				<torque rpm="1500" ptoTorque="450"/>
				<torque rpm="1600" ptoTorque="427"/>
			</realEngine>
	
			<gears defaultGear="1" shiftTimeMs="300">
				<gear speed="9.4"/>
				<gear speed="20.4"/>
				<gear speed="36.4"/>
				<gear speed="43.5"/>
			</gears>

			<ranges defaultRange="1" clutchRatio="1" shiftTimeMs="1000" reverseReset="true">
				<range ratio="0.2" name="Z" />
				<range ratio="0.5" name="M" />
				<range ratio="1" name="S" />
			</ranges>

	
		</gearboxMogli>		
		</vehicle>

**Comment by Mogli12** [comment]
Hi,
lade doch mal die log.txt (z.B. bei https://gist.github.com/) hoch. Da stehen normalerweise Meldungen drin.
Danke

**Comment by RagnarRoeg** [comment]
Ich habe den fehler bereits gefunden. ich habe nur die xml vom famulus hinzugefügt, jedoch nicht die vom famulus_c.

vielen dank trotzdem
