### ISSUE TITLE
Automatic mode seem the gears won't want to change only range and again speed locked issue

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/GearboxAddon#300]
in this config external gearboxAddonConfig.xml:
`	</vehicle>
			<vehicle>fendt1000
			<mod name="FS17_Fendt_1000">
				<xmlFile name="fendt1000.xml"/>	
			</mod>

		<gearboxMogli speedLimiter="false" autoStartStop="true" defaultOn="true" maxAIGear="3">
			<gears defaultGear="2" speedMatching="false">
				<gear maxForwardSpeedRatio="0.099" name="P1"/>
				<gear maxForwardSpeedRatio="0.231" name="P2"/>
				<gear maxForwardSpeedRatio="0.406" name="P3"/>
				<gear maxForwardSpeedRatio="0.943" name="P4"/>
			</gears>
			
			<ranges defaultRange="2" shiftTimeMs="0" clutchRatio="1" automatic="true">
				<range name="LO" ratio="0.7"/>
				<range name="HI" ratio="1.0"/>
			</ranges>
		</gearboxMogli>	
	</vehicle>`

here the savegame config about it:
`
    <vehicle id="14" modName="FS17_Fendt_1000" filename="$moddir$FS17_Fendt_1000/fendt1000.xml" isAbsolute="true" age="42" price="438950" propertyState="1" operatingTime="139577.1717338"  fuelFillLevel="584.44265913979" cruiseControl="75.440001487732"  attacherJointComboDir="-1" dirtAmount="1" isReverseDriving="false"   mrGbMCurrentGear="1" mrGbMResetFwdGear="3" mrGbMResetRevGear="1" mrGbMMinTarget="0.13043478131294" mrGbMMaxTarget="0.86956518888474" mrGbMAllAuto2="true" mrGbMAllAutoMode="6" mrGbMEcoMode="true"  mrGbMSpeed2="60" mrGbMSpeed3="15"  ksmExponent="8" repairOperatingTime="0" fourWheel="true" diffLockFront="false" diffLockBack="false" ssLastRepairDay="40" ssYesterdayOperatingTime="100968840" ssCumulativeDirt="18329507.412154" ssYears="0.04166666790843" >
        <component1 position="40.635894775391 55.253051757813 -64.999641418457" rotation="-0.037233181297779 -0.77402544021606 0.01214896608144" />
        <component2 position="38.403255462646 55.797023773193 -63.76974105835" rotation="-0.037199642509222 -0.7740250825882 0.012149452231824" />
        <component3 position="39.419342041016 55.809368133545 -62.776420593262" rotation="-0.037418477237225 -0.77401804924011 0.012417753227055" />
        <component4 position="40.448699951172 55.88293838501 -66.239387512207" rotation="-0.0374969355762 -0.77401369810104 0.01252644136548" />
        <component5 position="41.871646881104 55.900226593018 -64.848335266113" rotation="-0.037450760602951 -0.77401578426361 0.012474741786718" />
        <configuration name="design" id="2" />
        <configuration name="wheel" id="1" />
        <configuration name="baseColor" id="5" />
        <configuration name="motor" id="5" />
        <configuration name="rimColor" id="7" />
        <configuration name="GearboxAddon" id="1" />
        <boughtConfiguration name="motor" id="1" />
        <boughtConfiguration name="motor" id="5" />
        <boughtConfiguration name="wheel" id="1" />
        <boughtConfiguration name="rimColor" id="1" />
        <boughtConfiguration name="rimColor" id="7" />
        <boughtConfiguration name="design" id="1" />
        <boughtConfiguration name="design" id="2" />
        <boughtConfiguration name="baseColor" id="1" />
        <boughtConfiguration name="baseColor" id="5" />
        <boughtConfiguration name="GearboxAddon" id="1" />
        <interactiveObject id="1" state="false"/>
        <interactiveObject id="2" state="true"/>
        <interactiveObject id="3" state="false"/>
        <interactiveObject id="4" state="false"/>
        <interactiveObject id="5" state="false"/>
        <interactiveObject id="6" state="false"/>
        <interactiveObject id="7" state="false"/>
        <interactiveObject id="8" state="false"/>
        <interactiveObject id="9" state="false"/>
        <interactiveObject id="10" state="false"/>
        <interactiveObject id="11" state="true"/>
        <interactiveObject id="12" state="true"/>
        <interactiveObject id="13" state="false"/>
        <interactiveObject id="14" state="true"/>
        <interactiveObject id="15" state="false"/>
        <interactiveObject id="16" state="false"/>
        <interactiveObject id="17" state="false"/>
        <interactiveObject id="18" state="false"/>
        <interactiveObject id="19" state="true"/>
        <interactiveObject id="20" state="false"/>
        <courseplay aiMode="8" courses="47" openHudWithMouse="false" lights="1" visualWaypointsStartEnd="true" visualWaypointsAll="false" visualWaypointsCrossing="true" waitTime="0" siloSelectedFillType="nil" runNumber="1" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="14" turn="14" field="24" max="80" />
           <combi tipperOffset="0.0" combineOffset="0.0" combineOffsetAutoMode="true" fillFollow="50" fillDriveOn="90" turnDiameter="9" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="false" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="true" manualWorkWidth="0.0" ploughFieldEdge="false" lastValidTipDistance="0.0" hasSavedPosition="false" savedPositionX="0.000000" savedPositionZ="0.000000" savedFieldNum="0" fertilizerOption="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="10" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0" drivingThroughtLoading="false" />
        </courseplay>
        <followMe backDist="10" sideOffs="0.0" />
        <wheelDirt wheel1="1.000000" wheel2="1.000000" wheel3="1.000000" wheel4="1.000000"/>
        <vehicleGroupsSwitcher grp="1" pos="3" grpName="Tracteurs" />
    </vehicle>`
and screen like automatic but no gear change:
![1](https://user-images.githubusercontent.com/25174503/34443560-4ed9753c-ecc8-11e7-8e52-3409e938ea08.jpg)
I profit of this to add persistent speed limited issue too

Best regard :)

**Comment by Mogli12** [comment]
You did not configure the gears to change automatically. To use the option in row 3 and column 2 you have to switch to simplified mode.

**Comment by Anonymous-any** [comment]
Hi happy , new year :) yes absolutely right but what I want to show you is in automatic mode no gears change with this config only range do it don't care of the row 3 column2 !!! you can see in the square under the column2 I paste it's in automatic mode but the gears won't change as old versions and it is the same external gearboxAddonConfig.xml file from date 28/07/2017 unmodified.  Of course I see the simplified version change the gears it but it seem don't care too to the RPM we can set, it seem wait full RPM and wait a time to change the gear a bit fast with range it seem, the old version was do it in automatic mode and the best option it has was to allow manually change in auto mode not restricted.

**Comment by Mogli12** [comment]
The setting in row 3 column 2 is only for the simplified mode. The automatic mode is always like in the configuration. 

The min. and max. target RPM is just the range of target RPM. In automatic mode the vehicle will choose the gear that is closest to the target RPM and the target RPM is inside this range.

**Comment by Anonymous-any** [comment]
Yes it's ok for simplified mode well understand but the issue it seem found is related to automatic mode his behavior is not like old versions now automatic mode won't want to change the gears and I gave you the config file like it is, maybe in few time I go upload you a movie it can be more simple to show you but I need few time for do it compress/build the movie and upload with low speed on an ftp server.
Back in few, keep well :)
Br

**Comment by Mogli12** [comment]
The gears cannot change automatically. There is not attribute "automatic=true".

**Comment by Anonymous-any** [comment]
Ahh it's ok I go try to add that but old version was run fine without this one.
Thank for all effectively this is in range but not in gears :/
