### ISSUE TITLE
Analoge Rpm Anzeige 

### ISSUE THREAD

**Issue by Martin1500** [Mogli12/GearboxAddon#302]
Moin Stefan wie funktioniert das mit der anzeige genau? Welche Daten bezieht sie die gearbox ?
Ich habe da die D Serie  von Modding Welt ich habe mir die Einträge in der xml  angeschaut 
D Serie: 
animation name="speedDisplay"
            part node="0>10|0" startTime="0" endTime="1" startRot="0 0 0" endRot="-180 0 0"/
        /animation

Original 1455:
animation name="speedDisplay"
            part node="0>10|0" startTime="0" endTime="1" startRot="0 0 0" endRot="-180 0 0"/>
        /animation
Die sind ja identisch aber die D Serie ist kmh Gebunden nicht Rpm 
Und der Originale 1455 ist rpm gebunden  weißt du vielleicht einen Rat ?Gruß Martin

**Comment by Mogli12** [comment]
Hallo Martin,

dann fehlt in der Konfiguration der Eintrag `rpmInSpeedHud="true"`.

Viele Grüße, Stefan

**Comment by Martin1500** [comment]
Gefunden Vielen Dank Stefan
