### ISSUE TITLE
Stufenlos

### ISSUE THREAD

**Issue by JohnDeere6920** [Mogli12/GearboxAddon#304]
Hallo,
Ich habe seid kurzem Einen John Deere 7530 mit AutoPowr. Sobald ich mit ihm ein Zapfwellengerät betreibe, Dauert es etwa 5 Sekunden, bis er Beschleunigt. Davor passiert nichts. Bei allen Schalt Getrieben, die ich habe, Funktioniert alles Einwandfrei.

MfG
JohnDeere6920

**Comment by Mogli12** [comment]
Hallo,

kannst Du mal einen ScreenShot machen?

Danke

**Comment by JohnDeere6920** [comment]
![fsscreen_2018_01_05_18_24_08](https://user-images.githubusercontent.com/33002905/34620467-d7e2b0fa-f245-11e7-879e-452f36f007bc.png)

Hier gerade beim Mist streuen ist das doof, da ungefähr 1000 liter so weg sind, bis er beschleunigt.

**Comment by Mogli12** [comment]
Ok, v3.0 build 219 ist von Ende Oktober. Hast Du mal die aktuelle Version (https://github.com/Mogli12/GearboxAddon/blob/master/FS17_GearboxAddon.zip?raw=true) probiert?

**Comment by JohnDeere6920** [comment]
Ja. Jetzt, nachdem Ich meine schaltungen nachgetragen habe klappt alles.

MfG
JohnDeere6920

**Comment by Mogli12** [comment]
Wieso nachgetragen? Die ZIP Datei soll doch nicht verändert werden. Für Einzelspieler (SP) legt man die eine weitere Datei gearboxAddonConfig.xml in den Mods-Ordner. Für MP ist es besser, wenn https://github.com/Mogli12/GearboxAddon/blob/master/gearboxAddonConfig.zip?raw=true verwendet.

**Comment by JohnDeere6920** [comment]
Ich hatte nur dem 7030 von mb3d umbenannt. das habe ich in der gearboxaddon config geändert. Alle neuen Schaltungen baue ich in die fahrzeuge selbst ein
