### ISSUE TITLE
Stufenlos

### ISSUE THREAD

**Issue by Leeon2908** [Mogli12/GearboxAddon#305]
Ich habe die Neueste Version aber iwie checkt mein Game nich das die Drin is somit kann ich kein Vario oder der gleichen auswählen wieso ist das so?
  #245

**Comment by Mogli12** [comment]
Kannst Du mal die log.txt bei Gist hochladen?

**Comment by Leeon2908** [comment]
[log.txt](https://github.com/Mogli12/GearboxAddon/files/1616411/log.txt)

**Comment by debejerry** [comment]
Du musst nicht den gesamten Inhalt (Das ganze GearBoxAddon Repository) aus dem Github herunter laden.
Eigentlich nur die FS17_GearBoxAddon.zip -> [hier](https://github.com/Mogli12/GearboxAddon/blob/master/FS17_GearboxAddon.zip)
und die in den Mod Ordner packen, dann hast du die aktuellste Version.

Im Spiel darfst du dann aber nicht wieder auf die 3.0.0.1 des GearBox Addons "aktualisieren" 😄

**Comment by Mogli12** [comment]
Die Version 3.0.0.1 ist ungefähr vom 19.12.2017
