### ISSUE TITLE
Braking delay when using handthrottle

### ISSUE THREAD

**Issue by ForrestIT** [Mogli12/GearboxAddon#306]
As the title says, i get a delay when braking wile i use the handthrottle. I tested it both on modded and original game vehicles, both had the problem. It's about a 2sec delay.

**Comment by Mogli12** [comment]
HI,
This is intended. Maybe the deceleration is too low With hand throttle or PTO the CVT goes into a throttle controls speed mode. This effect should not happen with an analog throttle.
Regards

**Comment by Frank1974** [comment]
Hello,
i found this  bug to, i think its a MP and CVT ounly thing, in SP i never saw something like this, and also ounly with CVT.
I am using a G 27 with pedals to drive if thats what you mean with analog.

Greets.

**Comment by Mogli12** [comment]
This is not a bug. If PTO is on the brake pedal will first just reduce the target speed.

**Comment by Frank1974** [comment]
Hello,
so its a feature that you can anymore break in MultiPlayer if you use the handthrottel ? Or am i understanding this wrong ?

**Comment by Mogli12** [comment]
I am not in the mood to discuss it in this atmosphere

**Comment by Frank1974** [comment]
I dont want do discusse, that was just a question, i am sorry if you understood that wrong.

**Comment by Frank1974** [comment]
Hello,
i testet build 6, and it still like befor , if you got the Handthrottle on it takes about 2Sec. untill you can brake.

Greets.

**Comment by Mogli12** [comment]
I already wrote before. This is a feature and not a bug. The first second the brake pedal just reduces the target speed. You can press KEY_rshift KEY_leftbracket (Ü on a german keyboard) to increase the acceleration and deceleration via speed limit.

**Comment by Frank1974** [comment]
If am allowed to ask, wich benefit should that give you?

**Comment by Mogli12** [comment]
The braking should be improved with v3.1 build 10. The main problem is/was that the reduction of the gear ratio in the CVT was not fast enough for hard braking.

**Comment by Frank1974** [comment]
I think now its good, even if you got the Handthrottle on in the second you stay on the pedal it brakes.
Great worke Mogli, thanks.
