### ISSUE TITLE
"Hydraulic RPM" in den Globals

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#307]
Hallo, 
wie der Titel schon sagt wäre es toll wenn die "Hydraulic RPM" ihren weg in die Globals finden würden so wie z.B. die "PTO RPM".

Mit freundlichen grüßen, Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

da wird nur die minimale Solldrehzahl genommen. Die kann man in den Settings selber einstellen. 

Viele Grüße

**Comment by Frank1974** [comment]
Hallo Mogli,
ich glaube du verstehst mich da falsch, ich hätte es gerne in den Globals das man es so wie z.B. die PTO RPM dauerhaft abstellen kann da dies meiner Meinung nach recht nervig ist wenn man mit einem normalen Schaltgetriebe fährt.
Denn in dem Moment wo man z.B. den Frontlader hoch macht dreht der Motor hoch also beschleunigt der Traktor, wie bei den PTO RPM auch, bei einem CVT Getriebe lässt sich noch über die Sinnhaftigkeit streiten, aber bei einem (Last)Schaltgetriebe macht dies doch recht wenig sinn oder nicht?
Denn in echt würde der Motor eines Traktor allgemein nur hochdrehen/beschleunigen wenn man selber entweder mit dem Pedal gas gibt oder das Handgas erhöht. 

Ich hoffe du verstehst was ich meine.

Freundliche grüße, Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

dann stelle doch in den Einstellungen die minimale Solldrehzahl auf den niedrigsten Wert, Oder hilft das nicht?

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,

das habe ich gerade eben versucht, doch es geht leider nicht.

Viele grüße, Frank.

**Comment by Mogli12** [comment]
Ich habe jetzt ins Coding geschaut. Ich sehe nicht, dass man die PTO Drehzahl über gearboxMogliGlobals beeinflussen kann.

**Comment by Frank1974** [comment]
Eventuell habe ich das falsch gesagt/gesehen, ich meinte nicht die Globals sondern das was in gearboxMogli.lua über den Globals steht, da kann man den gearboxMogli.ptoRpmFactor auf 0 stellen und den gearboxMogli.ptoRpmFactorEco.
Dann ist es so wie in echt und der Motor des Traktors dreht nicht mehr hoch wenn man die Zapfwelle anschaltet, das gleiche würde ich mir für die HydraulikRPM wünschen.

Viele grüße, Frank.

**Comment by Frank1974** [comment]
Hallo,
damit geht alles so wie ich es gerne hätte, sogar noch viel besser!
Tausend dank für die super Arbeit! 

Viele Grüße,Frank.

**Comment by Mogli12** [comment]
<increaseRpmForPTO type="bool" valuie="false"/> in gearboxMogliConfig.xml under <gearboxMogliGlobals>
