### ISSUE TITLE
3.0.0.1 throwing a nil 

### ISSUE THREAD

**Issue by prjndigo** [Mogli12/GearboxAddon#309]

**Comment by prjndigo** [comment]
gearbox 3.0.0.1 from giants hub is throwing me a nil value for 'i18n', is that something you've encountered or should I track it down in my 700+ mods?

**Comment by Mogli12** [comment]
Please provide the complete log.txt (using Gist). Thanks

**Comment by prjndigo** [comment]
I had another mod crashing the game when I opened the options menu today.
Will get back soon

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by prjndigo** [comment]
<script src="https://gist.github.com/prjndigo/60749f1a2166858f943587f869d1d498.js"></script>

Verified:  with gearboxmod in I get the "i18n" error and a new map will not load, with it out I get a new map creation in normal amount of time (sosnovka)

Yes, it's a huge list of mods (19.3gb)

Win7pro 32gb i7-4930k R9-295x2 Steam version fs17

**Comment by Mogli12** [comment]
Hmm, where is the log.txxt?

**Comment by Mogli12** [comment]
Can you please try v3.1 build 11?
