### ISSUE TITLE
Rueckwaerts- und Vorwaertsgeschwindigkeit

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#31]
Moin, wollte das ewig schon ansprechen, ich fahre meiste manuell (ohne Kupplung) mit Tastatur, was mich manchmal stoert ist, das der Rueckwaertsgang immer dem Vorwaertsgant entspricht (z.B M6=R6, H4=R4, L2=R2 etcetc). Koennte man das so einstellen, dass er immer auf den eingelegten Rueckwaertsgang zurueck greift? Ich haette den R3 und fuer Vorwaerts den M5 eingelegt?

**Comment by Mogli12** [comment]
Hi,
dazu kannst Du bei <gears...> und <ranges...> das Attribut reverseReset="true" setzen. Default ist "false". 
Viele Grüße

**Comment by cabmac** [comment]
arrgh.... ;) , thx....

**Comment by cabmac** [comment]
hmm, habs probiert, das will aber irgendwie nicht, wir sprechen doch von der ...config.xml, oder?
