### ISSUE TITLE
Kirovets K-700A with GearBox

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/GearboxAddon#310]
In last version with this [mod,](http://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=58337&title=fs2017) I have such errors

>Error in updateVehiclePhysics : ../FS17_GearboxAddon/gearboxMogliMotor.lua:1519: attempt to compare number with nil

> Error: Running LUA method 'update'.
../FS17_GearboxAddon/gearboxMogliMotor.lua:1519: attempt to compare number with nil

With version 2.3.0.8 this errors absent

**Comment by Mogli12** [comment]
It should be fixed with v3.1 build 11.

**Comment by Gonimy-Vetrom** [comment]
Thank you. You quickly decided. The tractor has earned!
