### ISSUE TITLE
Block start driving

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Mogli12/GearboxAddon#311]
This is not an GearboxAddon problem but a mod problem. But it happens if I use GearboxAddon. 
Some trucks can not start driving if you turn the steering wheel to the left or to the right. But if the wheels turn straight, then the truck starts driving. Without GearboxAddon, they drive as usual.
What is not properly configured in the truck?

**Comment by Mogli12** [comment]
Do you have an example? It could be that the ackermann steering is not correct.

**Comment by Gonimy-Vetrom** [comment]
https://drive.google.com/open?id=1B1R3Xeel1G4suDclp32rhdU_TbRTku8-

**Comment by Mogli12** [comment]
If you turn the back wheels move to the side. Even with the vanilla gearbox the vehicle just makes 16 km/h in a circle.
