### ISSUE TITLE
Question (Build11)

### ISSUE THREAD

**Issue by alpha117** [Mogli12/GearboxAddon#313]
Not sure if this is an issue, first time I've seen this in the log.  First time I've used the Rathin Island map.

Thanks

I:/FS_Maps/Rathlin_Island///gearboxAddonConfig/gearboxAddonConfig.xml
Found external config in separate mod gearboxAddonConfig.zip
FS17_GearboxAddon: Found 0 configurations
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil
Error load MR vehicle into FS17_GearboxAddon: nil

**Comment by Mogli12** [comment]
Please post the complete log.txt

**Comment by alpha117** [comment]
[log.zip](https://github.com/Mogli12/GearboxAddon/files/1629419/log.zip)

Log as requested

**Comment by Mogli12** [comment]
I propose to use at least the FS17_moreRealistic version from Modhub (https://www.farming-simulator.com/mod.php?mod_id=97077).

**Comment by Mogli12** [comment]
But I guess the error message can be ignored.

**Comment by alpha117** [comment]
Thanks, just updated MR to V1.1.1.2 from GitHub

**Comment by alpha117** [comment]
Log now 'clean'

Great work as always
[log.zip](https://github.com/Mogli12/GearboxAddon/files/1629514/log.zip)
