### ISSUE TITLE
Handgas hat nicht die volle Leistung

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#317]
Hallo,
mit dem build11 hat das Handgas selbst wenn man es auf der höchsten Stellung hat nicht die volle Leistung, die Last des Motors geht nur bis auf ca. 50-70% und die Drehzahl sinkt ab wenn man vom Fußgas auf das Handgas wechselt da der Motor dann nicht mehr genug Leistung hat um die Drehzahl welche man mit dem Fußgas gefahren hat zu halten.
Ich hoffe ich konnte das Problem verständlich machen.

Mit freundlichen grüßen, Frank.

**Comment by Frank1974** [comment]
Mit dem build 13 geht wieder alles so wie es soll.
Danke für die tolle und schnelle Arbeit.

**Comment by Mogli12** [comment]
Gerne
