### ISSUE TITLE
Verbesserungsvorschlag- Härte/ Aggressivität der Wendeschaltung einstellbar machen

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#318]
Hallo,
ich weiß nicht ob dies möglich ist, aber es wäre eine nette Möglichkeit wenn man die Härte/ Aggressivität der Wendeschaltung einstellen könnte (wenn möglich direkt im Spiel).

Hier z.B. sieht man an einem Deutz Agrofarm wie dies in echt geht (die hier genannte "Reaktionsgeschwindigkeit" ist gleichbedeutend mit Härte/Aggressivität): 
https://youtu.be/_-Ou_ANmA-4?t=2m51s 

Leider konnte ich nicht mehr Video Beispiele finden, aber das ist eigentlich an jedem Modernen Traktor so, daher würde dies wenn es möglich wäre recht viel Sinn ergeben mit der Gearbox und wäre eine wunderbare Neureung/Verbesserung

Freundliche Grüße, Frank.

**Comment by Mogli12** [comment]
Hallo Frank,
ich bin mir nicht ganz so sicher, was man hier konkret verstellen soll. Soll die Kupplung schneller oder langsamer greifen? Das gilt aber nicht für stufenlose Getriebe, da hier die Kupplung nur die beiden Zustände "ganz auf" und "ganz zu" kennt. Den Rest übernimmt das stufenlose Getriebe. Hast Du einen konkreten Traktor, bei dem es zu weich oder zu hart ist?
Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo,
so wie es jetzt ist bremst die Wendeschaltung recht harsch ab und kuppelt schnell wieder ein, ich hätte es mir so vorgestellt, man kann es weicher stellen dann bremst der Traktor nicht mehr so rapide ab und die Kupplung greift langsamer. 
(z.B. in 5 Schritten 100% so wie es jetzt ist 80% die Bremse wird nicht mehr ganz durch gedrückt sonder nur noch zu 80%/ 80% der eigentlichen Bremswirkung und die Kupplung braucht 20% länger von 0 auf 100%, 60 % die bremse wird nur noch zu 60% durch gedrückt und die Kupplung braucht 40% länger von 0 auf 100%, das gleiche noch mit 40% und 20%, dann wäre für jede Arbeit etwas dabei. Bei dem CVT Getriebe wäre dies dann entsprechend nur die Bremse / Bremswirkung)

Also konkret geht es aber eher um das Bremsen wie um das ein Kuppeln, wo bei es schön wäre wenn man beides verstellen könnte.

So wie es jetzt ist ist es recht gut für Frontlader arbeiten wenn es eben ist und auf dem normalen Boden (kein foliage layer), aber wenn man z.B. am Vorgewende drehen will auf dem Acker und man über ~3km/h ist bremst der Traktor so schnell ab das die Räder blockieren und er ein paar dm rutscht. (Mit Seasons und Stuffandthings)
Oder wenn man Ballen in der Ballengabel hat und leicht bergab steht während mal die Wendeschaltung betätigt tendieren diese von der Gabel zu rutschen.

Freundliche Grüße, Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

ah ok, verstehe. Ich kann ja mal schauen, ob man die Stärke der Bremse einstellbar machen kann. Nur leider fehlt der Platz dafür im Settings-UI. Da muss ich wohl eine 2. Seite aufmachen.

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,
eventuell könnte man es ja auch über einen Tastendruck machen wie z.B. den Speedlimiter wenn dies Einfacher wäre.

Viele Grüße, Frank.

**Comment by Mogli12** [comment]
![image](https://user-images.githubusercontent.com/8790374/35012224-5d21afac-fb09-11e7-9ea3-7b0a079df517.png)

**Comment by Frank1974** [comment]
Ich hab es kurz getestet und kann nur so viel sagen, ich bin begeistert! 
Die Umsetzung ist genau so wie ich es mir vorgestellt hab.
VIELEN DANK! 
Wie immer ist es wieder eine super Arbeit von dir, vielen dank dafür!

**Comment by cabmac** [comment]
Hi...riiiichtig klasse feature...perfekt!!

**Comment by cabmac** [comment]
Moin, koennte man die Einstellung evtl. auch fuer Schaltgetriebe (wie z.B. CMTs Fendt 900 Favorit) einbauen?

**Comment by Frank1974** [comment]
Hallo,
so wie ich es gesehen habe baut sich diese Funktion überall ein wo eine Wendeschaltung vorhanden ist.
Und der Fendt 900 Favorit (Vario) hat kein Schalt sondern ein CVT Getriebe, die haben allgemein eine Wendeschaltung also sollte sie auch dort vorhanden sein.

Freundliche Grüße, Frank.

**Comment by cabmac** [comment]
jo, der Vario ist klar, der gehr ja auch, aber der Schalter geht bei mir jedenfalls nicht (der mit den 6 Gängen +4 Lastschaltstufen), der hat jedenfalls auch Wendeschaltung

**Comment by Mogli12** [comment]
Hallo,
die Einstellung ändert nichts an der Wendeschaltung selber. Es geht nur darum, wie stark oder sanft das Vehicle gebremst wird, wenn es in die falsche Richtung fährt. Die Physik-Engine von Giants selber ist da ziemlich gandenlos.
Viele Grüße,
Stefan

**Comment by cabmac** [comment]
@Frank1974 ...den 800er Favorit meinte ich natuerlich...uebrigens gehts auch nicht bei dem JCB Radlader...bei allen anderen, bei denen ichs probiert habe, gehts...komisch..

**Comment by cabmac** [comment]
Hallo, nein, ich fahre mit Tastatur und autom. Kupplung... Komisch ist halt, dass das nur bei diesem Fendt  passiert (vielleicht noch bei anderen, ich habe eine Reihe getestet, passiert iMo aber anscheinden nur bei dem Fendt  und dem Radlader)

**Comment by Mogli12** [comment]
Was genau passiert oder passiert nicht?

**Comment by cabmac** [comment]
hallo, wie. gesagt, bei dem 800er von CMT kannst du einstellen was du willst (shuttle factor), es hat keine Auswirkung...

**Comment by Mogli12** [comment]
Nun, was soll denn passieren. Wie bereit oben geschrieben, verändert der ShuttleFactor momentan nur die Bremse.

**Comment by cabmac** [comment]
jo, und wie ich schon sagte, funktioniert es bei diesem besagten Trecker nicht, also besagte Bremswirkung kann man mit dem shuttle factor, wie bei anderen, nicht einstellen... aber egal, bei anderen funktionierts ja...

**Comment by Frank1974** [comment]
Hallo,
eine Kleinigkeit ist mir noch aufgefallen, nach jedem spiel neustart steht die Wendeschaltung wieder auf 50%, also sie speichert die Einstellungen nicht.

Viele Grüße, Frank.

**Comment by Mogli12** [comment]
Ich habe gerade die aktuelle Version überprüft. Die Einstellung zur Wendeschaltung wird gespeichert. Am 7250 TTV merkt man auch einen klaren Unterschied.
