### ISSUE TITLE
Error load MR vehicle into FS17_Gearboxaddon: nil

### ISSUE THREAD

**Issue by TobiAs1995** [Mogli12/GearboxAddon#319]
Hy i found in my log. txt this error 
Error load MR vehicle into FS17_Gearboxaddon: nil.
I have no clue what that is. Can you help me please.  Thanks.

**Comment by Mogli12** [comment]
You are not using the latest version, right? (#313)

**Comment by TobiAs1995** [comment]
I use build 11. Also the latest

**Comment by TobiAs1995** [comment]
Hat sich erledigt wusste nicht das es schon build 13 gibt sry. 😊
