### ISSUE TITLE
Änderungen an der Drehzahlberechnung, und Kupplungs-Bug im manuellen Modus

### ISSUE THREAD

**Issue by modelleicher** [Mogli12/GearboxAddon#32]
Hi,

Seit langem hab ich mal wieder den LS raus gekramt und wollte ne runde spielen. Erst mal das neueste GearboxAddon herunter geladen.. 
Dann aber fest gestellt dass das sich da mit den Sounds was verändert hat.

Habe ja vor langer Zeit mal die gbAddSounds gebastelt ein kleines Script das zusätzliche Run-Sounds ermöglicht, ein Video davon gibts z.b. hier: https://www.youtube.com/watch?v=PDrcaX78YEk

Nur mit der neuen Version ist der normale runsound der durch das Script etwas in Hintergrund gerückt wird gar nicht mehr zu hören wenn man vom Gas geht, in etwa so wie das mein zusätzlicher runsound macht. Entsprechend hören sich dann die umgebauten Mods recht komisch an wenn man vom Gas geht.
Da ich nicht so genau lokalisieren kann was sich verändert hat nur dass es sich anders anhört möchte ich auf diesem Weg mal fragen was sich an der Sound Berechnung in der Zwischenzeit verändert hat.. Oder hat sich gar nix verändert und ich bilde mir das nur ein dass es früher anders war? 

LG

**Comment by modelleicher** [comment]
Ich glaub ich hab raus gefunden was sich verändert hat, manchmal fällt die Drehzahl beim Gangwechsel fast ruckartig ab auf etwa halb.. 
Hab mal ein kurzes Video gemacht: https://www.youtube.com/watch?v=gMF2FZCLf_0&feature=youtu.be

Bug? Oder übersehe ich was wieso es mal schnell abfällt und mal normal..

LG

**Comment by modelleicher** [comment]
Das Problem mit der Kupplung war tatsächlich ein Einstellungsfehler...

Die manchmal rapide fallende Drehzahl bleibt allerdings.

LG

**Comment by Mogli12** [comment]
Hmm, dafür habe ich nur eine Erklärung. Beim Treten der Kupplung kommt die Drehzahl ja nicht mehr vom Rad, sondern wird aus der letzen bekannten Drehzahl berechnet. Dazu habe ich eine geglättete Variable verwendet, die wohl etwas hinterher hinkt. Wenn es stimmt, dann sollte es in der Beta12 weg sein.

**Comment by modelleicher** [comment]
Hi,
Also... Zwischengas funktioniert in der Beta 12 wieder! :) Da war dann in der Tat die geglättete Variable etwas zu langsam um den kurzen Gasstoß korrekt zu berechnen, das klingt logisch.

Allerdings ist mein ursprüngliches Problem mit der schnell abfallenden Drehzahl immer noch vorhanden. Ich hab noch mal ein Video gemacht, dieses mal ist es deutlicher. revDownMs hab ich auf 3000 gesetzt, im Normalfall sollte der Motor also schön langsam von der Drehzahl abfallen.
Was man im Video auch deutlich sieht, dass es im Leerlauf auch ist, also nicht nur beim Gangwechsel. Ebenso tritt es mit getretener oder nicht getretener Kupplung auf. 
Auch im Video zu erkennen dass es nicht immer ist, sondern nur zwei drittel der Fälle in etwa.
Im Video wirkt es als würde ich manchmal ganz langsam vom Gas gehen, manchmal schnell. Ich mache aber immer das selbe, voll rein treten, dann den Fuß vom Gas ziehen.. 

https://www.youtube.com/watch?v=6CBn7dDn20k&feature=youtu.be

Was ebenfalls wichtig sein dürfte, das Problem tritt nur im G27 Modus auf, und auch da nur wenn man mit dem Pedal gas gibt. Selbst wenn ich im G27 Modus bin aber mit Taste "W" gas gebe tritt das ganze nicht auf.
Es hängt also irgendwie mit der Eingabe des Pedals zusammen.


LG

**Comment by modelleicher** [comment]
Hi,

Ich denke mal ich hab die verursachende Zeile bzw. "Gegend" gefunden, Zeile 7419 in der Beta 12
self.currentRpmS  = Utils.clamp( self.lastMotorRpm + 5 * self.lastThrottle * self.tickDt * self.vehicle.mrGbMS.RpmIncFactor, self.minRequiredRpm, self.minRequiredRpm + self.lastThrottle * ( self.maxAllowedRpm - self.minRequiredRpm ) ) 

Das Problem meines Erachtens nach ist das clampen des RPM Bereichs, wenn man mit der analogen Achse spielt dann wird das fast nie von 1 auf 0  also Vollgas auf kein Gas, so schnell kann man das Gaspedal gar nicht los lassen. So wird der RPM Bereich durch das clampen beim loslassen des Gaspedals entsprechend verkleinert dadurch die rapide abfallende Drehzahl.

Hab das jetzt für mich erst mal so geändert:
self.currentRpmS  = Utils.clamp( self.lastMotorRpm + 5 * self.lastThrottle * self.tickDt * self.vehicle.mrGbMS.RpmIncFactor, self.minRequiredRpm, self.maxAllowedRpm ) 
Allerdings hat das zur Folge dass man die Drehzahl nicht mehr dosieren kann sondern im Leerlauf nur noch die "Beschleunigung" der Drehzahl mit dem Pedal regeln kann. Stört mich aber fürs erste nicht fährt sich definitiv schöner als vorher.

Ansonsten müsste man wohl überprüfen ob der Pedalwert gerade ansteigt/gleich bleibt oder abfällt, sodass im Falle des ansteigenden oder gleich bleibenden Pedalwertes die Drehzahl entsprechend geclamped wird und im Falle des fallenden Pedalwertes die Drehzahl nicht auf den Pedalwert geclamped wird.


LG

**Comment by Mogli12** [comment]
Hi,

ich hoffe mal, dass ich das in Beta14 beheben könnte. 

Viele Grüße

**Comment by modelleicher** [comment]
Hi,

Bin leider erst heute zum testen gekommen.
Im Stand funktioniert es nun perfekt dass die Drehzahl langsam runter kommt, allerdings während der Fahrt ist es noch genau so wie vorher, sobald man auskuppelt geht die Drehzahl ruckartig runter.
Wenn man vom Gas geht und dann erst auskuppelt dann geht die Drehzahl gewöhnlich langsam runter, aber wenn man gleichzeitig oder etwas schneller die Kupplung tritt als vom gas geht hat man den rapiden Drehzahl-Abfall.

LG
