### ISSUE TITLE
New Holland T7 Motor

### ISSUE THREAD

**Issue by Fracking** [Mogli12/GearboxAddon#321]
Hallo Stefan,

mir ist aufgefallen, dass der New Holland T7.290 und T7.315 wohl keinen eigenen Motor haben. Im Spiel wird beim Fahren mit dem New Holland der Optum CVX Motor angezeigt.

Hier ein Auszug aus dem [Log](https://gist.github.com/Fracking/8ae4a397148215910aa1c77eb8ba2edb):

FS17_GearboxAddon: Warning! Engine names to not match: "Optum 270 CVX" <> "T7.290"
FS17_GearboxAddon: Warning! Engine names to not match: "Optum 300 CVX" <> "T7.315"

Grüße

Andreas

**Comment by Mogli12** [comment]
Hallo Andreas,

Im Grunde sind NH T7 und Case Optum ja auch baugleich, oder? Beide haben einen FPT Motor.

Viele Grüße,
Stefan

**Comment by Fracking** [comment]
Ob die mehr oder weniger baugleich sind kann ich nicht sagen. Wenn die den gleichen Motor haben, dann ist es egal welchen Motor man nimmt. Ich dachte nur, dass der NH motor "fehlt", da im Log ein Eintrag und im HUD der Optum Motor steht. Wenn das aber so sein soll, dann ist alles OK :).

Andreas
