### ISSUE TITLE
Lua error when activating Tajfun EGV80AHK winch

### ISSUE THREAD

**Issue by Kamuhoro** [Mogli12/GearboxAddon#323]
[log.txt](https://github.com/Mogli12/GearboxAddon/files/1649781/log.txt)
Geladene Mods: Tajfun Winch (https://www.farming-simulator.com/mod.php?lang=de&country=ch&mod_id=78879&title=fs2017), Gearbox Addon [v3.1 Build 15]

Problem: Kurz nach Start der Winde gibts LUA Fehler:
```
Warning (LUA): 'worldDirectionToLocal': Argument 1 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Kingblade/Documents/my games/FarmingSimulator2017/mods/test/FS17_GearboxAddon/gearboxMogliMotor.lua (1432) : worldDirectionToLocal
  =C:/Users/Kingblade/Documents/my games/FarmingSimulator2017/mods/test/FS17Contest_TajfunEGV80AHK_50k/script/logsWinch.lua (387) : updateMotorRpm
  dataS/scripts/vehicles/Vehicle.lua (2642) : update
  dataS/scripts/network/Client.lua (64) : update
  dataS/scripts/BaseMission.lua (1521) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1922) : update
Error: Running LUA method 'update'.
dataS/scripts/utils/Utils.lua(137) : attempt to perform arithmetic on local 'x' (a nil value)
Warning (LUA): 'worldDirectionToLocal': Argument 1 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Kingblade/Documents/my games/FarmingSimulator2017/mods/test/FS17_GearboxAddon/gearboxMogliMotor.lua (1432) : worldDirectionToLocal
  =C:/Users/Kingblade/Documents/my games/FarmingSimulator2017/mods/test/FS17Contest_TajfunEGV80AHK_50k/script/logsWinch.lua (387) : updateMotorRpm
  dataS/scripts/vehicles/Vehicle.lua (2642) : update
  dataS/scripts/network/Client.lua (64) : update
  dataS/scripts/BaseMission.lua (1521) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1922) : update
Error: Running LUA method 'update'.
C:/Users/Kingblade/Documents/my games/FarmingSimulator2017/mods/test/FS17_GearboxAddon/gearboxMogliMotor.lua:1436: attempt to perform arithmetic on local 'vx' (a nil value)
```
Bin leider nicht vom Fach, aber es wird damit zusammenhängen, dass die Winde die Rpm nicht hochdrehen kann.

**Comment by Mogli12** [comment]
Hallo,
ich denke, dass eine Drehzahlanhebung über updateMotorRpm so nicht erlaubt ist. Stattdessen sollte die Winde besser die Spec PowerConsumer verwenden.
Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo,
es ist sehr schade das man die Winde so nicht mit der Gearbox verwenden kann, leider ist das "updateMotorRpm" in dem winden Script fest eingebaut, das heißt ohne Script Erfahrung kann man es nicht ausbauen. 
Und den Modder der Winde kann man auch nicht erreichen so weit ich weiß.
 
Also wäre es sehr sehr schön wenn du vielleicht die Gearbox so anpassen könntest das es wieder funktioniert. 
Mit dem Build 12 ging die Winde noch, ich vermute dass es durch die Änderungen welche zum Build 13 hin vorgenommen wurden nicht mehr Funktioniert.

Viele Grüße, Frank.

**Comment by Frank1974** [comment]
Hallo, 
mit dem Build 16 geht es wieder.
Danke für die tolle und schnelle Arbeit.

Viele Grüße, Frank.
