### ISSUE TITLE
Error: 'tempomatMogli' expected

### ISSUE THREAD

**Issue by Kamuhoro** [Mogli12/GearboxAddon#326]
Getestet im MP, geladene Mods: 
- GearboxAddon (v3.1 build 16)
- Case D-Familie (https://www.modding-welt.com/downloads/entry/2134/)

Beim Kauf vom IHC_CaseIH_DFamilie **mit Allrad** gibt's folgende Fehler:
```
C:/Users/Kingblade/Documents/my games/FarmingSimulator2017/mods/test/IHC_CaseIH_DFamilie/i3d/D_Familie_81_85.i3d (596.91) ms
GearboxAddon: setting current configuration at client
GearboxAddon: setting current configuration at client
ERROR in client coding of mogliBase.lua: unknown type: 132
ERROR in client coding of mogliBase.lua: unknown type: 128
Error: 'tempomatMogli' expected
```
Beim Kauf mit Hinterantrieb gibt's keine Fehler.
An was könnte das liegen? Anbei noch die Log.
[log.txt](https://github.com/Mogli12/GearboxAddon/files/1656926/log.txt)

Vielen Dank schon mal für die Stunden, die du hier reinsteckst.
Gruss, Kamuhoro

**Comment by Mogli12** [comment]
Hallo,

das kling ja wie #299. Da war das Problem auch im MP-Coding von AGO's mod. Das passiert, wenn die Anzahl gelesener Felder im Client nicht ganz genau dieselbe ist wie geschriebene Felder im Server. Dann verschiebt sich die komplette Synchronisation Client/Server um einige Bytes, und jeder Mod, der danach erst dran kommt läuft auf einen Fehler.

Dieses Problem tritt also in der Regel gar nicht in dem Mod auf, der das Problem verursacht.

Viele Grüße,
Stefan
