### ISSUE TITLE
Problem bei Steigung und freeze 

### ISSUE THREAD

**Issue by TobiAs1995** [Mogli12/GearboxAddon#327]
Ich habe bei manchen Traktoren wenn ich egal welche Art von Hänger die Steigung nicht direkt schaffen. Z.b
Fendt 309MR, Eicher 2090T-2100T MR
Und Steyr 760. Beim Eicher waren das nur ein paar Ballen . Beim fendt ein leerer Hänger und. Beim Steyr ein Mini Hänger mit ein bisschen Holz beladen also nur 5 kleine wirklich kleine Stämmchen.

Und das habe ich schon öfter gemerkt wenn ich gearbox in der Kauf obtion off Stelle freeze das Spiel nach dem Kauf des trekers. Ich kann natürlich auf vario Stellen nur da ist der Sound so komisch lang gezogen. 

Und wirklich Respekt zu diesem mod ohne gearbox kann ich im ls nicht mehr. Danke 😊

**Comment by Dbilas-MachVRTTuning** [comment]
Also bei mir ist das nicht aufgetreten! Kein freeze noch das er die Last nicht schafft. Hast du die neueste [gearboxAddon Version](https://github.com/Mogli12/GearboxAddon/blob/master/FS17_GearboxAddon.zip)? 

![fsscreen_2018_02_03_13_31_15](https://user-images.githubusercontent.com/35869903/35767156-f0e0f3a2-08e6-11e8-9eeb-163b4083dfae.png)

**Comment by Mogli12** [comment]
Hallo,
@TobiAs1995 : Vielleicht kannst Du ja einen ScreenShot machen und die log.txt anhängen.
Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo,
es gibt einen Fehler in FS17_FuelUsageDisplay, wenn ein Fahrzeug ohne Getriebe konfiguriert wird. Version 3.1 Build 38 sollte das umgehen.
Viele Grüße
