### ISSUE TITLE
Issue using LS17_Fraese.zip

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/GearboxAddon#328]
Hello tonight:) I'm back to report you when I use this mod fraese and Gearbox latest build 16, it simply stop to work (like stopping the PTO).
If I disable Gearbox to off then Fraese continue to run fine without stop.

here it is:
![fsscreen](https://user-images.githubusercontent.com/25174503/35366039-9bc6fa68-0177-11e8-8c77-cde28fa4698e.png)
Hope it's not too hard to fix...:/
Br Stephan

**Comment by Mogli12** [comment]
I guess that you do not have enough power.

**Comment by Anonymous-any** [comment]
It was that I think 1st and I would like it's so simple, but I put gearbox manually then LL1 the engine cannot go down rpm no message popup low RPM you know and then the issue continue to happen the only way I have is to disable gearbox for this step work :/

**Comment by Anonymous-any** [comment]
It's ok you right !!! there is no stop working the fraeze with a bigger HP tractor, but then the question persist, why a low tractor with a low gearbox LL1 high RPM got no advice for low hp to the PTO for running fine and simply stop the fraeze without saying no alert ... :/ thank for all Br :)

**Comment by Mogli12** [comment]
The tool is stopped by a standard script, maybe PowerConsumer. It is not stopped by gearboxAddon.

**Comment by Anonymous-any** [comment]
Thank you Maestro, I understand there is nothing I can do then, got 2 questions again not linked, you know I ask you more than one time there a bit lock with the max speed depending of vehicles and I see when I change some gearbox to the Shop then the max speed can change !! depending of what gearbox you install in the vehicle by the way can you ask me what "valueName" do the change of this? as example the case tractor who it can go to max 43km/h if I'm good as default, with torqueconverter box it show it can go to 53 km/h max ^^ but of course it can't do it it's just show there somewhere on gearboxconfig.xml file a locked or not "value" as I can infer for all vehicles I hope you know what I mean.

Another question is do you think you can suggest to "Courseplay" to add their option like they do with "DriveControl" but with your Gearbox o_O ? that seem not interesting them... I don't know why your great job is not recognized as it should.

My best regard
