### ISSUE TITLE
GearboxAddon im Fahrzeug verbauen und allgemeine Fragen.

### ISSUE THREAD

**Issue by Dbilas-MachVRTTuning** [Mogli12/GearboxAddon#329]
Ich hatte bei meinem Mach VRT 250 die Warning das der Motorname nicht vorhanden ist und der 7250 TTV genommen wird. Ok die gearboxAddonConfig.xml in den Mod Ordner gepackt und den Motor hinzugefügt damit die Warning weg ist.

`--- Getriebe v3.1 build 16 von Mogli ---
  35 vehicle types enhanced / 0 vehicle types updated
  Register configuration 'GearboxAddon'
Found external config in gearboxAddonConfig.xml
--- Getriebe v3.1 build 16 von Mogli ---`
`FS17_GearboxAddon: Warning! Engine names to not match: "7250 TTV" <> "Mach 250 VRT"`

**Edit: Irgendwie kommt github nicht mit dem Anfang des Codes klar weil es wohl meint das es ein Zitat ist?**
`<engines>		
				<engine name="7210 TTV" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="450" motorTorqueEco="411" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="733" motorTorqueEco="669" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="844" motorTorqueEco="770" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="873" motorTorqueEco="797" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="876" motorTorqueEco="800" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="857" motorTorqueEco="783" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="843" motorTorqueEco="771" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="828" motorTorqueEco="758" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="806" motorTorqueEco="734" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="785" motorTorqueEco="703" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="763" motorTorqueEco="666" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="742" motorTorqueEco="622" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="650" motorTorqueEco="544" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
			
				<engine name="7230 TTV" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="588" motorTorqueEco="537" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="807" motorTorqueEco="737" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="863" motorTorqueEco="788" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="878" motorTorqueEco="802" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="876" motorTorqueEco="800" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="857" motorTorqueEco="783" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="843" motorTorqueEco="771" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="828" motorTorqueEco="758" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="805" motorTorqueEco="734" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="779" motorTorqueEco="703" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="750" motorTorqueEco="666" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="719" motorTorqueEco="622" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="629" motorTorqueEco="544" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
			
				<engine name="7250 TTV" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="510" motorTorqueEco="475" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="830" motorTorqueEco="774" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="956" motorTorqueEco="891" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="989" motorTorqueEco="922" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="997" motorTorqueEco="926" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="987" motorTorqueEco="907" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="980" motorTorqueEco="894" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="972" motorTorqueEco="880" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="946" motorTorqueEco="857" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="919" motorTorqueEco="834" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="891" motorTorqueEco="811" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="863" motorTorqueEco="789" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="755" motorTorqueEco="691" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
				
				<engine name="Mach 210 VRT" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="450" motorTorqueEco="411" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="733" motorTorqueEco="669" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="844" motorTorqueEco="770" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="873" motorTorqueEco="797" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="876" motorTorqueEco="800" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="857" motorTorqueEco="783" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="843" motorTorqueEco="771" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="828" motorTorqueEco="758" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="806" motorTorqueEco="734" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="785" motorTorqueEco="703" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="763" motorTorqueEco="666" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="742" motorTorqueEco="622" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="650" motorTorqueEco="544" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
				
				<engine name="Mach 230 VRT" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="588" motorTorqueEco="537" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="807" motorTorqueEco="737" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="863" motorTorqueEco="788" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="878" motorTorqueEco="802" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="876" motorTorqueEco="800" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="857" motorTorqueEco="783" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="843" motorTorqueEco="771" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="828" motorTorqueEco="758" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="805" motorTorqueEco="734" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="779" motorTorqueEco="703" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="750" motorTorqueEco="666" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="719" motorTorqueEco="622" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="629" motorTorqueEco="544" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
				
				<engine name="Mach 250 VRT" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="510" motorTorqueEco="475" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="830" motorTorqueEco="774" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="956" motorTorqueEco="891" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="989" motorTorqueEco="922" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="997" motorTorqueEco="926" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="987" motorTorqueEco="907" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="980" motorTorqueEco="894" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="972" motorTorqueEco="880" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="946" motorTorqueEco="857" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="919" motorTorqueEco="834" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="891" motorTorqueEco="811" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="863" motorTorqueEco="789" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="755" motorTorqueEco="691" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
			</engines>
		
		</gearboxMogli>	
	</vehicle>`

Mit diesem Code sagt er mir nun aber

`Warning: GearboxAddonConfigurations are not present in 'data/vehicles/steerable/lamborghini/Mach230VRT.xml' anymore! Ignoring this configuration.`

Wie verbaue ich den Mod in meinem Fahrzeug? Der SampleMod2 ist ja für LS15 ?

Ich habe das GetriebeAddon aus dem Modhub aktiviert und wollte nun den blowOffVentilSound testen doch dieser wird nicht abgespielt.

 `<gearboxMogli>
			<blowOffVentilSound volume="4" type="float"/>
                        <blowOffVentilRpmRatio value="0.7" type="float"/>
	</gearboxMogli>`

Ist es möglich die Umschaltung Vorwärts/Rückwärts nicht mehr über die Leertaste zu machen sondern so wie im Spiel original mit W/S? Also Vorwärts/Stop/Rückwärts?

Was etwas kurios ist das ich einige Fahrzeuge habe die ein LüfterSound Script (LuefterSound.lua) verbaut haben und ab dem Update 1.5 funktioniert das nicht mehr (Sound wurde nicht abgespielt) nun mit aktiviertem gearboxAddon  funktioniert diese Funktion kurioser weise wieder. Hast du da vielleicht eine Idee was dein Addon für eine Funktion aktiviert die von 1.4 zu 1.5 geändert wurde? Über Umschalt + Ö kann man das Addon ja ein und ausschalten und sobald es deaktiviert ist macht der Lüfter keinen Mux mehr.

**Edit2:** Ich habe jetzt noch einmal eine frische gearboxAddonConfig.xml genommen und die Änderungen für den Mach 230 VRT vorgenommen. Die Warning `Warning: GearboxAddonConfigurations are not present in 'data/vehicles/steerable/lamborghini/Mach230VRT.xml' anymore! Ignoring this configuration.` tritt nun nicht mehr auf es bleibt nur die `FS17_GearboxAddon: Warning! Engine names to not match: "7250 TTV" <> "Mach 250 VRT"`

Ich habe mal angefangen eine Getriebeabstufung für meinen Mod zu erstellen und das läuft ohne Warning!

`<vehicle>FS17_Lamborgini_Mach_VRT_Tuning
		<mod name="FS17_Lamborgini_Mach_VRT_Tuning">
		<xmlFile name="Mach230VRTTuning.xml"/>
		</mod>
		<gearboxMogli> 
      
      
      <blowOffVentilSound volume="1"/>
	  <hydrostatic profile="Input"/>
      <gears automatic="true">
        <gear speed="8"/> 
        <gear speed="17"/> 
        <gear speed="33"/> 
        <gear speed="67"/>  
      </gears>
			<engines>		
				<engine name="Mach 250 VRT Stage1" idleRpm="1000" ratedRpm="2350">		
					
					<torque rpm="350" motorTorque="450" motorTorqueEco="510" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="733" motorTorqueEco="830" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="844" motorTorqueEco="956" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="873" motorTorqueEco="989" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="883" motorTorqueEco="1000" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="900" motorTorqueEco="1000" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="920" motorTorqueEco="1000" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="945" motorTorqueEco="1000" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="960" motorTorqueEco="1000" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="988" motorTorqueEco="1000" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="996" motorTorqueEco="1000" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="1005" motorTorqueEco="1000" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="1020" motorTorqueEco="1000" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="1050" motorTorqueEco="997" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="1098" motorTorqueEco="987" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="1140" motorTorqueEco="980" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="1180" motorTorqueEco="972" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="1180" motorTorqueEco="946" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="1172" motorTorqueEco="919" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="1159" motorTorqueEco="891" fuelUsageRatio="281.4"/>
					<torque rpm="2250" motorTorque="1150" motorTorqueEco="863" fuelUsageRatio="300.4"/>
					<torque rpm="2300" motorTorque="1145" motorTorqueEco="755" fuelUsageRatio="320.4"/>
					<torque rpm="2350" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
				
				<engine name="Mach 250 VRT Stage2" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="588" motorTorqueEco="537" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="807" motorTorqueEco="737" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="863" motorTorqueEco="788" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="878" motorTorqueEco="802" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="883" motorTorqueEco="806" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="876" motorTorqueEco="800" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="857" motorTorqueEco="783" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="843" motorTorqueEco="771" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="828" motorTorqueEco="758" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="805" motorTorqueEco="734" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="779" motorTorqueEco="703" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="750" motorTorqueEco="666" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="719" motorTorqueEco="622" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="629" motorTorqueEco="544" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
				
				<engine name="Motor swap T9.565 66km/h" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="510" motorTorqueEco="475" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="830" motorTorqueEco="774" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="956" motorTorqueEco="891" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="989" motorTorqueEco="922" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="997" motorTorqueEco="926" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="987" motorTorqueEco="907" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="980" motorTorqueEco="894" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="972" motorTorqueEco="880" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="946" motorTorqueEco="857" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="919" motorTorqueEco="834" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="891" motorTorqueEco="811" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="863" motorTorqueEco="789" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="755" motorTorqueEco="691" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
				<engine name="Motor swap T9.565 85km/h" idleRpm="800" ratedRpm="2100">		
					
					<torque rpm="350" motorTorque="510" motorTorqueEco="475" fuelUsageRatio="230.9"/>
					<torque rpm="700" motorTorque="830" motorTorqueEco="774" fuelUsageRatio="212.6"/>
					<torque rpm="900" motorTorque="956" motorTorqueEco="891" fuelUsageRatio="205.8"/>
					<torque rpm="1000" motorTorque="989" motorTorqueEco="922" fuelUsageRatio="203.4"/>
					<torque rpm="1100" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.6"/>
					<torque rpm="1200" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.5"/>
					<torque rpm="1300" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200"/>
					<torque rpm="1400" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="200.2"/>
					<torque rpm="1500" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="201.2"/>
					<torque rpm="1600" motorTorque="1000" motorTorqueEco="932" fuelUsageRatio="202.9"/>
					<torque rpm="1700" motorTorque="997" motorTorqueEco="926" fuelUsageRatio="205.3"/>
					<torque rpm="1800" motorTorque="987" motorTorqueEco="907" fuelUsageRatio="208.4"/>
					<torque rpm="1850" motorTorque="980" motorTorqueEco="894" fuelUsageRatio="210.3"/>
					<torque rpm="1900" motorTorque="972" motorTorqueEco="880" fuelUsageRatio="212.3"/>
					<torque rpm="1950" motorTorque="946" motorTorqueEco="857" fuelUsageRatio="214.5"/>
					<torque rpm="2000" motorTorque="919" motorTorqueEco="834" fuelUsageRatio="216.9"/>
					<torque rpm="2050" motorTorque="891" motorTorqueEco="811" fuelUsageRatio="219.5"/>
					<torque rpm="2100" motorTorque="863" motorTorqueEco="789" fuelUsageRatio="222.2"/>
					<torque rpm="2150" motorTorque="755" motorTorqueEco="691" fuelUsageRatio="261.5"/>
					<torque rpm="2200" motorTorque="0" motorTorqueEco="0" fuelUsageRatio="444.4"/>
				</engine>
			</engines>
		
		</gearboxMogli>	
	</vehicle>`

**Comment by Dbilas-MachVRTTuning** [comment]
Wenn man den Mach auslagert also nicht mit dem Deutz zusammen dann ist die Warning `FS17_GearboxAddon: Warning! Engine names to not match: "7250 TTV" <> "Mach 250 VRT"` weg.

Die sonstigen, obigen Problemchen sind auch alle beseitigt. Respect für das was du da mit dem gearboxAddon leistest! 
[gearboxAddonConfig.zip](https://github.com/Mogli12/GearboxAddon/files/1687114/gearboxAddonConfig.zip)

**Comment by Mogli12** [comment]
Hallo,
ersetze man `<engine name=...` durch `<engine displayName=...`.
Viele Grüße,
Stefan

**Comment by Dbilas-MachVRTTuning** [comment]
Ja so ist die Warning dann weg mit dem Eintrag.
