### ISSUE TITLE
Abstellen der autom. autoHold?

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#33]
ist das moeglich irgendwo die autmatische Aktivierung der autohold beim verlassen des Fzg. abzustellen? ("manuelle" Tastaturschaltung, ohne Kupplung). In Kombination z.B. mit dem manualattaching bissl nervig, beim Einsteigen die autohold immer wieder rauszunehmen. Koennte man das irgendwie manuell machen, d.h. wenn ich in neutral aussteige, die Kiste auch in neutral bleibt? Soll der Trecker nicht wegrollen beim verlassen, muesste man halt manuell den autohold oder Handbremse bedienen

**Comment by Mogli12** [comment]
Mit manueller Kupplung sollte jetzt kein AutoHold mehr kommen.

**Comment by cabmac** [comment]
schoene Umgewoehung jetzt....ist nicht mal eben zum anderen Fzg tabben ohne die Handbremse zu ziehen... ;)...thx
