### ISSUE TITLE
option for gear change sound

### ISSUE THREAD

**Issue by ForrestIT** [Mogli12/GearboxAddon#331]
Hi! I don't know if this is something that could be implemented but it would be cool if inside the Gearbox mod there would be support for a gearchange sound if the modder had one. Simply something inline with writing down the searchpath and sound duration in the vehicle XML or something and every time gear was switched that sound would play. You can probably make it even more complex if you wanted too but just a minor sugestion.

**Comment by Mogli12** [comment]
Good idea

**Comment by Mogli12** [comment]
Please try version v3.1 build 17.

**Comment by Frank1974** [comment]
Hello,
is it intended that you also hear the Sound when changing a gear in G27 mod / with a real H shifter?

**Comment by Mogli12** [comment]
Yes, but I can disable it.

**Comment by Frank1974** [comment]
I think it would be better to disable it in G27 mode, because the Shifter makes its owne "sound" if you shift it so its wired to hear a 2nd one ingame.

**Comment by Mogli12** [comment]
Ok, I disabled the sound in G27 mode.

**Comment by Frank1974** [comment]
Hello, 
mabye it also would be a nice addition if you add an option to globaly turn the shiftsound off in the gearboxMogliGlobals.

Regards, Frank.

**Comment by Mogli12** [comment]
Options shiftingBaseVolume and handbrakeBaseVolume, type is "float" and default value is 1.
