### ISSUE TITLE
Automatisches Starten via Wendeschaltung mit manueller Kupplung 

### ISSUE THREAD

**Issue by Einfllslos** [Mogli12/GearboxAddon#335]
Ich hab ein kleines Problem mit dem autoStartStop="true" und manueller Kupplung. 
Bei moderneren Traktoren braucht man ja nur noch die Wendeschaltung zu betätigen und der Traktor fährt los ohne dass man die Kupplung nur berührt hat, aber das klappt bei mir im Spiel nicht so ganz.
Wenn ich mit manueller Kupplung spiele, kann ich nicht anfahren ohne die Kupplung zu treten, obwohl autoStartStop auf true steht. 
Stehen bleiben geht allerdings ohne Betätigung der Kupplung. 
Liegt der Fehler vielleicht an mir?

**Comment by Mogli12** [comment]
Hallo,
ich glaube, dass Du hier die automatische Kupplung eingeschaltet lassen musst. Die manuelle Kupplung funktioniert dann trotzdem.
Viele Grüße,
Stefan

**Comment by Einfllslos** [comment]
Ja, aber dann kann ich den Traktor nicht mehr abwürgen.

**Comment by Mogli12** [comment]
Verstehe ich nicht.

**Comment by Einfllslos** [comment]
Sobald ich auf automatische Kupplung umstelle, lässt sich der Traktor nicht mehr abwürgen.  Die Kupplung überhitzt zwar, aber der Traktor geht nicht aus.

**Comment by Frank1974** [comment]
Hallo,
ich denke das Problem besteht darin, in echt hat eine Wendeschaltung normalerweise 3 Stellungen, Vorwärts, Rückwärts und Neutral (Bzw. Vorwärts, Rückwärts und nichts), da in der Gearbox aber nur vorwärts und Rückwärts vorhanden ist muss man im G27 Modus den Gang raus nehmen da man sonst nicht in Neutral kommt, in echt hingegen kann man den Gang drin lassen und über die Wendeschaltung in Neutral gehen, und somit auch wieder über die Wendeschaltung den Gang einlegen und über die Wendeschaltung anfahren.

Dies kann man aber leider nicht ohne die entsprechende Hardware also einen Schalter mit 3 Stellungen  (V N R) umsetzen.

Viele Grüße Frank

**Comment by Mogli12** [comment]
Hallo,

der Schalter mit den 3 Positionen fehlt. Aber die Funktion wäre eventuell schon da. Es gibt die manuelle Kupplung sowohl als Achse fürs Kupplungspedal, als auch als einzelner Knopf (gearboxMogliCLUTCH_3 / KEY_period / "."). Ich habe aber keine Ahnung, ob das jetzt beim G27 bereits irgendwie hilft. Vermutlich gibt es da keine Blinkerhebel, oder?

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo,
ja, leider gibt es keinen Blinkerhebel oder sonst etwas an dem G27 mit dem man eine Wendeschaltung "nachstellen" könnte.

Grüße Frank.

**Comment by Einfllslos** [comment]
Also seit dem neusten Update funktioniert es bei mir so wie ich es gerne hätte.
Ich kann mit manueller Kupplung den Gang auch so einlegen ohne die Kupplung zu treten, aber fährt er jetzt sehr "aggressiv" an.
Das Einstellen der Empfindlichkeit bringt es nicht wirklich. 
Manchmal dauert es einfach geschätzt 5 Sekunden bis er dann mit einem großen Ruck anfährt und den Traktor teilweise abwürgt. 
Vorher wo man die Empfindlichkeit noch nicht einstellen konnte ging alles super.
Hab schon alles ausprobiert mal auf 30% mal auf 100% es hilft alles nicht so wirklich.

**Comment by Mogli12** [comment]
Welche manuelle Kupplung verwendest Du? Die Achse gearboxMogliCLUTCH oder den Knopf gearboxMogliCLUTCH_3? Die Empfindlichkeit gilt nur für den Knopf.

**Comment by Mogli12** [comment]
Tritt das Problem noch in der aktuellsten Version auf?

**Comment by Einfllslos** [comment]
Ne jetzt funktioniert es schon ziemlich gut. Daumen hoch ;)
