### ISSUE TITLE
G 27 Gang Hebel Teilweise ohne Funktion 

### ISSUE THREAD

**Issue by Martin1500** [Mogli12/GearboxAddon#336]
Servus Ich hebe seit der Neusten Version ein Problem mit der Gangschaltung und zwar erkennt GB diesen Hebel aber der  Gang Bleib auf 1 egal in Welcher Stellung der Ganghebel ist.  Irgend eine Idee ?  Mit der Einstellung G 27 + Tastatur hab ich schon probiert  ohne Erfolg. Gruß Martin

**Comment by Mogli12** [comment]
Hallo,
da habe ich von Build 17 nach 18 wohl etwas zu viel gelöscht. 
Vielen Dank!

**Comment by Martin1500** [comment]
Immer gerne Stefan 
Gruß Martin

**Comment by Mogli12** [comment]
Ja, funktioniert es denn jetzt wieder?

**Comment by Martin1500** [comment]
Ja  Allerdings hört man kein Schaltvorgang wie beim tasten schalten

**Comment by Mogli12** [comment]
Hmm, das war ein Wunsch in #331. Ich hielt die Begründung für sinnvoll.

**Comment by Martin1500** [comment]
Alles klar wusste  ich nicht.  Thema kann geschlossen werden.
Gruß Martin
