### ISSUE TITLE
With hand throttle at 100% or an implement attached and turned on, braking is super powerful.

### ISSUE THREAD

**Issue by TheCadde** [Mogli12/GearboxAddon#34]
Version 1.4 beta12.

If you put an implement on (such as a mower) and turn it on. Touching the brake pedal ever so slightly gives the tractor (John Deere 8530FH, CVT) super powerful brakes. Going from 50 km/h to 0 in a split second.
Same goes for hand throttle at 100% (don't know about < 100%, never tested that) on CVT transmission tractors.

Doesn't do it when you press the brake hard, but just tapping the brake though makes it stop like hitting a wall.

**Comment by Mogli12** [comment]
Hi,
For a long time I was not able to reproduce this issue. But finally... Please check the latest version.
Thanks!
