### ISSUE TITLE
John Deer Europa by Ago Bremen

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/GearboxAddon#343]
Hi Meine Problem ist das die Johnnys von Ago am stand immer wegrollen! Weist du vieleicht eine Lösung??
LG

**Comment by Mogli12** [comment]
Irgendwie geht AutoStartStop nicht an. Aber benutz doch einfach die Handbremse vom GearboxAddon oder den Handbrems-Mod von BPG.

**Comment by cabmac** [comment]
so sollte das bei allen sein... ;)

**Comment by Paul2510** [comment]
Ok Danke :-))!!
