### ISSUE TITLE
Reale Handbremse

### ISSUE THREAD

**Issue by DonPaul75** [Mogli12/GearboxAddon#345]
Hallo.
Erst mall vielen dank für das tolle mod. Fahre mit dem Thrustmaster T500+TH9 setup und es macht richtig spass auch mit der moglichkeit das mann sellber eigene getriebe/motor arten machen kann, also noch mall, tolles job. 
Habe dennoch eine frage, ob es moglich ist, das die automatische bremse ausschaltbar ist.
Der realität nah, gang rein, motor aus, wagen stehet. Gang raus und keine handbremse, kuplung nicht gedruckt... wagen rollt.
Ich wollte es gerne wie im realem lieben, also wenn mann wagen abstellt, endwieder handbremse oder gang rein sonst rollt der wagen weg.

Ist ewentuell diese moglichkeit schon drin (habe bis jetz nicht gefunden koennen) bitte ich um die zeillen, wo ich den kod anpassen kann.

Danke erst und viel spass bei weiter eintwicklung. (entschuldigung für mein Deutch ist aber nicht meine muttersprache)

**Comment by Mogli12** [comment]
Hallo,
nein, das ist momentan leider nicht möglich. Aber es wäre nicht so schwer einzufügen. Ich denke mal drüber nach.
Viele Grüße, Stefan

P.S.: We can continue in English if this would be better. So there is no global switch to turn off auto start stop but I could add it.

**Comment by DonPaul75** [comment]
Danke für die schnelle antwort. Hoffentlich klappt das. Ich bin aus der Slowakei und Deutch ist in ordnung, ich verstehe und spreche viel besser als ich schreiben kann. Habe halt nie, die sprache offiziel gelernt. Konnte mann im gegenzug was leisten, bin ich gerne dabei. Kann zwar nicht direkt programieren aber zum beispiel, researchern über motorleistung kurven genutze getriebe... kann ich versuchen.

**Comment by Mogli12** [comment]
Hello,

There is not a new option to turn off auto start stop. Please create a file gearboxAddonConfig.xml in your mods folder, if not already present:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<noAutoStartStop type="bool" value="true"/>
	</gearboxMogliGlobals>
</vehicles>
```
