### ISSUE TITLE
Shift sound in die Globals

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#347]
Hallo,
wäre es eine Möglichkeit den "Shift-Sound" in die Globals aufzunehmen ?

Ich denke nicht jedem gefällt der Shift-Sound.
Mich z.B. stört er da ich mit einem Lenkrad und und Joystick spiele und dieses selbst schon Geräusche macht wenn ich auf die Knöpfe drücke also es komisch ist weil man es dann doppelt hört.

Viele grüße Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

ich habe in Build 36 einen neuen Parameter eingebaut. Meine gearboxAddonConfig.xml sieht so aus:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<noAutoStartStop type="bool" value="true"/>
		<shiftingHandbrakeVol type="float" value="0"/>
	</gearboxMogliGlobals>
</vehicles>
```

Leider kann man den Klang der Lastschaltstufen nur ganz aus-/einschalten, da hier die Klang des Blinkerhelbels wiederverwendet wird.

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,
danke für das schnelle einbauen.
Ist es beabsichtigt das die "Handbrems-Sounds" dadurch auch beeinflusst werden?

Viele grüße Frank.

**Comment by Mogli12** [comment]
Hallo Frank,
ja, ich dachte, dass ich mit einem globalen Einstellung alle Klänge anpasse. Aber für die Handbremse kannst Du auch FS17_handbrake von Blacky_BPG verwenden.
Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Frank,

es gibt jetzt 2 Parameter:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<handbrakeBaseVolume type="float" value="1"/>
		<shiftingBaseVolume  type="float" value="1"/>
	</gearboxMogliGlobals>
</vehicles>
```

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan, 
jetzt passt alles, vielen dank.
