### ISSUE TITLE
Help with gearbox for Xerion 5000

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/GearboxAddon#348]
I wanted to add a gearbox (ZF Eccom 4.5, hydro-mechanical CVT) to the Claas Xerion 5000, but I do not really know how, because what I currently have is suitable only for driving the tractor, not for work in the field or transport. My current configuration:
```xml
<vehicle>Claas Xerion 4000, 4500, 5000
		<mod name="FS17_ClaasXerion5000">
			<xmlFile name="ClaasXerion4000.xml"/>
		</mod>
		
		<gearboxMogli maxForwardSpeed="60" maxBackwardSpeed="40">
			<hydrostatic profile="Input"/>
			
			<engines>
				<engine name="Xerion 4000" idleRpm="800" ratedRpm="1900" >
					<!-- 1700: 435(435) | 1900: 421(421) | 1300..1300: 2100(2100) | 85 | 0,5 | 99 | 3 | 1900 | 1270: 238 -->
					<torque rpm="350" motorTorque="1108" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="1660" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="1898" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="1987" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2050" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2087" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2100" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2053" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="1986" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="1901" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="1797" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="1683" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="1621" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="1556" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1355" fuelUsageRatio="359,8"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
				<engine name="Xerion 4500" idleRpm="800" ratedRpm="1900" >
					<!-- 1700: 490(490) | 1900: 476(476) | 1300..1300: 2300(2300) | 85 | 0,5 | 99 | 3 | 1900 | 1270: 238 -->
					<torque rpm="350" motorTorque="1213" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="1818" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="2079" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="2176" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2245" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2286" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2300" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2257" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="2197" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="2119" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="2024" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="1898" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="1830" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="1759" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1533" fuelUsageRatio="358,4"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
				<engine name="Xerion 5000" idleRpm="800" ratedRpm="1900" >
					<!-- 1700: 530(530) | 1900: 517(517) | 1300..1300: 2450(2450) | 85 | 0,5 | 99 | 3 | 1900 | 1270: 238 -->
					<torque rpm="350" motorTorque="1292" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="1937" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="2215" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="2318" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2391" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2435" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2450" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2409" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="2352" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="2279" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="2189" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="2055" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="1984" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="1911" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1665" fuelUsageRatio="356,9"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
				<engine name="Xerion 5000 Chip" idleRpm="800" ratedRpm="1900" >
					<!-- 1700: 586(586) | 1900: 572(572) | 1300..1300: 2640(2640) | 85 | 0,5 | 99 | 3 | 1900 | 1270: 238 -->
					<torque rpm="350" motorTorque="1392" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="2087" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="2387" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="2497" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2577" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2624" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2640" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2606" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="2558" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="2496" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="2421" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="2272" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="2194" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="2114" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1842" fuelUsageRatio="356,7"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
			</engines>		
		</gearboxMogli>
	</vehicle>
```

**Comment by Dbilas-MachVRTTuning** [comment]
Hello

These are my entries directly in the Mod.xml for the Claas Xerion.

> <transmissions>
			<transmission name="Xerion FPS" maxBackwardSpeed="23" maxForwardSpeed="64" ptoRpm="1803" ptoRpmEco="1592">
				<gears shiftTimeMs="0" clutchRatio="1" defaultGear="10" automatic="true" >		
					<gear speed="2.07" forwardOnly="true"/>
					<gear speed="2.99" forwardOnly="true"/>
					<gear speed="3.6"  />
					<gear speed="4.33" />
					<gear speed="5.2"  forwardOnly="true"/>
					<gear speed="7.52" forwardOnly="true"/>
					<gear speed="9.04" />
					<gear speed="10.9" />
					<gear speed="15.7" forwardOnly="true"/>
					<gear speed="18.9" forwardOnly="true"/>
					<gear speed="22.7" />
					<gear speed="27.3" forwardOnly="true"/>
					<gear speed="32.8" forwardOnly="true"/>
					<gear speed="39.4" forwardOnly="true"/>
					<gear speed="47.4" forwardOnly="true"/>
					<gear speed="57"   forwardOnly="true"/>	
					<gear speed="67"   forwardOnly="true"/>						
				</gears>
			</transmission>	
			<transmission name="Xerion CVX" maxBackwardSpeed="23" maxForwardSpeed="64" ptoRpm="1803" ptoRpmEco="1592">
				<hydrostatic profile="Input" correctGearSpeed="true"/>
				<gears automatic="true">	
					<gear speed="6.25" atRpm="1750"/>
					<gear speed="12.5" atRpm="1750"/>
					<gear speed="25"   atRpm="1750"/>
					<gear speed="50"   atRpm="1750"/>
					<gear speed="60"   atRpm="1750"/>
				</gears>
				<reverse ratio="1"/>
			</transmission>	
		</transmissions>	
>

with your engine setup

><transmissions>
			<transmission name="Xerion FPS" maxBackwardSpeed="23" maxForwardSpeed="64" ptoRpm="1803" ptoRpmEco="1592">
				<gears shiftTimeMs="0" clutchRatio="1" defaultGear="10" automatic="true" >		
					<gear speed="2.07" forwardOnly="true"/>
					<gear speed="2.99" forwardOnly="true"/>
					<gear speed="3.6"  />
					<gear speed="4.33" />
					<gear speed="5.2"  forwardOnly="true"/>
					<gear speed="7.52" forwardOnly="true"/>
					<gear speed="9.04" />
					<gear speed="10.9" />
					<gear speed="15.7" forwardOnly="true"/>
					<gear speed="18.9" forwardOnly="true"/>
					<gear speed="22.7" />
					<gear speed="27.3" forwardOnly="true"/>
					<gear speed="32.8" forwardOnly="true"/>
					<gear speed="39.4" forwardOnly="true"/>
					<gear speed="47.4" forwardOnly="true"/>
					<gear speed="57"   forwardOnly="true"/>	
					<gear speed="67"   forwardOnly="true"/>						
				</gears>
			</transmission>	
			<transmission name="Xerion CVX" maxBackwardSpeed="23" maxForwardSpeed="64" ptoRpm="1803" ptoRpmEco="1592">
				<hydrostatic profile="Input" correctGearSpeed="true"/>
				<gears automatic="true">	
					<gear speed="6.25" atRpm="1750"/>
					<gear speed="12.5" atRpm="1750"/>
					<gear speed="25"   atRpm="1750"/>
					<gear speed="50"   atRpm="1750"/>
					<gear speed="60"   atRpm="1750"/>
				</gears>
				<reverse ratio="1"/>
			</transmission>	
		</transmissions>	
                       <engines>
				<engine name="Xerion 4000" idleRpm="800" ratedRpm="1900" >
					
					<torque rpm="350" motorTorque="1108" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="1660" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="1898" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="1987" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2050" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2087" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2100" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2053" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="1986" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="1901" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="1797" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="1683" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="1621" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="1556" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1355" fuelUsageRatio="359,8"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
				<engine name="Xerion 4500" idleRpm="800" ratedRpm="1900" >
					
					<torque rpm="350" motorTorque="1213" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="1818" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="2079" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="2176" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2245" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2286" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2300" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2257" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="2197" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="2119" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="2024" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="1898" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="1830" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="1759" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1533" fuelUsageRatio="358,4"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
				<engine name="Xerion 5000" idleRpm="800" ratedRpm="1900" >
					
					<torque rpm="350" motorTorque="1292" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="1937" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="2215" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="2318" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2391" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2435" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2450" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2409" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="2352" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="2279" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="2189" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="2055" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="1984" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="1911" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1665" fuelUsageRatio="356,9"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
				<engine name="Xerion 5000 Chip" idleRpm="800" ratedRpm="1900" >
					
					<torque rpm="350" motorTorque="1392" fuelUsageRatio="278,5"/>
					<torque rpm="700" motorTorque="2087" fuelUsageRatio="253,6"/>
					<torque rpm="900" motorTorque="2387" fuelUsageRatio="244,6"/>
					<torque rpm="1000" motorTorque="2497" fuelUsageRatio="241,5"/>
					<torque rpm="1100" motorTorque="2577" fuelUsageRatio="239,4"/>
					<torque rpm="1200" motorTorque="2624" fuelUsageRatio="238,2"/>
					<torque rpm="1300" motorTorque="2640" fuelUsageRatio="238,1"/>
					<torque rpm="1400" motorTorque="2606" fuelUsageRatio="239,1"/>
					<torque rpm="1500" motorTorque="2558" fuelUsageRatio="241,5"/>
					<torque rpm="1600" motorTorque="2496" fuelUsageRatio="245,3"/>
					<torque rpm="1700" motorTorque="2421" fuelUsageRatio="250,3"/>
					<torque rpm="1800" motorTorque="2272" fuelUsageRatio="256,7"/>
					<torque rpm="1850" motorTorque="2194" fuelUsageRatio="260,4"/>
					<torque rpm="1900" motorTorque="2114" fuelUsageRatio="264,4"/>
					<torque rpm="1950" motorTorque="1842" fuelUsageRatio="356,7"/>
					<torque rpm="2000" motorTorque="0" fuelUsageRatio="0"/>
				</engine>
			</engines>

>

**Comment by KITT3000** [comment]
@Dbilas-MachVRTTuning 👍
