### ISSUE TITLE
Gearbox Auswahl kommt nicht hoch bei HKL TGS

### ISSUE THREAD

**Issue by reinholdmaehler** [Mogli12/GearboxAddon#349]
Hallo Stefan,

ich beisse mir an diesem Mod die Zaehne aus:
https://www.modhoster.de/download/5DxqW

Ich habe in meiner Externen Datei dies hier erstellt, und die Auswahl fuer die Gearbox kommt nie hoch. Auch nicht fuer die Default Einstellungen von dir. 

Kannst du mal schauen was da falsch ist / was ich falsch mache?

Gruss
Reinhold

[tgs hkl fuer gearboxaddon.txt](https://github.com/Mogli12/GearboxAddon/files/1778930/tgs.hkl.fuer.gearboxaddon.txt)
[log.txt](https://github.com/Mogli12/GearboxAddon/files/1778931/log.txt)
[tgs hkl aus savegame vehicle_xml.txt](https://github.com/Mogli12/GearboxAddon/files/1778932/tgs.hkl.aus.savegame.vehicle_xml.txt)

**Comment by Dbilas-MachVRTTuning** [comment]
In der GearboxAddonConfig sind doch schon einige Einträge für Mods. Daran kann man doch erkennen wie es aufgebaut sein muss!


![gear](https://user-images.githubusercontent.com/35869903/36951000-8589dcb6-1ffe-11e8-8d8b-b6491b0aa323.JPG)


Ist ja so schon mal nicht richtig. Ein Beispiel aus der Config

![gear](https://user-images.githubusercontent.com/35869903/36951006-a1e2c5a8-1ffe-11e8-9c91-24e1cfe2f1d9.JPG)

**Comment by Mogli12** [comment]
Hallo,
der Mod geht nicht, da hier die vehicleTypes konfigurierbar sind.
Viele Grüße

**Comment by Dbilas-MachVRTTuning** [comment]
Geht nicht gibt es nicht ;-)
![fsscreen_2018_03_05_17_16_58](https://user-images.githubusercontent.com/35869903/36986206-9749b4a8-2099-11e8-8d83-7f438e4535ee.png)
![fsscreen_2018_03_05_17_15_10](https://user-images.githubusercontent.com/35869903/36986208-9771acba-2099-11e8-97d2-6631a501085c.png)

**Comment by Dbilas-MachVRTTuning** [comment]
Hier ist die etwas bearbeitete Mod.xml mit verbautem Gearboxaddon und auch eingestellter Leistung da er in der 620PS Stufe über 1000PS hatte.
[manTGS68HKL.zip](https://github.com/Mogli12/GearboxAddon/files/1782478/manTGS68HKL.zip)

**Comment by Mogli12** [comment]
Ohne Korrektur am Mod geht es nicht.

**Comment by reinholdmaehler** [comment]
@Dbilas-MachVRTTuning : Vielen Dank, das macht mich Gluecklich!
@Mogli12 Vielen Dank dass du diese Mod mit uns teilst und auch immer mit Rat und Tat da bist! Kudos!
