### ISSUE TITLE
torque valor in motorneu file

### ISSUE THREAD

**Issue by astro80** [Mogli12/GearboxAddon#35]
Hi Mogli12, thank you for this wonderful mod!!! i have a question about the values that i have to set in the motorneu file to have the correct torque valor. were i can find this values and were i have to put this in the motorneu file? 

Thank you for your help.

**Comment by astro80** [comment]
no one can help me?

**Comment by Mogli12** [comment]
Hi,
I do not really understand what you are looking for. The documentation may not be up to date, But may you take a look at https://github.com/Mogli12/GearboxAddon/blob/master/Documentation/Description.pdf chapter "Own configurations"
BR

**Comment by astro80** [comment]
i`m looking for this  <torque rpm="900" motorTorque="440"/>, how i can set motortorque valor.

**Comment by Mogli12** [comment]
Hi, 
Did you already look into [zzzMrGearboxAddonConfig.xml](http://github.com/Mogli12/GearboxAddon/blob/master/zzzMrGearboxAddon/zzzMrGearboxAddonConfig.xml) There are several examples.
If you want to know how find out the correct torque values for a specific tractor I propose to look at [tractordata.com](http://www.tractordata.com/).
I use my Excel [MotorNeu.xlsx](https://github.com/Mogli12/GearboxAddon/blob/master/Documents/MotorNeu.xlsx?raw=true) to calculate a nice torque curve from the maximum torque, maximum power and rated power values. It is not very well documented. But maybe you can use it.
BR
