### ISSUE TITLE
gearboxMogli.lua:2723: attempt to index a nil value / tempomatMogli.lua:460: attempt to index field 'cruiseControl' (a nil value)

### ISSUE THREAD

**Issue by RuppMartin001** [Mogli12/GearboxAddon#351]
Hallo Stefan,

ich habe versucht in einem bestehenden Spiel Gearbox hinzuzufügen (Version 3.0.3.8 laut moddesc).
Leider startet das Spiel dann nicht.

Im Log steht:

C:/Daten/Landwirtschafts Simulator 17/Installed Mods/FS17_woodCrusher/FS17_woodCrusher.i3d (216.40) ms

Error 3 loading gearboxMogliLoader: C:/Daten/Landwirtschafts Simulator 17/Installed Mods/FS17_GearboxAddon_3_3_1_0_b38/gearboxMogli.lua:2723: attempt to index a nil value
Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Daten/Landwirtschafts Simulator 17/Installed Mods/FS17_GearboxAddon_3_3_1_0_b38

/tempomatMogli.lua:460: attempt to index field 'cruiseControl' (a nil value)

Möglichweise passen die anderne Mods nicht.
Ich vermute, dass es an FS17_ponyRideable oder  F17_woodcrusher liegt.
Die Mods haben motoren und sind doch eigentlich keine Fahrzeuge.

Ich habe bei einem Teil der Fahrzeuge dies zu der Konfiguration hinzugefügt:

<configuration name="GearboxAddon" id="1" />
...
<boughtConfiguration name="GearboxAddon" id="1" />

Beim Pony und bein Woodcrusher aber nicht.

An was könnte es liegen?

Die vehicles.xml findest du hier:
[vehicles.zip](https://github.com/Mogli12/GearboxAddon/files/1800995/vehicles.zip)

Viele Grüße

Martin

**Comment by Mogli12** [comment]
Hallo Martin,

irgendein Fahrzeug hat ein Getriebe aber nicht die Spec. Drivable?

Viele Grüße,
Stefan

**Comment by RuppMartin001** [comment]
Hallo Stefan,

 

vielen Dank!

 

Das Problem lag am „Holzbrecher“ (F17_woodCrusher.zip).

http://www.farming-simulator.com/mod.php?lang=de <http://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=101761&title=fs2017> &country=de&mod_id=101761&title=fs2017

 

Als ich den Mod vom Spiel abgewählt hatte, konnte ich das Spiel mit dem GearboxAddon-Mod öffnen.

 

Bei dem “Holzbrecher“- Mod gibt es eine Definition von Übersetzungen.

Drivable macht aber keinen Sinn,  da es ja ein Anhänger mit Holzhäcksler ist.

 

Viele Grüße

 

Martin

 

 

 

Von: Stefan Biedenstein [mailto:notifications@github.com] 
Gesendet: Montag, 12. März 2018 08:12
An: Mogli12/GearboxAddon
Cc: RuppMartin001; Author
Betreff: Re: [Mogli12/GearboxAddon] gearboxMogli.lua:2723: attempt to index a nil value / tempomatMogli.lua:460: attempt to index field 'cruiseControl' (a nil value) (#351)

 

Hallo Martin,

irgendein Fahrzeug hat ein Getriebe aber nicht die Spec. Drivable?

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
The problem should not occur anymore with version 3.0.4.0.

**Comment by RuppMartin001** [comment]
Thank you very much!

The errors appear no longer!
