### ISSUE TITLE
Error reading network ID: 311 (gearboxMogli)

### ISSUE THREAD

**Issue by MetalGovy** [Mogli12/GearboxAddon#353]
Hello,

With certain tractor mods i do get the following errors:

`Error sending network ID: nil (gearboxMogli)
------------------------------------------------------------------------
2: D:/home/sid_325208/farmingSim_2017/profile/mods/FS17_GearboxAddon/mogliBase.lua (994): writeStream

Is this a issue with the mod itself or the gearbox ?

**Comment by Mogli12** [comment]
Hi,

The problem is a mismatch in the number of bytes read and written on client and server. Such error affects all other mods that try to sync in the same time frame. 

I am pretty sure rhat the problem is in the other mod.

Regards, Stefan

**Comment by MetalGovy** [comment]
Hello,

I gotta ask the modder of the tractor mod then to sort it?
Or is this something that cannot be fixed ?
