### ISSUE TITLE
Turning the tool on registers as giving gas

### ISSUE THREAD

**Issue by madarHR** [Mogli12/GearboxAddon#354]
First of all i didint have this problem until the release of the ROPA DLC

I didint change a single setting, only updated a game and installed ropa dlc

The issue is following, it only happens if i use a tractor with manual gears so automatics (CVT) are fine

If i turn on a tool (mower, manure spreader etc.) it automatically starts accelerating my tractor too full possible speed without touching any other button so it basicly registers as accelerate

However in input binding the B button (used for turning on a tool) isnt binded anywhere else specialy not for gearbox commands so i cant figure this one out.

As for the settings per tractor it doesnt matter which i use 
If its manual gear changing of any kind problem persists

**Comment by KITT3000** [comment]
Show your LOG via www.pastebin.com

**Comment by Mogli12** [comment]
Hi,

Please check #307. You can disable increasing idle RPM for PTO with global parameter increaseRpmForPTO.

Regards,
Stefan

**Comment by madarHR** [comment]
I resolved the issue by downloading a mod from github and reinstalling it 
Thanks for help!
