### ISSUE TITLE
Soundfehler Valtra

### ISSUE THREAD

**Issue by AchhammerSebastian** [Mogli12/GearboxAddon#355]
Servus,

mir ist bei der aktuellen GitHubVersion bei den Valtra aufgefallen, dass ein "rattern" zu hören ist, wenn man im Direct-Getriebe den "Gang" voll ausfährt.
War bei der Aktuellen Modhub-Version nicht so.
Ist das gewollt?

**Comment by Mogli12** [comment]
Ja, oberhalb der Maximaldrehzahl wird ein Rattern eingespielt.

**Comment by Frank1974** [comment]
Hallo,
wenn ich fragen darf, welchen sinn hat dieses rattern, und was genau soll es nachstellen? Also ist das etwas was es auch in echt gibt? (nur hört man es in echt kaum?) oder einfach nur so eine Sache im Spiel damit man z.B. nicht dauernd vollgas fährt?, oder ist einfach nur der Ton falsch ausgewählt?

Es ist nicht böse gemeint, aber mir ist der Sinn von dieser Sache/diesem Sound noch nicht so ganz schlüssig.

Viele grüße, Frank.

**Comment by Mogli12** [comment]
Hallo,

das Rattern habe ich eingebaut um das Vibirieren des Motors beim Überschreiten der Maximaldrehzahl zu simulieren. Stört es zu sehr? Man kann es über den globalen Parameter engineHumVolume anpassen. Default ist 1:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<engineHumVolume type="float" value="1"/>
	</gearboxMogliGlobals>
</vehicles>
```
Viele Grüße

**Comment by Frank1974** [comment]
Hallo,
ja, ich finde es stört schon recht arg, zu dem macht es für mich nach wie vor keinen richtigen sinn, da man dies auch nicht in echt hat bei einem Traktor, zumindest nicht in diesem ausmaß.

Vielleicht sollte man es als Standardeinstellung auf 0 haben oder im GUI einstellbar machen da ich auch schon von anderen gehört hab die es stört aber nicht wissen bzw, nicht fähig sind es auszuschalten.

Grüße Frank.
