### ISSUE TITLE
G27 Modus Erhöhte Drehzahl im Stand wenn der Gang eingelegt wird / Anfahrschwäche

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#356]
Hallo,
vorab, vielen dank dass du hier deine Zeit für uns opferst und vielen dank dass du die Gearbox machst, sie ist nach wie vor seit dem LS15 mein Lieblingsmod und wird es auch wahrscheinlich für immer bleiben. Nur habe ich noch zwei drei Kleinigkeiten die mich stören, ich hoffe du kannst diese noch beheben.

Mit der b40 geht das Standgas sobald man den Gang im G27 Modus einlegt mit gedrückter Kupplung etwas nach oben wenn man den Gang raus nimmt oder anfährt geht es wieder auf normalem niveau.

Zu dem ist mir aufgefallen dass die Kupplung irgendwie etwas an Drehmoment verschluckt, z.B. wenn man mit viel last oder am Berg anfährt geht die Drehzahl runter und die Last hoch aber man kommt nicht los, dann ist die Drehzahl z.B. auf 1300U/min aber wenn man die Kupplung dann schnell komplett los lässt macht man einen Satz und hat sofort genug Leistung und ist sofort bei der Maximaldrehzahl, es ist also so als würde beim einkuppeln  irgendeine art Bremse gedrückt sein weswegen man nicht los kommt und sobald man ganz auskuppelt diese Bremse los lässt und man wieder genug Leistung hat.

Auch aufgefallen ist das man mit manchen Traktoren kaum bis gar nicht anfahren kann ohne gas zu geben, in echt hingegen hat ein Traktor Motor im Standgas so viel Drehmoment das man ihn immer ohne gas anfährt selbst mit Last oder am Berg. Und wenn man mal nicht loskommt reicht es schon minimal gas zu geben ( 1000-1100U/min) und man hat genug Drehmoment zum anfahren, wo man hingegen mit der Gearbox immer gleich vollgas geben muss und dennoch kaum Drehmoment hat.

Ist das mit der Kupplung eine Sache die sich beheben lässt oder stößt die Giants engine da einfach an ihre Grenzen?
Viele grüße und vielen dank -Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

das mit der Kupplung ist eher eine Simulation einer höheren Motordrehzahl im GearboxAddon. Auf Anfrage anderer User ist das Standgas momentan auf maximal 50% begrenzt. Liegt es eventuell daran?

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,

was genau wird damit Simuliert wenn ich fragen darf?

Ich denke nicht das es daran liegen sollte, da man dies meist nur bei dem ersten anfahren hat nach dem die "Handbremse" von Giants bzw. das aus der Physik nehmen von einem Fahrzeug stattgefunden hat.

Was ich vergessen habe zu sagen ist, erst nach dem v3.1 build 13 ist das mit dem Anfahren so, davor hatte man wesentlich mehr Kraft im Standgas und allgemein hatte man an den meisten Fahrzeugen ca. 10% mehr Leistung.

Viele Grüße, Frank.

**Comment by Frank1974** [comment]
Hallo,
was mir demletzt auch noch aufgefallen ist, ich habe test weise dem New-Holland 8340 die Motor Konfiguration des Same Fortis 190 gegeben, da dieser sich sehr gut anfahren lässt, aber nachdem der Motor im Ford war ist dies nicht mehr so.

Z.b. am Same Fortis kann man im 9km/h Gang die Kupplung "schnalzen" lassen ohne dass der Motor zu weit runter "gedrückt" wird/bzw. der Motor kommt sehr schnell wieder auf die Normalestanndgas Drehzahl, wenn man dies am Ford welcher den selben "Motor" hat macht geht die Drehzahl bis auf 500U/min und kommt nur sehr langsam wieder auf das Normalestandgas-Niveau.

**Comment by Frank1974** [comment]
Hallo,
ich habe gerade eben noch einmal mit dem Ford und Same getestet, und dabei ist mir aufgefallen, 
das der Ford wenn man ohne gas zu geben die Kupplung im ca. 9km/h Gang "schnalzen" lässt ca. 17ps vorhanden sind wenn er von 500 auf 800U/min "hochdreht" wenn man das gleiche aber bei dem Same macht sind es 37Ps, die Solldrehzahl ist in etwa gleich.

**Comment by Frank1974** [comment]
Hallo Stefan,
jetzt kann man wieder wie früher anfahren, vielen dank für den Fix.

Jedoch ist es leider immer noch so dass die die Drehzahl leicht erhöht ist wenn man im G27 Modus die Kupplung voll gedrückt und einen Gang eingelegt hat.

Viele Grüße und vielen Dank -Frank

**Comment by Mogli12** [comment]
Hallo Frank,

bei welchem Traktor geht die Drehzahl denn hoch? Wie hoch ist sie bei Neutral, mit Kupplung 0% und mit Kupplung 100%?

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo, 
mit dem B50 passt wieder alles, vielen dank dafür.
