### ISSUE TITLE
Gearbox Problem mit Schalten G27

### ISSUE THREAD

**Issue by BrunnerFabian** [Mogli12/GearboxAddon#357]
Ich habe ein Problem und zwar kann ich bei meinem G27 und dem Gearbox Addon den Rückwärtsgang nicht einlegen da kommt dann immer das kein Gang eingelegt ist

**Comment by Mogli12** [comment]
Hallo,
beim Wendegetriebe gibt es keinen echten Rückwärtsgang. Die Gänge 1-6 funktionieren dann sowohl vorwärts als auch rückwärts.
Viele Grüße

**Comment by BrunnerFabian** [comment]
Okay danke
