### ISSUE TITLE
Double clutch shift up

### ISSUE THREAD

**Issue by P-KK** [Mogli12/GearboxAddon#358]
Hi Mogli

First of all big thank you for this fantastic mod.

I have question about double clutch.
I am using mod with configuration present below. Zetor 12045
Shifting down of the gears works nicely. Shift out, rew, shift in. Cool stuff!

The issue is that this "middle rew" is applied also when shifting up and when changing direction fwd and backward. I do not think this should happen it those 2 cases.
Would you be able to advice what is wrong with configuration and how to fix it?

```
<gearboxMogli autoStartStop="false" speedLimiter="false">
			<blowOffVentilSound volume="0"/>
		
			<gears shiftTimeMs="2000" defaultGear="2"  doubleClutch="true">
				<gear speed="7.16"/>
				<gear speed="11.28"/>
				<gear speed="17.93"/>
				<gear speed="27.05"/>
			</gears>
			
			<ranges shiftTimeMs="0" clutchRatio="1" speedMatching="false" defaultGear="2" shiftNoThrottle="true">
				<range ratio="0.74627" name="T"/>
				<range ratio="1" name=""/>
			</ranges>
			
			<ranges shiftTimeMs="2000">
				<range ratio="0.34314" name="L" forwardOnly="true"/>
				<range ratio="0.46863" name="R" reverseOnly="true"/>
				<range ratio="1"       name="H" forwardOnly="true"/>
			</ranges>

</gearboxMogli>
```

**Comment by Mogli12** [comment]
Hi,

I think you should add `doubleClutch="false"` to the 2nd `<ranges ...` tag. If this attribute is not specified the system will calculate a default based on `shiftTimeMs`.

Regards,
Mogli

**Comment by P-KK** [comment]
Hi,
thx for quick response.
Adding `doubleClutch="false"` on 2nd range did not do anything. Setting `shiftTimeMs="400"` removes double clutch from range selector. One issue solved. No rew on changing direction fwd and backward :)

However, on the main gears, where I wan to have double clutch, it is still using "midle rew" while shifting up. 
I believe it should be using it only on shifting down.

Current configuration is following.
```
<gears shiftTimeMs="2000" defaultGear="2"  doubleClutch="true">
				<gear speed="7.16"/>
				<gear speed="11.28"/>
				<gear speed="17.93"/>
				<gear speed="27.05"/>
			</gears>
			
			<ranges shiftTimeMs="0" clutchRatio="1" speedMatching="false" defaultGear="2" shiftNoThrottle="true">
				<range ratio="0.74627" name="T"/>
				<range ratio="1" name=""/>
			</ranges>
			
			<ranges shiftTimeMs="400" doubleClutch="false" >
				<range ratio="0.34314" name="L" forwardOnly="true"/>
				<range ratio="0.46863" name="R" reverseOnly="true"/>
				<range ratio="1"       name="H" forwardOnly="true"/>
			</ranges>
```

**Comment by Mogli12** [comment]
The GearboxAddon uses double clutch if the shifting time is long enough. I disabled this now for up shifting. Can you try the latest version 3.0 build 45?

**Comment by P-KK** [comment]
Hi
I have just tested FS17_GearboxAddon.zip v3.1 build 45 (master branch)  and unfortunately, I see no change. Double clutch is used in shifting up and down.
I have tested with and without MR too but all the same.

Is there 3.0.45 somewhere or you meant this one?

**Comment by Mogli12** [comment]
Did you try [v3.1 build 78](https://github.com/Mogli12/GearboxAddon/blob/master/FS17_GearboxAddon.zip?raw=true)?

**Comment by P-KK** [comment]
Hi, I have just tested 3.1 79
I think it works now ! :) 
Thanks for looking into it.

What I have just realized is that is not doing the engine rev on downshift automatically now.
I have to do it with my accelerator key W. So if W is pressed at time double clutch action is happening, engine revs, if not it it doesn't.

It is really realistic now.
I am quite happy with this solution. You can close the issue.

**Comment by Mogli12** [comment]
Thanks for the great feedback!
