### ISSUE TITLE
1.3.2.5

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#36]
hi, der Hanomag 55d funktioniert auf mit dieser Version nicht mehr, k. A. warum

**Comment by cabmac** [comment]
nun ok mit 1.3.2.6.

**Comment by Mogli12** [comment]
Beim Drehmomentwandler kam es wohl irgendwie zu großen Drehzahlschwankungen und dann wurde der Motor abgewürgt.

**Comment by cabmac** [comment]
ok, das einzige ist nun, wenn man von A1 bis A3 durchschaltet, bleibt auf einmal der Sound weg...

**Comment by cabmac** [comment]
hmm, kann das sein, dass der cruise control nicht mehr bei eingeschalteter Zapfwelle reagiert?
