### ISSUE TITLE
Changing gearbox mode on one machine changes it on all others

### ISSUE THREAD

**Issue by Ciggy001** [Mogli12/GearboxAddon#361]
I have downloaded the latest version from the modhub and when I change the gearbox mode (simple to cvt for example) it will change the mode on all other vehicles. I have tried the game with all other mods disabled and it still does it.

Thanks

**Comment by Mogli12** [comment]
Yes, this is correct. The key short cut to change between simplified and normal gearbox mode switches all vehicles but on the current client in MP.

Additionally, there is a setting in the settings screen (page 1, column 2, row 2) to switch the automatic mode.
