### ISSUE TITLE
some lag rollback by hydraulic cylinder action in multiplayer

### ISSUE THREAD

**Issue by denut** [Mogli12/GearboxAddon#362]
hello

i tested last version b42 and the problem is the same on all 3.x bxx version

sample : i fold or unfold a tool like cultivator or mower or use the front loader and my tractor have lag rollback, in inside view it's like you head go to the windows and return back to the seat place verry fast and so long the hydraulic action move,  at the same time the other players on the server have the same problem

i see that some front loader are not recognized as "hydraulic tools" then the motor rpm speed don't follow the action and there is no lag rollback

thank's for you mod with g27 it's working great hope you find the solution to this bug

**Comment by Mogli12** [comment]
Does it occur in build 45?

**Comment by denut** [comment]
will test it maybe next week
