### ISSUE TITLE
can't shift gears unless clutch is fully depressed

### ISSUE THREAD

**Issue by Dudejo** [Mogli12/GearboxAddon#365]
I moved into version 3.0.4.5, out from 3.0.0.1

I don't know if this is intentional but I can't shift gears without having to lift the clutch entirely. Using the clutchratio flag had no effect unless I set it to 1.

Also, the clutch sometimes gets stuck at 0% no matter what I do.

**Comment by Mogli12** [comment]
Hi,

You use the manual clutch and not the automatic clutch. In this case the clutch percent have to be less or equal 10%. Does this explain the problem? The vehicle seems to be the standard NH 8340. Do you have problems to switch from H L 1 to H L 2 or from H L 1 to H H 1?

Regards,
Stefan

P.S.: My email should be visible here: https://github.com/Mogli12. But the current config for the H488 already makes 40.28 km/h @ 2500 RPM

**Comment by Dudejo** [comment]
It happens when I try to shift within the H-L range.

And like I said, in the previous 3.0.0.1 build (unlike the 3.0.4.5 build in this screenshot), I didn't need to lift the clutch all the way to 10% before being allowed to shift. The 57% seen in the screenshot would have allowed me to shift gears.

I'm wondering if this is intentional.

**Comment by Mogli12** [comment]
Yes, this was changed in build 28. (https://github.com/Mogli12/GearboxAddon/commit/072b110241431de38cd40f1c540e745c62ebcd7f#diff-702a9d353eba882c75f77a7c23d5b61bL5540). Is it a big problem? I though that you should really press the clutch completely for being able to shift gears.

**Comment by Dudejo** [comment]
so if I understand that bit of code properly, the clutch percent can still be adjusted to a different value?

In that case, the flag seems to be broken. For example, the Case IH 1455 has a flag for **minClutchRatio="0.6"**. In spite of that, the driver must still lift the clutch completely. This happens even in the 3.0.0.1 build that I've been mostly using.

Aside from that, I have never seen any evidence in real life that a clutch must be fully depressed. Not in my manual car (I would argue it's close to the standard 70% your mod has featured up until now). At worst, in a demonstration video I've seen on YouTube, the driver claims he is only lifting depressing at 50%.

https://youtu.be/8kBwYIlS-08?t=4m31s

This starts at the time stamp where the driver claims the clutching pressure he's roughly using.

In fact, I have even heard claims (that was during the era of Gran Turismo 5) that when a clutch needs to be depressed fully to shift at all, it's a sign that you need to bring your car to the closest mechanic ASAP.

**Comment by Mogli12** [comment]
Maybe we have to distinguish between the movement of the clutch pedal and clutch percent. But I think you can already manage this in the game settings.

**Comment by Dudejo** [comment]
If it matters, I've been using keyboard + mouse.

Also, I haven't been able to find anything that relates to clutches beyond the Auto Clutch setting, which was inside the mod's configuration screens (the ones that are accessed in-game).

Personally, I've been interpreting the in-game clutch percent display as :
0% = clutch pedal is pushed all the way back
100% = clutch pedal is not pushed at all

With that, it made sense to be able to shift gears without needing to wait for 0%. The previous behavior was compatible with my instinctive behavior when driving manual transmissions.

**Comment by Mogli12** [comment]
The clutch percentage has the following meaning:
Let T be the motor RPM without transmission and W the RPM of transmission input. Then the real motor RPM M for clutch percentage c is `M = (1-c) * T + c * W`.

So c = 0% means that the motor RPM is only controlled by the throttle. c = 100% means that the motor RPM is only controlled by the wheel RPM.

**Comment by Dudejo** [comment]
So if I understand correctly, a clutch status of 0% simply means that the engine isn't connected to the drive wheels at all.

With that perspective in mind, assuming such a feature does not exist, I see a need for the ability to adjust the clutch disengagement speed when using the digital clutch key.

At the moment, it takes a full second to completely disengage the clutch, which is unrealistically slow. An experienced driver, such as the trucker in the previously posted video, can fully shift gears within a second, let alone simply disengage the clutch.

**Comment by Dudejo** [comment]
I've been trying it out with the H 488 (noticed the new gear sets, nice!) and so far, it works great.

Is there a flag inside the addonconfig XML to set the speed in advance?
