### ISSUE TITLE
"Ausrollen"

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#367]
moin, weiss nicht, wie ichs gut beschreiben soll, Agos Traktoren (ohne MR) rollen aus ohne dass die Bremse auf einmal greift. Alle anderen, die ich so getestet habe (egal ob CVT oder Schaltgetriebe) bremsen automatisch nach ca. 2 sek, wenn ich z.B bei 1-2 km/h einfach kein Gas gebe.

**Comment by Mogli12** [comment]
Hallo,
AGO hat AutoStartStop ausgeschaltet.
Viele Grüße

**Comment by cabmac** [comment]
ok, wo oder wie kann man das bei anderen Fzg abstellen? hat er das ueber einen eigenen Script gemacht oder geht das ueber die gearbox?

**Comment by Mogli12** [comment]
In gearboxAddonConfig.xml:
'''xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<noAutoStartStop type="bool" value="true"/>
	</gearboxMogliGlobals>
</vehicles>
'''

**Comment by Dudejo** [comment]
do I need to make a second ZIP file to put my modified file in?
