### ISSUE TITLE
1.3.2.7

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#37]
hi, k.A warum von jetzt auf gleich das Getriebe-grinding bein keinem einzigen Traktor mehr geht, glaube fast, dass das nicht an gearbox liegt, da ich aeltere Versionen ausprobiert habe. Einer eine Idee? mit "manueller" Kupplung geht es noch

**Comment by cabmac** [comment]
absoluto nichts zu machen, auf einmal ist der grinding und "not too fast" weg. Es geht einwandfrei nur noch, wenn man selber kuppelt (tastatur). Ansonsten hoert man keinen sound mehr...ich habs probiert mit vorherigen Versionen und ohne mods (ausser gearbox.zip und config.xml)..ich kanns mir einfach nicht erklaeren

**Comment by Mogli12** [comment]
Hi, leider kann ich mir der Beschreibung nichts anfangen. Ein paar Screen Shots und Schritte, wie man das reproduzieren kann, wären schon hilfreich. Und lade doch bitte die log.txt im Gist hoch. Danke!

**Comment by cabmac** [comment]
[log.txt](https://github.com/Mogli12/GearboxAddon/files/323021/log.txt)

http://www.imagehub.de/thumb-i4028b3a7q2.png
http://www.imagehub.de/thumb-i4029bzgif9.png

hi, es geht nur darum, dass man den grinding sound nicht mehr hoert bei manueller Tastaturschaltung und automatischer Kupplung, vom wechseln auf vor-und rueckwaerts

**Comment by Mogli12** [comment]
Danke, aber kannst Du die Bilder etwas größer machen und dabei das Gearbox-Hud einblenden?

**Comment by cabmac** [comment]
auf einmal kann ich in voller Fahrt ebenfalls von rueck- auf vorwaerts gehen, ohne anzuhalten...komisch, entweder hab ich irgendwas ungewollt verstellt oder es ist sonstwas passiert...

http://www.imagehub.de/display-i4030bz8nmj.html
http://www.imagehub.de/display-i4031bdcgls.html

**Comment by Mogli12** [comment]
Du hast die automatische Kupplung an. Der Traktor kuppelt automatisch aus, wenn Du in voller Fahrt den Rückwärtsgang rein haust. Da der alte Deutz kein autoStartStop hat, wird nicht einmal automatisch gebremst.
Den Grinding Sound und die Meldung gibt es nur noch mit manueller Kupplung.

**Comment by cabmac** [comment]
tut mir leid, noch einmal aufmachen zu muessen...das ist eben genau das, was er nicht mehr macht, auskuppeln und grinding sound, das ging vorher definitiv und nun kuppelt er weder aus (d.h. er geht aus voller fahrt in den rueckwaertsgang ueber ohne grinding). ich spiele uebringens IMMER mit autom. Kupplung.
Das Oberseltsame ist, dass ich eine aeltere Version reinhaue (z.b. 1.3.2.4) und es einfach nicht mehr geht, und es ging IMMER -> siehe video 0:31

https://www.youtube.com/watch?v=g6qCBZyddpE
