### ISSUE TITLE
gear lockout flags don't work properly when engaging reverse

### ISSUE THREAD

**Issue by Dudejo** [Mogli12/GearboxAddon#370]
This (at the bottom) is my gear configuration.

I have maxRange="1" set on my R gear.

When I an in L range, nothing goes wrong. However, when I am in H range, the gear does not automatically switch to R. It will be in whatever other gear I happen to be in, even if it has the forwardOnly flag.

			<gears defaultGear="1" shiftTimeMs="800">
				<gear speed="33.64" maxRange="1" forwardOnly="true" name="L"/>
				<gear speed="47.90" maxRange="1" reverseOnly="true" name="R"/>
				<gear speed="47.90" forwardOnly="true" name="1"/>
				<gear speed="67.68" forwardOnly="true" name="2"/>
				<gear speed="93.40" forwardOnly="true" name="3"/>
				<gear speed="127.95" forwardOnly="true" name="4"/>
			</gears>
			
			<ranges defaultRange="3" shiftTimeMs="800">
				<range name="L" ratio="0.2632"/>
				<range name="H" forwardOnly="true" ratio="1"/>
			</ranges>

**Comment by Mogli12** [comment]
Hi,

I propose to remove the maxRange="1" line for gear with name "R". There are too many constraints.

Regards, Stefen

**Comment by Dudejo** [comment]
That fixed it. Thanks!
