### ISSUE TITLE
Differenziale verhalten sich komisch

### ISSUE THREAD

**Issue by reinholdmaehler** [Mogli12/GearboxAddon#371]
Hallo Stefan,

seit dem du die "Raeder Pfluegen" eingebaut hast, scheinen die Differentialsperren (zumindest bei mir) sehr viel Schlupf zuzulassen. Z.T. fahren sich meine Traktoren bei leichter Verschraenkung der Achsen zueinander fest, einmal hat es in der Halle beim ueberrollen des abgekippten Getreide zum Stillstand gefuehrt.

Log ist sauber. Ich fahre mit MR. Aufgefallen z.B. beim Modhub AXION800 und auch Standard TGS LKW im Spiel.

Gruss
Reinhold

**Comment by Mogli12** [comment]
Hallo Reinhold,

es könnte daran gelegen haben, dass der Standard-Pflug Haufen zerstört. Das sollte mit v3.1 build 52 behoben sein.

Viele Grüße,
Stefan

**Comment by reinholdmaehler** [comment]
Danke, laeuft jetzt echt gut. Top!
