### ISSUE TITLE
Chaff being destroyed by wheelslip

### ISSUE THREAD

**Issue by Spartan086** [Mogli12/GearboxAddon#375]
I put 600k chaff in a silage bunker then decided to compact it. Got to the top, then I got stuck and there was hole straight down to the ground in the chaff. After some more getting stuck I realized it was a new gearbox feature. The wheelspinning behaves as if I had a plough in the silage bunker. The wheelslipping is destroying all the chaff all the way down to the ground so the vehicle gets stuck and the silage pit/clamp gets emptied.

You say it should not work outside of field? But it still destroy "windrows"/"heaps" I think?

(With build 48)

**Comment by Mogli12** [comment]
Hi,
I will try to fix it. In the meantime you can disable this function per vehicle on settings page 2.
Regards

**Comment by punchi1** [comment]
i turned it off on page 2, "durchdrehende räder" still destroys chaff

**Comment by Mogli12** [comment]
If you really disabled this feature then the chaff is not destroyed by gearbox addon.

**Comment by Mogli12** [comment]
I tested v3.1 build 49 in West Coast. It does not destroy chaff.
