### ISSUE TITLE
Vorderradantrieb kein hinterrad?

### ISSUE THREAD

**Issue by TobiAs1995** [Mogli12/GearboxAddon#376]
Nur mal so am rande ne frage. Hab ja gesehen das es in den Settings vom gearbox einen reiter für antrieb gibt. Aber wieso eigentlich vorderrad. Bei atos ok. Aber bei traktoren kenne ich kein vorderrad antrieb. Allrad ist natürlich top. Ist mir halt schon läger auf gefallen. Und wieso zeigt mir gearbox nicht mehr an wie viel ps ich verbrauche fand es toll so. Aber ist nicht schlimm. Wollte es nur mal erwähnen.

Trotzdem super mod. spiele gar nicht mehr ohne gearbox

**Comment by Mogli12** [comment]
Hallo,

die PS-Anzeige kann man im Settings-UI wieder einschalten. Den Text habe ich korrigiert.

Vielen Dank.
Stefan
