### ISSUE TITLE
Build 54 : gears grind when shifting into Neutral without lifting the clutch

### ISSUE THREAD

**Issue by Dudejo** [Mogli12/GearboxAddon#377]
This happens even with a transmission that's not Double Clutch.

https://cdn.discordapp.com/attachments/412348931473801217/446989873879056386/neutralgrind.png

			<transmission name="RT-13 3.73 axle"  autoStartStop="false" rpmInSpeedHud="true" minHudRpm="0" maxHudRpm="4000" speedLimiter="false" maxRpmThrottle="0.1" fuelPerDistanceMinSpeed="10">
			<gears axleSpeed="3.73" tireWidth="315" tireRatio="80" rimDiameter="22.5" defaultGear="3" automatic="false" doubleClutch="true" shiftTimeMs="1000" autoShiftPriority="1">
				<gear name="Lo" forwardOnly="true" inverseRatio="12.31" maxRange="1">
					<extraName range1="1" range2="1" name="Lo"/>
					<extraName range1="2" range2="1" name="!!do not use!! (L)"/>
					<extraName range1="2" range2="2" name="!!do not use!! (H)"/>
				</gear>
				<gear name="R"  reverseOnly="true" inverseRatio="13.22">
					<extraName range1="1" range2="1" name="R1"/>
					<extraName range1="2" range2="1" name="R2"/>
					<extraName range1="2" range2="2" name="R3"/>
				</gear>
				<gear name="1"  forwardOnly="true" inverseRatio="8.59">
					<extraName range1="1" range2="1" name="1"/>
					<extraName range1="2" range2="1" name="5 L"/>
					<extraName range1="2" range2="2" name="5 H"/>
				</gear>
				<gear name="2"  forwardOnly="true" inverseRatio="6.11">
					<extraName range1="1" range2="1" name="2"/>
					<extraName range1="2" range2="1" name="6 L"/>
					<extraName range1="2" range2="2" name="6 H"/>
				</gear>
				<gear name="3"  forwardOnly="true" inverseRatio="4.43">
					<extraName range1="1" range2="1" name="3"/>
					<extraName range1="2" range2="1" name="7 L"/>
					<extraName range1="2" range2="2" name="7 H"/>
				</gear>
				<gear name="4"  forwardOnly="true" inverseRatio="3.23">
					<extraName range1="1" range2="1" name="4"/>
					<extraName range1="2" range2="1" name="8 L"/>
					<extraName range1="2" range2="2" name="8 H"/>
				</gear>
			</gears>
			
			<ranges doubleClutch="true" shiftTimeMs="1200" defaultRange="1" automatic="false" autoShiftPriority="3">
				<range name="Lo" ratio="1"    upGearOffset="-3" maxRange2="1"/>
				<range name="Hi" ratio="4.43" downGearOffset="3" minGear="2"/>
			</ranges>
			
			<ranges shiftTimeMs="300" clutchRatio="1" shiftNoThrottle="true" defaultRange="1" automatic="false" autoShiftPriority="1">
				<range name="L" ratio="0.8547"/>
				<range name="H" ratio="1.0000" minRange="2"/>
			</ranges>
			</transmission>

**Comment by Mogli12** [comment]
Hi,

Build 54 plays the sound but still goes into neutral. I thought that this would be good if you go into neutral w/o pressing the clutch.

If you add `manualClutchNeutral="true"` to the `transmission` tag than this will be disabled. But then you can switch from neutral into gear w/o pressing the clutch as well.

Regards,
Stefan

**Comment by Dudejo** [comment]
While I unfortunately can't speak 100% for non-synchronized manual transmissions, my regular car with a synchronized shifter most definitely does not grind when I pull it out of gear without lifting the clutch.

The effect should be conditional with the Double Clutch flag.

**Comment by Dudejo** [comment]
So I've spoken with a couple of truck drivers.

The vehicles were Freightliners. A Business Class M2 and a Cascadia. I didn't think of asking what transmission the M2 was equipped with (brochures suggest a possible synchronized shifter) but the Cascadia has the non-synchronized RT-13 by Eaton Fuller.

Both drivers confidently claim that they can simply pull the shift lever out of gear and the gears don't grind. The driver for the Cascadia explained that by simply releasing the throttle, the unloaded gears are loose enough to allow pulling the lever out with no effort or particular technique.

**Comment by Mogli12** [comment]
Please check v3.1 build 56.

**Comment by Dudejo** [comment]
So far so good!
