### ISSUE TITLE
GearboxAddon AutoHold Function Quit

### ISSUE THREAD

**Issue by archedian** [Mogli12/GearboxAddon#379]
Greetings Mogli, I want to say great addon and im truly enjoying it. However, i have an issue... 

The AutoHold function when holding the "S" Key worked fine on all tractors when i started my new game. It however has stopped working on one tractor only, rest are still working correctly. I have looked through the key controls and seen many times that ";" Key turns on auto hold to my understanding. I have been trying every CTRL, R-SHIFT and single key combos i can think of for the past 4 hours and auto hold will NOT activate again on that tractor. Is there another key or key combo i need to press to reactivate autohold on my tractor?    (   ";" only switches from manual to neutral and back to manual)

*EDIT: The tractor im having issues with activating the autohold is the Case 1455XL*

Thank you in advance Mogli!

**Comment by Frank1974** [comment]
Hello, 
only the newer tractores have got autohold, older tractors like the Case 1445XL havent got it, if that helps you with your problem.

**Comment by archedian** [comment]
Hello Frank, Thanks for the response! I could have swore the Case 1455XL had it when i started my game... May had just not paid as much attention to it, hmm

**Comment by KITT3000** [comment]
@archedian Maybe before, there was no typical gearbox configuration for this tractor and used an automatic transmission or CVT.

**Comment by Mogli12** [comment]
Hi,

Even old tractors used autiHold if you switched manually into neutral. I think I removed it as I fixed the double clutch without G27 gear shifter.

Maybe you can use the handbrake  (rCtrl+shift) instead. 

Regards, Stefan

**Comment by Mogli12** [comment]
Can you please check v3.1 build 62?

**Comment by Mogli12** [comment]
You can turn on the AutoHold for vehicles w/o AutoStartStop via the global parameter autoHold:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<autoHold type="bool" value="true"/>
	</gearboxMogliGlobals>
</vehicles>
```

You have to switch into Neutral and press the brake for about one second

**Comment by Mogli12** [comment]
I added something. If a vehicle does not have `autoStartStop="true"` but the automatic clutch is on then it will behave like with auto hold as long as you press the brake pedal.
