### ISSUE TITLE
Leerlaufproblem 1.3.2.8

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#38]
Hi wieder mal, neueste Version, (autom, Kupplung, Tastatur), der Traktor laeuft, wenn man den "Gang" rausnimmt bzw. in den Leerlauf geht nicht aus, sondern haelt seine Geschwindigkeit...das war definitiv vorher nicht so. Siehe video:

https://youtu.be/K-HMM3mbgO8
https://youtu.be/b7adSvVC_4g

**Comment by Mogli12** [comment]
Hi,
ich denke, dass es vorher falsch war. Motorbremse funktioniert so: Wenn man kein Gas gibt, dann wird auch beim normalen Getriebe etwas Bremskraft auf den Räder gegeben. Ich habe das so angepasst, dass diese Bremskraft zusätzlich noch von der Drehzahl abhängt. Dabei habe ich in der Vergangenheit nicht auf "neutral" geachtet. Jetzt ist es aber so, dass es in "neutral" keine Bremskraft mehr gibt. 
Viele Grüße
