### ISSUE TITLE
Auto-Kupplung verhält sich komisch

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#380]
Hallo,
in letzter Zeit verhält dich die Automatische-Kupplung relativ komisch, wenn man z.b. die Wendeschaltung betätigt bleibt sie bei 2% und der Traktor fährt nicht an, erst wenn man dann fast vollgas gibt dauert es noch 2-3 Sek. und dann geht die Kupplung sehr schnell auf 100% und man fährt mit einem riesen Ruck an.

Dazu hätte ich noch einen Verbesserungsvorschlag, bei der Wendeschaltung ist es ja momentan so das sie wie eine Automatische Kupplung ist, also sie kuppelt so ein dass der Motor nicht abgewürgt wird, in echt ist es jedoch so das die Wendeschaltung xyMs von 0-100% braucht, und das immer auch wenn der Traktor abgwürgt wird, aber diese xyMs kann man verstellen, wäre es vielleicht eine Möglichkeit dies auch in die Gearbox ein zu bauen? 

Viele Grüße -Frank.

**Comment by Mogli12** [comment]
Hallo Frank,

Die Kupplung schliesst sich derzeit innerhalb von 3000ms.

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,
was hat dies mit dem verhalten der Kupplung zu tun? 

Das Problem ist ja sie kuppelt nicht von selber ein im Standgas sondern erst wenn man vollgas gibt und dann auch nicht gleichmäßig sondern erst gar nicht und dann sofort ruckartig.

**Comment by Frank1974** [comment]
Hallo Stefan,
das normale anfahren ist jetzt gut, nur wenn man mit der Wendeschaltung in den Rückwärtsgang wechselt fährt er erst an wenn man aufs gas drückt, hingegen im Vorwärtsgang fährt er sofort nach dem "umschalten" an.

Wäre es vielleicht eine Möglichkeit wenn man die Reaktionsgeschwindigkeit der Kupplung so wie es jetzt bei der "One-Button-Clutch" ist auch für die Automatische Kupplung in das GUI aufnimmt?

Mir ist aufgefallen dass die Autohold Funktion nur noch mit Automatischer Kupplung funktioniert, ist dies gewollt?

Viel Grüße und vielen dank für deine ganze Arbeit und Zeit die du in die Gearbox steckst -Frank

**Comment by Frank1974** [comment]
Hallo Stefan,
mit Build 60 ändert sich leider nichts.

**Comment by Mogli12** [comment]
Hallo Frank,
bei mir läuft es perfekt. Ich habe keine Ahnung, was Du überhaupt machst, da es nicht in der Beschreibung steht. Welches Fahrzeug? Wie ist es konfiguriert? Ist vielleicht die manuelle Kupplung betätigt? 
Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,
damit ist es schon viel besser, Autohold funktioniert wieder, die Automatische Kupplung schließt auch jedes mal und gleich egal ob im V- oder R-Gang.

Wäre es noch möglich die Zeit wenn man die Wendeschaltung betätigt zwischen dem anhalten und wieder anfahren (wenn man kein Gas gibt) zu verkürzen? jetzt dauert es ca. 2sek.* bis er wieder anfährt, in echt hingegen fährt er sofort nach dem stehen bleiben wieder an.


*(sowohl mit der Automatischen als auch der Manuellen Kupplung wobei es bei der Automatischen länger ist) 

Und was hältst du von der Idee wenn man die Schließgeschwindigkeit der Automatische Kupplung (und Wendeschaltung) in die Globals/das Ingame GUI aufnimmt?

Viele Grüße und vielen dank für die tolle Arbeit -Frank

**Comment by Mogli12** [comment]
Hallo Frank,

die Empfindlichkeit der Wendeschaltung wirkt sich jetzt auch auf das Schließen der Kupplung aus.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Frank,

die Wartezeit ist dazu da, dass der Motor vor dem Einkuppeln auf Touren kommen kann. bei 50% beträgt sie 250ms. Die Kupplung wird einerseits über die Zeit und andererseits über die Drehzahl gesteuert. Der Ruck kommt daher, dass der Motor recht viel Gas gibt, um ihn auf Drehzahl zu halten.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Frank,

ich habe die Kupplung etwas weicher ausgelegt. Es sollte aber auch nicht zu einfach werden.

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,
wäre es eine Möglichkeit zu testen wie es sich ohne diese Wartezeit und mit einer rein Zeit gesteuerten Kupplung verhält?

Viele Grüße -Frank

**Comment by Frank1974** [comment]
Hallo Stefan,
mit dem Build 63 ist es jetzt so dass sich bei der Automatischen Kupplung nach dem Richtungswechsel die ersten 15-20% sehr langsam schließen und es dann sehr schnell/ruckartig bis auf 100% geht.

**Comment by miracleman51** [comment]
Hi Sefan.

Really enjoying the work your doing! Im finding the new gearbox fine so far.  However: 

Something Ive spotted recently with a few tractors is that the engine brake sound is too loud when in the cab, and the run/idle sound I would say is too quiet.  E.g. using the gbmod on M7400 series.
When driving the tractor (in cab) the engine brake sound is far far louder in the cab than the engine load sound. Which I don’t think is accurate.

**Comment by Frank1974** [comment]
Hallo Stefan,
mit dem Build 64 hat sich leider nichts geändert.

Viele Grüße -Frank

**Comment by Mogli12** [comment]
Dann muss es leider so bleiben. Ich kann keine fehlende Massenträgheit simulieren.

**Comment by Frank1974** [comment]
Hallo Stefan,
das wäre sehr schade.

Ich bin nach wie vor der Überzeugung wenn man die Kupplung rein Zeit gesteuert macht würde es besser werden, könnte man dies vielleicht einmal ausprobieren?

Viele Grüße und vielen dank für die ganze Arbeit -Frank

**Comment by Frank1974** [comment]
Hallo Stefan,
mir ist noch ein kleiner Fehler aufgefallen, glaube ich. Bei dem NewHolland T6 AutoCommand welcher ein Teil-lastschalt-getriebe hat geht Last auf 100% wenn er eine der "nicht-Lastschaltstufen" schaltet (Gang von 4 auf 5,  8 auf 9, 12 auf 13 und 16 auf 17). 

Viele Grüße -Frank

**Comment by Frank1974** [comment]
Hallo Stefan,
mit dem Build 65 hat sich leider nichts verändert.

Viele grüße -Frank

**Comment by Mogli12** [comment]
Hallo Frank,

es wird sich auch nichts ändern. Ich habe es selber probiert und die Traktoren fahren jetzt relativ weich an. Die Kupplung schließt bei mir beim Anfahren ohne Gas nur über die Zeit. Trotzdem schließt sie beim Schalten während der Fahrt über die Drehzahl schnell genug. Ich denke, dass Deine Ansprüche viel zu hoch sind. 

Ich gebe jetzt erstmal auf und mache am Getriebe nichts mehr.

Stefan
