### ISSUE TITLE
How do I set a default gearbox option for all vehicles?

### ISSUE THREAD

**Issue by Todiros** [Mogli12/GearboxAddon#385]
I've installed the mod into an existing save and I want the mod to be off by default (or gearbox set to the simplest option) unless I go with the vehicle into the store and change the gearbox. Is that possible?

**Comment by Mogli12** [comment]
Sorry, but this is not possible. But you can turn off all gearboxes of all vehicles with KEY_rshift KEY_semicolon.

**Comment by KITT3000** [comment]
@Todiros Use the "GameExtention" mod.

**Comment by Todiros** [comment]
@Mogli12 That might actually work as I have certain vehicle mods that just do not need a gearbox.
