### ISSUE TITLE
DruchdrehendeRäder Verbesserungsvorschlag

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#387]
Hallo Stefan,
wäre es eine Möglichkeit dass man in den Mogliglobals einstellen kann ab wie vielen % Schlupf die Durchdrehenden Räder den Boden umgraben?

Viele Grüße -Frank

**Comment by Mogli12** [comment]
Hallo Frank,

Wenn Du Dir in gearboxMogli.lua die Zeilen 4911 bis 4941 anschaust, dann siehst Du, dass es über Schlupf (20% bis 70% je nach Lenkwinkel), Mindestgeschwindigkeit (2 km/h) und Zeit (1 Sekunde) geht.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Frank,
ich denke, dass man bei 50% Schlupf den Effekt für durchdrehende Räder auch gleich ausschalten kann. 
Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo Stefan,
daher ja die Frage ob man die untere Grenze nicht einstellbar machen kann?
Damit könnte es sich dann jeder so einstellen wie er es haben will.

Grüße -Frank

**Comment by Mogli12** [comment]
Hallo Frank,

das Problem is doch, dass auf trockenem Gras die Räder viel zu stark durchdrehen. Da nützt es doch wenig, am Symptom herumzuschrauben. Den Pflugeffekt kann man ganz einfach über die Settings (LCtrl+Ö) auf Seite 2 aus- und einschalten.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Auch wenn ich es selber nicht für richtig halt: es gibt jetzt die beiden Parameter maxSlipFactor und maxSlipInc.
