### ISSUE TITLE
Enhancement request : Simulate torque pulses of individual pistons.

### ISSUE THREAD

**Issue by Dudejo** [Mogli12/GearboxAddon#389]
Hi

Would it be viable to simulate engine torque based on this article?

[http://www.epi-eng.com/piston_engine_technology/torsional_excitation_from_piston_engines.htm](url)

**Comment by Mogli12** [comment]
Hi,

I do not think that we can simulate this with only 30 to 60 FPS. 20000 rounds per minute corresponds to 33 rounds per second. So we have less than 2 frames per round of the engine.

Regards,
Stefan

**Comment by Dudejo** [comment]
is 20,000 rpm the game engine's limit?

**Comment by Mogli12** [comment]
Sorry, I meant 2,000 RPM. 

You can specify the attribute revUpMs in the gearboxMogli tag: 
```xml
<gearboxMogli ... revUpMs="2000" revUpMsFullLoad="15000" revUpMsNeutral="750" revDownMs="1500" .../>
```

**Comment by Dudejo** [comment]
thanks, I'll see if I can simulate something convincing for my own purposes.

btw, I recommend setting revDownMs in the LUA file to 3000 ms. When the current value of 1500 ms is used, vehicles that require double clutching are extremely difficult to shift because the RPMs simply drop too quickly.

Also, it feels like the engine has no flywheel to maintain rotational momentum.

**Comment by Mogli12** [comment]
You can overwrite all values of gearboxMogliGlobals w/o modifying FS17_gearboxAddon.zip. Just check https://github.com/Mogli12/GearboxAddon/issues/367 as example.

**Comment by Dudejo** [comment]
do I need to make a second ZIP file to put my modified file in?

**Comment by Dudejo** [comment]
I just noticed that the flags for revUp/Down/etc attach to transmissions. However, for my needs, I would need them to attach to engines.

Is this possible?

**Comment by Mogli12** [comment]
You can limit your configuration to certain engines:
```xml
	<vehicle>jcbFastrac150
		<mod>
			<!-- 40 km/h -->
			<xmlFile name="modernClassicsDLC/jcbFastrac150/jcbFastrac150.xml" engines="1"/>
		</mod>
```

**Comment by Dudejo** [comment]
how does that flag work?

does it point to an engine ID (engine 1, engine 2, etc)? would I type engines="1, 2, 3"?

or does it say how many engines the configuration has?

**Comment by Mogli12** [comment]
Suppose your vehicle has 5 motorConfigurations and the gearbox configuration should be valid for the 2nd, 3rd and 5th then it would look like this: `engines="2 3 5"`

**Comment by Dudejo** [comment]
ok, I'll look into it once I have some free time.

thanks

**Comment by Dudejo** [comment]
ok so...I typed out two configurations in an external file. Basically, I want config no.1 to apply to engine 1 and config no.2 to apply to the other engines.

However, no matter what engine I choose, the game defaults to config no.1 and will not apply config no.2 under any circumstance.

https://cdn.discordapp.com/attachments/412348931473801217/458832030789271553/gearboxAddonConfig.xml

**Comment by Dudejo** [comment]
Is there something I'm doing wrong?

**Comment by Mogli12** [comment]
Hi,

I think you use it with the build in Lizard Rodeo, right? In your config this works via the entry
```xml
<configFile xmlName="data/vehicles/steerable/lizard/lizardPickupRodeo.xml"/>
```
I propose to adjust it this way:
```xml
<configFile xmlName="data/vehicles/steerable/lizard/lizardPickupRodeo.xml" engines="1"/>
```
for the 1st entry and 
```xml
<configFile xmlName="data/vehicles/steerable/lizard/lizardPickupRodeo.xml" engines="2 3 4"/>
```
for the 2nd entry.

Regards

**Comment by Dudejo** [comment]
that worked.

thanks for the help.
