### ISSUE TITLE
game crashes with gearboxaddon errors, while gearboxaddon is not installed

### ISSUE THREAD

**Issue by ometinsu** [Mogli12/GearboxAddon#393]
Recently FS17 is crashing with as cause a gearboxaddon error. The thing is, i never have installed the gearboxaddon, But in te log of the game it says that there is a 'undefined input in tempomatMogli'.
I have deleted all my savegames, deleted all recently added mods en reinstalled the game multiple times and the game keeps crashing.  when the game crashes the screen turns black and the CPU goes to 100% and the PC turns unresponsive. Can someone tell me how to get my game working again?

i added the log from fs17.
[log.txt](https://github.com/Mogli12/GearboxAddon/files/2112545/log.txt)

**Comment by Mogli12** [comment]
Hi,

Sorry, but these warning are independent of your crash. The missing inputs are in the FS17_FENDT_800_VARIOS4_V1003_AGO_.

Regards, Stefan
