### ISSUE TITLE
4WD/  diflock does and does not auto disappear

### ISSUE THREAD

**Issue by mrPassion78** [Mogli12/GearboxAddon#394]
Hi there, i`m having some trouble with my conversions sins the update..the gearboxes to not auto disengage the 4WD on 25km/h in most of the conversions, although 1 does... and i cannot see where that goes wrong.. 
The tractors that will not disengage the 4WD, will not go faster than 25Km/H until i manually disengage the 4WD.

i will see if i can add the conversions of the IHC 644 that does not work, just as my JD4955, and the Fiat Agri 180-90 DOES work.. so i`m confused about that.. what did i do wrong there?.

[my mr conversions.zip](https://github.com/Mogli12/GearboxAddon/files/2116780/my.mr.conversions.zip)
so 3 files in the ZIP.. 644 and JD4955 do not work, and the fiat that works.. 

i hope you can help me again. 

thnx Pascal

**Comment by Mogli12** [comment]
I this is wanted. Currently it depends on the autoStartStop flag. If it is true then 4wd is automatically disengaged. Otherwise the speed limit of 25km/h is used..

**Comment by mrPassion78** [comment]
That is awesome and i now what to do.. thnx man..for the fast answer, and the awesome mod.. :D keep it up..

**Comment by Dudejo** [comment]
In my personal experience, 4WD does not seem to deactivate even if the icons disappears from the HUD.

The vehicle I tested with will show high levels of slip at all speeds if set to 2WD. However, if I set it to 4WD, it will maintain low levels of slip even past 25 km/h, where 4WD is supposed to deactivate.

**Comment by Mogli12** [comment]
Hello @Dudejo,

What version do you use and which vehicle? Maybe it still has 4wd?

Regards,
Stefan

**Comment by Dudejo** [comment]
I'm running 3.0.7.0

The vehicle is the Barrelcore tandem axle truck from the vanilla game.

**Comment by Mogli12** [comment]
Ok, with moreRealistic only the tandem axle is motorized. And without the gearbox does not modify the differentials.

**Comment by Dudejo** [comment]
Yes, the tandem axle is essentially configured as its own 4x4 vehicle. It works the same as a regular 4WD platform except that steering is handled by an extra, undriven axle.

It is also configured this way in vanilla because DriveControl can lock the differentials as well.

So why am I still getting 4WD grip long after 25 km/h?

**Comment by Mogli12** [comment]
In the vanilla game the vehicle has 5 diffs and gearbox addon will not modify it.

**Comment by Dudejo** [comment]
Indeed, I had not noticed that.

Although, if it makes any difference, the vehicle only has drive nodes on one pair of wheels. The Tatra Phoenix has drive nodes on two pairs.

I can't tell what difference this would make but here it is.

**Comment by Mogli12** [comment]
Gearbox supports only locking of 4 wheel drive (3 diffs) and 2 wheel drive (1 diff). The icons should not appear in the latest version (v3.1 build 78).
