### ISSUE TITLE
kein Allrad oder vordere Diff-Sperre auf Dedi

### ISSUE THREAD

**Issue by Evilman2517** [Mogli12/GearboxAddon#397]
Hallo,
ich habe gerade bemerkt, dass sich bei der aktuellsten Version auf dem Dedi-Server bei allen Fahrzeugen kein Allrad mehr aktivieren lässt, die vordere DifferentialSperre lässt sich ebenso nicht aktivieren. Die hintere funktioniert normal. Im Singleplayer funktioniert alles bestens wie immer.

Grüße

**Comment by Evilman2517** [comment]
Hat sich erledigt, mit dem gestrigen Update funktioniert Allrad und die vordere DifferentialSperre wieder auf dem Dedi.

Danke

**Comment by Mogli12** [comment]
Danke für die Rückmeldung
