### ISSUE TITLE
Сombine does not go

### ISSUE THREAD

**Issue by mrdarkshine** [Mogli12/GearboxAddon#398]
Does the combine eat at a speed of 5 km / h? Mission pass is not possible! At many modes, the combine swears at the power shaft. When the mod is disconnected from the combine, it is fed as if from a gearbox. How to fix??? The author does not see the harvesters on the trail and loves the tractor.

**Comment by Mogli12** [comment]
If you buy (or configure) the combine you can choose configuration option "off" for the transmission. The transmission configuration is typically the option at the bottom of the list.
