### ISSUE TITLE
Drive direction doesn't change on machines with switchable direction

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/GearboxAddon#4]
Using the current version of the gearbox Haddon from here, If the gearbox addon is active when using the Claas Xerion 4500 from http://www.modhoster.de/mods/claas-xerion-4500 the drive direction doesn't change automatically when the cab is rotated. When the gearbox addon is turned off the drive direction switching works normally again.

According to the log.txt it looks like the gearbox addon is trying to use a default config for the tractor, since it doesn't 'know' it yet:
/Users/don_apple/Library/Application Support/FarmingSimulator2015/mods//CZMOD_CLAAS_Xerion_4500/CLAAS.i3d (319.81 ms)
configFileName: /Users/don_apple/Library/Application Support/FarmingSimulator2015/mods//CZMOD_CLAAS_Xerion_4500/claas1.xml
zzzMrGearboxAddon: default50 inserted into CZMOD_CLAAS_Xerion_4500/claas1.xml (i)

Is there a way to prevent the gearbox addon from trying to insert the default config in a machine it doesn't  know? Or could the default config be changed to make the drive direction switch work on mods that have a rotatable cab?

**Comment by Mogli12** [comment]
Even with drive direction you have to go to reverse. Maybe I can automatically toggle reverse when then drive direction is changed.

**Comment by Mogli12** [comment]
It should be fixed with the latest commit. And I added a real configuration for the Claas Xerion 4500.

**Comment by fdanapfel** [comment]
Thank you, works perfect now!
