### ISSUE TITLE
Build 1.4b23 hire worker not functioning correctly

### ISSUE THREAD

**Issue by miracleman51** [Mogli12/GearboxAddon#40]
Just tried ploughing with a hire worker and its barely crawls.

**Comment by Mogli12** [comment]
Hi, Can you please describe the problem in more details? I miss to following things:
- what tractor?
- what plough?
- name of the map
- screen shot

**Comment by Mogli12** [comment]
Hi, I think this should be fixed with 1.4rc1, right? If yes, please "Close and comment". Thanks.
