### ISSUE TITLE
ratedRPM ohne engine Tag festlegen

### ISSUE THREAD

**Issue by Frank1974** [Mogli12/GearboxAddon#400]
Hallo Stefan,
ist es möglich bei einer Gearbox-Konfiguration welche keine "engine" hat die ratedRPM fest zu legen?

Viele Grüße -Frank

**Comment by Mogli12** [comment]
Ja, ratedRpm=... und idleRpm=... direkt bei gearboxMogli eintragen. Es wird dann die Drehmomentkurve übernommen.

**Comment by Frank1974** [comment]
Hallo Stefan,
kann es sein dass dies nur Funktioniert wenn die ratedRPM des Gearboxeintrages geringer ist wie die eigentlichen des Fahrzeuges?

Mein Problem ist, die ratedRPM von dem Fahrzeug selber sind viel zu nieder, das Fahrzeug ist wesentlich zu schnell, also möchte ich sie höher setzen (von jetzt 2350 auf 2500), dies scheint aber damit nicht zu funktionieren, nur wenn ich sie niederer mache z.b. 2200 funktioniert es.

**Comment by Mogli12** [comment]
Es bleibt ja bei der originalen Drehmomentkurve. Und ratedRpm muss auf jeden Fall kleiner als maxRpm sein.

**Comment by Frank1974** [comment]
Wie genau kann ich das globalRatioFactor Attribut setzen?

**Comment by Mogli12** [comment]
Damit wird die Ganggeschwindigkeit nochmal multipliziert.

**Comment by Frank1974** [comment]
Ich meine, wie/wo soll ich den Attribut einsetzen?

**Comment by Mogli12** [comment]
Das ist ein Attribut von `<gearboxMogli ...>` bzw. `<transmission ...>`. Der Wert `0.8` bedeutet also, dass die Gänge 20% langsamer sind als angegeben.

**Comment by Frank1974** [comment]
Hallo Stefan, 
damit funktioniert es, vielen dank.
