### ISSUE TITLE
Multiplayer error

### ISSUE THREAD

**Issue by mrPassion78** [Mogli12/GearboxAddon#402]
Hi Stefan, 
I was playing the multiplayer game, and the host updated the gearbox to the newest ( current) version, and after that we are not able to join anymore..
We also tried it with just sosnovka, and ONLY mod active ..gearbox, and cannot get i,.. getting the errors after synchorn. with other players..:
Warning: Mod-List download failed... retry in 4.018467 s. 1 trail
Warning: Mod-List download failed... retry in 6.006334 s. 2 trail
Warning: Mod-List download failed... retry in 8.026500 s. 3 trail
Lau callstack errors, ( witch where on the other player log file, sins he was the host.

i will try to recreate it, in the log files, cause they are overwritten, sins we rolled back the gearbox to version 3.0.6.8 ,witch works fine.. just the latest give the errors, so that one cannot join any multiplayer game..
and we eliminated all other mods, and they are fine, just not the newest version.

In single player the newest version is great..and works perfect.

I hope this helps a bit, if you need more info..let me now.

Greetings Pascal

**Comment by MrMazzony** [comment]
I was hosting a server on my own PC and Pascal was joining. He had a memoryleak issue after syncronation and he couldnt get on. Pc system memory usage would creep up to 100% in just a 30sec time (18gigs)

We used Gearbox 3.0.8.0 (moddesc version) with sosnovka and kuhn pack. All gamefiles updated the latest versions.
Downgrading from 3.0.8.0 to 3.0.6.8 wouldnt work on used savegame, ending to an error:

```
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/Vehicle.lua(1754) : attempt to perform arithmetic on local 'configNameId' (a nil value)
```

**Comment by Mogli12** [comment]
Is it fixed with 3.1 beta 82 ???

**Comment by MrMazzony** [comment]
Problem solved in builkd 82. Tested it wit oly it active. No memoryleaks noticed.

**Comment by MetalGovy** [comment]
@Mogli12 ,

Yep i can login again normally after update 82

**Comment by Mogli12** [comment]
Thanks!
