### ISSUE TITLE
ValtraNSeries - 5ter Gang wird nicht angeboten

### ISSUE THREAD

**Issue by RuppMartin001** [Mogli12/GearboxAddon#406]
Hallo Stefan,

mir ist aufgefallen, dass der fünfte Gang beim Valtra N nicht funktioniert.
In der gearboxAddonConfig.xml ist mir aufgefallen, dass eine maxForwardSpeed und eine maxBackwardSpeed von 53 km/h angegeben ist und beim fünften Gang eine Geschwindigkeit von 56,6 km/h.

Ausschnitt:

```xml
<transmission name="Versu" maxForwardSpeed="53" maxBackwardSpeed="53" swapGearRangeKeys="true">
				<blowOffVentilSound volume="0.5"/>
				
				<gears automatic="true" shiftTimeMs="0" clutchRatio="1">
					<gear speed="25.01"/>
					<gear speed="31.32"/>
					<gear speed="37.63"/>
					<gear speed="47.11"/>
					<gear speed="56.60"/>
				</gears>
...
</transmission>
```

Ich habe dann testweise in der persönlichen gearboxAddonConfig.xml-Datei eine Kopie des Vehicle-Eintrags eingefügt und dann die beiden Parameter: maxForwardSpeed und maxBackwardSpeed weggelassen. Danach hatte ich auch einen fünften Gang beim Valtra N.

Viele Grüße

Martin

**Comment by Mogli12** [comment]
Hallo Martin,

ich habe es gerade mit dem Standard Valtra N 134 mit Versu Getriebe probiert. Bereits vor Erreichen der Höchstgeschwindigkeit schaltet er automatisch in den Gang D 5 und erreicht 53 km/h bei ca, 1970 U/min,

Viele Grüße,
Stefan

**Comment by RuppMartin001** [comment]
Hallo Stefan,

ich habe eine Gangschaltung.
Wenn ich beim Valtra N 174 Versu versuche den 5. Gang auszuwählen kommt nichts, wenn maxForwardSpeed = 53 und maxBackwardSpeed = 53 gesetzt ist. 
Wenn ich die beiden entferne, kann ich den 5. Gang mit der Schaltung auswählen.

Wähle ich aber bei "Automatik" = "Automatik", bei Option: "Gänge und Gruppe 1 tauschen" = "Ja" aus und bei "Gang bei Gruppenwechsel" = "automatisch anpassen", kann ich mit der Gangschaltung die Bereiche A bis D (= Gruppe 1) auswählen und Gearbox schaltet automatisch die Gänge von 1 bis 5 durch. Auch mit gesetztem maxForwardSpeed und maxBackwardSpeed.

D.h. das Problem tritt auf, wenn ich mit der Gangschaltung die Gänge schalten will und maxForwardSpeed und maxBackwardSpeed auf 53 gesetzt sind.

Viele Grüße

Martin
