### ISSUE TITLE
Suggestion. 4WD with CP suppport?

### ISSUE THREAD

**Issue by MrMazzony** [Mogli12/GearboxAddon#407]
Opened issue on CP github, and they explained they have no support/commands for GB 4WD/difflock activation (only DriveControll).
I do not need Drivecontroll as i use mainly GB. It has "all" the same features as GB and vice-versa.
Possibility to add/consult?
My issue.
https://github.com/Courseplay/courseplay/issues/2789
Responce reference
https://github.com/Courseplay/courseplay/issues/2231

**Comment by Mogli12** [comment]
Hi,

Please check settings page 2. Per default CP and the hired worker drive with standard differentials (like w/o gearbox addon). But you can turn on gearbox diffs in the settings and lock them manually.

I did not implement automatic locking as I think that the standard diffs almost act like auto. lock diffs.

Regards,
Stefan

**Comment by MrMazzony** [comment]
Ok. Ill check them out as i get time to sit on PC, perhaps on saturday.

I use alot of simple/manual mode on workers (CP/FollowMe) as i like to hear the gears. And on some tracktors if you put 4wd "ON" and it has that <autoStartStop="false"> line in, will it disengage 4wd as it needs (ie: moving from fiel to road transport).

Testing more as i get time.
