### ISSUE TITLE
Durchdrehende Räder

### ISSUE THREAD

**Issue by Lasergott** [Mogli12/GearboxAddon#409]
Guten Tag,
wenn man mit einem Schlepper über eine Wiese fährt und dieser zu viel Schlupf bekommt (15-70%...)
sollte ja normal der Boden aufreißen? ("durchpflügen")
Irgendwie funktioniert das nicht richtig.
Bei der Wiese wird nur das Gras entfernt und nicht "durchgepflügt"...
Das ist bei allen Sorten von Gras/Wiesen so...  (Egal ob normale Wiese, selber angesät, ....)
Wenn die Wiese noch in der 1. Wachstumsstufe ist, sprich kurz nach der Saat funktioniert, das mit dem aufreißen vom Boden. 
Kurz gesagt:
Das aufreißen der Böden funktioniert überall, nur nicht auf Wiesen.
(Log ist Fehlerfrei, das Spiel einmal nur mit GearboxAddon gestartet und in der GearboxAddon Config "Durchdrehende Räder auf überall gesetzt)
**Habe gerade erfahren das dass wohl so gewollt ist. Wird es eine Option geben um das umgraben wieder zu aktivieren?**
Lg
Laser

**Comment by Mogli12** [comment]
Hallo Laser,
ich kann das wieder ermöglichen. Das eigentlich Problem war aber, dass gepflügter Boden bei FS17_moreRealistic viel weniger Grip hat. Der Grip reicht also auf Gras nicht auf, so dass die Räder durchdrehen. Dadurch wird der Boden gepflügt, und dadurch hat man dann noch weniger Grip. Im Grunde bleibt das Fahrzeug dann stehen, wenn auf Gras einmal der Grip zu niedrig war. Daher wird Gras auf die unterste Wachstumsstufe gesetzt.
Viele Grüße

**Comment by Mogli12** [comment]
Hallo,
Du kannst mit v3.2 build 3 auf Seite 2 der Einstellungen das Pflügen auf Gras aktivieren.
Viele Grüße
