### ISSUE TITLE
Build 1.4 b26 motor sound

### ISSUE THREAD

**Issue by miracleman51** [Mogli12/GearboxAddon#41]
At work so Ill post my log later, but I had a quick test last night.  New RPM/hand throttle works well, however idle sound does not change with rpm, and motor sound now does not seem to change in relation to motor load (i.e. get louder or deeper in tone).  In my opinion some of the earlier builds had the best implementation of this.

This was tested however with a mod NH T7.185.  Not yet tested with much else due to time constraints.

Oytherwise great work.

**Comment by miracleman51** [comment]
Hi Im finding with manual vehicles (like the quad trac and the T6160, that the idle sound seems to get quieter with tractor load and louder with less load on the tractor and doesn't always seem to rise in pitch with rpm.  Its almost like its doing the opposite of what it should.  CVT tractors seem to work fine.

**Comment by miracleman51** [comment]
Ah.  I think I see what you are trying to do.  Actually with actual CVT transmissions, when you brake, the engine revs increase as the on board computer uses engine braking to help slow the tractor (Durals implementation of this in MR for 2013 is quite accurate in this case).  Also is there a way to increase the amount that the idle engine sound increases (pitch) with rpm?

Im also finding that I get more power/louder engine sound when using the accelerator pedal, even if the engine hand throttle is set a full, which seems a bit odd as the two should effectively do the same thing.

Otherwise loving the mod!!

**Comment by miracleman51** [comment]
As an update.  I've found that changing the values in:         
<motorLoadVolumeFrom  type="float" value="0"/>
<motorLoadVolumeTo    type="float" value="1"/> 

did weird things to the sound - hard to explain but they didn't act as I expected.  However changing the motorLoadVolumeBrake to 0.4 seemed to give a much better balance to my tastes.

**Comment by Mogli12** [comment]
I think now I found the real bug in the calculation of the motor sound run. Afterwards I had to adjust some parameters because it did not fit together anymore. What do you think?

**Comment by miracleman51** [comment]
Nice.. working good!

I still feel that the idle run sound still doesn't increase in pitch enough in line with rpm however.  Is there anyway to adjust that?

Otherwise CVT is working better and the overall sound is much better.  I like in the inclusion of the inertia as well!

**Comment by miracleman51** [comment]
Hmm..

Just tried ploughing, I'm finding that the sound in relation to motor load isn't quite as it was.  Before if load was approaching ~90% or so you could hear the engine load up more that it does now.  Also when in 'autohold'  and you change gear (like powershift gears), the revs blip which they didn't before and wouldn't do IRL, unless the clutch was engaged and you were moving.

**Comment by miracleman51** [comment]
As an update from some playing about.  The motor load sound is much better with the CVT tractors than the ones with a gearbox.

**Comment by Mogli12** [comment]
I tried something new in 1.5 beta 8. I changed the formula for motorSoundRun. There are the following parameters:
r: rpm factor (0 ~ minRpm; 1 ~ maxRpm)
m: motor load (0..1)
a, b: parameter from gearbox settings

This was the old formula: v = r * ( a + m * b )
And this is the new formula: v = r * a + m * b

The motor load has much more influence on the volume at low rpm.

What do you think?

**Comment by miracleman51** [comment]
Hey bud.

Yea thats working pretty well.  I'm finding however it works great for the CVT tractors (and the CVT is working better... nearly perfect), but still doesn't seem to work so well for tractors with a Gearbox (especially if you set rpm to say 1800, selected a gear an go up a hill for example).  The CVT tractors the load sound seems to track better.

Also I would say the idle sound pitch still doesn't increase enough.

**Comment by miracleman51** [comment]
Sound is working great now!

Im finding with a gearbox however now when you brake and you are on autohold, engine load creeps up to 100% for some reason?

**Comment by Mogli12** [comment]
This should be fixed in FS17 (v2.0)
