### ISSUE TITLE
problem with auto clutch settings and cruise control 

### ISSUE THREAD

**Issue by DirectCedar** [Mogli12/GearboxAddon#410]
I'm using Gearbox and More Realistic. Overall they're both fantastic, game-changing mods. 

 I drive with a Mad Catz joystick for throttle and steering. 

 Something peculiar is happening with the auto clutch when I set the cruise control. For certain jobs I set the GPS and cruise control and sip coffee and listen to the birds while going down the field, and just do the headland sequence myself. (just like in a lot of real fieldwork actually :biggrin2: )

 Generally when I turn on cruise control, the auto clutch goes up to about 50% and stays there. I don't know why it does this. For light jobs like spreading everything continues to work as expected with the clutch technically half burning itself out but the game doesn't get too worked up about it. For heavy jobs with the auto clutch at 50%, the clutch quickly starts to overheat and I get the warning message. 

 It doesn't always do this with every tractor and every job. It never does it when I'm driving manually - only with cruise control on. 

 I can "manually override" the auto clutch setting in two ways - one is to push the stick all the way forward which then drops the auto clutch setting down to 0 and the overheating stops and everything works fine. However as soon as I release the stick the auto clutch goes back to 50%. The second is to hit "." key which turns off the auto clutch and then everything works fine, until I manually turn around and start the next row, and then the auto clutch comes back on and goes back to 50%. 

 Turning off auto clutch in the Gearbox settings doesn't change anything. 

 Some tractors it doesn't do this at all, and most tractors with a CVT (like the Fendts) it does not do this at all (yes, all with the Gearbox mod still on). 

 Any ideas what is happening here and how to properly correct it?

**Comment by Mogli12** [comment]
Can you please add a screen shot?

**Comment by Dudejo** [comment]
did you bind the analog clutch open/close controls to your joystick, by any chance?

I tested with my gamepad and if I bind the clutch open/close to my analog sticks, the clutch will hang around 50%, auto-clutch or not.

**Comment by DirectCedar** [comment]
Well I'll be darned; this seems to be the problem.  Way down at the very bottom of the key bindings menu there was Gearbox: Open Clutch tied to joystick Axis 8.  I didn't even know I had an Axis 8.  Turned off that binding and it seems to have gone away.


Thanks very much for the help.


________________________________
