### ISSUE TITLE
Tatra Phoenix 5. Gang

### ISSUE THREAD

**Issue by loenne-michel** [Mogli12/GearboxAddon#413]
Hi,
mir fiel auf, daß der 5. Gang des ZF Getriebes "reverseonly" eingestellt ist. Ist aber ein Vorwärtsgang ;-)
Ansonsten dickes Lob an deine Mod!!! Für mich im LS nicht mehr wegzudenken! Grüße...Micha

**Comment by Mogli12** [comment]
Hallo,
Vielen Dank. Es sollte jetzt korrigiert sein. Auch das Anpassen des Ganges beim Gruppenwechsel sollte jetzt wieder funktionieren, wenn man manuell schaltet.
Viele Grüße,
Stefan
