### ISSUE TITLE
Mähdrescher fahren mit Allrad

### ISSUE THREAD

**Issue by Evilman2517** [Mogli12/GearboxAddon#414]
Hallo,

mir ist kürzlich aufgefallen, dass die Mähdrescher nun plötzlich mit Allrad fahren. Habe daraufhin mehrere Drescher gegen ein Hindernis gefahren und festgestellt, dass bei allen Dreschern  die hinteren Räder mit antreiben. Ich bin der Meinung, dass dies früher nicht der Fall war. 
Des Weiteren habe ich bemerkt, dass man bei vielen Dreschern Allrad zuschalten und die Differentiale sperren kann. Bei einigen Standard-Dreschern geht dies nicht (so ist es ja korrekt), aber anderen aus dem Spiel und all meinen Mod-Dreschern kann ich die Option wählen. 

Ich wiederhole mich, aber: Vielen Dank für deine Mühen und konstanten Updates dieses genialen Mods ;-)

**Comment by Mogli12** [comment]
Hallo,

Das GearboxAddon verändert nur die schon vorhandenen Differentiale. Es fügt aber kein Allrad hinzu.

Die meisten Mods haben allerdings Allrad.

Viele Grüße, 
Stefan

**Comment by Evilman2517** [comment]
Hallo,

vielen Dank für die Antwort. Ich schließe das Issue dann wieder ;-)

Grüße
Christian
