### ISSUE TITLE
Ruckartiges Anfahren bei manuellen/automatischen Getrieben

### ISSUE THREAD

**Issue by FloSch02** [Mogli12/GearboxAddon#415]
Hallo allerseits! 👋 

Mich stört die aktuelle (ModHub-Verson 3.1.0.1) automatische Kupplung. Vor allem in kleinen Gängen, beim rangieren und bei Präzisionsarbeiten (Frontlader etc.) muss man unglaublich viel Gas geben (ca. 1800 U/min), bis das Kupplungspedal "losgelassen" wird. Doch sobald dies der Fall ist, dreht der Motor so hoch, dass der Traktor sofort anfährt, und das natürlich mit einem grossen Ruck... Wumms, man fährt gegen den Anhänger, den Pflug oder sogar die nächstgelegene Mauer. 
Ich weiss nicht, wie hoch Ihr eure Traktoren in echt drehen lasst, aber unser John Deere 6410 fährt beim rangieren bereits bei 1300 U/min sehr gut... 😄 

Verwendete Ausrüstung:
- Saitek LS-Lenkrad
- Same Fortis (Standard Konfigurationen) (ist auch mit allen anderen manuell oder automatisch geschalteten Traktoren so; Ausnahme ist der Case IH 1455XL mit Drezahlwandler(?!)...) 
- Ich habe auch schon versucht dieses Problem mit der Option "Empfindlichkeit der Wendeschaltung" zu lösen -> Das brachte nicht viel...

Die vorherige ModHub-Version (<3.1.0.1 (ich weiss die Version nicht...)) hatte dieses Problem nicht.
Ich bin aber sehr zu Frieden mit der Kupplung des Case IH 1455XL mit Drehzahlwandler. Der wandler ist sehr angenehm um anzufahren. 

**Ist es möglich ein global in die gearboxAddonConfig.xml zu schreiben, das die Kupplung bei allen Traktoren so macht, wie sie nun beim Case IH 1455XL (mit Drehzahlwandler) ist?**

z.B.
`<minClutchRatio value="0.6" type="float" />`
Ich meine, dass diese Zeile angibt, dass die Kupplung (wenn nichts gedrückt wird) zu 60% eingekuppelt  ist. 

Vielen Dank für die Hilfe. Ein grosses Dankeschön auch an Mogli für den (ansonsten) sehr genialen Mod! 👍 
-FloSch

**Comment by Mogli12** [comment]
Hallo,

hast Du nach dem Richtungswechsel einfach mal gewartet? Die Kupplung sollte in gewisser Zeit von selber schließen. Im kleine Gang sollte man so ganz ohne Gas anfahren können. Hast Du mal überprüft, ob Du auch eine Achse fürs Kupplungspedal zugewiesen hast und die Kupplung deshalb öffnet?

Viele Grüße,
Stefan

**Comment by FloSch02** [comment]
@Mogli12 
> Hast Du mal überprüft, ob Du auch eine Achse fürs Kupplungspedal zugewiesen hast und die Kupplung deshalb öffnet?

Ja, es war eine Achse belegt. 😆 
Wusste ich nicht, dass es daran liegen könnte!
Vielen, vielen Dank für die schnelle Hilfe! Ich bin begeistert.... 👍
-FloSch
