### ISSUE TITLE
Traktor greift auf nicht vorhandenen Eintrag zurück 

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#42]
Ich habe dem Steyr 8150 vor ca. 1. Monat einen Gearbox Eintrag verpasst, jetzt habe ich ihm aber einen neuen gemacht doch er greift immer noch auf den alten zurück, selbst wen ich den Eintrag komplett lösche so dass nichts über den Steyr im Gb Addon steht hat er immer noch die alten Daten welche ich ihm am Anfang gegeben habe. In der log steht das was immer da steht wenn man ein Fahrzeug mit Gb Addon kauft. 
Ich bitte um Hilfe. Mfg Blaggy

**Comment by Mogli12** [comment]
Hallo,
lade doch mal die log.txt (oder nur den kurzen Auschnitt mit zzzGearboxAddon: plus ein paar Zeilen davor und danach) bei Gist hoch.
Danke

**Comment by BlaggyXD** [comment]
[log.txt](https://github.com/Mogli12/GearboxAddon/files/375357/log.txt)

Hier ist die Log, Der Gb Eintrag ist fast ganz am ende.

**Comment by Mogli12** [comment]
Also das Getriebe lädt die Einstellungen aus der Datei zzzMrGearboxAddonConfig.xml direkt im Mods-Verzeichnis. Anscheinend hast Du den Mod umbenannt. Und die zzzMrGearboxAddonConfig.xml scheint auch eine ganze Reihe von Standard-Konfigurationen zu enthalten. Sind die alle nochmal von Dir geändert?

**Comment by BlaggyXD** [comment]
Der Fehler war meine schuld ich hatte die Config der Gb im Modordner als Sicherheitskopie daher hatte es die (Alte) Version geladen , ich hab sie gelöscht jetzt geht alles.

Danke für die Hilfe

**Comment by Mogli12** [comment]
Hi, Du solltest aber die ZIP-Datei gar nicht ändern müssen. Nimm doch einfach die originale ZIP-Datei (z.B. hier von GitHub) und dazu die von Dir geänderte zzzMrGearboxAddonConfig.xml im Mods-Ordern. Und die Traktoren, die Du gar nicht geändert hast, löscht Du dann einfach aus Deiner zzzMrGearboxAddonConfig.xml raus. So ist es auch in der Doku beschrieben.
