### ISSUE TITLE
Problem mit Gearbox Addon und IC Control

### ISSUE THREAD

**Issue by HerrMann81** [Mogli12/GearboxAddon#421]
Hallo,
Mir ist aufgefallen, das sich das Gearbox Addon mit der IC Control überschneidet. Also man aktiviert ja über die Leertaste die IC Control und beim Gearbox Addon schaltet man in den Rückwärtsgang. Wie kann ich das denn beheben? Weil wenn ich im Tractor sitze und IC aktiviere ich automatisch nach hinten schaue.....

**Comment by KITT3000** [comment]
Ändern Sie die Tasten in den Einstellungen für eine Funktion.  //Google Translate

**Comment by Mogli12** [comment]
Hallo,
man kann die Tastenbelegung in den Einstellungen selber ändern. Die Leertaste wurde schon bereits in FS13 von moreRealistic fürs Wechseln der Fahrtrichtung verwendet.
Viele Grüße
