### ISSUE TITLE
Schalten ohne Kupplung zu drücken mögich

### ISSUE THREAD

**Issue by RuppMartin001** [Mogli12/GearboxAddon#422]
Hallo Stefan,

ich verwende eine analoge Kupplung (Pedal) und auch eine Gangschaltung.
Leider kann ich bei Autos den Gang wechseln ohne das Pedal betätigen zu müssen.

Automatische Kupplung steht auf "Aus" und bei Automatik steht "Manuell".

Kann ich in der XML-Datei das "manualClutch"-Attribut setzen, damit ich die Kupplung treten muss?
Ich meine, dass es früher nötig war, auch die Kupplung treten zu müssen.

Ich verwende die Version: 3.1.0.4 (wird seltsamerweise manchmal auch 3.2 build 4 genannt).

Viele Grüße

Martin

**Comment by Mogli12** [comment]
Hallo Martin,

welches Auto und welches Getriebe? Ist es zufällig ein Automatikgetriebe?

Viele Grüße,
Stefan

**Comment by Frank1974** [comment]
Hallo,
ich denke hier ist die Rede vom Floaten.
Also dem schalten der Gänge durch anpassen der Getriebe- /Motordrehzahl ohne die Kupplung zu benutzen. 

Hier sind ein paar Beispiel Videos dazu:

https://www.youtube.com/watch?v=dd4s22TAER0

https://www.youtube.com/watch?v=jLw0hAtOik4

**Comment by Mogli12** [comment]
Hallo,

ich hoffe mal, dass Du nicht die gearboxAddonConfig.xml direkt in FS17_GearboxAddon.zip geändert hast. Du kannst Deine Einträge entweder in einer Datei gearboxAddonConfig.xml direkt im Mods-Odner lassen, oder Du verwendest die gearboxAddonConfig.zip.

Und ja, Autos mit Automatikgetriebe haben keine manuelle Kupplung.

Viele Grüße,
Stefan
