### ISSUE TITLE
G29 Standard Fendt Kupplung

### ISSUE THREAD

**Issue by cowboyjo** [Mogli12/GearboxAddon#423]
Hallo,
ich benutze das Gearbox Addon seit dem ich vor ca. nem 3/4 Jahr mein Logitech G29
gekauft habe. Bisher hat auch immer alles super funktioniert. 
Bei den Standard Fendts im Spiel konnte ich immer mittels Kupplung treten die Traktion zwischen
Motor und Getriebe trennen, was ich auch sehr oft genutzt habe. 
Nun habe ich nach längerer Zeit den Mod auf die neuste Version geupdated. (V3.0) 

Mein Problem ist nun, dass das Kupplungspedal keinerlei Wirkung mehr auf die Variogetriebe hat.
Somit habe ich nur die Möglichkeit die Gangschaltung auf Neutral zu stellen um Gas geben zu können, ohne das der Trecker beschleunigt.

Ist das jetzt Absichtlich so oder ist das ein Bug?

Mir währe es schon wichtig, dass es diese Funktion weiterhin gibt, weil ich nun auch einen neuen Mod installiert habe, der die Frontlader Geschwindigkeit nach der Motordrehzahl steuert.

Vielen Dank für die Antwort.
Gruß cowboyjo

**Comment by Mogli12** [comment]
Hi cowboyjo,

Das Problem sollte mit 3.1 build 5 gelöst sein.

Viele Grüße
