### ISSUE TITLE
External Config file not working

### ISSUE THREAD

**Issue by kananesgi** [Mogli12/GearboxAddon#428]
I'm fairly new at modding with the gearbox addon, and I'm just trying to get the transmission and engine options for some of the default vehicles into some modded versions of those vehicles. Specifically, I'm working with the Tatra Phoenix and the Lizard TT Pickup. These are the stock vehicles that are included and already have entries in the default gearboxAddonConfig file. What I'm trying to do is make those default configs available to a set of modded versions of those trucks (Tatra Phoenix AR Frame and the Lizard TT Dually and Single Cab mods). This worked last night by simply copying the gearboxAddonConfig.xml file from the gearbox mod into the main mods folder, then adding the lines at the end for the Tatra mod. This had the unexpected side effect of adding an "External" option to every other vehicle that had configurations in that file. 

This afternoon, I started putting the pickups into it and deleted all the other vehicles to get rid of the "External" options. Now, the game is no longer reading the external xml file (the one in the mods folder). Even if I delete the one I created and copy the the original straight out of the mod into the mods folder, there is no difference in game anymore. Any ideas?

**Comment by Dudejo** [comment]
In my experience, this issue is almost always caused by a syntax error inside the XML file.

Be sure to double-check your tags and even spelling. the slightest deviation will cause the file to fail.

If you have to, start over.

**Comment by kananesgi** [comment]
I don't know why, but it's working again. It wasn't a syntax error because copying the original straight out of the zip file and doing something simple like changing a gear range name (no syntax change) would not have any effect. 

I went to lunch with the family and when I got back and tried again, it's working now. I haven't done anything differently. But, issue closed.
