### ISSUE TITLE
Ponsse lack of power with 3.1.1.1

### ISSUE THREAD

**Issue by Jurkkis** [Mogli12/GearboxAddon#429]
I've not played FS17 for a while and installed newest GearboxAddon to give it a try, but have a problem with Scorpion King, very little power to the wheels when using gearboxAddon, video: 
https://www.youtube.com/watch?v=AhFQa1KZjcQ

No other mods, or errors in the log. And fresh install of the game Version: 1.5.3.1 b1848

I tested it with very old GearboxAddon (2.2.2.2) that I had backed up and issue was not present in that. 

Even the standard Giants gearbox would be fine with forestry machines, but I would like to use the gearboxAddon shuttle mode for them. And not use DriveControl as extra mod just for that.

**Comment by Gonimy-Vetrom** [comment]
On Fortschritt E303 same problem. With version 3.1.1.0 no problem.

**Comment by Mogli12** [comment]
Please try build 12 or 13

**Comment by Jurkkis** [comment]
Both Ponsses are fine with 13. Thank you.
