### ISSUE TITLE
LS 19

### ISSUE THREAD

**Issue by Paul2510** [Mogli12/GearboxAddon#437]
Wird es deine tollen modis für LS 19 geben?? 

LG

**Comment by Dudejo** [comment]
(Google Translate) In Ausgabe 417 glaube ich, dass Stefan den neuen Code lernen muss

**Comment by cabmac** [comment]
"lernen" wuerde ich  nicht unbedingt sagen...aber Giants muesste mal die neuen lua.docus veroeffentlichen....

**Comment by Mogli12** [comment]
The handling of texts, input bindings and the visibility of global attributes (e.g. vehicle types) changed so much that a conversion is impossible without LUADOCs.
