### ISSUE TITLE
LS17 beta wirf errors

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#45]
Hi, vielen Dank, dass du dich doch noch dem 17er "annimmst" :) ...mit der jetztigen beta friert das Spiel beim einsteigen ein und wirft folgenden error ins Unentliche:

Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/Motorized.lua:0: attempt to compare number with nil

**Comment by Mogli12** [comment]
Hi,
ich hatte, bevor ich den Getriebe-Mod aktiviert habe, einen Spielstand mit manuellem Motorstart gespeichert. Damit hatte ich das Problem nicht.

Die Fehlermeldungen sind leider jetzt nicht mehr so spezifisch wie früher. Die Zeilennummer fehlt.

**Comment by cabmac** [comment]
die zweite Version scheint zu klappen, werde es nachher nochmal testen..... modelleicher meinte,  da waere noch was mit dem sound.... k. A.

**Comment by cabmac** [comment]
edit,  Zeilennummmer anscheinend hinzugefügt 
https://forum.giants-software.com/viewtopic.php?f=874&t=96267

**Comment by Mogli12** [comment]
This should be fixed now. #
