### ISSUE TITLE
various...

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#47]
Moin, ein paar Sachen, ich weiss nicht, sehr warhscheinlich ists dir sogar selbst aufgefallen:

-wenn man die Rueckfahreinrichtung aktiviert, z.B. beim 900er, will er weder rueck-/noch vorwaerts
-schmeisst errors, wenn man die Anzeige mit "-" minimieren will 
-Umschalten von vorwaerts auf rueckwaerts noch ein bisschen "ruppig"

So long... :)

**Comment by Slomo1965** [comment]
Hallo Stefan,

schön das du dich der LS-Geschichten noch annimmst !

Ich werde mich heute auch mal ans testen machen.

Das Login für das Profi-Archiv hast du noch, oder ?

Wenn nicht geb ich dir das gern nochmal rüber.

Gruß

Stefan

**Comment by Mogli12** [comment]
Hi,

das sollte soweit gelöst sein.

Viele Grüße
