### ISSUE TITLE
revUpMs/revDownMs parameters, settings are not saved, freezing mrGearboxMogliREVERSE

### ISSUE THREAD

**Issue by Kynuska** [Mogli12/GearboxAddon#49]
Hello.
first, thank you very much for the transfer LS17.
I found a couple of mistakes, so I wonder if they are just in my game.
- Does not function parameter revUpMs / revDownMs. RPM after releasing the pedal quickly fall down
- after saving the game remembers settings (auto/manual clutch)
- and when changing direction (mrGearboxMogliREVERSE) freezes the game. I attach the log.
  [log.txt](https://github.com/Mogli12/GearboxAddon/files/560034/log.txt)

Thank you in advance for your time. Keana

**edit1:** ad3: the game frozen, when i have activate manual clutch. autoclutch is OK
**edit2:** ad3: when i delete "forwards and reverse only", its OK

**Comment by massyas** [comment]
Hello,

> Does not function parameter revUpMs / revDownMs. RPM after releasing the pedal quickly fall down

I encounter same issue when trying to change revUpMs / revDownMs. It was working fine on FS2013 version (not tested on FS15 version).

**Comment by simon50keda** [comment]
Same here, after releasing gas pedal rpm drops almost instantly. Looks like revDownMs is not taken into account anymore (tried latest one v2.0 rc2). 

To reproduce this issue:
1. Shift to neutral
2. Press gas pedal until full rpm
3. Quickly release gas pedal
4. Rpm will drop instantly.

**Comment by Kynuska** [comment]
> and when changing direction (mrGearboxMogliREVERSE) freezes the game. I attach the log.
> log.txt

solved. thank

**Comment by Mogli12** [comment]
Hi,
I cannot really control how fast revs drop w/o throttle. revDownMs is only during gear shift or in neutral. But at least the hydrostatic unit will look for it now.
Regards, Stefan

**Comment by simon50keda** [comment]
But I have feeling that this worked before in FS15?

**Comment by Mogli12** [comment]
Hi,

It should be better in v2.0 beta 16. If not please reopen the issue.

Regards, Stefan
