### ISSUE TITLE
When using the "mini HUD" the drive direction indicator only changes when machine is already moving

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/GearboxAddon#5]
Using the "mini HUD" when a machine is standing still the drive direction indicator changes to "N" or "P", and stays like this until the machine starts moving, even if the drive direction is switched in the meantime. When moving trailers or trying to attach machinery this makes it difficult to see in which direction a machine is going to move when the throttle is engaged.

I would therefore prefer if the "mini HUD" only shows "F" and "R", I don't really care to see if the gearbox is in neutral, and for the parking brake there is already a n indicator provided by the driveControl mod.

**Comment by Mogli12** [comment]
There is now a new drive direction indicator with arrows.

**Comment by fdanapfel** [comment]
Great, this is much better now!
