### ISSUE TITLE
v2.0 rc2 Rueckfahreinrichtung

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#50]
Moin, mit besagter Version ist bei der Rueckfahreinrichtung W und S invertiert, d.h. W fuer bremsen und S fuer Gas...

LG, Claudio

**Comment by Mogli12** [comment]
Hi Claudio,
Mit Version 1.9.2.3 sollte es besser sein. Ein paar Probleme gibt es aber noch - auch in KeyboardSteer.
LG, Stefan

**Comment by cabmac** [comment]
Hi, mit 1.9.2.3 laeufts jetzt, ausser einer kleinen Sache mit Keyboardsteer 2.0.1.1, die automatische Zurueckblicken-Funktion ist bei der Rueckfahreinrichtung noch invertiert, also fahr ich vorwaerts, wechselt die Kamara auf Rueckwaerts (was ja ohne Rueckfahreinrichtung richtig waere ;) )

LG, Claudio

**Comment by Mogli12** [comment]
Ja, für die Wendeschaltung und fürs weiche Anfahren habe ich einiges getan...
