### ISSUE TITLE
Autohold stops vehicle in neutral - v2.0 beta 15

### ISSUE THREAD

**Issue by simon50keda** [Mogli12/GearboxAddon#51]
With latest version gearbox is put in auto hold mode even if you have pressed clutch:
1. drive
2. press clutch
3. shift to neutral
4. vehicle will switch to auto stop and will be stopped in few seconds

So this means that when you are shifting with G27 setup, in between gears vehicle will get stopped but shouldn't as I am still having clutch pressed.

**Comment by Mogli12** [comment]
Hi, it should be fixed with beta 16
