### ISSUE TITLE
Abnormal fuel usage 

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/GearboxAddon#53]
Received via email from Pascal:
Hello
I have a concern some wear abnormally diesel tractors in IA mode or with the regulator
diesel decreases of a sudden?
have you encounter this problem

**Comment by simon50keda** [comment]
Yep, this happens with CVT when you are press space or switch gear while vehicle is not stopped.

**Comment by cabmac** [comment]
it happens also with cvt and helper mode... like #54,  sorry,  its in german

**Comment by Mogli12** [comment]
I hope that it is fixed with 2.0 beta 17
