### ISSUE TITLE
Spritverbrauch 1.9.2.6

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#54]
Moin, bei dieser Version gibts ein Problem mit dem Maehen mit dem Helfer z.B. (dort ist es mir jedenfalls passiert und aufgefallen, interessant waere, dass noch mit weiteren Maschinen zu pruefen).  Fogendes Szenario: Poettinger Maehwerke und z.B. Fendt 720, ich stelle den Helfer auf der Wiese ein, die MW gehen an und sofort wieder aus, da der Spritstand sofort auf 0 runtergeht, das wars. Auch ohne Helfer springt der Spritstand, d.h. von einer auf die naechste Sekunde von 350 auf 300 zum Beispiel. Das verrueckte dabei ist, dass die gleiche Aktion bei einem etwas kleinerem Trecker mit z.B. 150-160 PS ein Valtra oder Same einwandfrei gehen. Das scheint nur bei groesseren Traktoren der Fall zu sein. Ich habs ebenfalls mit dem 900er probiert sowie mit einem Deutz. Das liegt definitiv an gearbox, ich habe mittlerweile gefuehlte 97 Tests hinter mir. Gearde probiert, mit der 1.9.2.4 gehts einwandfrei...

kleiner Valtra, einwandfrei:
http://www.imagehub.de/images-i4262bmbf7t.png
http://www.imagehub.de/images-i4265bfcn6u.png

900er, Motor an, Helfer an, Motor aus, da Sprit sofort auf 0:
http://www.imagehub.de/images-i4263bv34tx.png

700er, dasgleiche Problem:
http://www.imagehub.de/images-i4264bihg1c.png

Deutz, wieder das gleiche:
http://www.imagehub.de/images-i4266brg6rv.png

Der "kleine" Same, wieder alles Ok:
http://www.imagehub.de/images-i4268b8jeeg.png

Ich hoffe, ich konnte das einigermassen vermitteln, wenn du moechtest, mach ich ein kleines Vid dazu. 

LG, Claudio

PD. gerade nochmal mit dem 900er und einem Pflug und dem grossen Grubber probiert, dort gibts kein Problem, scheint wirklich nur in Kombination mit den MW zu sein und Getrieben ohne Gangschaltung...komisch

**Comment by Mogli12** [comment]
I hope that it is fixed with 2.0 beta 17
