### ISSUE TITLE
after mis a jour 1.3

### ISSUE THREAD

**Issue by calou19** [Mogli12/GearboxAddon#56]
Hello
After the update 1.3
Here is the error in my log: FS17_GearboxAddon: looking for default configuration (defaultHydrostatic1)
GearboxMogli: Initialization of client ...
Error 7 loading gearboxMogliLoader: C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / FS17_GearboxAddon / gearboxMogli.lua: 441: attempt to perform arithmetic on global 'g_uiScale'
FS17_GearboxAddon: no configuration found for gearboxMogli into data / vehicles / steerable / jcb / jcb260.xml
Data / vehicles / tools / jcb / jcbPalletFork.i3d (15.20) ms
C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / International1455xl_FS17_V1_2 / caseIH1455.i3d (572.68) ms
FS17_GearboxAddon: looking for default configuration (defaultTractors)
GearboxMogli: Initialization of client ...
Error 7 loading gearboxMogliLoader: C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / FS17_GearboxAddon / gearboxMogli.lua: 441: attempt to perform arithmetic on global 'g_uiScale'
FS17_GearboxAddon: no configuration found for inserting gearboxMogli into International1455xl_FS17_V1_2 / caseIH1455.xml
Data / vehicles / tools / poettinger / poettingerNovacat302ED.i3d (21.27) ms
Data / vehicles / tools / vicon / viconFanex604.i3d (19.47) ms
Data / vehicles / trailers / kroeger / kroegerTKD302.i3d (31.82) ms
C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / FS17_newHollandBalerPack / newHollandRollBelt460.i3d (75.93) ms
Data / objects / roundbales / roundbaleStraw_w112_d130.i3d (4.19) ms
Data / vehicles / steerable / fendt / fendt700.i3d (85.63) ms
GearboxMogli: Initialization of client ...
Error 5 loading gearboxMogliLoader: C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / FS17_GearboxAddon / gearboxMogli.lua: 441: attempt to perform arithmetic on global 'g_uiScale'
FS17_GearboxAddon: looking for default configuration (defaultTractors)
GearboxMogli: Initialization of client ...
Error 7 loading gearboxMogliLoader: C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / FS17_GearboxAddon / gearboxMogli.lua: 441: attempt to perform arithmetic on global 'g_uiScale'
FS17_GearboxAddon: no configuration found for gearboxMogli into data / vehicles / steerable / fendt / fendt700.xml
GearboxMogli: Initialization of client ...
Error 5 loading gearboxMogliLoader: C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / FS17_GearboxAddon / gearboxMogli.lua: 441: attempt to perform arithmetic on global 'g_uiScale'
FS17_GearboxAddon: looking for default configuration (defaultTractors)
GearboxMogli: Initialization of client ...
Error 7 loading gearboxMogliLoader: C: / Users / pascal / Documents / My Games / FarmingSimulator2017 / mods / FS17_GearboxAddon / gearboxMogli.lua: 441: attempt to perform arithmetic on global 'g_uiScale'
FS17_GearboxAddon: no configuration found for gearboxMogli into data / vehicles / steerable / fendt / fendt700.xml

**Comment by Slomo1965** [comment]
You have to edit the gearbox.lua and replace in line 441 the "ui_scale" simply by "1"

It seems to be set as "0", and then, there is a unalowed Division.

With "1" the Interface has the normal size.

Just my 2 Cents

Stefan

@ THX a lot to Mogli for this excellent script !!

**Comment by calou19** [comment]
Thank you very much for this quick reply
@ THX a lot to Mogli for this excellent script !!
