### ISSUE TITLE
Info about Parameters to modify the HUD Appearance and Position are missing from documentation

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/GearboxAddon#6]
As you mentioned a while ago on the official LS15 forum it is possible to modify the HUD using the following parameters in the zzzMrGearboxAddonConfig.xml, but there is no info about those parameters in the documentation:

```XML
<gearboxMogliGlobals>
   <defaultHudMode value="2" type="int"/>
   <hudPositionX value="0.84" type="float"/>       
   <hudPositionY value="0.65" type="float"/>       
   <hudTextSize  value="0.02" type="float"/>       
   <hudTitleSize value="0.03" type="float"/>       
   <hudBorder    value="0.005" type="float"/>       
   <hudWidth     value="0.15" type="float"/>       
</gearboxMogliGlobals>
```
Would be nice if those parameters were documented somewhere.

BTW. there is still an "u" to much in the Title of the Readme.md, instead of "Farminug" it should be "Farming" :-)

**Comment by Mogli12** [comment]
Yes, the documentation is not (yet) up to date.

**Comment by mngrazy** [comment]
hi mogli

vielleicht wäre ein mod von DeckerMMIV eine option für das gearboxAddon
damit kann man die position vom hud in einer externen config.xml "modifizieren" wie man es am liebsten mag

https://github.com/DeckerMMIV/FarmSim_Mod_ModsSettings

die aktuelle dev version vom soilmod unterstützt den modSettings mod schon
https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod

schlecht wäre es nicht wenn man das hud extern einstellen könnte , dann muss man nicht immer in deiner lua rum schreiben :)

grüsse grazy

**Comment by Mogli12** [comment]
Hi,
In der LUA muss man dazu nicht rum schreiben. Lege doch einfach (wenn nicht schon vorhanden) eine Datei zzzMrGearboxAddonConfig.xml im "mods"-Ordner an. Dort fügst Du einfach folgende Zeilen ein:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<hudPositionX          value="0.84"  type="float"/> 
		<hudPositionY          value="0.65"  type="float"/> 
		<hudTextSize           value="0.02"  type="float"/> 
		<hudTitleSize          value="0.03"  type="float"/> 
		<hudBorder             value="0.005" type="float"/>
		<hudWidth              value="0.15"  type="float"/> 	
		<defaultHudMode value="2" type="int"/>
	</gearboxMogliGlobals>                                                        

</vehicles>

Das geht mit allen Komponenten von mrGearboxMogliGlobals. Ich schaue mir ModsSettings trotzdem mal an.

Viele Grüße

**Comment by mngrazy** [comment]
achsooo

jetzt check ich das erst , ich kann die config.xml aus der zip auch in den mods ordner ziehen und dann dort meine fahrzeuge hinzufügen ,,,, incl hud position ändern ^^

getestet und bestanden , funzt alles :)

danke für die info mogli 

grüsse grazy
