### ISSUE TITLE
error 1.9.3.2

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#60]
Hi,
habe diese 2 errors auf einmal in der log:

Error in updateVehiclePhysics :dataS/scripts/vehicles/specializations/Drivable.lua:0: attempt to perform arithmetic on a nil value
Error in updateVehiclePhysics :C:/Users/Claudio/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua:6792: attempt to perform arithmetic on local 'dt' (a nil value)

ich weiss nicht ob da ein Zusammenhang besteht...

LG 
Claudio

edit: ich kanns einfach nicht mehr reproduzieren...

**Comment by Mogli12** [comment]
Hi,
Ich konnte es jetzt zufällig reproduzieren. Und zwar fährt der Traktor ja weiter, wenn man das Fahrzeug verlässt und der Tempomat noch an ist. Beim Aufruf der entsprechenden Funktion gab es eine Änderung von FS15 zu FS17, die ich noch nicht umgesetzt hatte. Es ist gelöst mit 1.9.3.7.
Viele Grüße, Stefan
