### ISSUE TITLE
CVTs are creeping at idle revs

### ISSUE THREAD

**Issue by mrbear** [Mogli12/GearboxAddon#62]
I have tested a few of the machines with CVT gearboxes among them Fendt 300 and the Kramer front loader. They all seams to creep forward on idle revs almost like a car with an automatic gearbox.

The expected behavior would be for them to stay put until I push the accelerator and first then to start moving, if I release the throttle they should roll to a stop.

This worked with earlier revisions of the mod for FS17. If it helps I can try to see which version was the last one with the correct behavior.

This is a problem for two reasons. First it's not the way that the real machines work. Even the Valtra N series with it's conventional ranges + powershifts transmission work like I expect the CVT transmissions to do. You can watch it in action here: https://youtu.be/W5JW4p5cHDg?t=4m39s the whole video is rather interesting if  you are interested in the Valtra transmissions by the way.

The second reason is that it makes precision driving like pallet handling unnecessarily cumbersome moving your foot back and forth between throttle and break. You cant drive with just shuttle and throttle like I have been doing the few times I have been driving a loader in real life. 

Note that the current implementation should not be changed for equipment with manual clutch and traditional gears.

To see an extreme example of the problem try driving the Kramer with a speed of a few km/h and touch the break so the machine just stops. When you release the break it will take of again without you touching the throttle.

**Comment by Mogli12** [comment]
Hi, this was a tough one. But it really improved the gearbox. Thanks for pointing me to this problem.
