### ISSUE TITLE
Translate to czech

### ISSUE THREAD

**Issue by Kynuska** [Mogli12/GearboxAddon#63]
https://github.com/Kynuska/GearboxAddon/commit/782333c7c47192d4059299846d2a8f22d0890d4f
https://github.com/Kynuska/GearboxAddon/commit/b1d64392838bc889f84dd04c9aecaca4cfef2439

**Comment by Mogli12** [comment]
Thanks for the translation. I added it to the gearbox.

**Comment by Kynuska** [comment]
I am sorry. I had a mistake. When I tested it, the inscriptions were long. so I replaced Gearbox for GB. Unfortunately, I noticed that it replaced more
ad1890a73dcb461c8c05a2e4994f54cf404ae43d
