### ISSUE TITLE
JCB 3200 Automatik, keine Leistung

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#68]
Nabend, 

habe eben eine Mission mit dem JCB 3200 und der 6m Direktsaat Maschine (benötigt 180PS) gefahren.
Bei leichter Steigung geht dem JCB die Power aus. Selbst im heavy duty Gang geht nichts mehr. 

Bitte einmal überprüfen, irgendwo schließt da die Kupplung nicht richtig. :D 

Grüße

**Comment by Mogli12** [comment]
Hi, ein Screenshot wäre wirklich super. Danke

**Comment by Mogli12** [comment]
Hi,
mit Version 1.9.3.7 sollte es etwas besser sein. Aber selbst im Arbeitsmodus erreicht der JCB noch 45 km/h. Daher ist der hydrostatische Anteil bei niedrigen Geschwindigkeiten deutlich höher. Dadurch kommen nur noch gut 80% der Motorleistung an den Rädern an, und schon sind wir unter 180 PS
Viele Grüße
