### ISSUE TITLE
G27 & doubleClutch (modelleicher)

### ISSUE THREAD

**Issue by Mogli12** [Mogli12/GearboxAddon#7]
Hi.. Hab was zum meckern gefunden... 
Und zwar unsynchronisierte Getriebe/doubleClutch.. Die Reihenfolge stimmt nicht ganz.
Reihenfolge in echt:
- Kupplung treten
- Gang raus
- Kupplung raus
- (zwischengas geben, nur beim runterschalten oder extrem langer Schaltzeit)
- Kupplung wieder treten
- nächster Gang rein
- Kupplung wieder raus

Reihenfolge im Gearbox Script (G27 Modus)
- Kupplung treten
- Gang raus
- nächster Gang rein
- Kupplung raus
- Kupplung treten
- Kupplung wieder raus

Fällt mit automatischer Kupplung denke mal nicht wirklich auf, aber komplett manuell macht es doch nen Unterschied.. Und ist so gar nicht Intuitiv

**Comment by Mogli12** [comment]
Neue Idee: Kratzgeräusch abhängig vom Drehzahlunterschied.

**Comment by modelleicher** [comment]
-100 bis +500 funktioniert schon nicht schlecht, wobei -200 +800 deutlich einfacher zu spielen ist. Allerdings ist es nach wie vor eine ziemliche Übungssache bei welcher Drehzahl man schalten muss und wie lange das Gaspedal drücken, und für jedes Fahrzeug wieder anders. Dauert also bis man die Gänge wirklich rein bekommt jedes mal... Ist die Frage ob das nicht für die meisten dann eher frustrierend wirkt.. 
(evtl. nur Geräusche wenn die Drehzahl nicht passt aber Gang geht trotzdem rein) oder doch die Drehzahlüberprüfung weglassen und nur prüfen ob beim runterschalten eingekuppelt und zwischengas gegeben wurde, und beim hochschalten ob eingekuppelt wurde.

Sorry dass ich mich so spät erst melde. Wollte noch mehr mit "DoubleClutch" Fahrzeugen spielen vorher aber bin nicht dazu gekommen.

LG

**Comment by Mogli12** [comment]
Hi,
I added a new global parameter: grindingMaxRpmSound. The default is 600. So you should here the grinding sound if the rev is below target rpm - 100 or target rpm + 200. Since grindingMaxRpmDelta is now huge, you can always shift if rev is too high.
Regards, Stefan

**Comment by DarcReaver** [comment]
Passt zwar nicht ganz ins Thema, aber ich hätte noch einen Vorschlag für den Getriebe-Automatikmodus "einfach": Ist es möglich, den Schaltvorgang halbautomatisch laufen zu lassen, quasi wie bei einem Automatikwagen?

Z.B. dass man durch Druck auf die Kupplungstaste in den nächsten Gang hochschalten kann (runterschalten würde weiterhin automatisch passieren) - zur Zeit ist es halt so, dass der Traktor manchmal erst spät oder garnicht von alleine hochschaltet, und daher ist die Feldausfahrt öfters mal gefährlich, weil man über Zeiträume von 10-20 sec im 1. Gang auf die Straße fährt. 

So könnte man zumindest schonmal einen oder zwei Gänge erhöhen, damit man vom Fleck kommt.

**Comment by Mogli12** [comment]
Hi,
Du kannst auch im Automatikmodus jederzeit selber schalten. Die Tasten Ä, Ü, + und # funktonieren auch im Automatikmodus weiterhin.

**Comment by DarcReaver** [comment]
Achso okay, wusst ich nicht^^ Ist ja top :)
