### ISSUE TITLE
JCB 3230 Keine Leistung V2

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#70]
Hallo, da ich gestern nicht mehr dazu kam und mein Thread schon dicht ist dachte ich, ich mache kurzerhand einen neuen auf.

Habe mir heute mal die Arbeit gemacht und verschiedene Traktoren verglichen. Von 143PS (Deutz)
bis 240PS (Fendt 724). Beim JCB handelt es sich um einen 3230 mit 230PS. Der Valtra hat 185PS und der Same 193 PS. 

Im Video sieht man das beim JCB im transport Modi gar nichts geht, im heavy duty Modus sieht das schon besser aus. "Gemessen" habe ich immer an der selben Strecke, mit selbigen Anhänger/Gewicht. Start bei diesem Busch bis zur Stopstelle oben. Ich finde die 230PS des JCBs gehen total unter, der Same mit 40PS weniger zieht gleich schnell hinauf. Auch von der Leistung des Varios bin ich irgendwie enttäuscht... 

https://www.youtube.com/watch?v=I7l8P-gonyY&feature=youtu.be

Außerdem hat der 3230 doch "nur" Automatik, aber trotzdem Gänge. Also kein Vario! Siehe hier =>> 
https://youtu.be/OtHwSrz-rVE?t=149
Handelt sich zwar um den "alten" Fastrac, aber beim neuen soll es wohl änhlich sein. 
http://fastracneu.indesign.at/fileadmin/Bilder/Prospekte/fastrac_3000_techn.daten.pdf

Grüße Maxter

**Comment by Mogli12** [comment]
Ok, ich habe die Konfiguration für den JCB Fasttrac 3000 erstmal wieder gelsöcht.

**Comment by Mogli12** [comment]
So, mit Version 1.9.3.9 hat der JCB nun ein Getriebe mit 6 Gängen, 3 Gruppen und 3 Lastschaltstufen.
