### ISSUE TITLE
IHC 1455 1.9.3.8

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#73]
Hi, Situation: L4 vorwaerts, nun fahre ich Rueckwaerts (R4) und bei naechsten Richtungswechsel geht er automatisch auf H4. Wuenschenswert waere jedoch, dass er im vorherigen Gang bliebe (L4). Bin mir jetzt im moment nicht sicher, ob das mit der "alten" gearbox (A/S) auch so war oder nicht.

LG
Claudio

**Comment by Mogli12** [comment]
Hi,

dafür gibt es im Getriebe das Attribut reverseReset. Es ist aber lästig, sowas in jeder Konfiguration extra zu setzen, daher habe ich den Default etwas intelligenter gemacht. Ist also gelöst mit 1.9.3.9

LG Stefan
