### ISSUE TITLE
1.9.4.0 Ruefa Ruecklichter

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#74]
Hi, ich habe gerade mein FS neu aufgesetzt und nun faellt mir auf einmal auf, dass mit dieser Version bei aktivierter Ruefa beim Vorwaertsfahren die Rueckwaertslichter an sind. K.A. ob das in vorherigen Vesionen auch so war, fiel mir irgendwie nur grad auf...:

![fsscreen_2016_11_25_18_42_48](https://cloud.githubusercontent.com/assets/16596142/20632645/6d029430-b33f-11e6-9b4e-27067c2d3a1f.png)

bei den Valtras uebrigens ebenso...

LG
Claudio

**Comment by Mogli12** [comment]
Hi,

das war zwar schon immer so, aber ich kann es leicht korrigieren. 

LG Stefan

**Comment by Mogli12** [comment]
Hi,

das ist mit Commit ca284f184c6ab350279d2cf876d2e13e38a17d85 gelöst.

LG Stefan
