### ISSUE TITLE
Mods in die Config einfügen

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#75]
Hallo, eine frage:
Werden die Mods immer noch gleich wie in FS15 in die Config eingetragen? Oder hast du am System etwas geändert? 

Grüße Maxter

**Comment by Mogli12** [comment]
Hi Maxter,

solange die Mods nur eine Motorkonfiguration haben, geht noch das alte Format. Für die neue austauschbar Motoren habe ich <realEngine idleRpm="900" ratedRpm="2100">...</realEngine> durch

<engines>
  <engine name="???" idleRpm="900" ratedRpm="2100">
...
  </engine>

  <engine...>
...
  </engine>
</engines>

Du Anzahl Motoren muss genau passen, da sie leider über die Position, nicht über den Namen zugeordnet werden.

Viele Grüße, Stefan
