### ISSUE TITLE
Zetor 12045 RPM when shifting gear

### ISSUE THREAD

**Issue by Kynuska** [Mogli12/GearboxAddon#76]
Hello. I would like to ask for help. When you make the transmission settings for Zetor Crystal 12045 from modhub (http://www.farming-simulator.com/mod.php?ang=en&country=cz&mod_id=57670&title=fs2017)
 are strange rpm when changing gear.
when gears up rpm jumps from min to a value
when gears down rpm jumps from max to a value
(https://youtu.be/-4IP3i0Fpr8)
I do not know where it would be a mistake.

[gearboxAddonConfig.zip](https://github.com/Mogli12/GearboxAddon/files/614395/gearboxAddonConfig.zip)

Thank Keana

**Comment by Mogli12** [comment]
Hi, you created a power shift transmission. There is a gear shift effect, that's why the RPM "jumps". You can turn it off with shiftEffect="false". But I think the better solution is to take shiftTimeMs="300" or more, but not less.

**Comment by Kynuska** [comment]
Thank. I have shiftTimeMs="0", because i need change želva (thurtle) zajíc( rabbit) without clutch.  If i used manualClutch="false" is all without clutch.  I need gears witch clutch, range zajic/želva without clutch, range red/sil/zp with clutch.

**Comment by Mogli12** [comment]
So this Zetor has a power shift transmission?

**Comment by Kynuska** [comment]
torque multiplier (turtle / rabbit), shifting under load
http://www.tractordata.com/farm-tractors/001/7/2/1728-zetor-12045-transmission.html

**Comment by Mogli12** [comment]
Hi,
Please check the latest update:
Rhttps://github.com/Mogli12/GearboxAddon/commit/ca284f184c6ab350279d2cf876d2e13e38a17d85
BR

**Comment by Kynuska** [comment]
thank
