### ISSUE TITLE
call stack

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#77]
Hi Stefan,
ich habe seit einre Woche immer wieder einen call stack, ich habe den immer nach einiger Zeit spielen und zwar immer dengleichen, Spiel friert ein und das wars. Ich habe mittlerweile so ziemlich alles durchgespielt , mods rein, mods raus etcetc.  Obwohl ichs fast nichtd glaube, kann der etwas mit der gearbox zu tun haben? Ïch haeng dir mal die log mit an.

LG,
Claudio
[log.txt](https://github.com/Mogli12/GearboxAddon/files/616274/log.txt)

**Comment by Mogli12** [comment]
Hi,
das klingt mir eher nach einem Problem in Patch 1.3.1. Ich hatte das einmal. Ich bin dann nur ein kurzes Stück gefahren und habe das Savegame gesichert. Nach dem Neutart trat es nicht mehr auf.

LG Stefan

**Comment by cabmac** [comment]
Hallo, also ich hab jetzt einige Tests durch, eine der letzten war nur mit 5 oder 5 mods, 2 davon Keyboardsteer und gearbox. Ich wede morgen mal ein save anfangen nur mit den beiden, dann schauen ich mal, obs daran haengt...komische Sache, anbei die letzte log von heute nachmittag:

LG
Claudio
[1.txt](https://github.com/Mogli12/GearboxAddon/files/617244/1.txt)

**Comment by Mogli12** [comment]
Hallo,

ich habe keine Ahnung, woher das Problem kommt. Eigentlich wollte ich den Mod noch vor Weihnachten auf Modhoster veröffentlichen. Ich selber habe momentan weder Zeit noch Lust den Mod weiter zu entwickeln. Aufgrund der beiden Probleme #52 und #77 habe ich nun entschieden, den Mod nicht zu veröffentlichen und die Arbeiten daran einzustellen.

Viele Grüße

**Comment by cabmac** [comment]
hmm, hoert sich ja fast so an, als ob das meine Schuld nun ist...Ich weiss ja noch nicht mal, ob mein Problem ueberhaupt mit der gearbox zusammenhaengt.  :(

**Comment by Appaloosa70** [comment]
Und ich habe keinerlei Probleme. Keinen callstack, nichts. Und der Ordner ist voll mit diversen Skripten.

**Comment by cabmac** [comment]
so wie das aussieht, hat KEINER ausser mir das Problem, ich dachte nur, dass es mit gearbox zusammenhaengen koennte, da ich das Problem zeitlich zurueckverfolgt hatte, und sich mehr oder weniger  mit der neuesten Version ueberschnitten hatte. Nicht mal Stegei und MadMax kann mir irgendwas sagen...werde jetzt mal alles runterschmeissen und "neu" anfangen...und.....hoffen, dass sich Stefan wieder einkriegt... :D

**Comment by Mogli12** [comment]
Hi,

es geht hier nicht um Schuld oder nicht Schuld. Ich habe einfach momentan nicht genug Zeit und ich kann den Mod ja wohl nicht mit solchen Fehlern auf Modhoster veröffentlichen.

Viele Grüße

**Comment by MaxterTM** [comment]
Problem ist mir ebenfalls unbekannt. Die realclock hat zB. ein Problem mit der Winde von modelleicher, keine Ahnung warum? Ist auch vollkommen egal. Allein anhand der Komplexität wäre es wohl einfach den Fehler im Realclock Mod zu suchen. Deshalb cabmac, teste mal NUR mit dem Gearshift mod. Und dann Mod für Mod rein kopieren um das Problem genauer zu lokalisieren.

**Comment by cabmac** [comment]
also ich denke langsam, dass es da einen Zusammenhang zwischen Realmodule 1 und 3, camara-mod und compass gibt, ich probiere das morgen nochmal nur mit den dreien mit und ohne gearbox. Das Ding war naemlich das, dass ich heute 90min einwandfrei ohne gearbox gespielt hatte, gearbox rein und dann hatt er  in der log stehende fehler geschmissen. Ich werde es auch nochmal probieren mit einer aelteren Version der gearbox. Wie gesagt, ich weiss es halt nicht, obs mit der gearbox zusammenhaengt, das Problem ist halt, dass man in der jeweiligen config immer min. ne halbe STunde spielen muss, damit der Fehler sich reproduziert. Komisch auf er anderen  Seite ist ja, dass es ja anscheinden z.B, bei Appa funktioniert.....
[log.txt](https://github.com/Mogli12/GearboxAddon/files/619823/log.txt)

**Comment by cabmac** [comment]
Moin STefan...ich weiss, dass du keine oder wenig Zeit hast, trotzdem laesst mich das nicht in Ruhe. Nun hab ich nochmals gefuehlte 47 Tests hinter mir. Zunaechst die Frage, hast du mit der aktuellen Version irgendwas an den Fendts geaendert? Und nun das wieso: mit 1.9.4.0 hab ich diese immer besagte call stacks, und zwar zu 99% in Verbindung mit einem Fendt 300 oder 700, bei anderen Fahrzeugen passierts nicht. Der FS laeuft jetzt seit 2 STunden mit dem 700er Fendt und mit Version 1.9.3.7 ohne Probleme....!?!

Ich warte noch ab, was Appa sagt, er hat die Version noch nicht mit FEndt probiert....kann natuerlich sein, dass ich mich irre, aber es sieht alles danach aus...

**Comment by cabmac** [comment]
vergiss bitte alles, was ich gesagt habe...nach knapp 3 Std. im save ists mir nun mit 1.9.3.7 wieder abgestuerzt...wieder mit einem Fendt. aber das wird wohl nichts zu bedeuten haben.

**Comment by Mogli12** [comment]
Ich habe mal probiert, die Getriebeübersetzung noch auf gültige Werte zu untersuchen, bevor es an die Engine geht. Vielleicht hilft das was.

**Comment by cabmac** [comment]
Danke fuer die Mühe, ich werds gleich morgen frueh probieren...

**Comment by cabmac** [comment]
Moin, so, ein kleiner "Zwischenbericht". ich habe die Keyboardsteering und gearbox version ausgetauscht (1.9.4.1). Das savegame laeuft bis  jetzt seit bissl mehr als 2 Stunden ohne Probleme. Was mir auffaellt ist, dass die Lenkung (bei mir jedenfalls) nun wesentlich angehehmer und weicher geht (wie bei LS15), das war bei mir bei der 2.1 nicht der Fall, ich hatte mich schon gewundert, dass das bei mir fast nicht zu spueren war. Hast du daran etwas geaendert oder koennte da vielleicht der Hund begraben liegen?

**Comment by Mogli12** [comment]
Hi, ich denke, dass ich mit 1.9.4.1 den Fehler identifizieren und vermeiden konnte. Mit 1.9.4.2 ist auch die Ursache korrigiert. Ich mache daher dieses Issue zu. Sollte doch noch ein Problem bestehen, dann mache bitte diese Issue wieder auf.
LG, Stefan
