### ISSUE TITLE
Dedicated Server Sound Probleme

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#78]
Hallo mogli, 

leider sind mit dem neusten Update die Fehler nicht beseitigt. Im Dedicated ist immer noch genau das selbe Problem. Anbei ein Video dazu. ==> 

https://www.youtube.com/watch?v=ujaU1xFsOjo&feature=youtu.be

Grüße

**Comment by Mogli12** [comment]
Hallo,

da kann das Getriebe meiner Ansicht nach nichts dafür. Die Drehzahl und MotorLoad für den Sound werden von Standard-Skripten übertragen. Es ist nur so, dass beim Standardgetriebe die Drehzahlsprünge viel größer als bei einem stufenlosen sind. Wenn dann Netzwerkverbindung zu langsam ist, dann treten die Probleme mit dem GearboxAddon stärker zu Tage.

Aber um weitere Missverständnisse zu vermeiden habe ich in Version 1.9.4.3 den MultiPlayer-Support ausgeschaltet.

Grüße

**Comment by modelleicher** [comment]
Hi,

Da es schade wäre wenn der Mod ohne Multiplayer-Support auskommen müsste würde haben sich Maxter und ich mal daran gemacht die Ursache für das Problem zu suchen oder zumindest einzugrenzen. Ich hätte am liebsten gleich eine Lösung präsentiert allerdings bin ich im Moment mit meinem Latein am Ende.

Das Standard-Script berechnet die Sound-Lautstärke anhand der Drehzahl. Und genau da liegt dann das Problem. Sobald der Traktor die Endgeschwindigkeit im jeweiligen Gang erreicht hat (und das Gaspedal oder Taste W noch gedrückt ist) fällt die Drehzahl ab auf ~20 (bzw. auf 1020 je nach dem welchen Wert man abliest ob da schon ein min Wert mit eingeflossen ist oder nicht)
Da die Lautstärke mit aktueller Drehzahl / (max rpm - min rpm) berechnet wird ist die Lautstärke dann natürlich entsprechend bei 0.001 oder so, also nicht mehr hörbar.

Das Problem tritt nur auf wenn self.noTransmission nicht true ist, d.h. sobald man das Gaspedal los lässt oder die Kupplung tritt stimmt die Drehzahl wieder. Ebenso stimmt die Drehzahl wieder wenn der Traktor unter Last kommt.

Hier noch ein Video dazu:
https://www.youtube.com/watch?v=kgq9ZbMy0RM


Die motorized holt die Drehzahl über self:getEqualizedMotorRpm() sprich self.equalizedMotorRpm.
Das wiederum wird ja im GBAddon unabhängig von Server/Client oder noTransmission anhand von self.lastMotorRpm berechnet.
Dann self.lastMotorRpm wiederum über self.lastRealMotorRpm und das wiederum anhand von
self.nonClampedMotorRpm.
Wenn ich nichts übersehen habe ist bis dahin keine Abtrennung zwischen noTransmission true/false geschehen die Einfluss haben könnte.

Die meiner Meinung nach ausschlaggebende Sache passiert in der  gearboxMogliMotor:updateMotorRpm() , allerdings hier wieder ob noTransmission true/false spielt keine Rolle beides mal wird über self:getMotorRpm() die Drehzahl geholt.
In self:getMotorRpm() gibt es ja die Unterscheidung zwischen noTransmission true/false, aber in beiden Fällen wird self:getThrottleRpm() verwendet, nur bei noTransmission false noch die Kupplungs-Drehzahl mit einbezogen.
Und da bin ich dann mit meinem Latein am Ende..  Weil wo kommt da das ganze Last/keine Last Problem mit rein? Schließlich passiert es ja nur wenn der Traktor nicht mehr beschleunigt.


 Du kennst dein Script ja am ehesten, vielleicht hilft das ja um raus zu finden wo es Probleme gibt. Irgend ein Wert der wohl beim Client nicht existiert oder so was.. 

Alternativ würde ich als "Pflasterlösung" vorschlagen den RPM Wert beim Clienten künstlich zu setzen sofern der echte rpm Wert kleiner als minRpm ist.
Wenn raw rpm < minRpm dann rpm = (maxRpm-minRpm) * Gaspedalstellung + minRpm

Ist vermutlich ein nicht zusammenhängendes Problem aber wie man sieht wird die Drehzahl-Anzeige beim Client auch nicht synchronisiert der Wert hängt immer bei min rpm fest.


LG

**Comment by Mogli12** [comment]
Hi,

die Methoden von gearboxMogliMotor bzw. VehicleMotor werden nur auf dem Server aufgerufen. Es macht also keine Sinn zu überlegen, was in updateMotorRpm schief läuft, da diese Methode nur auf dem Server durchlaufen wird. 

Drehzahl und MotorLoad werden dann vom Standard-Skript vom Server zum Client übertragen:
[https://gdn.giants-software.com/documentation_scripting.php?version=script&category=70&class=2245#readUpdateStream30876](https://gdn.giants-software.com/documentation_scripting.php?version=script&category=70&class=2245#readUpdateStream30876)

Gruß, Stefan

**Comment by modelleicher** [comment]
Hi,

So... Maxter und ich haben gerade noch mal getestet. Der Fehler passiert tatsächlich in der Übertragung. Beim Server sind die Werte passend, beim Client kommen sie falsch an.

 streamWriteUIntN(streamId, rpm, 11);
11 Bit Übertragung der Drehzahl.. => max. 2048 bzw. 2047

Die Enddrehzahl von 2200 kommt aber nach der ganzen Mathematik am Beispiel des Fords auf 2073.. Entsprechend fließt das über und es werden nur die restlichen 25 übertragen..

Wenn man das ganze auf 12 Bit Übertragung ändert funktioniert alles.

Die motorized readUpdateStream und writeUpdateStream Funktionen zu überschreiben sollte ja nix gegen sprechen.. Eventuell kann man die Berechnung anpassen dass man nicht über die 11 Bit hinaus geht.. Oder aber einfach 12 Bit übertragen, ob es darauf ankommt..


Warum das ganze beim treten der Kupplung oder los lassen des Gaspedals Einfluss hatte ist mir noch nicht so recht klar.. Vermutlich ist die Drehzahl dann genau um den minimalen Wert gefallen dass man unter die 2048 gekommen ist.

Jedenfalls hab ich das jetzt Testweise auf 12 Bit geändert und wir haben im MP getestet das Problem ist behoben dadurch.


LG

**Comment by Mogli12** [comment]
Hi,

danke für die Analyse. Mit 1.9.4.4 bleibt equalisedMotorRpm jetzt zwischen minRpm und maxRpm.

LG

**Comment by ivanlii** [comment]
Hi, i'l post here to not open new issue as is related to 1945 sound update:
_Error: keyframes not strictly monotonic increasing_
[log.txt](https://github.com/Mogli12/GearboxAddon/files/635873/log.txt)

**Comment by Mogli12** [comment]
I close this issue after one week w/o feedback. I think the issues are fixed.
