### ISSUE TITLE
AutoOff for AI helpers

### ISSUE THREAD

**Issue by ivanlii** [Mogli12/GearboxAddon#79]
Hi, is there a way to do that ?

auto: (mostly for combines) they keep changing gears and not smooth riding.(=uneven swath);
manual: If i set it to manual mode and set a gear (G27 shifter), when TABing to another vehicle i must move the shifter position and then when back to AI the gear is wrong.

I tried 
gearboxMogli.AIGearboxOff         = "Y"
gearboxMogli.AIGearboxOn          = "N"
with lo luck..

And thank you for this mod!

**Comment by Mogli12** [comment]
Hi,

Please do not change LUA coding in the mod if not necessary. You can automatically turn of the gear box with hired worker:

Create empty gearboxAddonConfig.xml in the mods folder with the following content:

`<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<defaultEnableAI type="string" value="N"/>
	</gearboxMogliGlobals>
</vehicles>`

This way you can easily change every value in gearboxMogliGlobals inside gearboxMogli.lua. Possible values for type are: "string", "bool", "float", "degree" and "int".

But you can also test if if works better with v1.9.4.4. This version will automatically turn off G27 mode with hired worker.

BR

**Comment by ivanlii** [comment]
Quickly tested both solutions and they work.
Thank you

**Comment by Mogli12** [comment]
If you look into gearboxMogli.lua there is a large list starting with gearboxMogliGlobals. You can change all of these fields.
