### ISSUE TITLE
Idle Sound nach abwürgen immernoch aktiv

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#82]
Hallo, 
auf dem Dedicatedserver, wenn man den Motor abwürgt bleibt der Idle Sound erhalten. Im Gearbox wird "off" angezeigt. Ich muss den Traktor mit "Enter" aber erst ausmachen (stop Sound ertönt) und dann wieder normal anmachen. Tritt mit manuellem Motor start auf. 

Grüße

**Comment by Mogli12** [comment]
Ist es mit 1.9.4.9 oder 1.9.5.0 besser?

**Comment by MaxterTM** [comment]
Jop mit der neusten Version gefixt, vielen dank :)
