### ISSUE TITLE
Rated-Rpm Fehlfunktion / Funktionslos 

### ISSUE THREAD

**Issue by BlaggyXD** [Mogli12/GearboxAddon#84]
Hallo, 
Die Funktion der "ratedRpm" ist meines Wissens nach bei welcher Drehzahl das Getriebe die angegebene Geschwindigkeit er reicht, mir ist heute aufgefallen dass dies aber nicht (mehr) funktioniert. 
Bsp. 
        6 Gang 42Km/h ratedRpm=2400 Geschwindigkeit bei 2700 Rpm = 47 Km/h (Früher)
        6 Gang 42Km/h ratedRpm=2400 Geschwindigkeit bei 2700 Rpm = 54 Km/h (Zurzeit)                                                                    
                           Endgeschwindigkeit bei: (Zurzeit) entspricht ratedRpm=2200                 

Ich hoffe ich konnte mein Problem hier mit deutlich machen.

Mit freundlichen Grüßen,
Blaggy

**Comment by Mogli12** [comment]
Die Drehzahl wird nicht höher als 2700 angezeigt und der Ton verändert sich auch nicht mehr. Ich vermute, dass von 47 bis 54 km/h es gleich klingt und immer 2700 angezeigt wird. Richtig?

**Comment by BlaggyXD** [comment]
Falsch , nein das Problem liegt nicht beim Ton (der Ton verändert sich bis auf 2700 Rpm, so wie die Km/h und die Rpm syncron sind)sondern dass er die 42 Km/h schon bei 2200 Rpm erreicht aber er es erst bei 2400 Rpm sollte (des wegen ist die endgeschwindikeit auch erhöht).  Das Problem tritt z.B. auch beim Standard Hürlimann auf evtl. Kannsts dir da mal selber anschauen.

**Comment by Mogli12** [comment]
Ah, ich habe den Fehler gefunden und mit 1.9.5.1 korrigiert.

**Comment by BlaggyXD** [comment]
An dieser stelle muss ich mal meinen Dank aus sprechen der Mod ist das m.M.n. beste für den Ls, so wie die Hilfe wenn es Probleme gibt.

Mit freundlichen Grüßen,
Blaggy

**Comment by Mogli12** [comment]
Vielen Dank fürs Lob!

**Comment by cabmac** [comment]
schliess ich mich natuerlich auch an, drivecontrol etcetc ja alles gut und schoen, aber ohne gearbox wuerde das alles nur halb soviel Spass machen... ;)
