### ISSUE TITLE
Ruppiges anfahren

### ISSUE THREAD

**Issue by cabmac** [Mogli12/GearboxAddon#85]
Hi, ich finde, dass seit ein paar Versionen das Anfahren (autom. clutch/Tastatur) bei den Fendts (andere hab ich nicht getestet) wieder ziemlich ruppig geworden ist, so als wenn die Kupplung zu spaet kommt und auf einmal losgelassen wird. Ich weiss, dass hatten wir 2015 schonmal, aber das war mMn schon mal sanfter.

LG
Claudio

**Comment by Mogli12** [comment]
Zum sanften Anfahren mit der Tastatur drück mal die "entf" Taste. Oder Du gibst nur ganz kurz Gas und läßt sofort wieder los. Dann rollt der Traktor nur leicht und sollte dann im "Active Stop" landen, d.h. das Getriebe ist aktiv aber die Übersetzung ist quasi unendlich.

**Comment by Mogli12** [comment]
Hallo Claudio,

probiere doch mal die 2.0rc2. 

Viele Grüße, Stefan

**Comment by cabmac** [comment]
hi, ich habs leider nur mal 5 min antes ten koennen, anscheinend gehts jetzt ein bisschen fluessiger

**Comment by cabmac** [comment]
hi nochmal..so, das Anfahren geht jetzt besser, nur ruckts jetzt etwas mehr mit der "Wendeschaltung". D.h. ich fahre vorwaerts, mit space auf rueckwaerts und er bremst ziemlich aprurppt ab...das war vorher besser...(waere allerdings "nur" Feintuning, das sollte dich nciht vom release abhalten)

**Comment by cabmac** [comment]
Hi, Anfahren jetzt mit dieser Version top....wenn man das jetzt noch hinkriegen wuerde mit der Wendeschaltung, waere das einwandfrei..die laeuft mit diesem update viiiiel zu brutal... ;)

**Comment by cabmac** [comment]
Hi, leider immer ncoh ziemlich "ruppig"...Anfahren nach wie vor ok:

https://youtu.be/bUNiabpJWr0

**Comment by Mogli12** [comment]
Ich würde es gerne so lassen, weil sonst die Kompaktlader zu langsam beim Rangieren sind.

**Comment by cabmac** [comment]
prioritaet haetten bei mir die Traktoren,  mMn ist die Benutzung der Kompaktlader doch  eher sehr gering.  Meine persönliche Meinung,   letztendlich und logischerweise deine Entscheidung...  ;)

**Comment by Mogli12** [comment]
Hallo Claudio,

Ok, beim Fahrtrichtungswechsel war doch noch ein Problem, das jetzt behoben sein sollte. Der Traktor bremst jetzt bei geöffneter Kupplung bis zum Stillstand und legt dann erst wieder den Gang automatisch ein. Aber Drehmoment vom Motor gegen die Fahrtrichtung scheint zur extremen Vollbremsung zu führen.

Viele Grüße, Stefan

**Comment by cabmac** [comment]
Moin Stefan...klasse jetzt...so kanns mMn bleiben. ;)
