### ISSUE TITLE
Error 3 bei Konfiguration in mod XML

### ISSUE THREAD

**Issue by RivalAUT** [Mogli12/GearboxAddon#86]
Hallo,

Seit einigen Versionen kommt immer folgender Fehler, wenn man ein Fahrzeug mit einer Gearbox-Konfiguration in dessen xml kauft. Zum Beispiel tritt es beim Fendt 310/312 Pack auf.

`Error 3 loading gearboxMogliLoader: C:/Users/[...]/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogliLoader.lua:334: attempt to index local 'entry' (a nil value)`

Bitte beheben!^^

MfG

**Comment by Mogli12** [comment]
Hi,

das sind ein paar wenig Details. Ist das ein Traktor mit eingebautem Getriebe? Der Fendt 300LSA?

Viele Grüße

**Comment by RivalAUT** [comment]
Jein, die Getriebe Konfiguration ist eingebaut, das Script an sich nicht. Ja das Fendt 300 Pack von Modhub/Modhoster

**Comment by RivalAUT** [comment]
funktioniert seit der v1.9.5.2 wieder. Danke!
