### ISSUE TITLE
Eaton Fuller splitter?

### ISSUE THREAD

**Issue by Jurkkis** [Mogli12/GearboxAddon#87]
Hello! 

Love the mod hopefully can find time to learn to make custom transmissions to it and contribute!

I see that the standard FS17 "american" trucks have Eeaton Fuller 13 speeds implemented in them and I've got some IRL exprience wit them so I expected to see splitter (high range "half" gears") in them but its just regular gears?
With Splitter I mean clutchless shifting of the "half gears" with throttle in high range for 13 speed? So when you are in first gear of HIGH RANGE and splitter in LOW/DIRECT position, 5ft-L, then moving the splitter to OVERDRIVE/HIGH and lifting the throttle would result in automatic shift to 5ft-H, OVERDRIVE/HIGH or vice versa? Would this be possible with current code By just configuring xml?

**Comment by Mogli12** [comment]
Hi Jurkkis,

That would be possible except the fact that it only shifts when you lift the throttle. So the shift between hi and low is like a powershift?

Regards, Stefan

**Comment by Jurkkis** [comment]
Yes its clutchless shift but I would not call it powershift as the actual shifting will only happen when you lift the throttle, or in other words, remove torque from the gearing. When splitting downwards from OD/High, you would first move the splitter switch to Direct/Low, then lift throttle, and then blip the throttle to rev match allowing the lower gearing engage. Splitting upwards to Overdrive/High will happen by first moving the splitter switch, letting of the throttle and letting the rpm to drop. For the game I think it would work nicely updwards and downwards just letting go of the throttle. And the difference beetween 13 and 18 speed is just that in 13 you only can split high range gears (5,6,7,8), and in 18 speed all 8.

**Comment by Mogli12** [comment]
Hi,
Can you try out version 2.0.0.2? The two american trucks have now gears and ranges.
Thanks, Stefan

**Comment by Jurkkis** [comment]
Thanks, the throttle splitting works! But you should not be able to shift the range without clutch, only the splitter.

**Comment by Mogli12** [comment]
The range shifter now needs double clutch. And you should now hear the double clutch if used with automatic clutch.
