### ISSUE TITLE
Seltsames, sinnfreies herunter schalten von Automatik Getrieben

### ISSUE THREAD

**Issue by MaxterTM** [Mogli12/GearboxAddon#88]
Hallo, 

auf unserem Dedicated Server ( neuste Version, Gearbox V1.9.5.2  & neuster Patch) haben wir beim zB. beim Valtra N & beim JCB 3230 mit Gearbox oft das Problem dass das Automatikgetriebe bei der Bergabfahrt unter Vollgas plötzlich bis in den ersten Gang (von 6-1) Gang für Gang herunter schält. vollkommen ohne Grund, ohne Hinderniss. Oft legt der JCB auch beim anfahren in Gruppe D nach vollgas fahrten, abbremsen und wieder aus dem Stand beschleunigen nicht den ersten Gang ein und verhart somit im 6 und kommt nicht vom Fleck. Auch mit Ladung hat der JCB in Gruppe A mit Gang 1 nicht genügend Kraft einen beladen Wagen am Berg loszuziehen. Wobei er bei 230PS und einem dermaßen kleinen Gang ja genug Leistung haben sollte. 

2. Auch die Handbremse fehlt mir sehr, da die 2-3 sec auf Auto Hold warten recht nervig ist wenn man ein Fahrzeug mit normalem Getriebe (MB-Trac) fährt. 

3. Auch das Handgas ist bei 100% nicht gleich Gas Pedal 100%, was im echten leben aber auch 1:1 sein sollte. 

Leider konnte ich die Anomalien nicht auf Video einfangen, trotz größter Anstrengungen. 

Über eine Rückmeldung würde ich mich freuen, evtl. haben ja auch andere das selbe Problem dann dürfen sie gerne bei der Schilderung des Problemes behilflich sein. 

Grüße Steffen

**Comment by Mogli12** [comment]
Hallo Steffen,

das sinnlose Herunterschalten sollte mit 2.0rc2 behoben sein.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Steffen,

zu 2.: AutoHold sollte sich nach 1000 ms einschaltet. Man kann das in gearboxMogliGlobals mit dem Parameter brakeNeutralTimeout verstellen. Wenn also noch nicht vorhanden, dann lege eine Datei gearboxMogliConfig.xml im Mods-Ordner an und füge direkt hinter 
`<vehicles>`
folgende Zeilen ein:
`  <gearboxMogliGlobals>
    <brakeNeutralTimeout value="500"/>
  </gearboxMogliGlobals>`
Mit den obigen Zeilen stellst Du es auf 0,5 Sekunden.

zu 3.: Ich habe lange überlegt, ob Handgas nun die Drehzahl oder das Gaspedal steuert. Derzeit legt Handgas die Drehzahl fest. Das verwendet dieselben Coding-Strecken wie das Zapfwellen-Coding.

Viele Grüße, Stefan
