### ISSUE TITLE
make transmission selectable as an option when buying a tractor

### ISSUE THREAD

**Issue by Quintto** [Mogli12/GearboxAddon#89]
Hi, i was thinking would it be possible to make the transmission type an option in the buying screen (like engine size, colour and tires) for example Massey offers 3 transmissions on the 7700 series (dyna 4 and dyna 6 powershift gearboxes and the dyna VT CVT gearbox) it would be nice to be able to choice one.

**Comment by Mogli12** [comment]
Hi,

This is a great idea. But I want to finish the 1st official release before looking into new features. 

Regards, Stefan
