### ISSUE TITLE
Standard Helfer + Gearbox Addon "problem"

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/GearboxAddon#9]
hi mogli

hab ein kleines problem festgestellt

der standard helfer kann am feld ende irgendwie nicht umdrehen wenn das gearbox aktiv ist
wenn ich autoCombine helfer nutze oder courseplay , geht es ohne probleme , nur der standard helfer will nicht drehen

ich hab mal 2 bilder gemacht um das zu verdeutlichen

http://up.picr.de/23683612he.jpg
http://up.picr.de/23683614aw.jpg

bis jetzt is mir das nur beim drescher aufgefallen , beim trekker funzt alles

gearbox version : 1.2.99.91

Log ist clean

grüsse grazy

**Comment by Mogli12** [comment]
Ui, da ist die Kupplung wohl verschlissen. Ich habe mal die Kupplung getauscht ;-)

**Comment by mngrazy** [comment]
danke mogli

die neue kupplung funzt 1a ;)
das ein service ,,, nicht wie bei VW ,,, LOL

grüsse grazy
