### ISSUE TITLE
Issue with rough terrain   

### ISSUE THREAD

**Issue by knarF86** [Mogli12/GearboxAddon#90]
From my experience it seems like the engine gives up if the surface is slightly rough.
When driving a truck, it wont accelerate like it should, even on almost flat terrain.

I also think the tractors should get more Torque on lower gears.
A real tractor would start spinning wheels even on high range gear for at least 2 first gears.
But other then this i think the mod is awesome with more realistic driving :)

**Comment by Mogli12** [comment]
I think that problem is that in FS17 the tire have too much grip. I looked at the Fendt Vario and maximum torque transferred through the Fendt transmission. In real life the transmission can deliver more torque than the wheels can handle. But in FS17 the wheels will not start spinning. 

Do you have an example (picture, name of map and truck) of "...it seems like the engine gives up..."?

**Comment by knarF86** [comment]
Yea, i think the grip is waaay to high as well, wish it could be easy to adjust that.

The map i'm using is: https://fs-uk.com/mods/view/38500/coldborough-park-farm-17
Problem occurs on dirt roads that are a bit bumpy, but also on fields, especially on the edge of the fields, where it may get a little more bumpy.

The truck is really notice this on is: https://fs-uk.com/mods/view/38478/man-a-helmer-hkl
But i also notice it on stock tractors

**Comment by knarF86** [comment]
I made a video if you wanna see what i mean.
When i drive up the field and road i push the gas all down, but it dont use 100% of engine.

http://178.164.57.239:8282/Farming%20Simulator%202017%2001.13.2017%20-%2014.10.47.01.mp4

**Comment by Mogli12** [comment]
Do you use [GroundResponse](https://farming-simulator.com/mod.php?mod_id=52696&title=fs2017)?

**Comment by knarF86** [comment]
Yea, might it be a conflict?

**Comment by Mogli12** [comment]
I do not think that there is a conflict. But GroudResponse adds extra force to the wheels. And this extra force leads probably to not reaching 100% motor load.

**Comment by knarF86** [comment]
I tried removing the ground response, and it seems like it got better 🙂
