### ISSUE TITLE
Realistic clutch

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/GearboxAddon#92]
Hi thank for your great great job. I just come to say a suggest i see when i'm clutch and accelerate motor increase slowly something glued in oil xD, tried with slow tractor engine and fast engine like700hp or more that always increase slowly you know that not real i see. In real with a car or other engine you want when you clutch the engine go faster immediately in full RPM I hope you know what i mean with my sad english Best regard again happy new year too :p

**Comment by knarF86** [comment]
I feel like the same thing. Rpm increase too slowly.
When i accelerate from 1-4 i think its ok. But when in neutral it increases very slow.

This isnt a part of the issue, but am i the only one that thinks the clutch work a bit late? It seems for me like it dont start before about 50% clutch.

**Comment by Mogli12** [comment]
Hi,
You can change the globals. Just create a file gearboxAddonConfig.xml (if it not already exists) with the following content:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<DefaultRevUpMs0 value="2000"/>
		<DefaultRevUpMs1 value="2000"/>
		<DefaultRevDownMs value="2000"/>
	</gearboxMogliGlobals>
```
DefaultRevUpMs0 is the time from idle to rated RPM at 0% load. DefaultRevUpMs1 is the same at 100% load. DefaultRevDownMs is the time from rated to idle RPM. 2000 is the current default for all three.

The clutch percentage is not a movement of the clutch pedal. It means how much RPM is directly coming from the wheels.

**Comment by knarF86** [comment]
Thank you.

Can i change the globals even on mp?
Dedicated server.

**Comment by cabmac** [comment]
hi, when i want to setup only 1 Tractor in my gearboxAddonConfig?  Those would be the same values?

**Comment by Mogli12** [comment]
For one tractor you can change these values at tag gearboxMogli:
```xml
<gearboxMogli revUpMs="2000" revDownMs="2000">
```
In this case is is not necessary to specify revUpMsFullLoad.

**Comment by Anonymous-any** [comment]
Hi Maestro Mogli ;) ** you wonderful** it's exactly what we would like. I think this trick must be added as permanent in configfile you know but it's just my think. I don't know why the value must be 2k but my brain is not a lot available ^^, I add you I use the clutch as button switch on/off joystick emulation you know not real pedal but that work PERFECT !!. Hey Mogli I tried too to add a config for a specific tractor with copying and modify some value from another like your video tutorial but it was a disaster, the tractor was slow event modifying value lol, it's nothing there is so lots of value by the way I leave it but it's very interesting of how the behavior change and with the clutch trick it compensate the tractor that I wanted to change.

Okay I found a weird thing recent not linked but I profit to report: when you lock the speed as auto full speed with the 3 key button you know... the acceleration and gear torque etc etc.. got a weird behavior but maybe it's only me?

Again you amazing thank for you good job never see somewhere.

**Comment by Anonymous-any** [comment]
Okay now we have a nice clutch, and I would want to try to do some burn-out ^^ got 700 hp under the hood but wheels won't slide immediately (i hope the image scenario talk to you cause) my english is limited you know :/ is there a possibility the wheels become more aggressive like slide when immediately load?
Regard

**Comment by Mogli12** [comment]
The grip in FS17 is way too high. But I do not know how to change it. In fact it creates problems in the gearbox. When in real life the wheels would spin nothing happens in FS17.

**Comment by Anonymous-any** [comment]
Thank for reply damnnnnn it's so sad I had to expect a response of this kind in all cases thank for all. It's weird because if do front of a wall and a very low gear the wheels are slides but the engines rpm go down you know. Cya

**Comment by Anonymous-any** [comment]
Hi, up have you try and see?

**Comment by Anonymous-any** [comment]
So sorry to disturb again but I tried to update to v2.0.2 and the clutch trick mod is not running, then to try to understand better I tried to back down one by one versions and it sort the v2.0.0.3 clutch trick mod is ok, all higher versions won't work with the trick mod:
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicles>
	<gearboxMogliGlobals>
		<DefaultRevUpMs0 value="2000"/>
		<DefaultRevUpMs1 value="2000"/>
		<DefaultRevDownMs value="2000"/>
	</gearboxMogliGlobals>
</vehicles>

I add to say when I was create the subject to request you and do it fine I was on v2.0.0.2 :/

**Comment by Mogli12** [comment]
Hi, what do you mean with "the clutch trick mod"?

**Comment by Anonymous-any** [comment]
Hi I mean the informations you posted here 3rd post (trick=cunning):

<vehicles>
	<gearboxMogliGlobals>
		<DefaultRevUpMs0 value="2000"/>
		<DefaultRevUpMs1 value="2000"/>
		<DefaultRevDownMs value="2000"/>
	</gearboxMogliGlobals>
</vehicles>
Regards

**Comment by Mogli12** [comment]
Hi,
This still works. If not then your gearboxAddonConfig.xml is not valid.

**Comment by BlaggyXD** [comment]
I got the same issue , the "the clutch trick mod"/ "faster reving" isnt working.

**Comment by Anonymous-any** [comment]
It's weird that you say that Maestro cause when I tried all test like as I say you (I don't want to disturb you for nothing) I just (copy move) the same gearboxAddonConfig.xml (without modify it who it get the trick you know) in the different files archives tested... and it work with v2.0.0.2 and 2.0.0.3 but not highers versions Mogli for me in all cases.

**Comment by Anonymous-any** [comment]
Hi, always not work with your latest version :/ I tried too:

<gearboxMogli revUpMs="2000" revDownMs="2000">

same issue

**Comment by Mogli12** [comment]
Hi, 

I think the moment of inertia causes this effect. I found that the vehicles accelerate too good in very small gears. So I increased the moment of inertia until it suited in small and big gears. Additionally, this resulted in a more realistic motor brake.

If the moment of inertia is too big for your tractor you can change it. The current formula is:
```lua
momentOfInertia = 2 + 4 * motorTorque / 1000
```
motorTorque is in Nm. You can change the default with:
```xml
<gearboxMogli momentOfInertia="1">
```
Giants default is 1.

BR

**Comment by Anonymous-any** [comment]
Hi Mogli, I think I don't understand the link with the clutch but it's your job :) at time chief,
I again tested with v2.0.3.4 and the engine does not run anymore once the clutch disengaged as before. In my opinion this is really not realistic I wait almost 3 sec !! For the engine to be at the breakers it's way too soft I think and the modification you gave at the beginning no longer works. Have you been able to test the trick with v2.0.0.3 and the difference with the news?

Ps: if your value above replace the trick clutch then I don't know what value I must put.
Best regards ;)

**Comment by Anonymous-any** [comment]
```
 Mogli12 commented 7 days ago

Hi,
This still works. If not then your gearboxAddonConfig.xml is not valid.
```
Hi
Then maybe can you paste somewhere your config with the trick running please cause I really not know where i'm wrong in my gearboxAddonConfig.xml that would not work with new versions
Regards

**Comment by ivanlii** [comment]
Hi, about that "trick":
changed `<DefaultRevUpMs0 value="2000"/>` to
`<DefaultRevUpMs0 value="2000" type="float"/>` and is working.

Now another question about the clutch: why at given rpm, under load, when i disengage the clutch (manual or G27 pedal) the revs go down? Is it normal? I was expecting to at least stay constant or even rise if we take the load off.

Thanks!

**Comment by Anonymous-any** [comment]
Hi thank for help but I tried your code with the latest version It's not working sorry

**Comment by ivanlii** [comment]
One more try, my _gearboxAddonConfig.xml_ in _mods_ folder look like this:
`	<gearboxMogliGlobals>
	
		<defaultEnableAI 	value="N" 		type="string"/>
	
		<hudPositionX   	value="0.605" 	type="float"/>
		<hudPositionY   	value="0.14" 	type="float"/>
		<hudTextSize    	value="0.018" 	type="float"/>                    
		<hudTitleSize   	value="0.02" 	type="float"/>
	
		<DefaultRevUpMs0 	value="300" 	type="float"/>	
		<DefaultRevDownMs 	value="500" 	type="float"/>	
	
		<stallMotorOffTime 	value="500" 	type="float"/>
	
		<brakeNeutralTimeout value="500" 	type="float"/>
		
	</gearboxMogliGlobals>
`
Did not work for the first time without specifying the data type.

**Comment by Anonymous-any** [comment]
Thank for reply Ivanlii but again I put all your config in the latest zip file Mogli give, then I buy a new vehicle to be sure it's in the vehiclesavegame file then save the game then I reload the game then nothing happen better. RPM continue to increase in glue and have something like 3 seconds to reach full RPM... sad + he say he stop the gearboxaddon related to More Realistic...

**Comment by ivanlii** [comment]
>  I put all your config in the latest zip file Mogli give,

You know you must put your "gearboxAddonConfig.xml in mods folder", not in mogli`s _FS17_GearboxAddon.zip_

**Comment by Anonymous-any** [comment]
Ohhh many many thank for your fix I really not know why I was not understand that where we must put the config file :+1: 
"Fortunately is not the case" Mogli say that in the last update readme :/ I hope you right, for all thank you again Ivan :) Your set are lots reactive ^-^and windows good place i think i keep that set and I can upgrade to latest version now thanks to you.
Best Regards

**Comment by Anonymous-any** [comment]
Closed by me and solved cause I was not read custom configuration :)
