### ISSUE TITLE
Annoying sound

### ISSUE THREAD

**Issue by knarF86** [Mogli12/GearboxAddon#93]
Hi,

I keep wondering if it is possible to remove an annoying sounds when you drive.
I don't know how to explain it, but it kinda hard to hear the engine with that sound.
It forces me to keep an eye on the gearbox-ui and is kinda annoying.

I added a video for you.
I'm sure you know what i mean if you watch it.

http://178.164.57.239:8282/Farming%20Simulator%202017%2001.20.2017%20-%2020.44.40.02.mp4

- Frank

**Comment by knarF86** [comment]
Only in Mp it seems like tho

**Comment by Mogli12** [comment]
Hi, I still cannot load the MP4 file. Can you upload it to youtube or copy it into https://drive.google.com/drive/folders/0BwwLILj-1B5BZll4TjZjYUZRd3c?usp=sharing?

**Comment by knarF86** [comment]
I will upload it after work today

**Comment by knarF86** [comment]
I just uploaded the video.

**Comment by Mogli12** [comment]
https://drive.google.com/open?id=0Bw0R2oG6wTFlZkROWFRwOHY3bWM

**Comment by knarF86** [comment]
Huh?
You just posted the video :)

**Comment by Mogli12** [comment]
Hi, please check if it is fixed with version 2.0.3.3. Thanks!

**Comment by knarF86** [comment]
I can confirm that it is fixed in 2.0.3.3

Great job on the mod! ;)
