### ISSUE TITLE
Engines should stall when RPM is too low.

### ISSUE THREAD

**Issue by Velorium117** [Mogli12/GearboxAddon#97]
I'm assuming there's a reason engines don't stall when you drop the clutch in the mod, but just wondering if it is at all possible to include this? I'm sure there's someway to program the engine to turn off below a certain RPM? The game already has the option to manually start and stop the engine. I know nothing about programming so this might be something that's impossible at the moment.

Regardless, great mod, I used it in FS15 and I'm really enjoying it in FS17. Thank you for your hard work!

**Comment by Mogli12** [comment]
I just tested the NH 8340. I switched from auto clutch to manual clutch. I got the warning and afterwards the engine went off. Did you test it with the Case IH 1455 XL? This has a torque converter and it cannot stall.

**Comment by BlaggyXD** [comment]
I think he means that the engine should stall not after a like 5 Sec bellow lets say 400 RPM it should stall as soon it get bellow 400 RPM, so its more like in RL.

**Comment by Velorium117** [comment]
AH I see now, yeah the tractors I were using were ones with torque converters, I see what you mean now Mogli. But yes, as BlaggyXD said, it would be more realistic if it would stall out immediately. 

Thank you for your reply :)

**Comment by Mogli12** [comment]
You can reduce the stallMotorOffTime in gearboxMogliGlobals. I would not go below 250 ms.

**Comment by BlaggyXD** [comment]
Also i am wondering if it is globaly possible to stop the engine from reving up if you use a PTO driven thing.

**Comment by Anonymous-any** [comment]
Is input name="gearboxMogliAUTOCLUTCH2" is the right command for switch between manual auto clutch?

**Comment by Velorium117** [comment]
Thank you very much for the support Mogli!

**Comment by loenne-michel** [comment]
Thank you very much for the fantastic Gearbox Addon, Stefan!

Here is my question: Where can i set the "ptoRpmFactorEco" ? I didn´t find it in the globals or
gearbox config.

Best regards....Michael

**Comment by BlaggyXD** [comment]
You can find it in "gearboxMogli" it is in line 35 ("gearboxMogli.ptoRpmFactorEco      = 2/3   -- 0.5  -- reduce PTO RPM in eco mode; e.g. 1600 with PTO and 2200 rated RPM")

**Comment by Mogli12** [comment]
There is no need to change the lua. You can specify ptoRpmEco in the gearbox config.

**Comment by BlaggyXD** [comment]
It is a lot more easy to do it in the .lua because its globaly working.

**Comment by loenne-michel** [comment]
Thank you very much for your help guys, works fine!
