### ISSUE TITLE
French translation contribution

### ISSUE THREAD

**Issue by Anonymous-any** [Mogli12/GearboxAddon#98]
How I give you that if you want? can I upload it in your project? any other way? I'm not Github user ...
Regard

**Comment by Mogli12** [comment]
Hi, It seems you managed to upload your french translation. Thanks! Maybe it is a good idea if you would create a GitHub user? I think it is not a big deal.

**Comment by Anonymous-any** [comment]
Hi np Mogli , well I did as I could, I put too the button "push request" but maybe it was not needed.
Happy you receive it. Please Mogli, can you answer my 2 stupid question please?
https://github.com/Mogli12/GearboxAddon/issues/92 and here
https://github.com/Mogli12/GearboxAddon/issues/95

Best regards

**Comment by Mogli12** [comment]
By default the power shift will match the speed of the range during gear shift.

**Comment by Mogli12** [comment]
You can turn off speed matching if it is your own configuration:
```xml
<gears speedMatching="false">
...
<ranges speedMatching="false">
```
